### ISSUE TITLE
not enough RAM or sth. like that? hashindex: malloc buckets failed(Cannot allocate memory)

### ISSUE THREAD

**Issue by mpathy** [borgbackup/borg#339] opened 2015-10-27 14:16 UTC
I got following error here:

---

borg create --compression lzma,3 root@192.168.1.123:/media/sdk/BACKUP/borg::REPOSITORY /media/sda/

hashindex: malloc buckets failed(Cannot allocate memory)

borg: Error: Remote Exception.

Remote Traceback by Borg 0.27.0
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 83, in serve
    res = f(*args)
  File "/usr/lib/python3.4/site-packages/borg/repository.py", line 373, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3.4/site-packages/borg/repository.py", line 127, in get_transaction_id
    self.replay_segments(replay_from, segments_transaction_id)
  File "/usr/lib/python3.4/site-packages/borg/repository.py", line 251, in replay_segments
    self.index[key] = segment, offset
  File "borg/hashindex.pyx", line 114, in borg.hashindex.NSIndex.__setitem__ (borg/hashindex.c:2478)
Exception: hashindex_set failed

---

It seems the other machine has not enough RAM, or what does that mean?

(It is a Banana Pi SMB, 1 GB RAM.)

**Comment by ThomasWaldmann** [comment] 2015-10-27 14:43
If you want to backup lots of stuff using not that much memory, you should adjust using --chunker-params=19,23,21,4095.

That creates much less chunks (and much less chunk management overhead) with 2MiB chunk size than the default of 64kiB chunk size.

If it is still using too much RAM, you can also disable the files cache, but that will have a performance impact on 2nd+ backup.

**Comment by ThomasWaldmann** [comment] 2015-10-27 14:48
Btw, "::REPOSITORY" is a bit misleading. The repo is on the left side of the "::", on the right side is the archive (== the individual backup).

**Comment by ThomasWaldmann** [comment] 2015-10-28 16:24
I am closing this, this is not a bug, just how it works.

I am considering changing the chunker-params default at next major release btw.

**Closed by ThomasWaldmann** 2015-10-28 16:24 UTC
