### ISSUE TITLE
Instructions for gpg verification incorrect

### ISSUE THREAD

**Issue by aardbol** [borgbackup/borg#5292] opened 2020-08-11 08:04 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Include any warning/errors/backtraces from the system logs

The README,txt mentions the following:

> Verifying your download
> -----------------------
> 
> Please check the GPG signature to make sure you received the binary as I have
> built it.
> 
> To check the GPG signature, download both the binary and the corresponding
> *.asc file and then (on the shell) type, e.g.:
> 
>     gpg --recv-keys 9F88FB52FAF7B393
>     gpg --verify borg-linux64.asc borg-linux64
> 
> The files are signed by:
> 
> Thomas Waldmann <tw@waldmann-edv.de>
> GPG key fingerprint: 6D5B EF9A DD20 7580 5747 B70F 9F88 FB52 FAF7 B393
> 
> My fingerprint is also in the footer of all my borgbackup mailing list posts.

Importing the key:

> gpg: key 9F88FB52FAF7B393: new key but contains no user ID - skipped
> gpg: Total number processed: 1
> gpg:           w/o user IDs: 1

But the file is signed with a different key:

`gpg --verify borg-linux64.asc borg-linux64`
> 
> gpg: Signature made Sun 07 Jun 2020 12:38:17 AM CEST
> gpg:                using RSA key 2F81AFFBAB04E11FE8EE65D4243ACFA951F78E01
> gpg:                issuer "tw@waldmann-edv.de"
> gpg: Can't check signature: No public key

So I can't reliably verify the download.

**Comment by ThomasWaldmann** [comment] 2020-08-11 11:10
Just checked in a fresh VM:

```
$ gpg --keyserver pgp.mit.edu --recv-keys 9F88FB52FAF7B393
gpg: key 9F88FB52FAF7B393: 284 signatures not checked due to missing keys
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
gpg: key 9F88FB52FAF7B393: public key "Thomas Waldmann <tw@waldmann-edv.de>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1

# note: no compaint about "w/o user IDs" here. so maybe retry using a different keyserver.

$ wget https://github.com/borgbackup/borg/releases/download/1.1.13/borg-linux64
...
2020-08-11 13:08:03 (1.73 MB/s) - ‘borg-linux64’ saved [15210800/15210800]

$ wget https://github.com/borgbackup/borg/releases/download/1.1.13/borg-linux64.asc
...
2020-08-11 13:08:08 (55.0 MB/s) - ‘borg-linux64.asc’ saved [862/862]

$ gpg --verify borg-linux64.asc borg-linux64
gpg: Signature made Sun Jun  7 00:38:17 2020 CEST
gpg:                using RSA key 2F81AFFBAB04E11FE8EE65D4243ACFA951F78E01
gpg:                issuer "tw@waldmann-edv.de"
gpg: Good signature from "Thomas Waldmann <tw@waldmann-edv.de>" [unknown]
gpg:                 aka "Thomas Waldmann <tw-public@gmx.de>" [unknown]
gpg:                 aka "Thomas Waldmann <twaldmann@thinkmo.de>" [unknown]
gpg:                 aka "Thomas Waldmann <thomas.j.waldmann@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6D5B EF9A DD20 7580 5747  B70F 9F88 FB52 FAF7 B393
     Subkey fingerprint: 2F81 AFFB AB04 E11F E8EE  65D4 243A CFA9 51F7 8E01
```

So, **works for me**.

**Closed by ThomasWaldmann** 2020-08-11 11:10 UTC

**Comment by Jorgen-P** [comment] 2020-10-14 11:50
This seems to depend on the keyserver. I got the same problem with whatever the default server is but when I specified --keyserver hkps://keyserver.ubuntu.com it worked. I think the instructions should include a specification of keyserver (which you seem to have done when reproducing the problem @ThomasWaldmann).

**Comment by ThomasWaldmann** [comment] 2020-10-14 12:13
Well, usually the keyserver should sync between each other, AFAIK.

So I guess one can use any of them, except the broken ones (which may change over time, thus hard to recommend any one specifically). If the default one is broken, this should be filed as a bug against the gpg dist package I guess.
