### ISSUE TITLE
Much slower list files with borg 0.26.1 vs. 0.26.0

### ISSUE THREAD

**Issue by storcium** [borgbackup/borg#222] opened 2015-09-29 01:40 UTC
Timing listing of files in a repo between borg 0.26.0 and 0.26.1.  The backup source size is about 3TB

[0.26.0]
time ./borg list /vault/sn201509281917::vault1-2015-09-27-0900
...
real    0m52.276s
user    0m6.108s
sys     0m11.420s

[0.26.1] - visually much slower line by line, 39 minutes!
...
real    39m52.519s
user    39m0.488s
sys     0m19.992s

sha256sum borg (this is 0.26.0)
8bb7b0659c3ad78a39e115b9a320735af1ef0da101df19ed436ec2dac20b21ae  borg

sha256sum borg-linux64 (this is 0.26.1)
d67c53fb7dec1aa94c67a6a768de4913333b07ad82bb343ea75b051e8e8f3d89  borg-linux64

uname -a
Linux issapl1 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.6) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.

**Comment by ThomasWaldmann** [comment] 2015-09-29 15:26
That's strange.

There were only few changes in our repo between .0 and .1.

.0 binary: python 3.4.x
.1 binary: python 3.5.0

.0 binary: glibc from ubuntu 14.04
.1 binary: glibc from centos 6

.0 binary: queue ImportError unfixed
.1 binary: queue (logging.config) ImportError fixed

**Comment by ThomasWaldmann** [comment] 2015-09-29 17:55
Having slight troubles to reproduce this. I see rather different measurements using precisely the same version connecting to a remote ssh repo via wireless lan. Like between 1.5 and 6 minutes. This is more variance than I see when switching from 2.6.0 to 2.6.1 binary. For the binaries, all results are also in that range.

I am redirecting borg list output to /dev/null to avoid terminal scrolling performance influence.

@storcium did you also redirect output (to a file or /dev/null)?

@storcium I see it is not ssh: in your case, but how is access performance (throughput / latency) to /vault?

**Comment by storcium** [comment] 2015-09-29 21:31
On Tue, Sep 29, 2015 at 1:55 PM, TW <notifications@github.com> wrote:

> Having slight troubles to reproduce this. I see rather different
> measurements using precisely the same version connecting to a remote ssh
> repo via wireless lan. Like between 1.5 and 6 minutes. This is more
> variance than I see when switching from 2.6.0 to 2.6.1 binary. For the
> binaries, all results are also in that range.
>
> I am redirecting borg list output to /dev/null to avoid terminal scrolling
> performance influence.
>
> @storcium <https://github.com/storcium> did you also redirect output (to
> a file or /dev/null)?
>
> @storcium <https://github.com/storcium> I see it is not ssh: in your
> case, but how is access performance (throughput / latency) to /vault?
>
I did not redirect, was just looking at terminal.  /vault is local and it
has a very fast storage connection.  I accessed /vault with 0.26.0 and
0.26.1 on the same machine, same data etc.

Thanks,
Alex

**Comment by ThomasWaldmann** [comment] 2015-09-30 13:32
I did a python 3.5 based build on ubuntu 14.04 using a current pyinstaller git checkout, it does not have the slowdown issue. Thus it either must be centos6 or the pyinstaller code (or the py 3.5 build via pyenv) I used when building 0.26.1.

**Comment by matysek** [comment] 2015-10-01 07:44
I guess because of python 3.5.

**Comment by ThomasWaldmann** [comment] 2015-10-01 16:34
@matysek some specific reason why you think so (considering my post right above yours)?
I am doing a new 3.4.3 based build on centos now, just to find out...

**Comment by ThomasWaldmann** [comment] 2015-10-01 18:38
Built a centos6_64 python 3.4.3 based binary with latest pyinstaller-develop code, it is slow also.
So it does not seem to depend on pyinstaller version nor on python 3.5.

**Comment by storcium** [comment] 2015-10-05 22:07
On Thu, Oct 1, 2015 at 2:38 PM, TW <notifications@github.com> wrote:

> Built a centos6_64 python 3.4.3 based binary with latest
> pyinstaller-develop code, it is slow also.
> So it does not seem to depend on pyinstaller version nor on python 3.5.
>
Is there a chance this is somehow different between Ubuntu and CentOS?
Would a binary built on Ubuntu work better?  I am going to try pyinstaller
and see if I can figure it out.

Thanks,
Alex

**Comment by ThomasWaldmann** [comment] 2015-10-05 22:34
https://paste.thinkmo.de/ry4rTtqH < binaries built on debian 7

**Comment by storcium** [comment] 2015-10-06 10:21
On Mon, Oct 5, 2015 at 6:34 PM, TW <notifications@github.com> wrote:

> https://paste.thinkmo.de/ry4rTtqH < binaries built on debian 7
>
Much appreciated, seems to work well.

**Comment by ThomasWaldmann** [comment] 2015-10-06 16:45
OK, so debian and ubuntu covered. Now we just need to know whether the redhat/fedora users could be also happy with these built-on-debian7 binaries.

**Comment by storcium** [comment] 2015-10-06 17:04
On Tue, Oct 6, 2015 at 12:45 PM, TW <notifications@github.com> wrote:

> OK, so debian and ubuntu covered. Now we just need to know whether the
> redhat/fedora users could be also happy with these built-on-debian7
> binaries.
>
Very much appreciated, unfortunately we do not have any of either of those,
but will keep using in high load/high pressure mode on Ubuntu.  I noticed
some performance numbers where:

a server with 1 x E5-2609v2 - 4 cores @ 2.5GHz, Ivy Bridge

was twice as fast processing Borg based dedup for 1TB data set than

a server with 2 x E5-2620 - 6 cores each @ 2.0GHz, Sandy Bridge

probably explained by CPU speed.

**Comment by ThomasWaldmann** [comment] 2015-10-07 14:37
I did a try on centos7 using the binaries built on debian7. They worked and were much faster than the ones built on centos6. Thus, I am closing this as fixed in 0.27.0.

**Closed by ThomasWaldmann** 2015-10-07 14:37 UTC
Labels: bug

**Comment by tgharold** [comment] 2015-10-07 19:01
The 64bit binary also (seems to) work on CentOS 6.4 and is much faster then a 'pip3 install' version

```
wget https://paste.thinkmo.de/Acdubjme/+download
mv +download borg
chmod u+x borg

**Comment by ThomasWaldmann** [comment] 2015-10-07 19:44
@tgharold ah, ok, so we now know that something is slow on centos6 in general. and if we build a binary there, we include the slowness in that binary.
