### ISSUE TITLE
Ubuntu 20.04 - transport not connected

### ISSUE THREAD

**Issue by lgwapnitsky** [borgbackup/borg#5748] opened 2021-03-28 14:12 UTC
I've installed the latest borg from the ubuntu PPA. When I try to view a mounted borg repo, I receive the following:

```
root@borg:~# borg mount /mnt/serverbackups/::test_etc ~/test/
Enter passphrase for key /mnt/serverbackups: 
root@borg:~# cd test
-bash: cd: test: Transport endpoint is not connected
root@borg:~# ls -al
ls: cannot access 'test': Transport endpoint is not connected
total 40drwx------  7 root root 4096 Mar 28 10:00 .
drwxr-xr-x 22 root root 4096 Mar 28 10:09 ..
-rw-------  1 root root 3842 Mar 28 10:09 .bash_history
-rw-r--r--  1 root root 3811 Mar 20 18:11 .bashrc
drwx------  4 root root 4096 Mar 28 09:44 .cache
drwxr-xr-x  5 root root 4096 Mar 28 09:44 .config
drwx------  3 root root 4096 Mar 20 18:11 .emacs.d
drwxr-xr-x  3 root root 4096 Mar 28 09:43 .local-rw-r--r--  1 root root  161 Dec  5  2019 .profile
-rw-r--r--  1 root root  180 Mar 28 09:43 .wget-hsts
d?????????  ? ?    ?       ?            ? test
root@borg:~# 
```

I'm running this in an LXC container on Ubuntu 20.04. /mnt/serverbackups is an S3 rclone mount

**Comment by infectormp** [comment] 2021-03-28 14:33
Try to remount /mnt/serverbackups.
Maybe you find here some useful information https://stackoverflow.com/questions/14010115/amazon-s3-with-s3fs-and-fuse-transport-endpoint-is-not-connected

**Comment by lgwapnitsky** [comment] 2021-03-28 14:46
finding this in syslog - it's not the right URL, but rclone has it set and mounted properly

Mar 28 10:33:38 borg s3fs[884]: s3fs.cpp:s3fs_check_service(3905): unable to connect(host=https://s3.wasabifs.com) - result of checking service.

**Comment by lgwapnitsky** [comment] 2021-03-28 14:46
> Try to remount /mnt/serverbackups.
> Maybe you find here some useful information https://stackoverflow.com/questions/14010115/amazon-s3-with-s3fs-and-fuse-transport-endpoint-is-not-connected

a regular s3fs mount works fine.

**Comment by ThomasWaldmann** [comment] 2021-03-28 16:35
transport not connected simply means it is not working, maybe because it has crashed.

as you're running 2 fuse filesystems on top of each other, you now have to find out which one is malfunctioning.

this issue tracker is only to discuss the borg code, so if you find out the issue is in rclone or s3fs, please take it to the appropriate issue tracker.

to debug whether it is a borg issue, you can run `borg mount -f ...` to let it stay in the foreground. if it then crashes, you'll see some traceback. if that is the case, please add the traceback here or we likely can't do any further analysis.

**Comment by ThomasWaldmann** [comment] 2021-04-19 20:55
@lgwapnitsky did you find the root cause?

**Comment by ThomasWaldmann** [comment] 2021-04-20 17:23
Hah. OK, so I am closing this...

**Closed by ThomasWaldmann** 2021-04-20 17:23 UTC
