### ISSUE TITLE
Msgpack version constraints wrong on Ubuntu PPA - Missing upper limit

### ISSUE THREAD

**Issue by timwsuqld** [borgbackup/borg#4959] opened 2020-02-26 03:47 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).
borg 1.1.10

#### Operating system (distribution) and version.
Ubuntu 16.04.1

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg benchmark

## Describe the problem you're observing.
Borg complains about the version of msgpack installed, this is due to another repo providing a newer msgpack than is supported by borg, but the borg PPA doesn't restrict the upper limit on the msgpack version.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
1. Install salt (saltstack salt-minion) on a server using the py3 repos.
2. Install borgbackup from the PPA (https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup)
3. Borg will fail to work due to python3-msgpack being at version 0.6.2-1 as provided by the saltstack repo, because the borg package doesn't limit the upper limit.

#### Include any warning/errors/backtraces from the system logs
```
You do not have a supported msgpack[-python] version installed. Terminating.
This should never happen as specific, supported versions are required by our setup.py.
Do not contact borgbackup support about this.
```

```
Package: borgbackup
Priority: optional
Section: admin
Installed-Size: 2294
Maintainer: Danny Edel <debian@danny-edel.de>
Architecture: amd64
Version: 1.1.10-2~ubuntu16.04.1~ppa2
Suggests: borgbackup-doc
Depends: fuse, python3-llfuse (<< 2.0), python3-pkg-resources, python3 (<< 3.6), python3 (>= 3.5~), pyth
on3-msgpack (>= 0.5.1), libacl1 (>= 2.2.51-8), libb2-1, libc6 (>= 2.14), liblz4-1 (>= 0.0~r130), libssl1
.0.0 (>= 1.0.1), libzstd1 (>= 1.3.2)
```

```
$ apt-cache policy borgbackup
borgbackup:
  Installed: 1.1.10-2~ubuntu16.04.1~ppa2
  Candidate: 1.1.10-2~ubuntu16.04.1~ppa2
  Version table:
 *** 1.1.10-2~ubuntu16.04.1~ppa2 500
        500 http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.12-0ubuntu1.16.04.1 500
        500 http://mirror.overthewire.com.au/ubuntu xenial-updates/universe amd64 Packages
     1.0.2-1 500
        500 http://mirror.overthewire.com.au/ubuntu xenial/universe amd64 Packages

$ apt-cache policy python3-msgpack
python3-msgpack:
  Installed: 0.6.2-1
  Candidate: 0.6.2-1
  Version table:
 *** 0.6.2-1 500
        500 https://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     0.5.6-1ubuntu16.04.1~ppa2 500
        500 http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu xenial/main amd64 Packages
     0.4.6-1build1 500
        500 http://mirror.overthewire.com.au/ubuntu xenial/main amd64 Packages
```

Normally I wouldn't open a bug like this as it's a conflict between 2 3rd party repos. However the fix is simple, we know the upper limit of msgpack compatibility, we just need to set those limits in the Deb file that we build for the PPA.

**Comment by ThomasWaldmann** [comment] 2020-02-26 10:51
The problem is not primarily the missing dependency constraint (that would just restrain you from installing a conflicting version or any other software that requires a conflicting version), but that the package does not use the known-good msgpack which we bundle into the borg code.

@LocutusOfBorg ^^^

**Comment by timwsuqld** [comment] 2020-02-29 23:49
@ThomasWaldmann It's tricky when packaging things for Debian/Ubuntu. The recommended way is to use a package for libraries. This is what the PPA currently does, it creates a package for the known good python3-msgpack and depends on it, but by not restraining the maximum version, if another repo provides a newer msgpack, that will get installed.

I actaully package some software and use custom version numbers so that version XYZ of the software depends ONLY on version ABC of the library I want it bundled with. This way unless the known good library is the one that's installed, the package won't install. Given that we bundle the msgpack library in this instance, we could depend on the exact version of msgpack that we bundle, as long as other installed software has loose msgpack requirements, this will allow borg to be installed and won't prevent other software also working.

**Comment by ThomasWaldmann** [comment] 2020-02-29 23:52
@timwsuqld yes, that works as long there is an overlap in wanted versions.

If not, only using the bundled stuff would work. As msgpack had incompatible changes, some other stuff might likely require a non-overlapping-with-us version range for msgpack.

**Comment by ThomasWaldmann** [comment] 2020-10-11 11:46
Can you check if this is fixed now? See https://github.com/borgbackup/borg/pull/5404#issuecomment-706541761 .

**Comment by LocutusOfBorg** [comment] 2020-10-12 08:34
Now bundled msgpack is used, no more issue, we can close this one

**Closed** 2020-10-12 10:38 UTC
