### ISSUE TITLE
Borg2 benchmark CPU fails

### ISSUE THREAD

**Issue by dagelf** [borgbackup/borg#7139] opened 2022-11-09 03:45 UTC
```
[coenraad@coenraad-24r0 Downloads]$ ./borg2 -V
borg2 2.0.0b3

[coenraad@coenraad-24r0 Downloads]$ ./borg2 benchmark cpu
Chunkers =======================================================
buzhash,19,23,21,4095    1GB        1.170s
fixed,1048576            1GB        0.068s
Non-cryptographic checksums / hashes ===========================
xxh64                    1GB        0.083s
crc32 (zlib)             1GB        0.658s
Cryptographic hashes / MACs ====================================
hmac-sha256              1GB        1.942s
blake2b-256              1GB        1.243s
Encryption =====================================================
aes-256-ctr-hmac-sha256  1GB        2.443s
aes-256-ctr-blake2b      1GB        2.844s
aes-256-ocb              1GB        0.368s
chacha20-poly1305        1GB        0.581s
KDFs (slow is GOOD, use argon2!) ===============================
pbkdf2                   5          0.232s
argon2                   5          0.499s
Compression ====================================================
Local Exception
Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 594, in main
  File "borg/archiver/__init__.py", line 522, in run
  File "borg/archiver/benchmark_cmd.py", line 208, in do_benchmark_cpu
  File "timeit.py", line 233, in timeit
  File "timeit.py", line 177, in timeit
  File "<timeit-src>", line 6, in inner
  File "borg/archiver/benchmark_cmd.py", line 208, in <lambda>
  File "src/borg/compress.pyx", line 172, in borg.compress.DecidingCompressor.compress
TypeError: compress() takes exactly 2 positional arguments (1 given)

Platform: Linux coenraad-24r0 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b3  Python: CPython 3.9.14 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 29634  CWD: /home/coenraad/Downloads
sys.argv: ['./borg2', 'benchmark', 'cpu']
SSH_ORIGINAL_COMMAND: None

[coenraad@coenraad-24r0 Downloads]$ python -V
Python 3.10.8

```

**Comment by ThomasWaldmann** [comment] 2022-11-09 08:55
I think I already have fixed that in master, but let's check again...

**Comment by ThomasWaldmann** [comment] 2022-11-15 16:50
duplicate of #7075

**Closed by ThomasWaldmann** 2022-11-15 16:50 UTC
