### ISSUE TITLE
No condorscript.py file was detected in directory

### ISSUE THREAD

**Issue by kanyi** [borgbackup/borg#4284] opened 2019-01-30 13:15 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yew

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).
1.1.8

#### Operating system (distribution) and version.
Ubuntu 14.04.5

#### Hardware / network configuration, and filesystems used.
Older hardware; local copyjob w/o network; ext4

#### How much data is handled by borg?
~500Gbyte

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
sudo borg create --dry-run --one-file-system --progress --verbose --compression zstd,1 --exclude-from /home/rgadmin/borg_exclude /mnt/backup/ld_backup/::{now:%Y-%m-%d} /

## Describe the problem you're observing.
borg is not running:
$ borg
No condorscript.py file was detected in directory

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes every time, I have got only these one line now.

#### Include any warning/errors/backtraces from the system logs
Nothing

**Comment by ThomasWaldmann** [comment] 2019-01-30 14:33
Guess you did not install `borgbackup` but something else.

**Comment by kanyi** [comment] 2019-01-30 14:37
Nope, it is there:
pip list
Package             Version         
------------------- ---------------- 
borg                2012.4.1        
borgbackup          1.1.8           

BUT my python is only python3.4, maybe this casue these error message?

**Comment by ThomasWaldmann** [comment] 2019-01-30 14:46
if you do not use "borg 2012.4.1", remove that and reinstall "borgbackup" afterwards.

**Comment by ThomasWaldmann** [comment] 2019-01-31 06:16
i am closing this, the problems are obviously caused by installing a completely unrelated `borg` package - that is not `borgbackup`.

**Closed by ThomasWaldmann** 2019-01-31 06:16 UTC
