### ISSUE TITLE
WSL Errno 38 When Using Binary / Borg Version Greater Than Linux Repo Version

### ISSUE THREAD

**Issue by ShadowRylander** [borgbackup/borg#3977] opened 2018-07-11 22:11 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

### Filesystem Used

`NTFS`

### Report
```
Local Exception2 MB C 15.55 MB D 1990 N j/.hg/store/dh/magic_pa/pewter/d/hl/rgqb4fsm/ol22x7tqubt42iqcljbowsc62et6cbwhfcisroehqeg356081789a5e1bb3c0aa264811c2379029acf239b5.d
Traceback (most recent call last):
  File "borg/archiver.py", line 4312, in main
  File "borg/archiver.py", line 4244, in run
  File "borg/archiver.py", line 152, in wrapper
  File "borg/archiver.py", line 547, in do_create
  File "borg/archiver.py", line 511, in create_inner
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 621, in _process
  File "borg/archiver.py", line 598, in _process
  File "borg/archive.py", line 1028, in process_file
  File "borg/archive.py", line 956, in chunk_file
  File "borg/archive.py", line 944, in chunk_processor
  File "borg/cache.py", line 898, in add_chunk
  File "borg/repository.py", line 1072, in put
  File "borg/repository.py", line 1442, in write_put
  File "src/borg/platform/linux.pyx", line 255, in borg.platform.linux.SyncFile.write
  File "src/borg/platform/linux.pyx", line 229, in borg.platform.linux._sync_file_range
OSError: [Errno 38] Function not implemented

Platform: Linux surfacebook2 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64
Linux: debian 9.4
Borg: 1.1.6  Python: CPython 3.5.5
PID: 2296  CWD: /mnt/s/testing
sys.argv: ['borg', 'create', '--progress', '--compression', 'zstd,22', 'i::test', 'j/']
SSH_ORIGINAL_COMMAND: None
```

### How much data is handled by borg?

40 or so megabytes.

## Describe the problem you're observing.

This error crops up when using the `borg 1.1.6 binary` on the `Windows Subsystem for Linux, Debian`; it seems almost time-based. The first time, it worked in creating the archive, but the next few times, it didn't work if the backup process lasted more than a few seconds, such as if backing up the same data again, or backup up an empty directory.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

To reproduce, I'm assuming you'd have to use the subsystem and version number of borg I used; as I am quite new to this, attempts to find out `error 38` did not yield entirely useful results for me.

In addition, I have used various different arguments, primarily the ones I needed the most, such as different compression algorithms and levels, chunker parameters, etc. I have also noticed that the backup process stops on a different file every time.

**Comment by ThomasWaldmann** [comment] 2018-07-12 11:20
```
File "src/borg/platform/linux.pyx", line 229, in borg.platform.linux._sync_file_range
OSError: [Errno 38] Function not implemented
```

That means that's microsoft's api implementation is incomplete and misses the function for syncing file ranges.

This is a known problem and will likely persist until MS fixes that. If that happened on a current windows, you should open an issue with MS.

**Comment by ThomasWaldmann** [comment] 2018-07-12 11:22
duplicate of #1961.

**Closed by ThomasWaldmann** 2018-07-12 11:22 UTC

**Comment by srd424** [comment] 2019-08-18 14:04
Interestingly I've just hit this in a systemd-container .. very odd. Will report back; clues gratefully received..
