### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by savvasdalkitsis** [borgbackup/borg#6450] opened 2022-03-14 13:26 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

BUG/ISSUE

#### Your borg version (borg -V).

1.1.17

#### Operating system (distribution) and version.

alpine:latest docker image (https://gitlab.com/epicdocker/borgbackup/-/blob/master/Dockerfile) running inside lubuntu:

cat /proc/version_signature
Ubuntu 5.13.0-28.31-generic 5.13.19

lsb_release -a
LSB Version:    core-11.1.0ubuntu3-noarch:security-11.1.0ubuntu3-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

#### Hardware / network configuration, and filesystems used.

Borg repository sits on a gocryptfs file system on an external ext4 formatted hard drive

#### How much data is handled by borg?

The repo size is about 300GB compressed and deduped

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

docker run --rm \
    --name=backup-full-borg-create \
	--volume "$MAIN_DRIVE/data:/data" \
	--volume $BACKUP_DRIVE:$BACKUP_DRIVE:shared \
	--env-file $ENV_FILE \
	--user root \
	registry.gitlab.com/epicdocker/borgbackup:latest \
	create --files-cache=disabled --verbose --stats "$BACKUP_REPO::backup-$YEAR-$MONTH-$DAY--$HOUR-$MINUTE-$SECOND" /data

(I added the --file-cache=disabled option after finding issue #3307 which recommended that as a potential fix but the erorr persists with or without that option)

## Describe the problem you're observing.

The create command fails consistently with a segmentation fault during the chunk cache syncronisation. It fails on different archives each time so it doesn't look like it's a specific archive issue

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

As mentioned above, this crash happens consistently on my setup

#### Include any warning/errors/backtraces from the system logs

```
Creating archive at "/home/savvasdalkitsis/backup/borg::backup-2022-03-07--04-00-00"
Synchronizing chunks cache...
Archives: 27, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 27.
Fetching and building archive index for backup-2020-05-31--01-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2020-06-30--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2020-07-31--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2020-08-01--02-59-57 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2020-09-20--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2020-10-31--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2020-11-25--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2020-12-27--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-02-28--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-03-31--03-13-24 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-04-30--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-05-30--03-09-38 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-06-20--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-07-22--19-04-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-07-31--02-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2021-12-1--20-08-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-01-27--14-54-51 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-06--04-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-13--04-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-18--04-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-19--04-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-20--04-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-21--04-00-00 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-22--04-00-02 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2022-02-23--04-00-00 ...
Fatal Python error: Segmentation fault

Current thread 0x00007f0a98a33b48 (most recent call first):
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 740 in write_archive_index
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 736 in fetch_and_build_idx
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 824 in create_master_idx
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 870 in sync
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 474 in __init__
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 379 in local
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 387 in __new__
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 586 in do_create
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 177 in wrapper
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 4622 in run
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 4690 in main
  File "/usr/bin/borg", line 33 in <module>
```

**Comment by ThomasWaldmann** [comment] 2022-03-14 13:38
```
        def write_archive_index(archive_id, chunk_idx):
            nonlocal compact_chunks_archive_saved_space
            compact_chunks_archive_saved_space += chunk_idx.compact()     #     <----- line 740
            fn = mkpath(archive_id, suffix='.compact')
            fn_tmp = mkpath(archive_id, suffix='.tmp')
```

So the crash is in `hashindex_compact` which is C code (see `_hashindex.c`) and we do not yet know where exactly.

So without some gdb debugging and the precise line number, we can not do anything about this. Just search this issue tracker for other issues talking about gdb debugging.

But considering it is in hashindex, it could be a borg bug.

**Comment by ThomasWaldmann** [comment] 2022-03-14 13:43
This is likely a duplicate of #5899, closing.

If you can find out more about it, please add it there.

**Closed by ThomasWaldmann** 2022-03-14 13:43 UTC
