### ISSUE TITLE
flush of closed file

### ISSUE THREAD

**Issue by patatetom** [borgbackup/borg#1316] opened 2016-07-12 10:16 UTC
hi,

recent upgrade of borg :

```
~ # strings pacman.log | grep borg
[2016-04-15 15:55] [PACMAN] Running 'pacman -S borg'
[2016-04-15 15:55] [ALPM] installed borg (1.0.1-1)
[2016-04-25 09:29] [ALPM] upgraded borg (1.0.1-1 -> 1.0.2-1)
[2016-06-01 10:12] [ALPM] upgraded borg (1.0.2-1 -> 1.0.3-1)
[2016-07-11 13:22] [ALPM] upgraded borg (1.0.3-1 -> 1.0.5-1)
```

and now backup fails :

```
~ $ borg list /backup  ## /backup is cifs (w$ server)
Enter passphrase for key /backup: 
20160613                             Mon, 2016-06-13 11:34:32
20160615                             Wed, 2016-06-15 15:15:19
20160621                             Tue, 2016-06-21 09:57:41



~ $ borg info /backup::20160621
Enter passphrase for key /backup: 
Name: 20160621
Fingerprint: 40271f59866f87c293a8f0634f4ebca9f617ce8ad9d02041bc862d8485ef470
Hostname: archlinux
Username: user
Time (start): Tue, 2016-06-21 09:57:41
Time (end):   Tue, 2016-06-21 09:58:50
Command line: /usr/bin/borg create -v --stats /backup::20160621 /home/user
Number of files: 134298

                       Original size      Compressed size    Deduplicated size
This archive:                7.75 GB              7.76 GB             89.27 MB
All archives:               23.06 GB             23.08 GB              7.37 GB

                       Unique chunks         Total chunks
Chunk index:                   93078               399192



~ $ borg create -v --stats /backup::20160712 ~
Enter passphrase for key /backup: 
Exception ignored in: <bound method Repository.__del__ of <Repository /backup>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 72, in __del__
    self.close()
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 189, in close
    self.io.close()
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 532, in close
    self.close_segment()
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 752, in close_segment
    self._write_fd.flush()
ValueError: flush of closed file
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 81, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 247, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 219, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 275, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3.5/site-packages/borg/archive.py", line 666, in process_file
    chunks.append(cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats))
  File "/usr/lib/python3.5/site-packages/borg/cache.py", line 365, in add_chunk
    self.repository.put(id, data, wait=False)
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 481, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 721, in write_put
    fd = self.get_write_fd(raise_full=raise_full)
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 608, in get_write_fd
    self.close_segment()
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 759, in close_segment
    sync_dir(os.path.dirname(self._write_fd.name))
  File "/usr/lib/python3.5/site-packages/borg/platform.py", line 9, in sync_dir
    os.fsync(fd)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1601, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1538, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 81, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 94, in __exit__
    self.close()
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 189, in close
    self.io.close()
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 532, in close
    self.close_segment()
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 752, in close_segment
    self._write_fd.flush()
ValueError: flush of closed file

Platform: Linux archlinux 4.4.14-1-lts #1 SMP Fri Jun 24 21:35:25 CEST 2016 x86_64 
Linux: arch  
Borg: 1.0.5  Python: CPython 3.5.2
PID: 8978  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '/backup::20160712', '/home/user']
SSH_ORIGINAL_COMMAND: None



~ $ borg list /backup/
Failed to create/acquire the lock /backup/lock.exclusive (timeout).
```

**Comment by enkore** [comment] 2016-07-12 10:24
What is the filesystem your repository is stored on?

There's a known regression introduced in 1.0.4 that's causing problems with CIFS/SMB (#1287). It will be fixed in 1.0.6 (due today).

**Comment by patatetom** [comment] 2016-07-12 10:35
Windows (ntfs/cifs) :

```
~ # mount | grep backup
... on /backup type cifs (rw,relatime,vers=1.0,cache=strict,username=...,domain=...,uid=1000,forceuid,gid=0,noforcegid,addr=...,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=61440,wsize=65536,actimeo=1)
```

**Comment by enkore** [comment] 2016-07-12 10:38
Ok, thanks for the bug report. Will be fixed in 1.0.6 (you can try 1.0.6rc1 right now, if you like).

**Closed by enkore** 2016-07-12 10:38 UTC

**Comment by patatetom** [comment] 2016-07-12 10:51
ok, thanks.

**Comment by patatetom** [comment] 2016-07-12 11:42
update to 1.0.6rc1 :

```
~ # pip install -U borgbackup==1.0.6rc1
Collecting borgbackup==1.0.6rc1
  Downloading borgbackup-1.0.6rc1.tar.gz (447kB)
    100% |████████████████████████████████| 450kB 221kB/s 
Requirement already up-to-date: msgpack-python>=0.4.6 in /usr/lib/python3.5/site-packages (from borgbackup==1.0.6rc1)
Building wheels for collected packages: borgbackup
  Running setup.py bdist_wheel for borgbackup ... done
  Stored in directory: /root/.cache/pip/wheels/f5/78/05/3fa8f0eefb6dfd774ae3608d744aef61a31441a9dc9d17c4c7
Successfully built borgbackup
Installing collected packages: borgbackup
  Found existing installation: borgbackup 1.0.5
    Uninstalling borgbackup-1.0.5:
      Successfully uninstalled borgbackup-1.0.5
Successfully installed borgbackup-1.0.6rc1
```

and now it's ok :

```
~ $ borg --version
borg 1.0.6rc1


~ $ borg list /backup
Enter passphrase for key /backup: 
20160613                             Mon, 2016-06-13 11:34:32
20160615                             Wed, 2016-06-15 15:15:19
20160621                             Tue, 2016-06-21 09:57:41


~ $ borg create -v --stats /backup::20160712 ~
Enter passphrase for key /backup: 
------------------------------------------------------------------------------
Archive name: 20160712
Archive fingerprint: a04a3a1d200213010cbf42cbf3092b4c3847a79063b325b37f0b274ff185ac0
Time (start): Tue, 2016-07-12 13:36:12
Time (end):   Tue, 2016-07-12 13:37:36
Duration: 1 minutes 24.08 seconds
Number of files: 135354
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                7.78 GB              7.78 GB            148.26 MB
All archives:               30.84 GB             30.86 GB              7.52 GB

                       Unique chunks         Total chunks
Chunk index:                   94066               537876
------------------------------------------------------------------------------


~ $ borg list /backup
Enter passphrase for key /backup: 
20160613                             Mon, 2016-06-13 11:34:32
20160615                             Wed, 2016-06-15 15:15:19
20160621                             Tue, 2016-06-21 09:57:41
20160712                             Tue, 2016-07-12 13:36:12
```
