### ISSUE TITLE
Bountysource introduces 2-year-timeout for bounties

### ISSUE THREAD

**Issue by fantasya-pbem** [borgbackup/borg#5230] opened 2020-06-17 05:45 UTC
Bountysource will change its terms of service on July 1st, 2020:

_„If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.“_

BorgBackup has already a bunch of old bounties there which sum up to about $2500. I suggest you check their terms of service change and try to save at least some of the bounties.

**Comment by aidantwoods** [comment] 2020-06-17 08:02
Just to make the urgency here abundantly clear: the two year clock will start from the original date the bounty was posted (not the new ToS date). Which means on July 1st, any old bounties will be lost. 

> For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

**Comment by ThomasWaldmann** [comment] 2020-06-17 15:26
Guess I don't need a crystal ball to see major trust issues in bountysource's immediate future...

**Comment by ThomasWaldmann** [comment] 2020-06-17 15:35
List of affected tickets with bounties and backers:
- #37 by many backers
- #14 by borgbackup
- #465 by borgbackup and kirrus
- #1289 by borgbackup
- #2209 by borgbackup
- #900 by borgbackup
- #2444 by borgbackup
- #3494 by borgbackup
- #2870 by borgbackup
- #1553 by borgbackup and thomaswaldmann

**Comment by ThomasWaldmann** [comment] 2020-06-17 15:42
For the bounties where the backing was organized by me (backers thomaswaldmann and also borgbackup) I will just close the bounties and claim them.

Guess I trust myself more than bountysource right now. :-)

**Comment by ThomasWaldmann** [comment] 2020-06-17 16:18
Considering #37, this is a copy of my email to support@bountysource.com as of 2020-06-17 18:16 CEST:

Considering your upcoming ToS change: I find that pretty much unacceptable and I guess I don't need a crystal ball to see major trust issues in bountysource's immediate future caused by that.


As the borgbackup github project and borgbackup bountysource organisation administrator and one of the backers of that bounty, I request that all backing on this bounty

https://www.bountysource.com/issues/17668505-multithreading

(total USD 1500)

gets transferred to that bounty

https://www.bountysource.com/issues/91760112-multithreading

(currently at USD 10, which i needed to create the new bounty)

There should be no expiry on the new bounty (or the longest possible one, in case no expiry is not possible).

**Comment by ThomasWaldmann** [comment] 2020-06-17 17:04
related HN discussion: https://news.ycombinator.com/item?id=23551098

**Comment by ThomasWaldmann** [comment] 2020-06-17 17:07
Here's the full text of their new ToS section 2.13:

2.13 Bounty Time-Out. If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

**Comment by ThomasWaldmann** [comment] 2020-06-17 17:10
Notable: they say the **backer** needs to redeploy, so e.g. all 16 backers of #37 need to write an email similar to as I did.

as org admin, i try to get them to redeploy of **all backings** of #37, but maybe they would really want 16 emails for that. or keep the money, if a backer does not write that email.

**Comment by ThomasWaldmann** [comment] 2020-06-17 17:13
## Suggestion for backer redeploy request email:

As a backer (account name: XXX, account email: XXX), I request that all my backing (total USD XXX) on this bounty

https://www.bountysource.com/issues/17668505-multithreading

gets redeployed to that bounty

https://www.bountysource.com/issues/91760112-multithreading .

**Comment by aidantwoods** [comment] 2020-06-17 17:20
How much is locked up in other bounties? Not a perfect solution, but it might be worth going round the issues and trying to contact everyone that posted a bounty to encourage redeploying to a newer bounty so that there's more time to claim it towards project development. 

Based on the wording in the new ToS, it would appear this isn't even an option for anything that happens to be slightly newer than 2 years old, with say a bounty posted on 1st July 2018 having only a couple weeks before being lost, but not having the redeploy option :(

**Comment by ThomasWaldmann** [comment] 2020-06-17 17:36
I didn't sum it up yet, but the other tickets are significantly less value compared to #37.

**Comment by rugk** [comment] 2020-06-17 18:11
Wtf bountysource. Actually they also seem to have deleted my account (although I think it had something backed to this :thinking:).

Anyway, as for the other issues: I hope you will also reopen the issues when this is finished, won't you? :smile:

**Comment by m3nu** [comment] 2020-06-18 01:05
Already withdrawn:

> Withdrawal of new Terms of Service 
> Yesterday, we communicated a change to the Bountysource Terms of Service (ToS) agreement.
> These changes have been withdrawn and the ToS reverted to its prior state.
> The ToS will be revised and clarified in the future.

**Comment by level323** [comment] 2020-06-18 01:50
@ThomasWaldmann isn't there still a bounty on #916 also?

https://www.bountysource.com/issues/33011952-many-servers-without-cache-rebuilding

**Comment by ThomasWaldmann** [comment] 2020-06-18 13:18
@level323 oh, yeah, I missed that one - I added it to the list (but didn't close it [yet?]).

**Comment by ThomasWaldmann** [comment] 2020-06-18 13:19
So, considering they pulled back but their try still leaving a bad impression, do you think we should do anything about the old bounties and/or about bountysource in general?

**Comment by kirrus** [comment] 2020-06-18 13:30
Re my  $50 bounty on #465 , I'm okay it going to borg generally. Gonna be a while before I trust bountysource again.

**Comment by Gu1nness** [comment] 2020-06-25 16:35
Maybe there are some other bounty services that are better than bounty source and that would not even try to implement such ToS ?
We could setup a workgroup in order to find another service or do you think borgbackup will go on using BountySource ?

**Comment by ThomasWaldmann** [comment] 2020-07-07 15:48
I'll reopen the issues now that were closed just because of the announced (but then taken back) ToS change...

**Comment by ThomasWaldmann** [comment] 2020-07-07 22:00
So, guess this issue can be closed.

What remains is a trust issue in bountysource... :-(

**Closed by ThomasWaldmann** 2020-07-07 22:00 UTC
Labels: Bountysource
