### ISSUE TITLE
borg delete repo hangs with restricted ssh

### ISSUE THREAD

**Issue by gleb** [borgbackup/borg#1789] opened 2016-10-31 21:27 UTC
I setup rsync.net to use ssh forced command as per docs http://borgbackup.readthedocs.io/en/latest/usage.html#borg-serve

```
command="borg1 serve --restrict-to-path /data/home/1111/backup",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc ssh-rsa AAA...
```

This mostly works fine.   However deleting the repo hangs after I answer yes to the confirmation.  The repo is not deleted   After I kill the client with C-c I can run other borg commands on this repo.

```
export BORG_REPO='myhost.rsync.net:backup/foo'
borg init
borg create ::test-archive backup-test 
borg delete ::test-archive
borg delete ::  # this hangs
```

Before I added forced command deleting repo worked fine.

**Comment by ThomasWaldmann** [comment] 2016-10-31 23:22
So, your home directory there is /data/home/1111 ?

**Comment by gleb** [comment] 2016-10-31 23:28
No.  I censored my real user id, hostname, home path, and subdirectories

**Comment by gleb** [comment] 2016-10-31 23:31
But aside of those censor'ed things, yes that is the home directory

**Comment by enkore** [comment] 2016-11-01 00:24
I can't reproduce this. I created another SSH key and configured it exactly like yours above (on rsync.net); moving my normally used rsync.net key out of the way I used BORG_RSH='ssh -i <key>` to force the appropriate key. The forced command works as it should (--remote-path has no influence anymore).

```
$ BORG_RSH='ssh -i id_ed2' borg delete rsyncnet:i1789
You requested to completely DELETE the repository *including* all archives it contains:
test                                 Tue, 2016-11-01 01:16:33
Type 'YES' if you understand this and want to continue: YES
$
```

**Comment by gleb** [comment] 2016-11-01 00:51
Let me try to reproduce this again.   I've seen this couple of times, but in the writeup I probably missed some step that didn't seem important but was.

**Comment by gleb** [comment] 2016-11-01 01:09
I reproduced it, but it turns out to be more of UX/user error.   If you type in lower case "yes" and press Enter borg does nothing, just sits there. Press Enter again and it exits.  Interestingly when you type in "no" the behavior is different.  And "YES" does work.  Needless to say I can reproduce this with local repos same as rsync.net

```
$ borg delete ::
You requested to completely DELETE the repository *including* all archives it contains:
Type 'YES' if you understand this and want to continue: yes

$ 
$ borg delete ::
You requested to completely DELETE the repository *including* all archives it contains:
Type 'YES' if you understand this and want to continue: no
Aborting.
$ borg delete ::
You requested to completely DELETE the repository *including* all archives it contains:
Type 'YES' if you understand this and want to continue: YES
$
```

**Comment by gleb** [comment] 2016-11-01 01:25
This is borg 1.0.7 on Ubuntu 16.04

**Comment by gleb** [comment] 2016-11-01 01:35
Looking at the code, think it was fixed in 7b9d0c9739c459066caad9122eb92505d13a6c16

**Comment by ThomasWaldmann** [comment] 2016-11-01 02:56
Yup, that was that. Closing.

**Closed by ThomasWaldmann** 2016-11-01 02:56 UTC

**Comment by enkore** [comment] 2016-11-01 09:20
Thanks!

Duplicate of #1622
