### ISSUE TITLE
Crash creating a backup 

### ISSUE THREAD

**Issue by blablup** [borgbackup/borg#2305] opened 2017-03-15 10:45 UTC
Hello,

I just started to try borg because it looks promising. 
I installed borg an a arch machine via AUR and on a debian jessie by packaging the newest beta  myself. 
Now i got a crash doing a backup:

BORG_PASSPHRASE=XXX borg create -x -v -p --exclude-caches  --stats --compression lzma,2 test@10.232.40.52:backup::'{hostname}-{now:%Y-%m-%d}_3' /root /home --exclude-from /root/.config/borg/ignore
Local Exception GB C 1.24 GB D 105081 N home/myuser/configs/proxy/lpx000d01/squid3/errors/en/ERR_AGENT_WPAD                                                      
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 3457, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 3385, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 116, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 475, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 439, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 3 more times]
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 511, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 970, in process_file
    self.add_item(item)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 431, in add_item
    self.items_buffer.add(item)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 229, in add
    self.buffer.write(self.packer.pack(item.as_dict()))
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 203, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2925)
  File "msgpack/_packer.pyx", line 152, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2068)
  File "msgpack/_packer.pyx", line 144, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:1925)
OverflowError: Python int too large to convert to C long

Platform: Linux C000-NB-32085 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 
Linux: arch  
Borg: 1.1.0b4.dev214+ng21178617  Python: CPython 3.6.0
PID: 3385  CWD: /root
sys.argv: ['/usr/bin/borg', 'create', '-x', '-v', '-p', '--exclude-caches', '--stats', '--compression', 'lzma,2', 'test@10.232.40.52:backup::{hostname}-{now:%Y-%m-%d}_3', '/root', '/home', '--exclude-from', '/root/.config/borg/ignore']
SSH_ORIGINAL_COMMAND: None

Kind regards

**Comment by Abogical** [comment] 2017-03-15 11:14
This looks familiar to #2304

**Comment by enkore** [comment] 2017-03-15 11:21
Use `-v --list` to find which file exactly is causing the crash - is there something interesting about it (`stat`), like very-far in the future timestamps or something like that?

**Comment by blablup** [comment] 2017-03-15 11:56
The file looks good to me:

d /home/myuser/configs/proxy/lpx000d01/squidGuard
A /home/myuser/configs/proxy/lpx000d01/reports/exclude_hosts
A /home/myuser/configs/proxy/lpx000d01/reports/sarg.conf
d /home/myuser/configs/proxy/lpx000d01/reports
d /home/myuser/configs/proxy/lpx000d01/.git/branches
Local Exception
Traceback (most recent call last):


C000-NB-32085# stat /home/myuser/configs/proxy/lpx000d01/.git/branches
  Datei: /home/myuser/configs/proxy/lpx000d01/.git/branches
  Größe: 0         	Blöcke: 0          EA Block: 4096   Verzeichnis
Gerät: 34h/52d	Inode: 207254      Verknüpfungen: 1
Zugriff: (0755/drwxr-xr-x)  Uid: ( 1000/l0003366129)   Gid: (  100/   users)
Zugriff    : 2017-03-14 15:12:09.523264738 +0100
Modifiziert: 2013-02-06 12:49:11.000000000 +0100
Geändert   : 2014-12-11 16:23:14.487529643 +0100
 Geburt    : -
C000-NB-32085# 


Also if I restart it, it will have another file, so it's not the file. It looks like every time bork finishes around 20 more files.

**Comment by enkore** [comment] 2017-03-15 11:58
Hmm, that's strange

**Comment by Abogical** [comment] 2017-03-15 12:15
I don't think this has to do with timestamps

**Comment by enkore** [comment] 2017-03-15 12:19
There's flags, size, user and group IDs, link counts and for device files stuff like the rdev (maj/min device numbers). `class Item` in item.pyx has a list.

**Comment by enkore** [comment] 2017-03-15 13:24
Try this diff:

```diff
@ archive.py:433 @ def iter_items(self, filter=None, preload=False):
    def add_item(self, item, show_progress=True):
        if show_progress and self.show_progress:
            self.stats.show_progress(item=item, dt=0.2)
        print(item)
        self.items_buffer.add(item)

    def write_checkpoint(self):
```

Then we should see which field exactly is the issue here.

**Comment by blablup** [comment] 2017-03-15 14:00
Sorry, I have to correct that the last 3 times it always stopped at a specific directory:

[root@C000-NB-32085 ~]# stat /home/myuser/configs/proxy/lpx000d01/.git/branches
  Datei: /home/myuser/configs/proxy/lpx000d01/.git/branches
  Größe: 0         	Blöcke: 0          EA Block: 4096   Verzeichnis
Gerät: 35h/53d	Inode: 207254      Verknüpfungen: 1
Zugriff: (0755/drwxr-xr-x)  Uid: ( 1000/l0003366129)   Gid: (  100/   users)
Zugriff    : 2017-03-14 15:12:09.523264738 +0100
Modifiziert: 2013-02-06 12:49:11.000000000 +0100
Geändert   : 2014-12-11 16:23:14.487529643 +0100
 Geburt    : -

**Comment by blablup** [comment] 2017-03-15 14:30
Found it, Problem was that the last file which worked was printed. The File which had the Problem has a suspicious atime. This is same Problem like #2304 


[root@C000-NB-32085 ~]# stat /home/l0003366129/configs/proxy/lpx000d01/.git/refs/heads/master
  Datei: /home/l0003366129/configs/proxy/lpx000d01/.git/refs/heads/master
  Größe: 41        	Blöcke: 8          EA Block: 4096   reguläre Datei
Gerät: 35h/53d	Inode: 213172      Verknüpfungen: 1
Zugriff: (0644/-rw-r--r--)  Uid: ( 1000/l0003366129)   Gid: (  100/   users)
Zugriff    : -6698727701578022144.000000000
Modifiziert: 2014-08-20 14:27:59.000000000 +0200
Geändert   : 2014-12-11 16:21:59.694175706 +0100
 Geburt    : -

Here is the log output:

Item(internal_dict={'path': b'home/l0003366129/configs/proxy/lpx000d01/.git/refs/heads/master', 'hardlink_master': False, 'mode': 33188, 'uid': 1000, 'gid': 100, 'mtime': 1408537679000000000, 'atime': -6698727701578022144000000000, 'ctime': 1418311319694175706, 'user': b'l0003366129', 'group': b'users', 'chunks': [ChunkListEntry(id=b'm\x036e\x17\xb9V\xa6\xdb\x8d\xc4Lb\xe6y\xf3\x93\x08S\x98\xac\xff\xb9\xe2\n\xc0\x8cw\xb1\x98\xac\xf2', size=41, csize=135)], 'size': 41})
Local Exception

**Comment by Abogical** [comment] 2017-03-15 14:55
Great! this should now be closed as duplicate of #2304.

**Comment by enkore** [comment] 2017-03-15 14:59
That's... curious.

-6698727701578022144000000000 is a huuuge timestamp. It just-so fits into a 64-bit timespec (64 bit seconds + separate nanoseconds), but is too large for most date handling routines. Converting it manually: It's 212 billion years ago.

If you don't mind, what's the filesystem this is on?

**Comment by ThomasWaldmann** [comment] 2017-03-15 15:58
closing this as duplicate of #2304 to avoid double work. seems to be "bad timestamp day" today.

**Closed by ThomasWaldmann** 2017-03-15 15:58 UTC
Labels: duplicate
