### ISSUE TITLE
Undefined symbol with FreeBSD release on 10.1

### ISSUE THREAD

**Issue by AaronM04** [borgbackup/borg#807] opened 2016-03-27 17:17 UTC
```
% sha256 ~/bin/borg
SHA256 (/home/freebsd/bin/borg) = 0f41e4d4e7cca705579102c163104c91611ca3a17d15458c373b91f32fd6936c
% ~/bin/borg
/tmp/_MEIsbx5Qc/libthr.so.3: Undefined symbol "__set_error_selector"
% freebsd-version
10.1-RELEASE-p31
```

**Comment by rumpelsepp** [comment] 2016-03-27 18:19
Aside from that, you can now build a native pkg: https://github.com/borgbackup/borg/issues/105#issuecomment-201270876

**Comment by enkore** [comment] 2016-03-27 18:29
Duplicate of #744?

**Comment by ThomasWaldmann** [comment] 2016-04-03 19:12
The binaries are built on 10.2, so that could be the reason why they don't work on older releases.

I am not a FreeBSD user myself and i don't know about compatibility properties.

Would building on a older (but still security-supported) freebsd help?
Do older binaries run on newer freebsds in general or do we then get just the opposite problem?

**Comment by ThomasWaldmann** [comment] 2016-04-05 21:38
closing, issue is expected. if you have an idea how to do better, add it here and reopen the ticket.

**Closed by ThomasWaldmann** 2016-04-05 21:38 UTC
