### ISSUE TITLE
Data integrity error when creating backup using google-drive-ocamlfuse

### ISSUE THREAD

**Issue by michamos** [borgbackup/borg#469] opened 2015-12-06 15:01 UTC
Hello,

When backing up to a Google Drive mounted with [googe-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse), I got the following error:

```
$ borg create drive/backup::test-Dropbox-lzma Dropbox -ps -C lzma                                                                                                                                                                       ⏎
Enter passphrase for key drive/backup: 
Enter passphrase for key drive/backup: 
reading files cache
processing files
Data integrity error
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 1206, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 1160, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 170, in do_create
  File "/vagrant/borg/borg/borg/archiver.py", line 231, in _process
  File "/vagrant/borg/borg/borg/archiver.py", line 231, in _process
  File "/vagrant/borg/borg/borg/archiver.py", line 231, in _process
  File "/vagrant/borg/borg/borg/archiver.py", line 208, in _process
  File "/vagrant/borg/borg/borg/archive.py", line 542, in process_file
  File "/vagrant/borg/borg/borg/archive.py", line 224, in add_item
  File "/vagrant/borg/borg/borg/archive.py", line 228, in write_checkpoint
  File "/vagrant/borg/borg/borg/archive.py", line 253, in save
  File "/vagrant/borg/borg/borg/repository.py", line 158, in commit
  File "/vagrant/borg/borg/borg/repository.py", line 219, in compact_segments
  File "/vagrant/borg/borg/borg/repository.py", line 527, in iter_objects
borg.helpers.IntegrityError: Invalid segment magic [segment 18, offset 0]
```

This happened with the 64bit v0.28.2 binary release.

# Some background
I am trying to set-up remote backups on Google Drive using borg.
The most straightforward way would be to backup locally and then upload, but I want to use encryption for the remote backup (for the local one I don't) and I lack the disk space to make two local backups. Hence the need to do the remote backup in one step.
As Google Drive is not natively supported by borg, I tried to use [googe-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse) to mount my google drive using FUSE, and perform what should be, from borg's point of view, a regular local backup. Unfortunately, my first test failed with the aforementioned error. 

# Some questions

- Does this mean that google-drive-ocamlfuse is corrupting my backup, or is its filesystem implementation somehow lacking?
- Is there a better way to backup to google drive or is the only reliable option to upload a local backup?

**Comment by ThomasWaldmann** [comment] 2015-12-06 16:02
I would suspect that the answer to your first question is yes, because what fails is the check for the "magic", which is just a few bytes at the beginning of each segment file. Can't imagine writing these is somehow going wrong on our side.

About your second question: I don't use any cloud backup, so I can't help much on that. In theory, it could be possible to add a special backend for google drive (see also the ticket about adding S3 support), but that's quite a lot of work and not trivial. There is rsync.net though, they offer remote backup space and support borgbackup.

**Comment by ThomasWaldmann** [comment] 2015-12-06 16:04
I tagged it wontfix for now as this is extremely likely not a bug on our side. I'll leave this issue open for a while so we can get more feedback on the topic, but I'll also close it later.

**Comment by ThomasWaldmann** [comment] 2015-12-27 13:30
OK, seems like noone has to give feedback here, so I am closing this.

 As it likely is a google-drive-ocamlfuse issue, I suggest you open a ticket there.

**Closed by ThomasWaldmann** 2015-12-27 13:30 UTC
Labels: wontfix

**Comment by michamos** [comment] 2015-12-28 19:50
OK, thanks for your comments!

**Comment by bgemmill** [comment] 2016-11-10 02:29
@ThomasWaldmann I see this happen on acdcli when an error occurs and a 0 byte file is left behind. Would it be possible to detect that case?

**Comment by ThomasWaldmann** [comment] 2016-11-10 03:10
@bgemmill right, this can be (also) triggered by a 0 bytes segment file.

but the point is, there should be no 0 bytes segment file, this points to a malfunction in the filesystem.
in your case, what does borg check say?

**Comment by bgemmill** [comment] 2016-11-10 03:21
With nearly a 1TB backup on amazon, it says "replaying segments" for about 20 minutes and then this error on a 0 byte file, and then borg crashes.

Totally agreed it's a filesystem problem. Luckily I'm one of the authors of the filesystem in question :-) An earlier run of acdcli gave a 1000 error code on that file, and I've since changed my PR of acdcli to retry file operations through that code so this doesn't happen again.

That said, it still leaves a borg repo in a funny state... I'd imagine that the backups that required the file are in need of repair.

Would it be possible to have this error mark the affected backups as bad somehow and move on rather than crashing borg?

If not, what should I do about a repo in this state?

Thanks a lot for all the help.

**Comment by ThomasWaldmann** [comment] 2016-11-10 03:31
are you saying borg check crashes on this? that should not be the case, please open a new ticket about that and provide all needed infos.

**Comment by plmuon** [comment] 2017-02-07 19:29
Hello,

I had a data integrity error at the end of a very long (12TB) borg check --repair:

```
Data integrity error: Segment entry checksum mismatch [segment 12555, offset 1752715]                                                               
Traceback (most recent call last):                                                                                                                  
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 2052, in main                                                                      
    exit_code = archiver.run(args)                                                                                                                  
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1997, in run                                                                       
    return func(args)                                                                                                                               
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 90, in wrapper                                                                     
    return method(self, args, repository=repository, **kwargs)                                                                                      
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 168, in do_check                                                                   
    if not repository.check(repair=args.repair, save_space=args.save_space):                                                                        
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 480, in check                                                                    
    self.compact_segments(save_space=save_space)                                                                                                    
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 300, in compact_segments                                                         
    for tag, key, offset, data in self.io.iter_objects(segment, include_data=True):                                                                 
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 705, in iter_objects                                                             
    (TAG_PUT, TAG_DELETE, TAG_COMMIT))                                                                                                              
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 781, in _read                                                                    
    segment, offset))                                                                                                                               
borg.helpers.IntegrityError: Segment entry checksum mismatch [segment 12555, offset 1752715]                                                        
                                                                                                                                                    
Platform: Linux d4f04c9c37e9 3.12.6 #1 SMP Wed Dec 14 01:35:05 CST 2016 x86_64                                                                      
Linux:                                                                                                                                              
Borg: 1.0.9  Python: CPython 3.5.2                                                                                                                  
PID: 16  CWD: /data                                                                                                                                 
sys.argv: ['/usr/bin/borg', 'check', '-v', '--repair', 'borg-sol-data']                                                                             
SSH_ORIGINAL_COMMAND: None                                                                         
```

I was doing the check first on the box itself (local filesystem on a NAS, borg in a docker container), then on another server that has the borg-backup mounted through NFS.

I fear I have to re-create my whole archive?

**Comment by enkore** [comment] 2017-02-07 19:35
Try to re-run it, the trace indicates that some data was first read OK but a later read was corrupted. More importantly, check your logs (dmesg, smartctl) if there are issues with the disks.
