### ISSUE TITLE
Better progress report for delete

### ISSUE THREAD

**Issue by Narfinger** [borgbackup/borg#1621] opened 2016-09-20 13:54 UTC
At the moment a delete only shows a progress report for changing the references but nothing after that. Would it be possible to get more information while it is doing whatever it is doing?

**Comment by enkore** [comment] 2016-09-20 14:24
Yes, in 1.1.x we also have progress for the phase after that ("Compacting segments").

Duplicate of #1115 (has more details on this)

**Closed by enkore** 2016-09-20 14:24 UTC
Labels: duplicate
