### ISSUE TITLE
Data integrity error on prune

### ISSUE THREAD

**Issue by zeroone82** [borgbackup/borg#5515] opened 2020-11-19 16:45 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

borg 1.1.10

#### Operating system (distribution) and version.

Debian 8.11, Debian 6.0.10

#### Hardware / network configuration, and filesystems used.

Remote SSH, ext4 on source and destination

#### How much data is handled by borg?

30GB~ per repository

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg prune -v --stats --list --keep-daily=61 --keep-weekly=8 --keep-monthly=2 --keep-yearly=0 2>> borg.log

## Describe the problem you're observing.

I have a server with multiple borg repositories, one repository per host. Client host have append-only access to their repository, so I run prune from the server instead of client host.
On some of this repositories I'm getting the following error when running prune:
`Data integrity error: Invalid segment entry size 0 - too small [segment 163, offset 200401095]`
Segment and offset change with every repository.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I'm having the issue with multiple hosts. What I noticed is that all hosts with problems are running Debian 6 and borg 1.1.10.
Server is running Debian 8 and borg 1.1.10 (could probably upgrade to 1.1.14)

If I run 
`borg check --repair /repo/client`
on the server, I can then correctly run a prune job without errors.

#### Include any warning/errors/backtraces from the system logs

```
Traceback (most recent call last):
  File "borg/archiver.py", line 4501, in main
  File "borg/archiver.py", line 4433, in run
  File "borg/archiver.py", line 166, in wrapper
  File "borg/archiver.py", line 1609, in do_prune
  File "borg/archive.py", line 844, in delete
  File "borg/archive.py", line 821, in chunk_decref
  File "borg/cache.py", line 925, in chunk_decref
  File "borg/repository.py", line 1125, in delete
  File "borg/repository.py", line 1440, in read
  File "borg/repository.py", line 1467, in _read
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry size 0 - too small [segment 341, offset 7708436]

Platform: Linux storage 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64
Linux: debian 8.11
Borg: 1.1.10  Python: CPython 3.5.7 msgpack: 0.5.6
PID: 22612  CWD: /etc/borg/client
sys.argv: ['/usr/local/bin/borg', 'prune', '-v', '--stats', '--list', '--keep-daily=61', '--keep-weekly=8', '--keep-monthly=2', '--keep-yearly=0']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment] 2020-11-19 16:53
1.1.10 is too old and has known bugs, you need at least 1.1.11 and preferably the latest stable release (1.1.14 currently).

Release < 1.1.11 had a severe bug in the hashtable code and the error you see could be caused by a corrupt repo index due to that bug. See the advisory at the top of the changelog about how to proceed.

For debian (ubuntu), check the backports repo (maintainer ppa) to get a fresh borg or use the fat binary offered here:

https://github.com/borgbackup/borg/releases

**Comment by ThomasWaldmann** [comment] 2020-11-19 17:02
The hashtable bug was also fixed by debian maintainers by patching their borg 1.1.9 package, see there:

https://metadata.ftp-master.debian.org/changelogs//main/b/borgbackup/borgbackup_1.1.9-2~bpo9+2_changelog

**Comment by zeroone82** [comment] 2020-11-19 17:22
I should've mentioned that I'm using the binaries provided from
https://github.com/borgbackup/borg/releases

I guess is time to upgrade to 1.1.11, newer releases don't seem to work with Debian 6 as it has libc6 2.11

**Comment by ThomasWaldmann** [comment] 2020-11-29 13:22
guess this is solved. if not, please add more information below.

**Closed by ThomasWaldmann** 2020-11-29 13:22 UTC
Labels: question
