### ISSUE TITLE
borg crashes if user doesn't have permission to access backup

### ISSUE THREAD

**Issue by leaf-node** [borgbackup/borg#854] opened 2016-04-07 00:33 UTC
If I forget to use sudo when accessing or updating a backup owned by root, I get a nasty traceback:

```
$ borg list ....
$ borg create ....
```

```
Failed to create/acquire the lock /run/media/andrew/super0/backups/borg-locutus/lock.exclusive ([Errno 13] Permission denied: '/run/media/andrew/super0/backups/borg-locutus/lock.exclusive').
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1466, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1420, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 437, in do_list
    repository = self.open_repository(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 67, in open_repository
    repository = Repository(location.path, create=create, exclusive=exclusive, lock_wait=self.lock_wait, lock=lock)
  File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 64, in __init__
    self.open(self.path, exclusive, lock_wait=lock_wait, lock=lock)
  File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 142, in open
    self.lock = UpgradableLock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
  File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 260, in acquire
    with self._lock:
  File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 117, in __enter__
    return self.acquire()
  File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 140, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: ('/run/media/andrew/super0/backups/borg-locutus/lock.exclusive', "[Errno 13] Permission denied: '/run/media/andrew/super0/backups/borg-locutus/lock.exclusive'")

Platform: Linux mudita 4.4.6-300.fc23.x86_64+debug #1 SMP Wed Mar 16 21:54:26 UTC 2016 x86_64 x86_64
Linux: Fedora 23 Twenty Three  LibC: glibc 2.3.4
Borg: 1.0.0  Python: CPython 3.4.3
PID: 23749  CWD: /run/media/andrew/super0
sys.argv: ['/usr/bin/borg', 'list', 'backups/borg-locutus/']
SSH_ORIGINAL_COMMAND: None
```

**Comment by Ape** [comment] 2016-04-07 05:21
I agree that it would be better to only print
```
[Errno 13] Permission denied: '/run/media/andrew/super0/backups/borg-locutus/lock.exclusive'
```

The failure is not a bug in borg, so the traceback is not really useful.

**Comment by Woi** [comment] 2021-01-31 23:06
A minimal example to reproduce:
    $ sudo borg init -e=none /tmp/borgtest/{hostname}
    $ borg create /tmp/borgtest/{hostname}::{now} ~
(Linux, Borg: 1.1.15  Python: CPython 3.8.7 msgpack: 0.5.6)

**Comment by Woi** [comment] 2021-01-31 23:10
Looks like a specific case of  #1973 which is more general

**Comment by ThomasWaldmann** [comment] 2023-07-01 23:19
Closing as a duplicate of #1973.

**Closed by ThomasWaldmann** 2023-07-01 23:19 UTC
