### ISSUE TITLE
Incorrect documentation for prune's `--keep-within` option?

### ISSUE THREAD

**Issue by TimWolla** [borgbackup/borg#7687] opened 2023-06-30 08:27 UTC
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

Documentation BUG

#### Your borg version (borg -V).

borg 1.1.16

#### Operating system (distribution) and version.

Debian Bullseye (11.7)

#### Hardware / network configuration, and filesystems used.

Dedicated Server with ZFS

#### How much data is handled by borg?

2 GB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg prune --dry-run --keep-within=3d --keep-daily=7 --list .`

## Describe the problem you're observing.

The documentation for prune's `--keep-within` flag states:

https://github.com/borgbackup/borg/blob/f43fcd3bdbf36f71b33661d69284469a52d8c72f/docs/usage/prune.rst.inc#L145-L146

> The archives kept with this option do not count towards the totals specified by any other options.

Which I understand as “the regular options apply and then anything within the given timeframe is also kept”. However this does not appear to match the actual behavior. Instead `--keep-within` appears to work like any of the other `--keep` options.

Specifically for the command line given above (--keep-within=3d --keep-daily=7) with at least 1 backup per calendar day I expect the oldest backup to be 7 days old (i.e. from June 23rd or possibly June 22nd). However the oldest that is kept is from June 20th:

```
$ borg prune --dry-run --keep-within=3d --keep-daily=7 --list .
Enter passphrase for key *snip*: 
Keeping archive: 20230630_010050                      Fri, 2023-06-30 01:00:51
Keeping archive: 20230629_052755                      Thu, 2023-06-29 05:27:56
Keeping archive: 20230628_095254                      Wed, 2023-06-28 09:52:55
Keeping archive: 20230627_141757                      Tue, 2023-06-27 14:17:58
Keeping archive: 20230626_184853                      Mon, 2023-06-26 18:48:55
Keeping archive: 20230625_231152                      Sun, 2023-06-25 23:11:53
Keeping archive: 20230624_075552                      Sat, 2023-06-24 07:55:53
Keeping archive: 20230623_123652                      Fri, 2023-06-23 12:36:53
Keeping archive: 20230622_165751                      Thu, 2023-06-22 16:57:52
Keeping archive: 20230621_214251                      Wed, 2023-06-21 21:42:52
Keeping archive: 20230620_063009                      Tue, 2023-06-20 06:30:10
Would prune:     20230619_103109                      Mon, 2023-06-19 10:31:10
Would prune:     20230618_151109                      Sun, 2023-06-18 15:11:10
Would prune:     20230617_193409                      Sat, 2023-06-17 19:34:10
Would prune:     20230616_041608                      Fri, 2023-06-16 04:16:09
Would prune:     20230615_081931                      Thu, 2023-06-15 08:19:31
Would prune:     20230614_122429                      Wed, 2023-06-14 12:24:30
Would prune:     20230611_053828                      Sun, 2023-06-11 05:38:29
Would prune:     20230604_173041                      Sun, 2023-06-04 17:30:42
Would prune:     20230528_105338                      Sun, 2023-05-28 10:53:39
Would prune:     20230521_223141                      Sun, 2023-05-21 22:31:42
Would prune:     20230514_150938                      Sun, 2023-05-14 15:09:39
Would prune:     20230507_055427                      Sun, 2023-05-07 05:54:28
```

Similarly for `--keep-within=14d --keep-weekly=4` I expect the oldest to be 4 weeks old, however in reality it is almost 6 weeks old, because the 4 weekly backups are added to the 14d:

```
$ borg prune --dry-run --keep-within=14d --keep-weekly=4 --list .
Enter passphrase for key *snip*: 
Keeping archive: 20230630_010050                      Fri, 2023-06-30 01:00:51
Keeping archive: 20230629_052755                      Thu, 2023-06-29 05:27:56
Keeping archive: 20230628_095254                      Wed, 2023-06-28 09:52:55
Keeping archive: 20230627_141757                      Tue, 2023-06-27 14:17:58
Keeping archive: 20230626_184853                      Mon, 2023-06-26 18:48:55
Keeping archive: 20230625_231152                      Sun, 2023-06-25 23:11:53
Keeping archive: 20230624_075552                      Sat, 2023-06-24 07:55:53
Keeping archive: 20230623_123652                      Fri, 2023-06-23 12:36:53
Keeping archive: 20230622_165751                      Thu, 2023-06-22 16:57:52
Keeping archive: 20230621_214251                      Wed, 2023-06-21 21:42:52
Keeping archive: 20230620_063009                      Tue, 2023-06-20 06:30:10
Keeping archive: 20230619_103109                      Mon, 2023-06-19 10:31:10
Keeping archive: 20230618_151109                      Sun, 2023-06-18 15:11:10
Keeping archive: 20230617_193409                      Sat, 2023-06-17 19:34:10
Would prune:     20230616_041608                      Fri, 2023-06-16 04:16:09
Would prune:     20230615_081931                      Thu, 2023-06-15 08:19:31
Would prune:     20230614_122429                      Wed, 2023-06-14 12:24:30
Keeping archive: 20230611_053828                      Sun, 2023-06-11 05:38:29
Keeping archive: 20230604_173041                      Sun, 2023-06-04 17:30:42
Keeping archive: 20230528_105338                      Sun, 2023-05-28 10:53:39
Keeping archive: 20230521_223141                      Sun, 2023-05-21 22:31:42
Would prune:     20230514_150938                      Sun, 2023-05-14 15:09:39
Would prune:     20230507_055427                      Sun, 2023-05-07 05:54:28
```

As users might rely on the actual behavior I consider it to be unfixable in practice and thus this probably is a documentation bug, not an implementation bug.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

This is trivially reproducible by observing the output of `borg prune`.

#### Include any warning/errors/backtraces from the system logs

n/a

**Comment by ThomasWaldmann** [comment] 2023-06-30 12:10
Please reproduce this with borg 1.2.x (preferably with 1.2.4):
- some issues might be fixed there
- it also explains better **why** prune will keep each of the kept archives (by specifying the rule that kept it)

You can get a 1.2.4 fat binary from github releases in case your dist doesn't offer one (check debian backports).

**Comment by ThomasWaldmann** [comment] 2023-06-30 12:23
That was quick. :-) OK, so we can close this again?

**Comment by TimWolla** [comment] 2023-06-30 12:28
> OK, so we can close this again?

No, because to my understanding the documentation differs from the actual behavior – unless I'm misunderstanding the documentation – which would indicate a bug either in the implementation or the documentation.

The documentation states for `--keep-within` that:

> The archives kept with this option do not count towards the totals specified by any other options.

Based on the documentation I would expect the following output:

```
$ /tmp/borg-linux64 prune --dry-run --keep-within=3d --keep-daily=7 --list .
Enter passphrase for key *snip*: 
Keeping archive (rule: daily #1, within #1):       20230630_010050                      Fri, 2023-06-30 01:00:51
Keeping archive (rule: daily #2, within #2):       20230629_052755                      Thu, 2023-06-29 05:27:56
Keeping archive (rule: daily #3, within #3):       20230628_095254                      Wed, 2023-06-28 09:52:55
Keeping archive (rule: daily #4, within #4):       20230627_141757                      Tue, 2023-06-27 14:17:58
Keeping archive (rule: daily #5):                  20230626_184853                      Mon, 2023-06-26 18:48:55
Keeping archive (rule: daily #6):                  20230625_231152                      Sun, 2023-06-25 23:11:53
Keeping archive (rule: daily #7):                  20230624_075552                      Sat, 2023-06-24 07:55:53
Would prune:                                       20230623_123652                      Fri, 2023-06-23 12:36:53
Would prune:                                       20230622_165751                      Thu, 2023-06-22 16:57:52
Would prune:                                       20230621_214251                      Wed, 2023-06-21 21:42:52
Would prune:                                       20230620_063009                      Tue, 2023-06-20 06:30:10
Would prune:                                       20230619_103109                      Mon, 2023-06-19 10:31:10
Would prune:                                       20230618_151109                      Sun, 2023-06-18 15:11:10
Would prune:                                       20230617_193409                      Sat, 2023-06-17 19:34:10
Would prune:                                       20230616_041608                      Fri, 2023-06-16 04:16:09
Would prune:                                       20230615_081931                      Thu, 2023-06-15 08:19:31
Would prune:                                       20230614_122429                      Wed, 2023-06-14 12:24:30
Would prune:                                       20230611_053828                      Sun, 2023-06-11 05:38:29
Would prune:                                       20230604_173041                      Sun, 2023-06-04 17:30:42
Would prune:                                       20230528_105338                      Sun, 2023-05-28 10:53:39
Would prune:                                       20230521_223141                      Sun, 2023-05-21 22:31:42
Would prune:                                       20230514_150938                      Sun, 2023-05-14 15:09:39
Would prune:                                       20230507_055427                      Sun, 2023-05-07 05:54:28
```

and

```
$ /tmp/borg-linux64 prune --dry-run --keep-within=14d --keep-weekly=4 --list .
Enter passphrase for key *snip*: 
Keeping archive (rule: weekly #1, within #1):       20230630_010050                      Fri, 2023-06-30 01:00:51
Keeping archive (rule: within #2):                  20230629_052755                      Thu, 2023-06-29 05:27:56
Keeping archive (rule: within #3):                  20230628_095254                      Wed, 2023-06-28 09:52:55
Keeping archive (rule: within #4):                  20230627_141757                      Tue, 2023-06-27 14:17:58
Keeping archive (rule: within #5):                  20230626_184853                      Mon, 2023-06-26 18:48:55
Keeping archive (rule: weekly #2, within #6):       20230625_231152                      Sun, 2023-06-25 23:11:53
Keeping archive (rule: within #7):                  20230624_075552                      Sat, 2023-06-24 07:55:53
Keeping archive (rule: within #8):                  20230623_123652                      Fri, 2023-06-23 12:36:53
Keeping archive (rule: within #9):                  20230622_165751                      Thu, 2023-06-22 16:57:52
Keeping archive (rule: within #10):                 20230621_214251                      Wed, 2023-06-21 21:42:52
Keeping archive (rule: within #11):                 20230620_063009                      Tue, 2023-06-20 06:30:10
Keeping archive (rule: within #12):                 20230619_103109                      Mon, 2023-06-19 10:31:10
Keeping archive (rule: weekly #3, within #13):      20230618_151109                      Sun, 2023-06-18 15:11:10
Keeping archive (rule: within #14):                 20230617_193409                      Sat, 2023-06-17 19:34:10
Would prune:                                        20230616_041608                      Fri, 2023-06-16 04:16:09
Would prune:                                        20230615_081931                      Thu, 2023-06-15 08:19:31
Would prune:                                        20230614_122429                      Wed, 2023-06-14 12:24:30
Keeping archive (rule: weekly #4):                  20230611_053828                      Sun, 2023-06-11 05:38:29
Would prune:                                        20230604_173041                      Sun, 2023-06-04 17:30:42
Would prune:                                        20230528_105338                      Sun, 2023-05-28 10:53:39
Would prune:                                        20230521_223141                      Sun, 2023-05-21 22:31:42
Would prune:                                        20230514_150938                      Sun, 2023-05-14 15:09:39
Would prune:                                        20230507_055427                      Sun, 2023-05-07 05:54:28
```

**Comment by ThomasWaldmann** [comment] 2023-06-30 12:41
Hmm, guess we need a native english speaker here. :-)

I understand it like this:

- if you just say "keep daily 7", it keeps 7 daily backups.
- if you, additionally to "keep daily 7", also say "keep within 3 days", it additionally keeps all backups within the last 3 days.
- "do not count towards" means that the backups kept via "keep within 3 days" do **not reduce / do not influence** the number of backups kept via "keep daily 7"

**Comment by TimWolla** [comment] 2023-06-30 12:57
> "do not count towards" means that the backups kept via "keep within 3 days" do **not reduce / do not influence** the number of backups kept via "keep daily 7"

But this is no different from the other `--keep-*` options. They all work in addition to each other, as also is documented:

> The rules are applied from secondly to yearly, and backups selected by previous rules do not count towards those of later rules.

Anything kept by `--keep-daily` is ignored when processing `--keep-weekly` (and vice versa).

So I'm confused why `--keep-within` needs this special mention when it works exactly like the other options :thinking: 

----------------

In fact I would find `--keep-within` more useful if it would work like how I understood the documentation, because it works relative to the current time, instead of looking at specific “calendar chunks”.

It would allow me to keep 14 daily backups + 6 weekly backups + anything created in the last 48 hours in case there are extra backups created on manual request by doing `--keep-within=2d --keep-daily=14 --keep-weekly=6`. Currently I would have to subtract the `within=2d` from `daily=14`.

But that ship probably has long sailed :smile: 

> Hmm, guess we need a native english speaker here. :-)

FWIW: My native language is German, just like what I assume is yours. My German-speaking co-worker understood the documentation just like I did and this is what caused me to actually check it once more, because the observed behavior we both remembered was different.

**Comment by ThomasWaldmann** [comment] 2023-06-30 13:09
Well, you are saying that the "do not count towards" is redundantly specified there because that is the usual behaviour for all these options anyway.

But that should not lead you to understand the complete opposite to what it is saying / to how the other options behave.

**Comment by ThomasWaldmann** [comment] 2023-06-30 13:23
About changing anything there: yeah, I guess too that ship has long sailed. :-) we could change it easily in the code of course, but that would impact a lot of prune setups of users, **deleting more than before** - guess that wouldn't be expected.

Also, doing it differently might just confuse other people...

**Comment by TimWolla** [comment] 2023-06-30 13:25
The redundancy probably caused the misunderstanding (possibly combined with a little ambiguous wording / foreign language problems). If it gets an extra mention then my assumption is that it is somehow special.

I've now created #7688 with (what I believe to be) an improved phrasing.

**Closed** 2023-07-01 12:54 UTC
Labels: question
