### ISSUE TITLE
Enable one-JSON-object-per-line output for all log

### ISSUE THREAD

**Issue by a-gn** [borgbackup/borg#6053] opened 2021-11-14 14:14 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

borg 1.1.17

#### Operating system (distribution) and version.

macOS Monterey 12.0.1

#### Hardware / network configuration, and filesystems used.

MacBook Air M1, APFS on USB external drive

#### How much data is handled by borg?

A few dozen GB in total, only a 4KB text file here.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
sudo borg --log-json create /Volumes/hgst_data/borg_backups_mba::test6 backup_settings.json --json --progress
```

(Ran with Python's subprocess.Popen class.)

## Describe the problem you're observing.

The command runs fine, but I'm having a hard time parsing its output, because the final JSON object is printed over multiple lines:

```json
{"message": "Initializing cache transaction: Reading config", "operation": 1, "msgid": "cache.begin_transaction", "type": "progress_message", "finished": false, "time": 1636898729.14517}
{"message": "Initializing cache transaction: Reading chunks", "operation": 1, "msgid": "cache.begin_transaction", "type": "progress_message", "finished": false, "time": 1636898729.145416}
{"message": "Initializing cache transaction: Reading files", "operation": 1, "msgid": "cache.begin_transaction", "type": "progress_message", "finished": false, "time": 1636898729.149642}
{"operation": 1, "msgid": "cache.begin_transaction", "type": "progress_message", "finished": true, "time": 1636898729.154869}
{"original_size": 2092, "compressed_size": 674, "deduplicated_size": 0, "nfiles": 1, "time": 1636898729.1550038, "type": "archive_progress", "path": "backup_settings.json"}
{"message": "Compacting segments   0%", "current": 1, "total": 4, "info": null, "operation": 1, "msgid": "repository.compact_segments", "type": "progress_percent", "finished": false, "time": 1636898730.452299}
{"message": "Compacting segments  25%", "current": 2, "total": 4, "info": null, "operation": 1, "msgid": "repository.compact_segments", "type": "progress_percent", "finished": false, "time": 1636898730.452348}
{"message": "Compacting segments  50%", "current": 3, "total": 4, "info": null, "operation": 1, "msgid": "repository.compact_segments", "type": "progress_percent", "finished": false, "time": 1636898730.8090398}
{"message": "Compacting segments  75%", "current": 4, "total": 4, "info": null, "operation": 1, "msgid": "repository.compact_segments", "type": "progress_percent", "finished": false, "time": 1636898730.8095858}
{"operation": 1, "msgid": "repository.compact_segments", "type": "progress_percent", "finished": true, "time": 1636898730.809619}
{"message": "Saving files cache", "operation": 2, "msgid": "cache.commit", "type": "progress_message", "finished": false, "time": 1636898731.455538}
{"message": "Saving chunks cache", "operation": 2, "msgid": "cache.commit", "type": "progress_message", "finished": false, "time": 1636898731.771253}
{"message": "Saving cache config", "operation": 2, "msgid": "cache.commit", "type": "progress_message", "finished": false, "time": 1636898731.7764711}
{"operation": 2, "msgid": "cache.commit", "type": "progress_message", "finished": true, "time": 1636898731.778184}
{"original_size": 2808, "compressed_size": 1360, "deduplicated_size": 488, "nfiles": 1, "time": 1636898731.778211, "type": "archive_progress", "path": ""}
{
    "archive": {
        "command_line": [
            "/opt/homebrew/bin/borg",
            "--log-json",
            "create",
            "/Volumes/hgst_data/borg_backups_mba::test6",
            "backup_settings.json",
            "--json",
            "--progress"
        ],
        "duration": 0.294298,
        "end": "2021-11-14T15:05:29.000000",
        "id": "37e064fea4acbaf64c2893979a5145d6f1770dfe3ac7f78c00d40ae7c43e8736",
        "limits": {
            "max_archive_size": 2.3269698813326423e-05
        },
        "name": "test6",
        "start": "2021-11-14T15:05:28.000000",
        "stats": {
            "compressed_size": 1360,
            "deduplicated_size": 488,
            "nfiles": 1,
            "original_size": 2808
        }
    },
    "cache": {
        "path": "/Users/arno/.cache/borg/9d70a77950883d54a2627c9bc418b9881f994d5b299e0b82165ab0cab3db956d",
        "stats": {
            "total_chunks": 1447579,
            "total_csize": 748056825190,
            "total_size": 824076304335,
            "total_unique_chunks": 211585,
            "unique_csize": 110738350260,
            "unique_size": 120075707504
        }
    },
    "encryption": {
        "mode": "none"
    },
    "repository": {
        "id": "9d70a77950883d54a2627c9bc418b9881f994d5b299e0b82165ab0cab3db956d",
        "last_modified": "2021-11-14T15:05:29.000000",
        "location": "/Volumes/hgst_data/borg_backups_mba"
    }
}
```

I iterate over the process' output lines. Each log line can be parsed by `readline()` followed by `json.loads()`, except the last object.

It would greatly simplify the use of the JSON API if I could ask Borg to print every JSON object on its own line. I see that some commands support `--json-lines`, but not `borg create`.

Would it be possible to add such an argument to all Borg commands that can output JSON?

**Comment by a-gn** [comment] 2021-11-14 14:38
Note: I just found this only happens because I merge `stdout` and `stderr` together, and iterate over all their lines.

I work around this for now by parsing `stderr` and `stdout` separately, but printing all output as JSON lines would be easier to handle.

**Comment by a-gn** [comment] 2021-11-14 14:52
I fixed this bu parsing `stderr` and `stdout` separately, but it would still be easier if all output could be printed as one JSOB object per line, instead of pretty-printing the final object.

**Comment by knutov** [comment] 2021-11-18 06:11
As a quick fix it is possible to reformat json via `jq` I suppose.

First answer from google: https://stackoverflow.com/questions/40396445/get-outputs-from-jq-on-a-single-line

**Comment by a-gn** [comment] 2021-11-20 15:10
> As a quick fix it is possible to reformat json via `jq` I suppose.
> 
> First answer from google: https://stackoverflow.com/questions/40396445/get-outputs-from-jq-on-a-single-line

Parsing the object is easy if I have it as a string; the problem is that I want to process borg's output as it comes, without waiting for borg to quit. It's easier to read until a newline (`readline()`) than to read until the end of a JSON object.

Though if I understood correctly, borg only ever prints one final JSON object on stdout, and all other log lines go to stderr, so I guess the problem is more easily solved by parsing stdout separately after borg quits.

**Comment by enkore** [comment] 2023-05-24 10:28
Duplicate of #3605

**Closed** 2023-05-24 10:44 UTC
Labels: c: json api
