### ISSUE TITLE
SIGSTOP, SIGCONT

### ISSUE THREAD

**Issue by pguth** [borgbackup/borg#100] opened 2015-07-16 08:57 UTC
> In short, SIGSTOP tells a process to “hold on” and SIGCONT tells a process to “pick up where you left off”. This can work really well for rsync jobs since you can pause the job, clear up some space on the destination device, and then resume the job.

https://major.io/2009/06/15/two-great-signals-sigstop-and-sigcont/

**Comment by pguth** [comment] 2015-07-16 09:04
Wohooo, 100! :-)

**Comment by ThomasWaldmann** [comment] 2015-07-16 10:20
I tried with a python interpreter console process, sent it a kill -STOP pid and a kill -CONT pid.
Seems to be handled by the OS, so not much to do there?

But: afterwards my loop did not react to Ctrl-C any more, so there seem to be side effects.

**Comment by anarcat** [comment] 2015-10-06 07:01
here's what signal(7) says about this:

       SIGCONT   19,18,25    Cont    Continue if stopped
       SIGSTOP   17,19,23    Stop    Stop process
       SIGTSTP   18,20,24    Stop    Stop typed at terminal
       [...]
       The signals SIGKILL and SIGSTOP cannot be caught, blocked, or ignored.

@tw what test did you do here? things should just be working fine without us doing anything here, i believe... can you provide a way to reproduce the problem?

**Comment by ThomasWaldmann** [comment] 2015-10-06 17:09
Code:
```
#!/usr/bin/env python3.2

import time

i = 0
while True:
    time.sleep(1)
    print(i)
    i += 1
```

Output:
```
tw@tux:~/w/sigstop$ ./test.py 
0
1
2
^CTraceback (most recent call last):
  File "./test.py", line 7, in <module>
    time.sleep(1)
KeyboardInterrupt

# ^^^ I just pressed Ctrl-C and it terminates as expected.

tw@tux:~/w/sigstop$ ./test.py 
0
1
2
3
4
5
6
7
8
9
10
11
12

[1]+  Stopped                 ./test.py

# ^^^  issued "kill -SIGSTOP <PID>" from another terminal

# vvv issued "kill -SIGCONT <PID>" from another terminal

tw@tux:~/w/sigstop$ 13
14
15
16
^C        <---- trying to kill it with Ctrl-C, but it keeps going...
tw@tux:~/w/sigstop$ 17
18
^C        <---- trying to kill it with Ctrl-C, but it keeps going...
tw@tux:~/w/sigstop$ 19
20
21
^C        <---- trying to kill it with Ctrl-C, but it keeps going...
tw@tux:~/w/sigstop$ ^C
tw@tux:~/w/sigstop$ ^C        <---- trying to kill it with Ctrl-C, but it keeps going...
tw@tux:~/w/sigstop$ 22
^C
tw@tux:~/w/sigstop$ ^C
tw@tux:~/w/sigstop$ ^C
tw@tux:~/w/sigstop$ 23
24
25
26

^^^ issued "kill <PID>" in another terminal, now it's dead.
```

**Comment by anarcat** [comment] 2015-10-06 17:16
so the issue here is that your shell is not return control of the terminal to the process. you are telling the process to go in the foreground, but the shell doesn't know that and still presents you with the prompt, and intercepts control-c.

if you would do `fg` in the shell, everything would go well again.

in other words, "works for me":

```

[999]anarcat@marcos:borg1$ python borg/testsuite/test_stop.py
0
1
2
3
4
5

[2]+  Stoppé                 python borg/testsuite/test_stop.py
[999]anarcat@marcos:borg147$ # ^ issued STOP
[1000]anarcat@marcos:borg147$ # now issuing CONT
[1001]anarcat@marcos:borg147$ 6
7
^C
[1001]anarcat@marcos:borg147$ # control-c fails, it is intercepted by the shell, which gives me a prompt
8
9
10
11
fg
[1002]anarcat@marcos:borg147$ 12
13
14
^C
[1002]anarcat@marcos:borg147$ fg
python borg/testsuite/test_stop.py
15
^CTraceback (most recent call last):
  File "borg/testsuite/test_stop.py", line 7, in <module>
    time.sleep(1)
KeyboardInterrupt
[1003]anarcat@marcos:borg1$ # fg tells the shell to give control back
```

**Comment by ThomasWaldmann** [comment] 2015-10-06 18:55
Ah, ok, so this is expected? For all shells? I used bash.

Another concern is that when one is interrupting a system call like a disk / pipe read or write (if that is possible?), could it corrupt data we read or write?

Do we need Python 3.4 to support this safely? See: https://www.python.org/dev/peps/pep-0475/

**Comment by anarcat** [comment] 2015-10-06 20:35
> Ah, ok, so this is expected? For all shells? I used bash.

I would assume so. That is what i would expect anyways.

> Another concern is that when one is interrupting a system call like a disk / pipe read or write (if that is possible?), could it corrupt data we read or write?

I believe it is possible it gets interrupted during a syscall, unless the process is in the `D` state (`uninterruptible sleep (usually IO)` in the ps manpage), in which case the process is usually stopped after it returns from sleep. I don't believe it can corrupt I/O.

> Do we need Python 3.4 to support this safely? See: https://www.python.org/dev/peps/pep-0475/

pep-0475 is about interrupted syscalls (e.g. SIGINT AKA control-c), not suspended ones, so I don't believe this applies.

besides, we can't change handling of SIGSTOP, so there's nothing we could do to handle this better anyways. So i'll just close this. :)

**Closed by anarcat** 2015-10-06 20:35 UTC
Labels: enhancement, question

**Comment by dagelf** [comment] 2022-11-14 14:57
We can react to SIGINT or similar, and save state, flush to disk, whatever is necessary, to continue cleanly. Eg. reopen network sockets, or whatever is necessary, to prevent having to restart from scratch  - and to prevent `borg` from becoming a zombie process because of for example not being able to read the disk in the middle of an already long read operation, because the disk is suddenly waking up from suspend...

**Comment by ThomasWaldmann** [comment] 2022-11-14 16:30
@dagelf maybe do not add comments to 7y old tickets which are solved.

Also note that we already have some SIGINT handling in borg in recent 1.2 versions and in 2.0, so maybe just tried it and  open a new ticket if you find a specific problem with that.
