### ISSUE TITLE
Multi-Process borg operation

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#1046] opened 2016-05-16 16:54 UTC
id like to share some thoughts regarding a quick "implementation" of the effect of a multi threaded capability into borg.
maybe these thoughts are dumb - then simply delete this posting...

assumption: 
we work "locally" so the amount of data read/written is not a problem
we have suffient free space available
we need "only" a desaster type of backup then have the need to restore a single file
we prefer fast backup time as this enables us to do backup more often

following scenario:
DIR1
SUBDIR_1
..
SUBDIR_N

for each SUBDIR we start a borg process which has its repository in borgdir\subdir_*
(maybe the granularity (and speed) can even be enhanced more by adding a "layer" for subsubdir -level etc.)

all these processes can easily run independently as the affect each own repository only
after the last process has finished we start a "merging" borg process which accumulates the single subdirs into the main-repository

assumption: if a file in subdir1 has - from a borg point of view - some identical blocks like a file in subdir2, then in this moment, these blocks will be deduplicated (maybe for that it is needed to work with different block.sizes for "subdir-borg" compared to "main borg"...)

afterwards (by user option) these "temporary\working subdir repositories" either stay (for speed reasons of next backup) or will be deleted (for space reasons).

IMHO this "idea" may even be implemented on a scripting/bash level....

**Comment by ThomasWaldmann** [comment] 2016-05-16 17:15
yes, you can run N borg processes in parallel.

They will eat a bit more memory and disk space, but as long as your N data sets and N repositories (and N caches) do not have overlapping data, it might be tolerable.

There is no "repo merge" yet.

**Comment by ClipperS87** [comment] 2016-05-16 17:23
@ThomasWaldmann sorry for beeing unclear (as English is not my mother tongue):

I do not want a "repo merge" functionality in borg but use borg to backup different borg directories itself and simply I do not know sufficient about how data is stored inside borg:

_OC_ i want to use the benfits of deduplication of identical date inside all subdirectories.

lets start from the point that I have N repositories and use borg (call it the merge task") to simply backup these repositories 
So i may ask a simple as important question:
is there a way (maybe be using a bigger "block"-size in the merging borg process that borg recognise identical blocks in repo1 and repo 2 and stores this block only 1 time?
(maybe by using uncompressed data in the source repositiries....)

**Comment by ThomasWaldmann** [comment] 2016-05-16 17:41
Backing up borg repos with borg is maybe a bit impractical as you'ld need to do a step extraction process then, so for many people, this would be out of question.

If you'ld do it nevertheless, there might be some dedup if you do not compress or encrypt the N repos, but i guess it won't be as efficient as on the source files.

**Comment by ClipperS87** [comment] 2016-05-17 10:55
>>Backing up borg repos with borg is maybe a bit impractical as you'ld need to do a 2-step extraction process 
therefore i wrote in my initial posting: "assumption: we need "only" a desaster type of backup then have the need to restore a single file"

for my understanding:
if the same block of data is identified as unique and after that compressed using the same compression method - the result must be the same. so enabeleing compression should not hinder the deduplication of multiple repositories....

"there might be some dedup" - i would prefer a more accurate statement:
lets say a chunk in repo1 has x percent data and y percent header information, then i must create the "borg repo merge" job with a parameter which allows me to identify the data block in a chunk in Repo1 as the same data block in a chunk in Repo2 as soon booth subdir-backups did a backup of the same data in the filesystem... or?

**Comment by ThomasWaldmann** [comment] 2016-05-17 12:59
Compression: true - if you use same compression everywhere and you never change it, it will not impact deduplication.

Deduplication: maybe we need to differentiate between small (< min chunk size) and large files (>> min chunk size).

Small files give 1 chunk when processing them with borg. Multiple such chunks will be stored into a segment file (with some PUT header (PUT, id, crc, size) added). So if you backup a specific list of files, I guess the output to the segment file will be the same, but not necessarily the segment file boundaries (it will start a new segment file if the current one is considered full). Also, other stuff might get "in between" caused by metadata flushes and checkpoints.

Big files give multiple chunks and for the same list of chunks, I guess the output to the segment file(s) will be the same. Same issue for segment boundaries as above. Metadata flushes won't get in between, not sure about checkpoints.

BTW, the chunking algorithm ("content defined chunking" using buzhash) is NOT *searching* for the biggest run of deduplicatable/identical content in files. It just happens that cutting points are at logically the same place as the chunk cutting is driven by the hash value of the window that moves over the file. The deduplication happens when these chunks get stored: chunks with same sha256 hash won't be stored twice.

So you see: it is not simple. I guess the 2nd stage dedup will work better for big segment files and low checkpoint frequency in stage 1 repo. If you want to dedup chunks created from small files also, you'ld additionally need a small target chunksize for 2nd stage (which would increase the chunk management overhead (disk, ram) in stage 2 repo significantly).

**Comment by ClipperS87** [comment] 2016-05-18 09:25
I did a quick test - the result shows, that merging of repos containing big files works very well.
with smaller files the deduplication is not working (i tried chunking settings default and the smaller attic type)
-> help needed to find the appropiate chunker params

```
borg create --compression lz4 ...

TEST 1 - BIG Files

Files A,B,C,D each around 4GB VMWare .vmdk files

#######################
REPO1
Files: A B C
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               12.66 GB             12.71 GB             12.71 GB
All archives:               12.66 GB             12.71 GB             12.71 GB

                       Unique chunks         Total chunks
Chunk index:                    4866                 4866
------------------------------------------------------------------------------
#######################
REPO2
Files: B C D
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               12.79 GB             12.84 GB             12.84 GB
All archives:               12.79 GB             12.84 GB             12.84 GB

                       Unique chunks         Total chunks
Chunk index:                    4999                 4999
------------------------------------------------------------------------------

MERGE 1
Files: REPO1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               12.72 GB             12.77 GB             12.77 GB
All archives:               12.72 GB             12.77 GB             12.77 GB

                       Unique chunks         Total chunks
Chunk index:                    6321                 6321
------------------------------------------------------------------------------
Files: REPO2
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               12.84 GB             12.89 GB             12.89 GB
All archives:               25.55 GB             25.65 GB             25.65 GB

                       Unique chunks         Total chunks
Chunk index:                   12789                12791
------------------------------------------------------------------------------

TEST 2 - Small Files - size compared single repo vs. multiple repository merge
Files: Windows 10 Windows Directory

SINGLE Repo (6,22GB on disk):
Number of files: 108536
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               18.89 GB             10.97 GB              6.68 GB
All archives:               18.89 GB             10.97 GB              6.68 GB

                       Unique chunks         Total chunks
Chunk index:                   72745               115073
------------------------------------------------------------------------------
Multiple Repos (9,24 GB on disk):
Part 1
Number of files: 61141
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                6.43 GB              4.07 GB              3.82 GB
All archives:                6.43 GB              4.07 GB              3.82 GB

                       Unique chunks         Total chunks
Chunk index:                   56773                63669
------------------------------------------------------------------------------
Part 2
Number of files: 16345
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                5.74 GB              2.92 GB              2.33 GB
All archives:                5.74 GB              2.92 GB              2.33 GB

                       Unique chunks         Total chunks
Chunk index:                   16487                18090
------------------------------------------------------------------------------
Part 3
Number of files: 6412
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                2.68 GB              1.43 GB              1.37 GB
All archives:                2.68 GB              1.43 GB              1.37 GB

                       Unique chunks         Total chunks
Chunk index:                    7101                 7210
------------------------------------------------------------------------------
Part 4
Number of files: 12097
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.71 GB            880.28 MB            723.26 MB
All archives:                1.71 GB            880.28 MB            723.26 MB

                       Unique chunks         Total chunks
Chunk index:                    9012                12751
------------------------------------------------------------------------------
Part 5
Number of files: 12541
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                2.32 GB              1.67 GB              1.67 GB
All archives:                2.32 GB              1.67 GB              1.67 GB

                       Unique chunks         Total chunks
Chunk index:                   12604                13403
------------------------------------------------------------------------------
MERGED Repo (9,22 GB on disk):
Number of files: 1676
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                9.93 GB              9.96 GB              9.96 GB
All archives:                9.93 GB              9.96 GB              9.96 GB

                       Unique chunks         Total chunks
Chunk index:                    5200                 5207
------------------------------------------------------------------------------

MERGED Repo with finer chunking granularity (9,30 GB on disk):
--chunker-params 10,23,16,4095
Number of files: 1676
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                9.94 GB              9.98 GB              9.98 GB
All archives:                9.94 GB              9.98 GB              9.98 GB

                       Unique chunks         Total chunks
Chunk index:                  151084               151091
------------------------------------------------------------------------------
```

**Comment by ThomasWaldmann** [comment] 2016-05-18 12:00
There was no dedup when merging the big files' repos.

**Comment by ClipperS87** [comment] 2016-05-18 12:08
yes, corrected my typing error and wrote it more clearly

**Comment by ThomasWaldmann** [comment] 2016-07-15 13:09
close this?

**Closed** 2016-07-15 13:15 UTC
