### ISSUE TITLE
Permission problem with repository on ntfs

### ISSUE THREAD

**Issue by rsneyer** [borgbackup/borg#6881] opened 2022-07-20 16:50 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question / Issue

#### Your borg version (borg -V).

1.2.1

#### Operating system (distribution) and version.

synology diskstation manager dsm 6.2.4

#### Hardware / network configuration, and filesystems used.

diskstation with attached wd digital usb 3 hdd formatted ntfs

#### How much data is handled by borg?

7 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg-backup@DS716:~$ borg init --encryption=repokey /volumeUSB1/usbshare/borg

## Describe the problem you're observing.

I try to init a repository on a mounted USB harddrive formatted with ntfs. It works as user admin/root but not as a user "borg-backup" that has full read/write access to the usb drive. Borg output is:

`
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 5115, in main
  File "borg/archiver.py", line 5046, in run
  File "borg/archiver.py", line 168, in wrapper
  File "borg/repository.py", line 198, in __enter__
  File "borg/repository.py", line 297, in create
  File "borg/repository.py", line 323, in save_config
  File "borg/platform/base.py", line 248, in __exit__
PermissionError: [Errno 1] Operation not permitted: '/volumeUSB1/usbshare/borg/config-3aqcj0ga.tmp'

Platform: Linux DS716 3.10.105 #25556 SMP Sat Aug 28 02:13:34 CST 2021 x86_64
Linux: Unknown Linux  
Borg: 1.2.1  Python: CPython 3.9.13 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 16174  CWD: /volume1/homes/borg-backup
sys.argv: ['borg', 'init', '--encryption=repokey', '/volumeUSB1/usbshare/borg']
SSH_ORIGINAL_COMMAND: None
`

The user "borg-backup" has full access to  '/volumeUSB1/usbshare/borg':

`
borg-backup@DS716:~$ touch /volumeUSB1/usbshare/borg/test_for_permissions

borg-backup@DS716:~$ ls -l /volumeUSB1/usbshare/borg/test_for_permissions

-rwxrwxrwx 1 admin users 0 Jul 20 18:26 /volumeUSB1/usbshare/borg/test_for_permissions

borg-backup@DS716:~$ rm /volumeUSB1/usbshare/borg/test_for_permissions 

borg-backup@DS716:~$ ls -l /volumeUSB1/usbshare/borg

total 1
-rwxrwxrwx 1 admin users 209 Jul 20 18:25 config-3aqcj0ga.tmp
drwxrwxrwx 1 admin users   0 Jul 20 18:25 data
-rwxrwxrwx 1 admin users  73 Jul 20 18:25 README
borg-backup@DS716:~$
`

Most likely this is not a borg issue and someone can lead me in the right direction to solve this permission error.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

yes, borg init doesn't complete as a non root/admin user.

**Comment by ThomasWaldmann** [comment] 2022-07-20 17:44
Likely a duplicate of #6786.

**Comment by ThomasWaldmann** [comment] 2022-08-07 19:25
There has been another attempt to fix this, please test the code from PR #6935 #6936 #6940.

See also the issue in the python issue tracker: https://github.com/python/cpython/issues/95658

**Comment by ThomasWaldmann** [comment] 2023-01-16 19:58
The code referred to by previous comment is in borg 1.2.3 release. Can you test it?

**Comment by ThomasWaldmann** [comment] 2023-04-02 01:02
Guess this is solved?

**Closed by ThomasWaldmann** 2023-04-02 01:02 UTC
