### ISSUE TITLE
Missleading comment after repo init

### ISSUE THREAD

**Issue by rs-development** [borgbackup/borg#4904] opened 2020-01-02 13:25 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, borg init -h
## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

borg 1.1.10

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

sudo borg init -e repokey-blake2 /mnt/borg/box-etc

## Describe the problem you're observing.

As understand from the help, if the key file modes are used ,a keyfile is included in the repository and is decrypted via the passphrase, so why I have to export and store the key file separate?

#### Include any warning/errors/backtraces from the system logs
```
IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).
```

**Comment by ThomasWaldmann** [comment] 2020-01-02 13:49
Duplicate of #4803.

**Closed by ThomasWaldmann** 2020-01-02 13:49 UTC
