### ISSUE TITLE
borg mount: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by MrEgenius** [borgbackup/borg#3560] opened 2018-01-19 05:02 UTC
Hello!

Problem with access to mounted repository.
See debug log below.
```
$ borgfs --debug -f --last 1 repo/ls1/system/ /mnt/tmp/
using builtin fallback logging configuration
35 self tests completed in 0.09 seconds
Verified integrity of /home/backupuser/repo/ls1/system/index.253
Enter passphrase for key /home/backupuser/repo/ls1/system:
TAM-verified manifest
security: read previous location '/home/backupuser/repo/ls1/system'
security: read manifest timestamp '2017-11-29T20:01:40.592583'
security: determined newest manifest timestamp as 2017-11-29T20:01:40.592583
security: repository checks ok, allowing access
mount data cache capacity: 8 chunks
Mounting filesystem
Initializing llfuse
Calling fuse_mount
Calling fuse_lowlevel_new
Calling fuse_session_add_chan
Calling fuse_session_loop
```

After I try to access /mnt/tmp/ via another console from same user I see this error

```
handler raised <class 'TypeError'> exception ('NoneType' object is not iterable), terminating main loop.
Terminated main loop because request handler raised exception, re-raising..
Calling fuse_session_remove_chan
Calling fuse_session_destroy
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 1326, in do_mount
  File "borg/archiver.py", line 150, in wrapper
  File "borg/archiver.py", line 1336, in _do_mount
  File "borg/fuse.py", line 309, in mount
  File "borg/fuse.py", line 34, in fuse_main
  File "src/fuse_api.pxi", line 348, in llfuse.main (src/llfuse.c:38990)
  File "src/handlers.pxi", line 436, in llfuse.fuse_opendir (src/llfuse.c:19138)
  File "src/handlers.pxi", line 437, in llfuse.fuse_opendir (src/llfuse.c:19060)
  File "borg/fuse.py", line 550, in opendir
  File "borg/fuse.py", line 523, in _load_pending_archive
  File "borg/fuse.py", line 335, in process_archive
  File "borg/archiver.py", line 244, in build_matcher
  File "borg/patterns.py", line 136, in add_inclexcl
TypeError: 'NoneType' object is not iterable

Platform: Linux backup.oil-service.local 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64
Linux: CentOS Linux 7.4.1708 Core
Borg: 1.1.4  Python: CPython 3.5.4
PID: 32009  CWD: /home/backupuser
sys.argv: ['borgfs', '--debug', '-f', '--last', '1', 'repo/ls1/system/', '/mnt/tmp/']
SSH_ORIGINAL_COMMAND: None

```
I use linux64 binary version 1.1.4 from releases page.

Please, help!

**Comment by ThomasWaldmann** [comment] 2018-01-19 21:24
Is there a special reason why you use `borgfs ...` and not `borg mount ...`?

**Comment by ThomasWaldmann** [comment] 2018-01-19 21:27
duplicate of #3551?

**Closed** 2018-01-19 21:32 UTC

**Comment by MrEgenius** [comment] 2018-01-22 03:09
Ищкп

**Comment by ThomasWaldmann** [comment] 2018-01-25 02:20
@MrEgenius i just wondered, because borg mount ... is the usual way to mount from shell. borgfs is just for fstab usage.

Do you agree this is duplicate to #3551? If so, let's continue there.
