### ISSUE TITLE
Borg 1.2.0 binary: dlopen: libcrypt.so.1: No such file or directory

### ISSUE THREAD

**Issue by bulletmark** [borgbackup/borg#6339] opened 2022-02-22 22:00 UTC
I usually run the stand-alone version of borg on my Arch system. After update to borg 1.2.0, I get the following error:
```
$ borg --version
[12622] Error loading Python lib '/tmp/_MEIZgBk7j/libpython3.9.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory
```
Arch Linux, up to date. python = 3.10.2.

**Comment by ThomasWaldmann** [comment] 2022-02-22 22:10
Strange, that always used to work and nobody found it in beta tests...

Does someone else have this also?

Python 3.9 and the libs should be bundled into the pyinstaller fat binary, so it shouldn't matter if you have (only) Python 3.10 on your system.

**Comment by ThomasWaldmann** [comment] 2022-02-22 22:11
@bulletmark can you try the .tgz also? It's also made by pyinstaller, but in "directory mode".

There's also a "linuxold" binary, made on some older debian, you could also try that.

**Comment by ThomasWaldmann** [comment] 2022-02-22 22:13
BTW, fastest 1.2.0 release bug reporter! :-)

**Comment by bulletmark** [comment] 2022-02-22 22:22
Same problem with both `linux64.tgz` and `linuxold64.tgz`.

**Comment by ThomasWaldmann** [comment] 2022-02-22 22:25
I had a look into the tgz files: no libcrypt.so.1 in there.

I guess you also do not have such a file elsewhere installed on your system?

So this might by a pyinstaller bundling bug only noticable if the file is not present on the system.

**Comment by ThomasWaldmann** [comment] 2022-02-22 22:27
https://stackoverflow.com/questions/68611799/pyinstaller-binary-not-finding-library-files

**Comment by bulletmark** [comment] 2022-02-22 22:31
On Arch which recently updated to glibc 2.35-2 and gcc 11.2.0-3.
```
$ ls -l /usr/lib/libcrypt*
lrwxrwxrwx 1 root root      16 Dec 18 20:31 /usr/lib/libcrypto.so -> libcrypto.so.1.1*
-rwxr-xr-x 1 root root 2999144 Dec 18 20:31 /usr/lib/libcrypto.so.1.1*
lrwxrwxrwx 1 root root      23 Feb  3 21:16 /usr/lib/libcryptsetup.so -> libcryptsetup.so.12.7.0*
lrwxrwxrwx 1 root root      23 Feb  3 21:16 /usr/lib/libcryptsetup.so.12 -> libcryptsetup.so.12.7.0*
-rwxr-xr-x 1 root root  484192 Feb  3 21:16 /usr/lib/libcryptsetup.so.12.7.0*
lrwxrwxrwx 1 root root      17 Feb  2 17:12 /usr/lib/libcrypt.so -> libcrypt.so.2.0.0*
lrwxrwxrwx 1 root root      17 Feb  2 17:12 /usr/lib/libcrypt.so.2 -> libcrypt.so.2.0.0*
-rwxr-xr-x 1 root root  165824 Feb  2 17:12 /usr/lib/libcrypt.so.2.0.0*
lrwxrwxrwx 1 root root      19 Mar  8  2020 /usr/lib/libcryptui.so -> libcryptui.so.0.0.0*
lrwxrwxrwx 1 root root      19 Mar  8  2020 /usr/lib/libcryptui.so.0 -> libcryptui.so.0.0.0*
-rwxr-xr-x 1 root root   71368 Mar  8  2020 /usr/lib/libcryptui.so.0.0.0*
```

**Comment by bulletmark** [comment] 2022-02-22 22:40
BTW, fastest 1.2.0 release fix prepared! :-)

**Comment by ThomasWaldmann** [comment] 2022-02-22 22:44
https://github.com/pyinstaller/pyinstaller/issues/6618

**Comment by ThomasWaldmann** [comment] 2022-02-22 22:45
TODO: try the workaround from stackoverflow, try pyinstaller 4.9.

**Comment by bbx0** [comment] 2022-02-22 23:12
> Does someone else have this also?

Can confirm, same issue on Arch Linux with binary and tgz version. `glibc` with version `2.35` no longer provides `libcrypt.so.1`.

```bash
$ pacman -F libcrypt.so.1
core/glibc 2.33-5 [Installiert: 2.35-2]
    usr/lib/libcrypt.so.1

$ ls -l /usr/lib/libcrypt.so*
lrwxrwxrwx 1 root root     17  2. Feb 08:12 /usr/lib/libcrypt.so -> libcrypt.so.2.0.0
lrwxrwxrwx 1 root root     17  2. Feb 08:12 /usr/lib/libcrypt.so.2 -> libcrypt.so.2.0.0
-rwxr-xr-x 1 root root 165824  2. Feb 08:12 /usr/lib/libcrypt.so.2.0.0
```

Installing [libxcrypt-compat](https://aur.archlinux.org/packages/libxcrypt-compat) can act as a workaround on Arch Linux:
 
```bash
$ pacman -F libcrypt.so.1
custom/libxcrypt-compat 4.4.28-2 [Installiert]
    usr/lib/libcrypt.so.1

$ ls -l /usr/lib/libcrypt.so*
lrwxrwxrwx 1 root root     17  2. Feb 08:12 /usr/lib/libcrypt.so -> libcrypt.so.2.0.0
lrwxrwxrwx 1 root root     17 23. Feb 00:02 /usr/lib/libcrypt.so.1 -> libcrypt.so.1.1.0
-rwxr-xr-x 1 root root 182104 23. Feb 00:02 /usr/lib/libcrypt.so.1.1.0
lrwxrwxrwx 1 root root     17  2. Feb 08:12 /usr/lib/libcrypt.so.2 -> libcrypt.so.2.0.0
-rwxr-xr-x 1 root root 165824  2. Feb 08:12 /usr/lib/libcrypt.so.2.0.0

$ ./borg-linux64 --version
borg-linux64 1.2.0
```

Thanks a lot for the very fast response to this issue, that's really awesome!

**Comment by ThomasWaldmann** [comment] 2022-02-22 23:24
@bbx0's solution confirmed by pyinstaller developers:

https://github.com/pyinstaller/pyinstaller/issues/6618#issuecomment-1048297088

**Comment by bbx0** [comment] 2022-02-23 00:01
It's really more a workaround than a solution since [libxcrypt-compat](https://aur.archlinux.org/packages/libxcrypt-compat) is unsupported in Arch Linux as part of the AUR. Users have to install it at their own risk. (A fat package may not rely on such a scenario but provide all required libraries on its own. Maybe it's better to ship a dedicated version for glibc >2.35 instead.)

For a "non stand-alone" version this issue seems to get resolved for Arch Linux soon, since the testing repository already got updated by @Foxboron and this seems to work fine. :)
https://archlinux.org/packages/community-testing/x86_64/borg/

```bash
$ ls -l /usr/lib/libcrypt.so*                                                                                                 00:49:19
lrwxrwxrwx 1 root root     17  2. Feb 08:12 /usr/lib/libcrypt.so -> libcrypt.so.2.0.0
lrwxrwxrwx 1 root root     17  2. Feb 08:12 /usr/lib/libcrypt.so.2 -> libcrypt.so.2.0.0
-rwxr-xr-x 1 root root 165824  2. Feb 08:12 /usr/lib/libcrypt.so.2.0.0

$ borg --version                                                                                                              00:48:34
borg 1.2.0

```

**Comment by Foxboron** [comment] 2022-02-23 00:09
I got tagged, but the issue reads to me like it's not an Arch Linux bug nor a packaging bug on my end? From what I can tell from the issue I wouldn't really expect this standalone binary to really work on every distro sadly :/

I quickly read over the state of the Arch testing repositories and borg should be safe to partially upgrade if there is a need for borg 1.2.0 on Arch.

**Comment by ThomasWaldmann** [comment] 2022-02-23 00:44
Well, read the feedback over there in the pyinstaller issue, they say they intentionally don't bundle glibc and libcrypt belongs to glibc.

Yeah, maybe we could offer not only linux and linuxold, but also linuxbleeding binaries. :-)

**Comment by Foxboron** [comment] 2022-02-24 21:07
Arch is adding [libxcrypt-compat](https://archlinux.org/packages/testing/x86_64/libxcrypt-compat/) soon. So you can probably include some instructions around `libxcrypt-compat` instead of providing a bleeding edge version of the binary

**Comment by bbx0** [comment] 2022-02-26 09:52
That would be indeed best. Thanks for the notice! I see it is already merged and working fine.

```bash
$ pacman -F libcrypt.so.1
core/libxcrypt-compat 4.4.28-2 [Installiert]
    usr/lib/libcrypt.so.1

$ ls -l /usr/lib/libcrypt.so*
lrwxrwxrwx 1 root root     17 24. Feb 21:47 /usr/lib/libcrypt.so -> libcrypt.so.2.0.0
lrwxrwxrwx 1 root root     17 24. Feb 21:47 /usr/lib/libcrypt.so.1 -> libcrypt.so.1.1.0
-rwxr-xr-x 1 root root 182208 24. Feb 21:47 /usr/lib/libcrypt.so.1.1.0
lrwxrwxrwx 1 root root     17 24. Feb 21:47 /usr/lib/libcrypt.so.2 -> libcrypt.so.2.0.0
-rwxr-xr-x 1 root root 165824 24. Feb 21:47 /usr/lib/libcrypt.so.2.0.0

$ ./borg-linux64 --version
borg-linux64 1.2.0
```

I agree with the pyinstaller arguments in regards to not bundle a security relevant library statically. It's probably better to have them handled by the distribution.

Adding a comment that the standalone binaries are build against `libcrypt.so.1` which is provided by `libxcrypt-compat` on systems shipping without it, sounds like pragmatic solution without additional binary releases. :+1: :)

**Comment by ThomasWaldmann** [comment] 2022-04-14 20:05
I have updated the binaries' README accordingly, will be in 1.3.0a1 release the first time.

**Closed** 2022-04-18 20:02 UTC
Labels: documentation, binaries
