### ISSUE TITLE
Send local repository to remote server

### ISSUE THREAD

**Issue by Fossil01** [borgbackup/borg#2821] opened 2017-07-15 10:54 UTC
Hi,

Currently I'm using rsnapshot. For backup and restore speed I'm backing up to a local RAID-1 set first, then rsyncing the data to a remote backup machine.

Is there a better way to replicate the local data to a remote machine with Borg? I understand you can create a remote repository but then it will not backup locally first.

**Comment by ThomasWaldmann** [comment] 2017-07-15 14:25
I'ld just do 2 backups (one to local, one to remote) rather than rsync a local repo to remote.
See the FAQ about this. There is no borg replicate-repo command.

**Comment by milkey-mouse** [comment] 2017-07-16 04:31
pretty much a duplicate of issue #1697

**Comment by ThomasWaldmann** [comment] 2017-07-16 14:03
yup, closing this one as duplicate.

**Closed by ThomasWaldmann** 2017-07-16 14:03 UTC
