### ISSUE TITLE
v1.1 takes much more time to backup

### ISSUE THREAD

**Issue by bobblkabb** [borgbackup/borg#3178] opened 2017-10-17 06:06 UTC
I have 3 repositories and one of them suddenly takes up to 4-5, sometimes 7-8 hours to backup which used to be < 30 minutes!
Besides the borgbackup update (1.07 to 1.1.) I renamed the repository but so were the other 2 repos. Those are backing up as used to be, no time difference at all.

Right now (7:45)  I'm doing a manual backup just to see what happens. Usually it starts at 18:30.

Is there a way to add a timestamp to the 'borg create --list' option? The output is much more interesting with a timestamp.
What else can I do? Any advice?

**Comment by fsironman** [comment] 2017-10-17 07:38
Borg uses a File Cache in order to determinate if it has to backup a file again.

look at http://borgbackup.readthedocs.io/en/stable/usage/create.html Item Flags

If they are all 'A' you have a cache not used problem.

For adding a timestamp:
https://unix.stackexchange.com/questions/26728/prepending-a-timestamp-to-each-line-of-output-from-a-command

**Comment by bobblkabb** [comment] 2017-10-17 08:24
Thanks so far!

Right now (10:20) my backup from 7:45 is still running. At the moment all files have an 'U' flag.

**Comment by dimejo** [comment] 2017-10-17 08:57
Are you backing up device files? Might be related to #3130.

**Comment by bobblkabb** [comment] 2017-10-17 09:23
No. I'm backing up our file server, a Windows 2012 folder share.
[still running 11:20]

**Comment by ThomasWaldmann** [comment] 2017-10-17 12:06
There's a change in how the files cache works (see changelog), it is now using ctime (was: mtime) by default. Due to that, it might detect changes for a lot (or all) files once.

But the next backup after the slow one should be fast again.

**Comment by ThomasWaldmann** [comment] 2017-10-17 12:10
Adding docs tag, have to check whether docs / changelog says it can be slow once.

**Comment by bobblkabb** [comment] 2017-10-17 12:17
Unfortunately it wasn't..

-rw-r--r-- 1 root root  8656 Okt  1 18:48 fileserver-2017-10-01_1830.log
-rw-r--r-- 1 root root  8718 Okt  2 18:56 fileserver-2017-10-02_1830.log
-rw-r--r-- 1 root root  8780 Okt  3 18:34 fileserver-2017-10-03_1830.log
-rw-r--r-- 1 root root  8842 Okt  4 18:59 fileserver-2017-10-04_1830.log
-rw-r--r-- 1 root root  8904 Okt  5 18:53 fileserver-2017-10-05_1830.log
-rw-r--r-- 1 root root  8966 Okt  6 18:44 fileserver-2017-10-06_1830.log
-rw-r--r-- 1 root root  9028 Okt  7 18:57 fileserver-2017-10-07_1830.log
-rw-r--r-- 1 root root  9090 Okt  8 18:42 fileserver-2017-10-08_1830.log
-rw-r--r-- 1 root root  9152 Okt  9 18:55 fileserver-2017-10-09_1830.log
-rw-r--r-- 1 root root  9214 Okt 10 18:57 fileserver-2017-10-10_1830.log
-rw-r--r-- 1 root root 18985 Okt 12 **01:47** fileserver-2017-10-11_1830.log <-- !
-rw-r--r-- 1 root root 18849 Okt 12 **23:03** fileserver-2017-10-12_1830.log
-rw-r--r-- 1 root root 18978 Okt 13 **23:11** fileserver-2017-10-13_1830.log
-rw-r--r-- 1 root root 19107 Okt 15 **00:52** fileserver-2017-10-14_1830.log
-rw-r--r-- 1 root root 19236 Okt 15 **22:45** fileserver-2017-10-15_1830.log
-rw-r--r-- 1 root root 19365 Okt 16 **22:57** fileserver-2017-10-16_1830.log

**Comment by ThomasWaldmann** [comment] 2017-10-17 12:29
@bobblkabb do you have something that changes owner/group/mode/linkcount of your files without changing their content? That would trigger ctime (1.1), but not mtime (1.0).

**Comment by bobblkabb** [comment] 2017-10-17 12:57
No. Fileserver wasn't touched at all. 
The repo name was changed and it was moved to a subfolder and back to the root folder because my nas (qnap) was messing up the folder structure.
I created a 'repo' folder and its content showed the same directories as its root folder, kind of recursive. Very strange.
Hard to explain. Let me try:

root@dedup: mkdir repo
root@dedup: ls -l
_/folder1
/folder2
/repo 
/folder3_
root@dedup: cd repo
root@dedup: ls -l
_/folder1
/folder2
/repo
/folder3_

After that I decided to put the fileserver repo back to the root directory.

**Comment by ThomasWaldmann** [comment] 2017-10-17 13:43
The files cache is only used to decide whether source files have changed or not - it is unrelated to your repository location (assuming we talk about 1 repository and you just moved it to another location).

But maybe check how your ctime, size, inode information for the source files behaves.
If these values stay constant from one backup to the next, it should say "U" (unchanged), not "A".
If it says "A" all the time and is slow, check which value triggers it.

If you back up a network file system, it is maybe the inode number which is unstable.

In the past (1.0), you had to give --ignore-inode to ignore it (and get a speedup) - with borg 1.1 this is now just --files-cache=ctime,size (== the default value without "inode").

**Comment by ThomasWaldmann** [comment] 2017-10-18 00:11
keep us updated whether you found the root cause / when you have more info.

**Comment by bobblkabb** [comment] 2017-10-18 05:24
Yesterday I made a backup with the --files-cache=ctime,size option.
Little faster but still quite long: 3 hours 29 minutes

Right now I'm doing a fileserver backup in a new repository just for testing.
`borg create --compression lz4...`

**Comment by ThomasWaldmann** [comment] 2017-10-18 11:11
Please note that a first "after --files-cache mode switch" backup can take longer, because it first has to fill the cache with the data corresponding to that mode.

**Comment by ThomasWaldmann** [comment] 2017-10-18 11:12
Maybe it would make sense to test that with less data, so it is finished after a few minutes instead of hours.

**Comment by bobblkabb** [comment] 2017-10-18 11:20
But I have no comparison between v1.0.7 and v1.1 with less data.

So my new initial backup took approx. 6 hours. Tomorrow morning I will kick off the second backup.

**Comment by bobblkabb** [comment] 2017-10-19 09:45
The second backup of the new repo took 2:49h.
The regular backup took 2:46h.

Now I'm starting to doubt...
maybe v1.07 showed an incorrect end time?! 
Our file server has 410.000 files with a capacity of 295GB. 
Realistic to back up under 30 minutes?

**Comment by ThomasWaldmann** [comment] 2017-10-19 17:09
If the files cache works and you don't have many changes, borg can process hundreds or thousands files per second (depends on your setup).

So, if the 1.0 files cache (mtime,size,inode) worked fast for you and the 1.1 (default: ctime,size,inode) does not (for 2nd+ backup), check what's up with the ctime and inode of the files and adapt `--files-cache` as needed.

**Comment by ThomasWaldmann** [comment] 2017-10-19 22:17
Done: slowdown and workaround mentioned in compatibility notes of 1.1.1.

**Comment by ThomasWaldmann** [comment] 2017-10-20 02:08
BTW, I tried to reproduce the slowdown:

- used borg 1.0.7 and current borg 1.1-maint branch.
- borg 1.0 repo, with 1 archive, upgrade to borg 1.1: next backup slow (expected), 2nd next backup fast (expected)
- borg 1.1 repo, with 1 archive, downgrade to borg 1.0: same thing
- switching borg 1.1 --files-cache modes: same thing

So everything as expected here, thus I am closing this issue.

Absolute time needed for borg 1.1 "2nd next" backups (without changed files) was also similar as for "2nd next" backups with 1.0.

I was testing on Linux with ext4, so ctime and inode numbers worked flawlessly.

So, if you have the issue like OP, check if you ctime ("change time") and inode numbers work as expected.

That means:

- ctime only changes if there is some change on that file (metadata or content).
- ctime is NOT "creation time"
- inode number is stable if the file did not change

Workarounds:

- inode numbers are known to be instable for some network and fuse filesystems. for borg 1.0 the workaround was to use `--ignore-inode`, for borg 1.1 you'll need to use a `--files-cache` mode without `inode`, e.g. `ctime,size` (or `mtime,size`).
- if your ctime is broken somehow, use a `--files-cache` mode that has `mtime`, not `ctime`, e.g. `mtime,size,inode` (or `mtime,size`).

**Closed by ThomasWaldmann** 2017-10-20 02:08 UTC
Labels: documentation
