### ISSUE TITLE
borg prune .29 now printing output of successful runs to stderr instead of stdout

### ISSUE THREAD

**Issue by alraban** [borgbackup/borg#520] opened 2016-01-04 14:31 UTC
borg prune (with the -v option) appears to now print the output about what was pruned to stderr instead of stdout?  I assume this is a side effect of the combination/refactoring of log level and verbosity, but it seems like counterintuitive behavior, the successful completion of a prune isn't an error.  It seems like log-level info outptus should land on stdout conceptually.

I use the distinction between stdout and stderr to determine what happens to my cronjob outputs: stdout gets piped to the log, anything on stderr gets emailed to me.  I guess I just wanted to make sure this is intentional behavior (and not a bug) before I rewrite all my scripts/wrappers, and, if intentional, ask if you had any suggestions for programmatically distinguishing between a successful run and an unsuccessful run in a cronjob (other than ommitting the -v flag).

EDIT: Sorry for the static on the issue close reopen, pilot error

**Comment by ThomasWaldmann** [comment] 2016-01-04 16:42
Yes, this is due to the logging / output refactoring, see there: http://borgbackup.readthedocs.org/en/stable/development.html#output-and-logging

You can easily see at the return code whether there were warnings or a serious error, see there: http://borgbackup.readthedocs.org/en/stable/usage.html#general

**Comment by alraban** [comment] 2016-01-04 16:47
So it returns no error code (i.e. returns 0) but outputs on stderr?  That's pretty non-standard behavior, and not particularly clear from the docs.   

Regardless, thanks for the workaround.

**Comment by ThomasWaldmann** [comment] 2016-01-04 16:49
the problem with stdout was that this is sometimes used to transport data (e.g. if you pipe from borg into some other command, like with `borg extract --stdout`). so we can't use stdout to talk to the user.
thus, we decided to always use stderr when we want to talk to the user / log something.
yes, i see this is a bit unpretty, but we didn't see another systematic way.

**Comment by ThomasWaldmann** [comment] 2016-01-06 12:35
as this is documented / expected behaviour, I am closing this.

i am open to alternative ideas to solve this in a consistent way. we just didn't find any better idea.

**Closed by ThomasWaldmann** 2016-01-06 12:35 UTC

**Comment by devZer0** [comment] 2016-11-29 12:08
isn`t extract to stdout such a rare use case, that it would make more sense to make borg behave like a standard unix program and only change behaviour when using extract --stdout. i find it`s rather weird that verbose log output goes to stderr. every normal unix tools writes errors to stderr. borg should be no different

**Comment by edgewood** [comment] 2016-12-04 17:47
If it really bothers you, 1.1 uses Python's logging facility for the 
vast majority of output (there's a few calls to stderr left for good 
reasons). You can override the default configuration with a logging 
config file (use the BORG_LOGGING_CONF environment variable to point 
it).

Look at the Python logging documentation for what to put in the config 
file, and ping me if you have trouble (I am the author of the logging 
change).

-- 
Ed Blackman
