### ISSUE TITLE
borg check --repair issue

### ISSUE THREAD

**Issue by airbillion** [borgbackup/borg#2259] opened 2017-03-06 01:07 UTC
When I ran a check on all the archives in my repo it found 220 orphaned items...I ran a borg check --repair and it errors out when it finishes and does not repair the archives.  Is there anything I can do other than delete the whole repo and start from scratch?

Output:
```
230 orphaned objects found!
Remote: Borg 1.0.10: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "borg/remote.py", line 145, in serve
Remote:   File "borg/repository.py", line 550, in delete
Remote: borg.repository.Repository.ObjectNotFound: Object with key
b'\x10V\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.
Remote: 
Remote: Platform: Linux Backup 4.9.10-unRAID #1 SMP PREEMPT Wed Feb 15 09:38:14 PST 2017 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Remote: Linux: Slackware  14.2 
Remote: Borg: 1.0.10  Python: CPython 3.5.3
Remote: PID: 22850  CWD: /root
Remote: sys.argv: ['borg', 'serve', '--umask=077', '--info']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: Object with key 82 not found in repository root@192.168.1.135:/mnt/user/borg_backup/.

Traceback (most recent call last):
  File "borg/archiver.py", line 2089, in main
  File "borg/archiver.py", line 2025, in run
  File "borg/archiver.py", line 91, in wrapper
  File "borg/archiver.py", line 173, in do_check
  File "borg/archive.py", line 867, in check
  File "borg/archive.py", line 1165, in orphan_chunks_check
  File "borg/remote.py", line 462, in delete
  File "borg/remote.py", line 321, in call
  File "borg/remote.py", line 360, in call_many
  File "borg/remote.py", line 346, in handle_error
borg.repository.Repository.ObjectNotFound: Object with key 82 not found in
repository root@192.168.1.135:/mnt/user/borg_backup/.

Platform: Linux Tower 4.9.10-unRAID #1 SMP PREEMPT Wed Feb 15 09:38:14 PST 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Linux: Slackware  14.2 
Borg: 1.0.10  Python: CPython 3.5.3
PID: 1073  CWD: /boot/scripts/borg_scripts
sys.argv: ['borg', 'check', '--repair', '-v', '--archives-only', 'root@192.168.1.135:/mnt/user/borg_backup/']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment] 2017-03-06 02:52
Hmm, can you check the logs again. It is a bit strange that server (remote) reports:
```
Object with key
b'\x10V\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.
```
And client (local) reports:
```
Object with key 82 not found in repository root@192.168.1.135:/mnt/user/borg_backup/.
```

The numbers do not match.

**Comment by ThomasWaldmann** [comment] 2017-03-06 02:54
Also, there is more strangeness:

Orphaned objects might be a relatively harmless error: you have repo objects that are not used (any more).

The usual fix for that (within borg check --repair) is IIRC to just delete them.

But when it tried to do that, it did not find at least one of them.

**Comment by ThomasWaldmann** [comment] 2017-03-06 02:58
So, can you check:
- your RAID(?)
- your fs
- your disks (see SMART values / logs)

**Comment by airbillion** [comment] 2017-03-06 03:03
Double checked the log... This is a direct copy paste after running the check...No luck with check --repair...I have tried with Borg versions 1.08, .09, & .10... Same error with all 3 versions.  I can successfully run a check --repair on individual archives, but when it is run on all the archives in the repo the above error is thrown.  Is there any way to delete just the orphaned files?

**Comment by ThomasWaldmann** [comment] 2017-03-06 03:14
Huh, the orphaned chunks check should be only possible when checking all archives!?

**Comment by airbillion** [comment] 2017-03-06 03:24
You are correct...orphaned chunks check is only possible when checking all archives...no error is displayed but it says there is problems wit

When runing check --repair directly on server instead of ssh still errors at the end:

260 orphaned objects found!
Object with key b'\x10V\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.
Traceback (most recent call last):
  File "borg/archiver.py", line 2089, in main
  File "borg/archiver.py", line 2025, in run
  File "borg/archiver.py", line 91, in wrapper
  File "borg/archiver.py", line 173, in do_check
  File "borg/archive.py", line 867, in check
  File "borg/archive.py", line 1165, in orphan_chunks_check
  File "borg/repository.py", line 550, in delete
borg.repository.Repository.ObjectNotFound: Object with key b'\x10V\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.

Platform: Linux Backup 4.9.10-unRAID #1 SMP PREEMPT Wed Feb 15 09:38:14 PST 2017 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Linux: Slackware  14.2 
Borg: 1.0.10  Python: CPython 3.5.3
PID: 23562  CWD: /root
sys.argv: ['borg', 'check', '-v', '--repair', '--archives-only', '/mnt/user/borg_backup/']
SSH_ORIGINAL_COMMAND: None

**Comment by ThomasWaldmann** [comment] 2017-03-06 03:28
What's also curious is the chunkid: b'\x10V\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' is highly improbable ID.

The all-zero ID would be the manifest, this one has just 6 (of 256) non-zero bits. Usually chunkids are sha256(content) or hmac_sha256(content).

Can you make sure your RAM is ok, like with memtest86+?

**Comment by ThomasWaldmann** [comment] 2017-03-06 03:31
Your client is a Xeon, does it have ECC memory? Your server is a i7, so I guess it is non-ECC.

**Comment by airbillion** [comment] 2017-03-06 03:42
Primary server is xeon with ecc...backup server is i7 non-ecc...

re-ran the check --repair and found 9 less orphaned files:

251 orphaned objects found!
Object with key b'\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc4\xfa/\x07\x00\x00\x00\x00Zt\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.
Traceback (most recent call last):
  File "borg/archiver.py", line 2089, in main
  File "borg/archiver.py", line 2025, in run
  File "borg/archiver.py", line 91, in wrapper
  File "borg/archiver.py", line 173, in do_check
  File "borg/archive.py", line 867, in check
  File "borg/archive.py", line 1165, in orphan_chunks_check
  File "borg/repository.py", line 550, in delete
borg.repository.Repository.ObjectNotFound: Object with key b'\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc4\xfa/\x07\x00\x00\x00\x00Zt\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.

Platform: Linux Backup 4.9.10-unRAID #1 SMP PREEMPT Wed Feb 15 09:38:14 PST 2017 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Linux: Slackware  14.2 
Borg: 1.0.10  Python: CPython 3.5.3
PID: 29344  CWD: /root
sys.argv: ['borg', 'check', '-v', '--repair', '--archives-only', '/mnt/user/borg_backup/']
SSH_ORIGINAL_COMMAND: None

RAM should be fine...never had any issues prior to this...I have been using borg for a few months now without issue...

Is there a waty to re-build the cache or delete that chunk id?

**Comment by airbillion** [comment] 2017-03-06 03:45
ran it again and found more orphaned files:

All disks on backup server are OK with SMART data test...

271 orphaned objects found!
Object with key b'\x10V\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.
Traceback (most recent call last):
  File "borg/archiver.py", line 2089, in main
  File "borg/archiver.py", line 2025, in run
  File "borg/archiver.py", line 91, in wrapper
  File "borg/archiver.py", line 173, in do_check
  File "borg/archive.py", line 867, in check
  File "borg/archive.py", line 1165, in orphan_chunks_check
  File "borg/repository.py", line 550, in delete
borg.repository.Repository.ObjectNotFound: Object with key b'\x10V\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /mnt/user/borg_backup.

Platform: Linux Backup 4.9.10-unRAID #1 SMP PREEMPT Wed Feb 15 09:38:14 PST 2017 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Linux: Slackware  14.2 
Borg: 1.0.10  Python: CPython 3.5.3
PID: 2667  CWD: /root
sys.argv: ['borg', 'check', '-v', '--repair', '--archives-only', '/mnt/user/borg_backup/']
SSH_ORIGINAL_COMMAND: None

**Comment by ThomasWaldmann** [comment] 2017-03-06 04:10
Something is instable there.
I suggest you do not continue writing to the repo until you made sure your hw is OK.

**Comment by airbillion** [comment] 2017-03-06 19:15
Ok...all hardware and software seems ok...

Must have messed something up somewhere...I am running a check --repair on the whole repo to see if it can be repaired...

If it cannot I guess I'll have to redo the whole backup to another report...

**Comment by ThomasWaldmann** [comment] 2017-03-06 20:54
So, you ran memtest86+ for how many passes with how many errors as result?

Are these servers somehow exposed to untrusted users? Like being connected to the internet or users being able to run code on the server?

In case you restart with a new repository on the same hardware: please enable encryption, so we have MACs instead of just hashes.

**Comment by airbillion** [comment] 2017-03-07 15:58
Only 1 pass...no errors..

Servers are not exposed to anyone but myself.

OK...will try encryption...still running the check --repair onthe whole repo...about 75% through after 24 hours...should finish by tomorrow morning.

Hopefully the repository-only check --repair can fix the issue and not error out...

I'll keep you posted.

**Comment by ThomasWaldmann** [comment] 2017-03-07 20:51
Can you give me precise date and time when these 2 different ObjectNotFound happened?

**Comment by airbillion** [comment] 2017-03-09 15:44
good news!...the check --repair repository-only finally completed and was able to repair the repository.  I then ran the check --repair archives-only and it completed after finding and removing the orphaned items...no more errors found at all!

This ordeal prompted me to create a few separate repos for my backups rather than one large repo...I think this will be better for a few reasons:

1. repo/archive corruption will only affect a portion of my backups
2. ability to have backups/checks run in parallel
3. better control over archives/repos

Thank you for your help!

**Comment by ThomasWaldmann** [comment] 2017-03-09 15:55
Good to hear that borg check --repair worked for you.
Still a bit unsatisfying though as it seems we did not find the root cause of the problems yet.
Do you have the logs of the repair?

**Comment by ThomasWaldmann** [comment] 2017-03-09 23:18
"""
The actual error rate found was several orders of magnitude higher than previous small-scale or laboratory studies, with 25,000 to 70,000 errors per billion device hours per megabit (about 2.5–7 × 10^−11 error/bit·h) (i.e. about 5 single bit errors in 8 Gigabytes of RAM per hour using the top-end error rate), and more than 8% of DIMM memory modules affected by errors per year.
"""
Source: https://en.wikipedia.org/wiki/ECC_memory

Ehrm, that is a bit more than I'ld have expected. O.O

**Comment by ThomasWaldmann** [comment] 2017-03-25 14:06
Hmm, guess we won't be able to get more infos about this issue.

I still think this is some sort of corruption, maybe caused by a hardware issue.

I am closing this for now, please reopen or append to this issue if you get more information.

**Closed by ThomasWaldmann** 2017-03-25 14:06 UTC
