### ISSUE TITLE
Simple python API (Wish)

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2152] opened 2017-02-13 12:47 UTC
Hi guys,

while trying to make a python script for automating my backups I realise that I was using subprocess.run() for running a program that is actually written in python. So I thought that it might be useful to use the API instead. I took a quick look to archiver.py but it seems it is not as simple as I thought it would be. Do you have in mind to provide some simple API for using borg in other scripts?

I was thinking on something like:
```
list, stats = borg.create(compress=borg.compression.ZLIB, encrypt=borg.encryption.NONE, exclude=[], include=[]...)
```
this sort of things.
I would love not having to parse the text output to know how many new de-duplicated MB required my backup :).

**Comment by enkore** [comment] 2017-02-13 12:52
I think this is a duplicate of #654?

**Closed by enkore** 2017-02-13 12:52 UTC
Labels: duplicate
