### ISSUE TITLE
have repo-specific defaults for compression & chunker params stored in the repo and defined with init

### ISSUE THREAD

**Issue by sergiocallegari** [borgbackup/borg#659] opened 2016-02-14 16:05 UTC
Unless you use the default compression (none) and the default chunker params (now 2MB), you need to pass them on the command line whenever you invoke 'create'. However:

- as it was noticed in a thread regarding the default compression, 'best' compression really depends on your working environment.
    - For instance: if you backup locally no compression is OK, but if you backup remotely (as it is often advised, for safety) and you are on a slow link, it is better to use compression. Similarly, if you have files that are ready compressed (movies, music), no compression is OK, but if you have text, code, etc. compression can be very desirable.

- similarly the best chunker params really depend on your working environment.
    - For instance: if you have abundance of large files (movies, music), large chunks are better. However, if you have a very large number of small files, a large chunk param makes deduplication only work at the file level and all the chunker machinery becomes underused.

- passing the compression and chunker params on the command line is error prone, unless you you put your command line in a script. Even this may be errorprone if you backup to the same repo from multiple machines and the scripts on the different machines have poor consistency. If you get the chunker params or the compression params wrong, and you loose the cache, the create command can result in no deduplication at all, making your archive size grow too much.

For compatibility, the presence of repo-default compression and chunker params can be optional. If borg does not find it, then it falls back to its own default. If these parameters are given on the command line, they override the repo default. The repo-default could be made changeable by further invocation of the init command on an already initialized repo.

**Comment by ThomasWaldmann** [comment] 2016-02-19 05:43
duplicate of #346

**Closed by ThomasWaldmann** 2016-02-19 05:43 UTC
