### ISSUE TITLE
Provide utility to merge repos?

### ISSUE THREAD

**Issue by sergiocallegari** [borgbackup/borg#175] opened 2015-09-01 11:05 UTC
Hi,

this is an information or enhancement request (if it makes sense). Would it be possible/easy to provide a way to merge backup repositories?

E.g. suppose that one has a data area that got initially backed up as

  data_area/directory_A -> Repo 1 -> archives dirA_date1, dirA_date2, etc... 
  data_area/directory_B -> Repo 2 -> archives dirB_date1, dirB_date2, etc...

is it somehow possible to merge Repo2 into Repo1? That is to put all the archives
dirA_date1, dirA_date2, ... , dirB_date1, dirB_date2, ... into the same Repo 1?

**Comment by ThomasWaldmann** [comment] 2015-09-01 12:44
Good idea!

As long as the archive names do not conflict, this would be relatively easy. if they conflict, it would need some renaming to solve that.

The process would need to go over a borg client that has access to both repos (including crypto keys, if repos are encrypted). the client would iterate over one or all archives, over all items in the archive, decrypt and decompress chunks as needed, reassemble the data stream and then store the item into the destination repo (and chunk the stream, compress and encrypt chunks as needed).

so, it is somehow like extract + create, just that the content doesn't need to get written to / read from disk. quite a heavy operation, but would solve quite some use cases:

- change in crypto / maccing algorithm
- change in the crypto key used
- change in compression algorithm / level
- change in chunking parameters
- merge different repos into one
- split one repo into multiple

An even better idea than the above one might involve 2 borg clients pushing items (metadata+data) over a pipe between them.

**Comment by sergiocallegari** [comment] 2015-09-04 07:35
Thanks for considering the enhancement request. Also #176 seems interesting.

**Comment by enkore** [comment] 2016-07-18 23:22
Duplicate of #895 (closing this one, since 895 has more info)

**Closed by enkore** 2016-07-18 23:22 UTC
Labels: duplicate, enhancement
