### ISSUE TITLE
rsync from a borg mount throws "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by jsalatiel** [borgbackup/borg#2595] opened 2017-06-03 16:16 UTC
I have lost several files from my disk and i am trying to recover from my backup from last night. This is what i am doing:
```
# borg mount SOURCE /tmp/BACKUP
# rsync -avhH  /tmp/BACKUP/data/ /home/user/data/
```
after a few seconds, the rsync dies with lots of rsync: opendir "..." failed: Transport endpoint is not connected (107)

I tried to run borg mount -f , and i do not see any error, the borg running in foreground just exit.

Any ideas ?

debian jessie
borgbackup                           1.0.9-1~bpo8+1
```
# borg -V
borg 1.0.9
```

**Comment by enkore** [comment] 2017-06-03 16:20
Try --debug and -f combined to see whether there is some kind of unclean exit, or a clean exit.

Perhaps also check other system logs (dmesg/journal), maybe FUSE logged something there.

**Comment by ThomasWaldmann** [comment] 2017-06-03 17:33
To recover your data, consider rather using `borg extract`.

Helping to find the borg mount issue's root cause is ofc also welcome.

**Comment by jsalatiel** [comment] 2017-06-03 17:46
Running -f --debug
``` 
using builtin fallback logging configuration
TAM not found and not required
mount data cache capacity: 2 chunks
Mounting filesystem
Initializing llfuse
Calling fuse_mount
Calling fuse_lowlevel_new
Calling fuse_session_add_chan
Calling fuse_session_loop
Calling fuse_session_remove_chan
Calling fuse_session_destroy
```
```
# echo $?
0
```

**Comment by jsalatiel** [comment] 2017-06-03 17:46
@ThomasWaldmann , i recovered using extract. Thanks!
But i will try to help to find out why borg mount dies.

**Comment by jsalatiel** [comment] 2017-06-03 17:47
btw, whats 'ofc' ?

**Comment by ThomasWaldmann** [comment] 2017-06-03 17:51
"of course"

**Comment by jsalatiel** [comment] 2017-06-03 18:40
lol. Thanks!
Any other information that i can provide ?

**Comment by ThomasWaldmann** [comment] 2017-06-03 19:14
you could try 1.0.10 if it happens there also. use the binary if no package is easily available.

https://github.com/borgbackup/borg/releases/tag/1.0.10

**Comment by smariot** [comment] 2017-06-13 02:45
My archive contains a lot of files with UID and GID set to -1. borg mount aborts because fuse throws an exception when it encounters the negative group id.

The archive was created in Windows under Cygwin, and these 'ownerless' files came from an external drive.

**Comment by ThomasWaldmann** [comment] 2017-06-13 16:35
OK, so it seems there are multiple things to fix here:

fuse: must cope with negative uid/gid values (we already have them in archives)

extract and other places: check whether they can cope

create: shall we keep -1 as "undefined / unavailable uid/gid"? we have them anyway...

**Comment by enkore** [comment] 2017-06-13 16:39
extract: does chown, and -1 means for chown to not change it.

**Comment by enkore** [comment] 2017-06-13 16:44
create: kinda makes sense to just not store it at all on Windows, but I wouldn't change anything in mainline just to make that happen. Who cares about a few bytes per file wasted on cygwin...

**Comment by ThomasWaldmann** [comment] 2017-06-13 16:52
extract-to-tar puts item.uid/gid into tarinfo.

**Comment by enkore** [comment] 2017-06-13 16:57
GNU tar doesn't complain about it.

**Comment by ThomasWaldmann** [comment] 2017-06-13 16:58
Seems like uid/gid in tar format is a char[8].

**Comment by enkore** [comment] 2017-06-13 16:59
Yeah, it's two's complement for negative numbers.

**Comment by ThomasWaldmann** [comment] 2017-06-13 17:00
OK, so it seems the fix in #2673 is all what's needed.

**Comment by enkore** [comment] 2017-06-13 17:29
Btw. the issue raised by @smariot above seems unrelated to the issue reported by @jsalatiel.

**Comment by ThomasWaldmann** [comment] 2017-06-13 17:40
OK, I'll move everything related to @smariot to a new issue.

**Comment by smariot** [comment] 2017-06-13 17:53
They seem like the same issue to me: borg mount exits abnormally, and any program trying to read from the mounted directory gets a 'Transport endpoint is not connected.' error.

**Comment by ThomasWaldmann** [comment] 2017-06-13 17:56
@smariot that sounds like about anything crashing the fuse code can lead to that error msg.
So, it could have the same root cause or not, who knows...

**Comment by smariot** [comment] 2017-06-13 17:58
You're right, there isn't enough information to know.

**Comment by ThomasWaldmann** [comment] 2017-06-15 23:46
Note:

- I tried 1.0.9 from src on my dev machine, created a local repo, fuse mounted it, rsynced it to another local dir with the given options: worked.
- I'll try it on Debian Jessie now.

Problem: if I can't reproduce and we don't get more information, there is too little to find this issue (if it has a different root cause than the other issue linked above).

**Comment by ThomasWaldmann** [comment] 2017-06-16 00:23
@jsalatiel the fuse stuff in borg 1.0.9 maybe had some scalability issue (like consuming much memory and tempdir space).

Could it be that you just ran out of memory / tmpdir space or similar? How big was the repository you mounted?

I would've expected some exception for that case, though.

**Comment by ThomasWaldmann** [comment] 2017-06-16 00:25
Closing it as not actionable.

If we can get more information somehow, it can be reopened, of course.

**Closed by ThomasWaldmann** 2017-06-16 00:25 UTC
Labels: bug

**Comment by ThomasWaldmann** [comment] 2018-04-24 13:49
@christophlehmann likely the borg fuse process was already gone at that time. See the posts above how to get more information.

If you could add useful information to find the root cause of the problem, the ticket could be reopened, but without that, it is still not actionable.

**Comment by christophlehmann** [comment] 2018-04-24 15:42
Sorry for my bad description. I cancelt/killed a borg process and got the error message too.

My fix was `umount -l /mnt/restore`. Hope it helps someone else.

**Comment by riscie** [comment] 2019-01-15 12:44
I am hanving the same issue as poster before me. I am mounting the backup from a samba (cifs) share to my local machine, so maybe that's where the problems arise?

**Comment by ThomasWaldmann** [comment] 2019-01-15 13:11
@riscie you upgraded to an unsupported version of msgpack, use 0.5.6.

**Comment by riscie** [comment] 2019-01-15 13:24
thanks for your reply @ThomasWaldmann. Correct me if I am wrong but it seems that the borg arch community package (https://www.archlinux.org/packages/community/x86_64/borg/) uses the python-msgpack version I have on my system (0.6.0-1).

**Comment by riscie** [comment] 2019-01-15 14:25
Thank you for the fast reply @ThomasWaldmann. I found out the maintainer of the arch package is already aware of the bug (https://bugs.archlinux.org/task/61346?project=5&string=borg).

**Comment by ThomasWaldmann** [comment] 2019-01-15 20:20
The borg maintainer there is aware (and was aware before it broke), but that didn't help.

So maybe talk to the msgpack maintainer there.

**Comment by georghildebrand** [comment] 2019-02-07 19:04
I get a similar error when trying to mount an borg archive on my rpi. However, i still can use borg extract to retrieve data from the archive. 

```
borg mount /srv/e9d59a8a-3e86-4c44-a97b-cfc54f47a851/borgbackup::laptop-2019-01-25\ 10:21:19.017839 borg -f --debug

using builtin fallback logging configuration
35 self tests completed in 0.76 seconds
Enter passphrase for key /srv/e9d59a8a-3e86-4c44-a97b-cfc54f47a851/zbook_borgbackup: 
TAM-verified manifest
security: read previous location '/srv/e9d59a8a-3e86-4c44-a97b-cfc54f47a851/borgbackup'
security: read manifest timestamp '2019-01-25T11:28:28.006332'
security: determined newest manifest timestamp as 2019-01-25T11:28:28.006332
security: repository checks ok, allowing access
mount data cache capacity: 4 chunks
Mounting filesystem
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1332, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1342, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3/dist-packages/borg/fuse.py", line 292, in mount
    self._create_filesystem()
  File "/usr/lib/python3/dist-packages/borg/fuse.py", line 249, in _create_filesystem
    self.process_archive(self.args.location.archive)
  File "/usr/lib/python3/dist-packages/borg/fuse.py", line 349, in process_archive
    path = os.fsencode(item.path)
  File "/usr/lib/python3.5/os.py", line 860, in fsencode
    return filename.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 34: ordinal not in range(128)

Platform: Linux host 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l
Linux: debian 9.4 
Borg: 1.1.5  Python: CPython 3.5.3
PID: 19819  CWD: /srv/dev-disk-by-label-backup
sys.argv: ['/usr/bin/borg', 'mount', '/srv/e9d59a8a-3e86-4c44-a97b-cfc54f47a851/borgbackup::zbook-2019-01-25 10:21:19.017839', 'borg', '-f', '--debug']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment] 2019-02-07 20:44
@georghildebrand your fs encoding seems to be ascii, trying to encode non-ascii stuff.

so check your locales, LANG, etc. (and use some utf-8 locale).

**Comment by georghildebrand** [comment] 2019-02-10 11:30
thanks, for your quick reply @ThomasWaldmann.
