### ISSUE TITLE
Borg check output empty - via ssh

### ISSUE THREAD

**Issue by b1cata** [borgbackup/borg#6465] opened 2022-03-18 12:28 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, could be related to: "borg check gives no output #3785"

## Is this a BUG / ISSUE report or a QUESTION?

Issue

## System information. For client/server mode post info for both machines.

Client: CentOS 7.9.2009, borgbackup-1.1.17-2.el7.x86_64
Server: don't really know, Hetzner Storage Box

#### Your borg version (borg -V).

Client: borg 1.1.17
Server: don't know, anyway from docs it's 1.1.X

#### Hardware / network configuration, and filesystems used.

Repository it's accessed using samba and/or ssh.

#### How much data is handled by borg?

263 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg check --debug --repository-only "ssh://user@user.your-storagebox.de:23/./HOMES-borg"

## Describe the problem you're observing.

Borg output using check command it's empty when repository it's accessed through ssh. When it's accessed through samba, the output it's normal.
I have dozens of similar repositories on Hetzner, but this one it's the only one with this behavior.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Below, the bash script executing one check accessing repository through samba, and another check through ssh:

\+ export BORG_PASSPHRASE=**********
\+ BORG_PASSPHRASE=**********
\+ export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
\+ BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
\+ /usr/bin/borg -V
borg 1.1.17
\+ /usr/bin/time -f %E /usr/bin/borg check --debug --repository-only /misc/HOMES-borg
using builtin fallback logging configuration
35 self tests completed in 0.20 seconds
Starting repository check
Verified integrity of /misc/HOMES-borg/index.3571
Read committed index of transaction 3571
Segment transaction is    3571
Determined transaction is 3571
Found 1961 segments
checking segment file /misc/HOMES-borg/data/0/1...
checking segment file /misc/HOMES-borg/data/0/2...
checking segment file /misc/HOMES-borg/data/0/3...
checking segment file /misc/HOMES-borg/data/0/4...
checking segment file /misc/HOMES-borg/data/0/5...
  […]
checking segment file /misc/HOMES-borg/data/3/3565...
checking segment file /misc/HOMES-borg/data/3/3567...
checking segment file /misc/HOMES-borg/data/3/3569...
checking segment file /misc/HOMES-borg/data/3/3570...
checking segment file /misc/HOMES-borg/data/3/3571...
Starting repository index check
Index object count match.
Completed repository check, errors found.
2:03:35

\+ /usr/bin/time -f %E /usr/bin/borg check --debug --repository-only ssh://user@user.your-storagebox.de:23/./HOMES-borg
using builtin fallback logging configuration
35 self tests completed in 0.23 seconds
SSH command line: ['ssh', '-p', '23', 'user@user.your-storagebox.de', 'borg', 'serve', '--umask=077', '--debug']
user@user.your-storagebox.de's password:
RemoteRepository: 170 B bytes sent, 73 B bytes received, 3 messages sent
24:02.31

As I saw, the second check (through ssh) creates lock.roster file and lock.exclusive directory in the repository and remove it at the final. But the time it takes to run the check is considerably shorter.

**Comment by ThomasWaldmann** [comment] 2022-03-18 12:46
Maybe this is related to borg logging configuration on hetzner's side.

If you suspect it is a borg issue, please reproduce it with a system you control and where you know for sure there is no special configuration at the server side.

**Comment by b1cata** [comment] 2022-03-18 12:54
It's hard to test this because it's the only repository in Hetzner where this happens, and I have many identical...
Something it's wrong only with this one, and only using ssh connection.

**Comment by neeral85** [comment] 2022-05-03 18:13
This is not related to Hetzner as we have same issue since upgrading from 1.1.11 to 1.2.0. The issue only belongs to borg compact and borg check commands.

the server serves borg with this command:
_borg serve --verbose --debug --storage-quota 22T --restrict-to-path /Pools/Pool-0/data 2>>/var/log/borgserv.log_

**2>>/var/log/borgserv.log** is the root cause here. If removed it works as expected. However, this is not the intention that server breaks output of borg commands with forwarding errors to a logfile.

**Comment by ThomasWaldmann** [comment] 2022-05-03 18:30
@neeral85 not sure I understand what you want to say:

When using Hetzner Storage Box, `borg serve` is run by Hetzner and (AFAIK), the user has no control over how it is invoked.

So why are you saying "this is not related to Hetzner"?

The borg "RPC over ssh" works with stdin, stdout and stderr channels going over ssh.

**Comment by neeral85** [comment] 2022-05-04 05:55
not related to Hetzner Storage Box means it is related to channel redirection of `borg serve`. This was tested with my server and client.
I've not idea if Hetzner uses channel redirection with `borg serve`. However, I would assume this, because as server provider I need to be aware about error messages.

What you need to check is for what reason only `borg check` and `borg compact` are effected.  `borg create -v --stats` does output all details on client even stats are provided by stderr stream.

**Comment by ThomasWaldmann** [comment] 2023-06-08 21:07
btw, master branch has recent changes about how remote logging and remote progress information works: it is now not using stderr any more, but tunnels all log / progress info via the RPC channel (stdout).

**Comment by ThomasWaldmann** [comment] 2023-07-01 21:07
I am closing this:
- usually this works
- stderr must not be blocked or redirected elsewhere on the server side because borg 1.x is using this for log and progress output
- borg2 uses the stdout channel for log and progress output

**Closed by ThomasWaldmann** 2023-07-01 21:07 UTC
