### ISSUE TITLE
[Question] Backup timer support

### ISSUE THREAD

**Issue by deajan** [borgbackup/borg#5192] opened 2020-05-20 09:21 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, didn't find any related info.

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

Hello,

I am currently investigating using borg as laptop backup solution, and thought of a "nice to have" that maybe already be implemented by borg backup in some way.

Since user laptops are powered on at irregular schedules, I am seeking a way to assure that backups are done as soon as a laptop is online, but keeping not more than a backup a day.

I was thinking of adding a borg backup cron task that would:
- check if a backup newer than N minutes exists
- If yes, finish the task
- If no, execute the backup

Indeed this can be accomplished by a simple script, but I was wondering whether borg already integrates such a behavior, or a solution that addresses the usecase described in another manner.

The top notch would be if this setting could be configured directly in a borg repo.

Best regards.

**Comment by ThomasWaldmann** [comment] 2020-05-20 10:24
No borg does not have a scheduler and that is also out of scope of the borg project.

There is e.g. `vorta` which implements GUI and scheduling for borg backups for desktop users, in case that helps you.

**Closed by ThomasWaldmann** 2020-05-20 10:24 UTC

**Comment by deajan** [comment] 2020-05-20 12:37
Thanks for your answer.
I'm not talking about a scheduler, just a way that borg backup client knows if a backup has been taken in the last X seconds (or other timebase), so it won't create a new one too early.

I think of something like this:
```
borg create -s --progress --only-if-older-than=86400 repo::archive path
```

As a side question, is there a way to pass trivial variables (or json/strings or something else) from a repo to the client ?

Thanks for your time.

**Comment by ThomasWaldmann** [comment] 2020-05-20 13:19
Slightly different, but still nothing borg cares about.

It cares about doing the current operation, which in case of `borg create` results in an arbitrarily named archive (comes from cli). Concerning archive names, it does not really know what belongs together because it does not know what the corresponding "previous" backup name was nor what its precise status was.

There is only one little hack `--prefix` that kind of creates subsets of archive names that somehow belong together IF the user chooses to use a common prefix (which is advisable). Used e.g. by `borg prune`.

You don't need to care for "resume". Borg never really "resumes", it just does not transfer chunks to the repo again which it already has there, which **feels** like resuming an interrupted create operation, but in fact is a completely fresh and independent create operation.

There is a repo configuration, but it is only used for very basic stuff. Borg does not really trust the server.

**Comment by deajan** [comment] 2020-05-20 14:08
I am not really sure I explained my usecase right.

Let's say I backup over a really bad WAN that disconnects often.
My goal is to have borg run on the client side every 30 minutes by cron.
On every run, it would check whether a recent (less than 24 hours or so) archive exists (given that the archives have timestamps, that's possible).
If no recent one exists, let borg client backup.

I see what you mean with "you don't need to care for resume". By resuming I meant run the backup against the same archive name until all chunks are transferred and the archive name exists in the repo.

If I happen to make a PR for the "check if recent backup exists" feature, would the borg collective accept it ?

I still can achieve this without any PR (run borg every 30 minutes, check if current archive name exists, if not, run backup), but that's more hacky than elegant.

**Comment by ThomasWaldmann** [comment] 2020-05-20 14:46
An easy solution would be to just do the backups every 30 mins (or every hour or so) without checking.
If there is not much change in between, it should be finished rather quickly (and take less time compared to less frequently backup runs).

And once in a while, just run prune to reduce the overall amount of archives again.

I can't say in advance whether a not-yet existing PR is acceptable. But if it gets too complicated / too weird or is too much against the way borg is designed non-acceptance may happen.

If you like, you can prepare some finer grained plan and we can have a look again.

You need to consider that there well can be multiple series of archives in the same repo, can be even multiple clients backing up to same repo. Also, there is more than success (0) and total failure (2), there are also warning states. And failure can have misc. root causes...

**Comment by deajan** [comment] 2020-05-20 15:14
Works for me, I'll play around with borg until I hit a wall, then I'll see whether a PR is needed.
Again, thanks for your time.
