### ISSUE TITLE
bigendian woes (or just ppc64?)

### ISSUE THREAD

**Issue by verygreen** [borgbackup/borg#872] opened 2016-04-09 23:57 UTC
I tried to deploy borg on ppc64 and rpc code seems to be unhappy.
This is on Fedora 22 ppc64 and I don't have another bigendian OS handy to try ATM, but I suspect they all would behave in a similar way.

```
[root@powermac ~]# borg init --encryption=none backup@backup:/backups/borg/powermac
Illegal instruction (core dumped)
[root@powermac ~]# borg init --encryption=none /tmp/test
[root@powermac ~]#  # - so local, non-RPC case works

I also assumed at first that it's just a cross endianness issue, but alas:
[root@powermac ~]# borg init --encryption=none localhost:/tmp/test
Illegal instruction (core dumped)

The backtrace ends with:
{   "signal": 4
,   "executable": "/usr/bin/python3.4"
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 70366574793944
                ,   "build_id": "b25b960673a0f2d02a6e873c24af1a5be471bc46"
                ,   "build_id_offset": 54488
                ,   "function_name": "00000017.plt_call.PyBytes_AsString"
                ,   "file_name": "/usr/lib64/python3.4/site-packages/msgpack/_unpacker.cpython-34m.so"
                }
              , {   "address": 70366714197868
                ,   "build_id": "dbdd62cb43c5dce605c9b89e55227a8cf62666ee"
                ,   "build_id_offset": 1177452
                ,   "file_name": "/lib64/libpython3.4m.so.1.0"
                }
              , {   "address": 70366713679904
                ,   "build_id": "dbdd62cb43c5dce605c9b89e55227a8cf62666ee"
                ,   "build_id_offset": 659488
                ,   "function_name": "PyObject_Call"
                ,   "file_name": "/lib64/libpython3.4m.so.1.0"
...
```

(transparency note: edited by @enkore: inserted code tags around console log)

**Comment by ThomasWaldmann** [comment] 2016-04-10 01:59
looks like a msgpack issue? you could try running the pure python msgpack (it falls back to that if it can't import the compiled one).

**Comment by enkore** [comment] 2016-04-10 02:06
"Illegal instruction" pretty much only happens if some piece of (C!) code goes on a big rampage and starts to overwrite code with data. -- It also very rarely happens if your CPU and the CPU the binary was compiled for have different ISAs, like different SSE-variants and stuff like that.

The first step here is --- where does the Borg you installed come from? Compiled from source? Binary package?

**Comment by verygreen** [comment] 2016-04-10 02:09
hm, you are rgiht.
I removed system-provided python-msgpack and reinstalled borgbackup (with pip), at that time pip fetched a fresh copy of python-msgpack and now things are working.

I know there's also a python implementation that complains that it's suboptimal when used (met that at a different node), but I was not able to replicate that on the ppc64 node.

Anyway apparently fedora22-provided python-msgpack is broken on ppc64 (or 0.4.6 is broken since 0.4.7 was fetched by pip).

Thanks!

**Comment by ThomasWaldmann** [comment] 2016-04-10 11:46
you could try `pip install -U "msgpack==0.4.6"` to check whether it is the msgpack version or the self-compiling that makes the difference.
on x86/x64, msgpack 0.4.6 is ok.

**Comment by verygreen** [comment] 2016-04-10 16:17
Ok, let me try that.

Meanwhile I was playing some more with recent backups on the same ppc64 box and there are more problems, e.g. this is what I get from bort info:
`
                       Original size      Compressed size    Deduplicated size
This archive:               15.07 GB              8.63 GB             62.27 MB
All archives:                4.50 EB             -7.23 EB            -12.31 TB

                       Unique chunks         Total chunks
Chunk index:                  274262       10289249058816
`
I can open a separate ticket for this if you want.

**Comment by enkore** [comment] 2016-04-10 16:28
Looks like integer _underflow_.

**Comment by verygreen** [comment] 2016-04-10 16:35
So self-compiled (with pip) msgpack-python 0.4.6 module works, must be a problem in the fedora version of it for ppc64 distro.

**Comment by verygreen** [comment] 2016-04-10 16:48
For a comparison, I did borg info on the same archive from the x86 box (the one where the archive is actually located), here's the result for comparison:

```
                       Original size      Compressed size    Deduplicated size
This archive:               15.07 GB              8.63 GB             62.27 MB
All archives:               29.93 GB             17.22 GB              8.18 GB

                       Unique chunks         Total chunks
Chunk index:                  274262               618151
```

**Comment by ThomasWaldmann** [comment] 2016-04-11 13:05
@verygreen can you file a bug in fedora issue tracker about it? if it works when manually installing, they maybe had some bad compile options or something?

Is anything left for us here (that was not caused by badly compiled msgpack)?

**Comment by enkore** [comment] 2016-04-11 13:13
> Is anything left for us here (that was not caused by badly compiled msgpack)?

If downstream fedora doesn't fix it we'll want to document that these packages are broken. Apparently this explodes early on, before it can corrupt data, but better safe than sorry with this...

**Comment by verygreen** [comment] 2016-04-11 14:18
What's left is incorrect output of borg info command quoted above on ppc64, that is not fixed by msgpack recompile. Do you wat me to open a separate ticket for that?
Also is there an easy way to verify consistency of the data in the archive compared to the local fs? Just to make sure all is fine in this cross-endianess scenario since at least something is wrong as we can see.

I will file a fedora ticket.

**Comment by verygreen** [comment] 2016-04-11 14:52
https://bugzilla.redhat.com/show_bug.cgi?id=1326004

**Comment by ThomasWaldmann** [comment] 2016-04-11 18:51
@verygreen yes, file a separate issue so we can close this one (and mention you used a fixed msgpack, its version and whether you compiled or used pure python msgpack).

we do not track distribution issues here. @enkore i don't think we should document distribution bugs, especially not if obvious.

**Closed by ThomasWaldmann** 2016-04-11 18:51 UTC
