### ISSUE TITLE
borg check should honor progress command line option

### ISSUE THREAD

**Issue by mreitinger** [borgbackup/borg#1252] opened 2016-07-03 20:21 UTC
Right now borg check only supports a '-v' (verbose) option. This makes it hard to perform automated checks (by running via cron or similar) where you might want a 'verbose' output sent via mail.

Borg check should honor the -p (progress) and -v (verbose) in the same way borg create does.

**Comment by enkore** [comment] 2016-07-03 21:47
Duplicate of #824

**Closed by enkore** 2016-07-03 21:47 UTC
