### ISSUE TITLE
tips for using borg under Cygwin/Windows 10

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#988] opened 2016-04-27 07:03 UTC
_using windows 7 none of these issue occurred, as i wasted some time investigation id like to share_

issue 1
backup stops with message that the source cannot be accessed
external raid attached via USB

solution
had to change the detailed energy managment settings and take out the USB and HD from any power saving "feature"

issue 2
backup "crashes" with the following error:

> <current-filename-beeing-processed>: [Errno 13] Permission denied: '<path>/.cache/borg/<id>/txn.active'
> <current-filename-beeing-processed>: [Errno 17] File exists: '<path>/.cache/borg/<id>/txn.tmp
> Local Exception.
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 1498, in main
>     exit_code = archiver.run(args)
>   File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 1452, in run
>     return args.func(args)
>   File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 80, in wrapper
>     return method(self, args, repository=repository, **kwargs)
>   File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 246, in do_create
>     create_inner(archive, cache)
>   File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 220, in create_inner
>     archive.save(timestamp=args.timestamp)
>   File "/usr/lib/python3.4/site-packages/borg/archive.py", line 267, in save
>     self.cache.add_chunk(self.id, data, self.stats)
>   File "/usr/lib/python3.4/site-packages/borg/cache.py", line 359, in add_chunk
>     self.begin_txn()
>   File "/usr/lib/python3.4/site-packages/borg/cache.py", line 182, in begin_txn
>     os.mkdir(txn_dir)
> FileExistsError: [Errno 17] File exists: '<path> /.cache/borg/<id>/txn.tmp'
> 
> Platform: CYGWIN_NT-10.0 ah 2.5.0(0.297/5/3) 2016-04-11 09:58 x86_64
> Borg: 1.0.2  Python: CPython 3.4.3
> PID: 1916  CWD: /cygdrive/v
> sys.argv: ['/usr/bin/borg', 'create', '--compression', 'lz4', '-v', '--list', '-p', '-s', '<archivename>', '<path>']

solution 2
take out the <path> from windows search indexing options

**Comment by ThomasWaldmann** [comment] 2016-04-27 12:13
you are saying with windows 7 it does not happen - but under which circumstances did it happen?

**Comment by ClipperS87** [comment] 2016-04-27 12:26
I do not have sufficient knowledge about the differences in detail between W7 and W10
the way how I was able to solve these problems may guide this path...

ad solution 1
I could find a relation between the file beeing backed up and this behaviour:
i.e. sourcefile had 50 Gig, borg was "thinking" (reading, comparing, finding no changes, no need to write new chungs to dest drive) - and in the meantime the dest drive "disconnected" though power save and took longer then borg expected to be available again.
so imho there should be a parameter for "extra timeout" for slow network connections and or external drives....

ad solution 2
.cache is created in %USERPROFILE% user/username/
maybe is should be created in %APPDATA% user/username/appdata - which is excluded in windows indexing per default

p.s.
generally these are tips which solved me many hours - not bugs or issues rgearding borg - so plse move into another folder if needed

**Comment by theChaosCoder** [comment] 2016-04-27 14:35
I backup files to my NAS via cygwin on Win10 and never had any problems with the windows indexing service...

**Comment by ThomasWaldmann** [comment] 2017-10-02 00:59
closing this one.

issue 1 is outside of borg scope.

issue 2 seems to be not reproducable.

**Closed by ThomasWaldmann** 2017-10-02 00:59 UTC
Labels: os: windows
