### ISSUE TITLE
Allow file size limit

### ISSUE THREAD

**Issue by varac** [borgbackup/borg#3512] opened 2018-01-04 20:09 UTC
I'd love to have a file size limit which would ignore all files bigger than that limit.
I.e. I want to make sure I don't accidentially try to backup my blueray backup image file of 8gb, or sth like this.

**Comment by fullofcaffeine** [comment] 2018-01-05 04:01
+1 I'm looking exactly for that as well, very useful when syncing to S3. Excludes is not enough as there might be files/dirs/extensions that you did not take into account and you only find out after the backup is done or in progress.

**Comment by ThomasWaldmann** [comment] 2018-01-06 11:04
duplicate of #902

**Closed by ThomasWaldmann** 2018-01-06 11:04 UTC
