### ISSUE TITLE
Remote repo not accessible after crash (lock.exclusive)

### ISSUE THREAD

**Issue by pyotri** [borgbackup/borg#955] opened 2016-04-21 10:03 UTC
If the remote server in the middle of a backup crashes, will leave the repository in a state, so that it is not accessible any more.

Backtrace of a failed attempt shows this line:
Remote: borg.locking.LockTimeout: <path_to_repo>/lock.exclusive

Background: I'm currently evaluating borgbackup for a remote repository scenario. The remote server is running "borg serve".  #One of my standard test cases is to crash or simulate a server crash and look how the systems recover from this failure.

Steps to reproduce:
Start backup run:
$ borg create someuser@localhost://...

On the same machine, but in another shell, while backup is still running:
$ ps ax | grep "borg serve" | grep python
$ kill -9 <process id of borg serve>

Any access to the repo after that will fail.

Manually removing the lock (rm -r <path_to_repo>/lock.exclusive) makes the repo accessible again. If access on the remote server is limited to "borg serve" only, so "rm" cannot be executed, this makes the repo completely inaccessible until the remote admin manually fixes the bug.

**Comment by enkore** [comment] 2016-04-21 10:31
>this makes the repo completely inaccessible until the remote admin manually fixes the bug.

`borg break-lock`

For "soft" crashes (SIGINT and all Python exceptions) no stale locks should occur with 1.0.1 or newer (if they do, please file a bug report), "Hard" crashes (SIGKILL and harder) are not handle-able this way, and will usually require manual intervention.

**Comment by ThomasWaldmann** [comment] 2016-04-21 12:35
what @enkore says. if you kill -9, you can't expect lock cleanup. and as long as the lock is there, the only way to fix it is that someone checks the situation (is a borg still running? what happened?) and maybe even runs borg break-lock and borg check. Close?

**Comment by pyotri** [comment] 2016-04-21 13:02
Thanks for the clarification.

"borg break-lock" removes the lock and makes the repo accessible again. That's a working solution and I can live with that.

But it's not a very fine solution. A user that starts a backup, has to determine, if the lock is valid or not. That's not nice to the user. And the error message in case of a lock is not a well describing text, but a stack trace with additional information.

In case of using "borg serve" it is generally possible for the starting borg process on the remote server to check if the lock is valid or not but just checking if another borg instance is running. It could then silently remove an invalid lock and move along.

In case of a valid lock, the user could be clearly informed about the concurrent access.

If it cannot determined if the lock is valid or not, borg could tell the user exactly this and maybe give some hints to resolve the situation (like using borg break-lock).

Most possibly I did miss some nasty side effects and my proposals won't work that way, would they?

**Comment by enkore** [comment] 2016-04-21 13:10
> Most possibly I did miss some nasty side effects and my proposals won't work that way, would they?

"borg serve" can't conclude from "no other borg processes *on this machine*" that no borg is accessing the repository, since it can be accessed over SCP, NFS, SMB as well (with no additional server side support) etc.

Determining whether a lock is valid is thus not so simple. Besides, hard-crashes should be rare, and if they occur (regularly) should be investigated for cause, they aren't happening for no reason...

**Comment by ThomasWaldmann** [comment] 2016-04-21 22:14
closing, expected behaviour.

**Comment by RonnyPfannschmidt** [comment] 2016-04-22 06:20
maybe this an be solved by having a kind of promise in a borg repo that declares it will only be accessed by borg processes on that machine, (and explicitly failing using it if its noticed on a known network file-system)

**Comment by infectormp** [comment] 2016-04-22 06:40
something like borg init --local-only so repo will have local-only flag and borg need check if repo is mounted from remote host?

**Comment by jdchristensen** [comment] 2016-04-22 12:59
Having to remove locks manually might be best in many situations, so the admin knows that there was a problem.  It should be rare that locks are left.  However, if some kind of automated lock removal was desired, one idea would be for borg to update the timestamp on the lock every 5 minutes.  Then a future borg process could break a lock if it found it older than, say, 10 minutes.

**Comment by poelzi** [comment] 2021-01-22 15:35
The correct way to handle such locks is with a pid+machine id inside the lock and and timestamp couter that gets updated every minute. If there is no such process on the same machine: stale lock, remove. If the machineid is a foreign machine and the timestamp is not updated some minutes, remove lock. If the lock is updated, wait until cleared.
I now found that I did not have important backups for days because of a stale lock :(

**Comment by ThomasWaldmann** [comment] 2021-01-23 00:49
@poelzi that is a good suggestion, it should be checked whether we can do that.

If such an issue means your important backups aren't working AND you don't notice that, I guess you need some kind of monitoring / notification. This is not limited to the lock issue, non-working backups could also have all sorts of other causes.

**Comment by ThomasWaldmann** [comment] 2021-01-23 00:50
Reopening, see previous comments.

**Comment by ThomasWaldmann** [comment] 2021-01-26 16:59
i moved the suggestions to #5654.

**Closed by ThomasWaldmann** 2021-01-26 16:59 UTC
