### ISSUE TITLE
borg list without root slash

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2644] opened 2017-06-09 19:32 UTC
When using borg list REPO::ARCHIVE surprisingly the file path does not have a `/` at the beginning (even when it was created like this with a absolute path ala `/root/…`). It just becomes `root/…`.

This is a bit unexpected behaviour IMHO and especially when grepping for a particular dir/file one may not notice it and (wrongly) think "Ugh, this file is not in my/this backup?"…

**Comment by ThomasWaldmann** [comment] 2017-06-09 19:39
iirc we always have relative pathes in the archives.

that also is nicely consistent with that when extracting an archive, stuff will be extracted relative to the current directory (not to its original, absolute path).

**Comment by rugk** [comment] 2017-06-09 20:10
But when users don't know about this, they just think "I put in an absolute path, so an absolute path must come out". (That's very logical, IMHO. :smile:) And, as mentioned, when grepping, this is not nice.

**Comment by rugk** [comment] 2017-06-09 20:11
BTW it also affectes `borg extract`. When you use an absolute path there, the file is just not found.

**Comment by enkore** [comment] 2017-06-09 20:15
I don't think this is mentioned anywhere in the docs apart from the recreate docs, which specifically warn about this issue.

I agree, a warning would be good. (Though of course it won't be "perfect" — for patterns it can only detect some cases.)

**Comment by ThomasWaldmann** [comment] 2017-06-09 20:17
doesn't tar behave very similar with removing leading slashes?

**Comment by enkore** [comment] 2017-06-09 20:19
It depends. The tar format totally can have leading slashes and some implementations interpret them as absolute. I think GNU tar has that as one of it's many options.

**Comment by ThomasWaldmann** [comment] 2017-06-09 20:22
```
$ tar cvf foo.tar /dev
tar: Removing leading `/' from member names
...
$ tar tvf foo.tar 
drwxr-xr-x root/root         0 2017-06-08 15:48 dev/
crw-rw---- root/tty      7,130 2017-06-08 15:48 dev/vcsa2
crw-rw---- root/tty        7,2 2017-06-08 15:48 dev/vcs2
...
```

**Comment by rugk** [comment] 2017-06-10 09:37
IMHO in tar this is clear as this is an (relative) archive. But for the backup software, this is not automatically expected IMHO.

**Comment by rugk** [comment] 2017-07-22 22:24
Note: You also rather not make tar archives with directories in your root dir, i.e. one rather does not tar the whole `/etc/` dir (including the dir, not only the content) e.g.

**Comment by enkore** [comment] 2017-07-23 06:19
Duplicate of #2763

**Closed by enkore** 2017-07-23 06:19 UTC
