### ISSUE TITLE
Lock not released after KeyboardInterrupt

### ISSUE THREAD

**Issue by Soliloque** [borgbackup/borg#758] opened 2016-03-17 02:36 UTC
I changed hostname and username.

```
$ borg create -v -s -p x@xyz.com:mybackup::initial /home 
x@xyz.com's password: 
Enter passphrase for key ssh://bb@vps73167.vps.ovh.ca/~/mybackup: 
/home/lost+found: [Errno 13] Permission denied: '/home/lost+found'              
reading files cache
processing files
^CKeyboard interrupt. 26.58 MB D 116 N home/user/file.name
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1466, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1420, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 217, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 188, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 271, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 271, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 271, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 271, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 271, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 271, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 271, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 245, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 557, in process_file
    chunks.append(cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats))
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 363, in add_chunk
    self.repository.put(id, data, wait=False)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 336, in put
    return self.call('put', id_, data, wait=wait)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 204, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 248, in call_many
    r, w, x = select.select(self.r_fds, w_fds, self.x_fds, 1)
KeyboardInterrupt

Platform: Linux T410 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64
Linux: LinuxMint 17.3 rosa  LibC: glibc 2.9
Borg: 1.0.0  Python: CPython 3.4.3
PID: 26378  CWD: /home/sfillion
sys.argv: ['/usr/bin/borg', 'create', '-v', '-s', '-p', 'x@xyz.com:mybackup::initial', '/home']
SSH_ORIGINAL_COMMAND: None

$ borg list x@xyz.com:mybackupbb@vps73167.vps.ovh.ca's password: 
Remote: Borg 1.0.0: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 133, in acquire
Remote:     os.mkdir(self.path)
Remote: FileExistsError: [Errno 17] File exists: '/home/x/mybackup/lock.exclusive'
Remote: 
Remote: During handling of the above exception, another exception occurred:
Remote: 
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 94, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 119, in open
Remote:     self.repository = Repository(path, create, lock_wait=lock_wait, lock=lock)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 64, in __init__
Remote:     self.open(self.path, exclusive, lock_wait=lock_wait, lock=lock)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 142, in open
Remote:     self.lock = UpgradableLock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 260, in acquire
Remote:     with self._lock:
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 117, in __enter__
Remote:     return self.acquire()
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 138, in acquire
Remote:     raise LockTimeout(self.path)
Remote: borg.locking.LockTimeout: /home/x/mybackup/lock.exclusive
Remote: Platform: Linux xyz.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64
Remote: Linux: debian 8.3   LibC: glibc 2.9
Remote: Borg: 1.0.0  Python: CPython 3.4.2
Remote: PID: 5219  CWD: /home/bb
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
Remote Exception (see remote log for the traceback)
Platform: Linux T410 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64
Linux: LinuxMint 17.3 rosa  LibC: glibc 2.9
Borg: 1.0.0  Python: CPython 3.4.3
PID: 26426  CWD: /home/username
sys.argv: ['/usr/bin/borg', 'list', 'x@xyz.com:mybackup']
SSH_ORIGINAL_COMMAND: None

```

**Comment by ThomasWaldmann** [comment] 2016-03-17 12:39
Duplicate of #285 (but thanks for the additional traceback, it is a bit clearer than the one there).

**Closed by ThomasWaldmann** 2016-03-17 12:39 UTC
