### ISSUE TITLE
Inconsistent archive information due to part files

### ISSUE THREAD

**Issue by Thuffir** [borgbackup/borg#3690] opened 2018-03-14 16:01 UTC
```
borg 1.1.4
Python 2.7.9
Linux xxx #1 SMP Debian 4.9.30-2A~4.2.0.201801290155 (2018-01-29) x86_64 GNU/Linux
```

I added a rather big tar archive through stdin to a repository.

`borg list` tells me:
```
-rw-rw---- root   root   424575354880 Wed, 2018-03-14 10:25:07 stdin
```

but `borg info` tells me something other:
```
Archive name: xxx
Archive fingerprint: xxx
Comment: xxx
Hostname: xxx
Username: root
Time (start): Tue, 2018-01-02 03:51:44
Time (end): Tue, 2018-01-02 07:37:11
Duration: 3 hours 45 minutes 26.87 seconds
Number of files: 9
Command line: borg create -v -p --timestamp xxx --comment xxx --compression zstd,6 ::xxx -
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              849.16 GB            501.48 GB              1.46 GB
All archives:                5.43 TB              3.37 TB            311.19 GB

                       Unique chunks         Total chunks
Chunk index:                  970548             12114175

```

Notice the discrepancy on `Number of files` and `This archive` size statistics.

Am I doing something wrong? Does this something to do with #3522?

**Comment by Thuffir** [comment] 2018-03-14 16:34
Ok I think I got it now. It has something to do with the checkpointing mechanism.
If I run `borg list --consider-part-files ::xxx` I also get the checkpoint files:
```
-rw-rw---- root   root   60177828536 Wed, 2018-03-14 10:25:07 stdin.borg_part_1
-rw-rw---- root   root   63632969521 Wed, 2018-03-14 10:25:07 stdin.borg_part_2
-rw-rw---- root   root   49651236498 Wed, 2018-03-14 10:25:07 stdin.borg_part_3
-rw-rw---- root   root   55689387508 Wed, 2018-03-14 10:25:07 stdin.borg_part_4
-rw-rw---- root   root   57734516508 Wed, 2018-03-14 10:25:07 stdin.borg_part_5
-rw-rw---- root   root   50818778742 Wed, 2018-03-14 10:25:07 stdin.borg_part_6
-rw-rw---- root   root   46147344844 Wed, 2018-03-14 10:25:07 stdin.borg_part_7
-rw-rw---- root   root   40723292723 Wed, 2018-03-14 10:25:07 stdin.borg_part_8
-rw-rw---- root   root   424575354880 Wed, 2018-03-14 10:25:07 stdin
```
and now the sums make sense.

Nevertheless shouldn't `borg info` ignore those checkpoint files in the stats unless `--consider-part-files` is given?

**Comment by ThomasWaldmann** [comment] 2018-03-15 11:45
Good catch!

**Comment by ThomasWaldmann** [comment] 2018-03-17 16:16
This is a problem in the CacheSynchronizer (C code, .num_files in result).

**Comment by ThomasWaldmann** [comment] 2018-03-20 16:31
Guess this is a duplicate of #3522.

**Closed by ThomasWaldmann** 2018-03-20 16:31 UTC
