### ISSUE TITLE
Extraction fails on zlib decompression

### ISSUE THREAD

**Issue by vezult** [borgbackup/borg#2434] opened 2017-04-22 02:03 UTC
When attempting to extract files from an archive, I get this error:

```
Traceback (most recent call last):
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/archiver.py", line 100, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/archiver.py", line 461, in do_extract
    archive.extract_item(item, dry_run=True)
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/archive.py", line 367, in extract_item
    for data in self.pipeline.fetch_many([c[0] for c in item[b'chunks']], is_preloaded=True):
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/archive.py", line 125, in fetch_many
    yield self.key.decrypt(id_, data)
  File "/mnt/data/backups/bin/borgbackup/lib/python3.4/site-packages/borg/key.py", line 223, in decrypt
    data = self.compressor.decompress(memoryview(data)[1:])
  File "borg/compress.pyx", line 200, in borg.compress.Compressor.decompress (borg/compress.c:4944)
  File "borg/compress.pyx", line 168, in borg.compress.ZLIB.decompress (borg/compress.c:4177)
zlib.error: Error -3 while decompressing data: incorrect data check

```

This occurs when accessing the repository remotely (via ssh), or locally. Running a check on the repo shows no errors:

```
root@professorx:/home# borg check -v --archives-only $repo
Starting archive consistency check...
Analyzing archive professorx-2017-04-21 (11/11)
Analyzing archive professorx-2017-04-20 (10/11)
Analyzing archive professorx-2017-03-23 (9/11)
Analyzing archive professorx-2017-03-22 (8/11)
Analyzing archive professorx-2017-03-21 (7/11)
Analyzing archive professorx-2017-03-20 (6/11)
Analyzing archive professorx-2017-02-17 (5/11)
Analyzing archive professorx-2017-02-12 (4/11)
Analyzing archive professorx-2017-02-05 (3/11)
Analyzing archive professorx-2017-01-29 (2/11)
Analyzing archive professorx-2017-01-20 (1/11)
Archive consistency check complete, no problems found.

```

My clients are running debian linux, using borg 1.0.9. The server is running openbsd 5.7 and borg 1.0.9. This failure occurs when doing `borg extract -n $repo home/david/`.

I *am* able to access the archives using `borg mount` on the client, but it's a bit flakey, and not suitable for use in restoring a whole backup. Rsync fails after few gigabytes.

**Comment by ThomasWaldmann** [comment] 2017-04-22 13:43
It looks like data in your repo is corrupted.

Try running `borg check`. You must not skip the repository check to find this kind of corruption.

It's a good idea to use the latest release, but that corruption should be found by the crc32 check in 1.0.9 also.

**Comment by ThomasWaldmann** [comment] 2017-04-22 13:44
Also (maybe even do that first): check your hardware.

disks: SMART logs / tests (smartmontools)
memory: memtest86+

**Comment by ThomasWaldmann** [comment] 2017-04-22 13:57
related: https://github.com/borgbackup/borg/pull/2224 (note that code from this PR is not needed to detect this kind of corruption or enable the borg repository check to deal with it. it just transforms the special compressor exceptions to a subclass of IntegrityError.)

**Comment by vezult** [comment] 2017-04-22 18:33
I get the same result with the regular check:

root@professorx:~# borg check -v  $repo
Remote: Starting repository check
Remote: Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive professorx-2017-04-22 (11/11)
Analyzing archive professorx-2017-04-21 (10/11)
Analyzing archive professorx-2017-04-20 (9/11)
Analyzing archive professorx-2017-03-23 (8/11)
Analyzing archive professorx-2017-03-22 (7/11)
Analyzing archive professorx-2017-03-21 (6/11)
Analyzing archive professorx-2017-03-20 (5/11)
Analyzing archive professorx-2017-02-17 (4/11)
Analyzing archive professorx-2017-02-12 (3/11)
Analyzing archive professorx-2017-02-05 (2/11)
Analyzing archive professorx-2017-01-29 (1/11)
Archive consistency check complete, no problems found.

So you're saying that in order to actually *know* if data is corrupted, I need to use v1.1, with the --verify-data option?

It's a bit frightening to know that backups can be corrupted such that they are useless, without any indication prior to attempting a restore.

**Comment by ThomasWaldmann** [comment] 2017-04-22 23:09
Ehrm, now it's getting strange.

You are sure you always run against the same repo?

Having the crc32 check NOT fail, but zlib giving a decompression error on the same data would be strange. It could be possible, but should be a rather rare event.

I'll check out the 1.0.9 code and will have a look whether this could have other reasons.

Your disk and RAM is ok on the machines involved?

**Comment by ThomasWaldmann** [comment] 2017-04-22 23:14
Maybe create a copy of the repo and try borg 1.1.0b4 (see github release, just download the binary) like `borg1.1 check --verify-data ...`.

And please keep the repo state as it is now. If you do not find a simple reason for this (like hardware, filesystem or OS malfunction), I'ld really like to debug this with you, so we find the root cause.

**Comment by ThomasWaldmann** [comment] 2017-04-22 23:25
BTW, is it correct that you created that archive with zlib compression?

**Comment by vezult** [comment] 2017-04-23 02:22
I've only got two repos. I'm pretty sure I'm not getting confused about which one I'm using.

```
root@professorx:~# echo $repo
bkup@puffy:professorx
```

Regarding disks and memory...I've not run memcheck or disk diagnostics at this point, but I've seen no other indication of memory or disk errors. That said, this isn't ECC memory either, so who knows.

I'm sure I created the archive with zlib compression. Here's my backup script:

```
REPOSITORY=bkup@puffy:professorx

borg create -v --stats \
    --compress zlib \
    $REPOSITORY::'{hostname}-{now:%Y-%m-%d}' \
    / \
    --exclude /dev \
    --exclude /proc \
    --exclude /sys \
    --exclude /run \
    --exclude /mnt \
    --exclude /tmp \
    --exclude /media \
    --exclude /home/david_clymer \
    --exclude Downloads \
    --exclude .Private \
    --exclude '*.pyc'

# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
# archives of THIS machine. The '{hostname}-' prefix is very important to
# limit prune's operation to this machine's archives and not apply to
# other machine's archives also.
borg prune -v --list $REPOSITORY --prefix '{hostname}-' \
    --keep-daily=7 --keep-weekly=4 --keep-monthly=6

```

Since the check is being done on the remote machine, I upgraded to 1.10 there, and saw the same results. I'll experiment with the latest beta and see what that finds.

I mentioned earlier that the client machine is running Debian 8.7, and the server is running Openbsd 5.7. Is it possible this has nothing to do with borgbackup, and has to do with differing zlib versions, or something like that? 

on puffy (server): 
```
$ locate libz |grep libz.so 
/usr/lib/libz.so.4.1
/usr/lib/libz.so.5.0

```
on professorx (client):
```
root@professorx:~# locate libz.so |grep x86_64 |grep -vE 'flatpak|/home/david'
/lib/x86_64-linux-gnu/libz.so.1
/lib/x86_64-linux-gnu/libz.so.1.2.8
/usr/lib/x86_64-linux-gnu/libz.so

```

**Comment by ThomasWaldmann** [comment] 2017-04-23 04:17
Maybe don't run the beta on your prod repo. It's beta...

I'ld hope zlib is so old that there are no compatibility issues. Also, compression is only done on the borg client side only (not on the borg repo server, except if you run a borg client there also and create archives with it).

**Comment by ThomasWaldmann** [comment] 2017-04-24 12:54
any news?

**Comment by ThomasWaldmann** [comment] 2017-04-24 13:04
note: https://bugs.launchpad.net/bzr/+bug/598572 same error msg, caused by RAM/disk corruption.

**Comment by vezult** [comment] 2017-04-25 11:38
On Mon, Apr 24, 2017 at 05:54:57AM -0700, TW wrote:
> any news?
> 

Well, I tried borg 1.1b4, and the normal check succeeds. I then ran
it with --verify-data, and it does find at least one error (it's still
running).

```
(bb)$ borg check -v /mnt/data/backups/professorx-copy/                                                                                               
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive professorx-2017-01-29 (1/11)
Analyzing archive professorx-2017-02-05 (2/11)
Analyzing archive professorx-2017-02-12 (3/11)
Analyzing archive professorx-2017-02-17 (4/11)
Analyzing archive professorx-2017-03-21 (5/11)
Analyzing archive professorx-2017-03-22 (6/11)
Analyzing archive professorx-2017-03-23 (7/11)
Analyzing archive professorx-2017-04-20 (8/11)
Analyzing archive professorx-2017-04-21 (9/11)
Analyzing archive professorx-2017-04-22 (10/11)
Analyzing archive professorx-2017-04-23 (11/11)
Archive consistency check complete, no problems found.

```

```
(bb)$ borg check -v --verify-data /mnt/data/backups/professorx-copy/
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Starting cryptographic data integrity verification...
chunk
57aa66ab9c212fac9a8d057299fb72ccf2930d1d40c79b72c2914b9cca36e042,
integrity error: Decompression error: Error -3 while decompressing
data: incorrect data check

```

There appears to be a --repair flag for check, though I'm not exactly
sure how that would address data corruption. Is there a way to do a
backup, and re-write bad chunks if the backup can produce a chunk that
matches the correct hash? Perhaps that doesn't make any sense.

-davidc

**Comment by ThomasWaldmann** [comment] 2017-04-25 11:51
OK, so borg 1.1 basically found the same error (in the same way, via a decompression error) as borg 1.0. As you do not have encryption/authentication in your repo, borg needs to first uncompress before it could check the sha256 of the plaintext (which is all it has in repos w/o encryption). With encryption, it would first check the hmac-sha256 before even trying to decrypt/uncompress.

OK, it seems that chunk is corrupt, definitely.

Did you look at memtest86+ and smartctl -a to find the potential root cause?
At least 1 pass of memtest86+ (preferably multiple) and smartctl -t long + looking afterwards into SMART data would be a good idea before you continue writing to that repo.

**Comment by ThomasWaldmann** [comment] 2017-04-25 12:22
Seems like borg 1.0 could not fix your problem, because it does not even detect the problem.

What could it be?
- you have the possible, but rather unlikely case where no crc32 error is found, but the chunk contents was corrupted after the crc32 was computed.
- the chunk contents was corrupted before the crc32 was computed, like due to a RAM error

borg 1.1 with borg check -v --repair --verify-data would find the error and maybe could "fix" it by deleting the corrupt chunk. But consider this rather a test for our beta code than something you'ld run against your original repo, so create a copy first. It would be helpful for borg development if you could try the repair with borg 1.1, so we have it practically tested.

For your production repo, I guess best way is you get a list of defect chunks (like from check output) and then use borg 1.0 and manually kill these chunks and run borg (1.0) check --repair again.

The "repair" will replace defect or missing chunks with all-zero chunks of same length (so there will be some defect file in some archive if the chunk is a file content chunk). For this case it will remember the original hash and will be able to "heal" the archive in case that chunk re-appears in a later backup. The healing will happen if you run borg check --repair after the chunk is in the repo again.

**Comment by ThomasWaldmann** [comment] 2017-04-25 12:25
Example session about how to kill chunks (repo objects). I used the 0 object, which is the repo manifest. In you case you would use the id of the defect chunks, not 0.
```
$ borg debug get-obj -v repo 0000000000000000000000000000000000000000000000000000000000000000 0.chunk
object 0000000000000000000000000000000000000000000000000000000000000000 fetched.
$ borg debug delete-obj -v repo 0000000000000000000000000000000000000000000000000000000000000000
object 0000000000000000000000000000000000000000000000000000000000000000 deleted.
Done.
$ borg delete --cache-only repo
$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Repository manifest not found!
Archive consistency check complete, problems found.
$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
$ borg list repo
1                                    Mon, 2017-04-24 11:36:11
```

**Comment by vezult** [comment] 2017-04-25 12:25
On Tue, Apr 25, 2017 at 04:52:00AM -0700, TW wrote:
> OK, so borg 1.1 basically found the same error (in the same way, via
> a decompression error) as borg 1.0. As you do not have
> encryption/authentication in your repo, borg needs to first
> uncompress before it could check the sha256 of the plaintext (which
> is all it has in repos w/o encryption). With encryption, it would
> first check the hmac-sha256 before even trying to decrypt/uncompress.
> 
> OK, it seems that chunk is corrupt, definitely.

Yeah. OK, doesn't seem to be borg's problem. Thanks for looking at
this.

Looks like --repair just deletes the bad chunk so that subsequent
backups have a chance to replace it, if possible. I'll do that.

> 
> Did you look at memtest86+ and smartctl -a to find the potential
> root cause?
> At least 1 pass of memtest86+ (preferably multiple) and smartctl
> -t long + looking afterwards into SMART data would be a good
> idea before you continue writing to that repo.

No smart errors. I'll probably do some more investigation regarding
the source of the corruption.

Thanks all!

-davidc

**Comment by ThomasWaldmann** [comment] 2017-04-25 12:39
BTW, if you save the defect chunk(s) like I demonstrated above, it would be interesting to look at them.

**Comment by ThomasWaldmann** [comment] 2017-04-25 12:43
We can't be absolutely sure yet, but likely this is a hardware issue.

**Comment by ThomasWaldmann** [comment] 2017-04-28 23:29
Did you save the defect chunks? Shall I have a look?

**Comment by ThomasWaldmann** [comment] 2017-05-01 21:31
@vezult ^^

**Comment by ThomasWaldmann** [comment] 2017-05-13 17:30
No feedback, closing. Likely it is an hardware-issue.

**Closed by ThomasWaldmann** 2017-05-13 17:30 UTC
Labels: hardware-issue
