### ISSUE TITLE
IntegrityError: Segment entry checksum mismatch

### ISSUE THREAD

**Issue by piotrjurkiewicz** [borgbackup/borg#1208] opened 2016-06-27 00:36 UTC
How to recover from that? The documentation says nothing.

```
2016-06-23 22:30:59+02:00 Replaying segments 95%
2016-06-23 22:31:09+02:00 Data integrity error
2016-06-23 22:31:09+02:00 Traceback (most recent call last):
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1498, in main
2016-06-23 22:31:09+02:00 exit_code = archiver.run(args)
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1452, in run
2016-06-23 22:31:09+02:00 return args.func(args)
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/archiver.py", line 74, in wrapper
2016-06-23 22:31:09+02:00 kwargs['manifest'], kwargs['key'] = Manifest.load(repository)
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/helpers.py", line 93, in load
2016-06-23 22:31:09+02:00 cdata = repository.get(cls.MANIFEST_ID)
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/repository.py", line 442, in get
2016-06-23 22:31:09+02:00 self.index = self.open_index(self.get_transaction_id())
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/repository.py", line 150, in get_transaction_id
2016-06-23 22:31:09+02:00 self.replay_segments(replay_from, segments_transaction_id)
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/repository.py", line 306, in replay_segments
2016-06-23 22:31:09+02:00 self._update_index(segment, objects)
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/repository.py", line 315, in _update_index
2016-06-23 22:31:09+02:00 for tag, key, offset in objects:
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/repository.py", line 612, in iter_objects
2016-06-23 22:31:09+02:00 (TAG_PUT, TAG_DELETE, TAG_COMMIT))
2016-06-23 22:31:09+02:00 File "/usr/lib/python3/dist-packages/borg/repository.py", line 676, in _read
2016-06-23 22:31:09+02:00 segment, offset))
2016-06-23 22:31:09+02:00 borg.helpers.IntegrityError: Segment entry checksum mismatch [segment 46956, offset 8]
2016-06-23 22:31:09+02:00
2016-06-23 22:31:09+02:00 Platform: Linux dom-borg 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64
2016-06-23 22:31:09+02:00 Linux: debian 8.4
2016-06-23 22:31:09+02:00 Borg: 1.0.2 Python: CPython 3.4.2
2016-06-23 22:31:09+02:00 PID: 4795 CWD: /home/borg
2016-06-23 22:31:09+02:00 sys.argv: ['/usr/local/bin/borg', 'list', '/mnt/cifs/borg/dom']
2016-06-23 22:31:09+02:00 SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment] 2016-06-27 08:31
Looks like the entry in segment file 46956 at offset 8 is corrupted (crc does not match).

Was there a problem with your last backup (`borg create`)?

Can you try `borg check` (and, if it finds problems, `borg check --repair`)?

**Comment by piotrjurkiewicz** [comment] 2016-06-27 15:32
> Was there a problem with your last backup (borg create)?

Yes, this is what had been logged:

```
2016-06-23 21:56:07+02:00 /media/c/[filename redacted]: [Errno 5] Input/output error
2016-06-23 21:56:07+02:00 E /media/c/[filename redacted]
2016-06-23 21:56:08+02:00 Archive c-2016-06-23.checkpoint already exists
2016-06-23 21:56:08+02:00 terminating with error status, rc 2
```

I write my backup to a CIFS-mounted drive, so this had been probably caused by some networking problems.

> Can you try borg check (and, if it finds problems, borg check --repair)?

`borg check --archives-only --repair` fails with the same error (Segment entry checksum mismatch).

I can't run full `borg check --repair`, because it would download almost 1TB from remote location, what I can't afford.

**Comment by ThomasWaldmann** [comment] 2016-06-27 16:05
> 2016-06-23 21:56:07+02:00 /media/c/[filename redacted]: [Errno 5] Input/output error
> 2016-06-23 21:56:07+02:00 E /media/c/[filename redacted]

This likely could be issue #1138.  :(

Fix is scheduled for 1.0.4, but still in the works.

> I write my backup to a CIFS-mounted drive, so this had been probably
> caused by some networking problems.

Yes, very likely there was an I/O error on the network mount (destination) and it was not reported and handled in a good way, see #1138 for details.

The "E" log entry you got maybe was caused by an I/O error while writing to the destination file (while processing that source file) - not (as the log seems to show) while reading the source file.

>     Can you try borg check (and, if it finds problems, borg check --repair)?
> 
> |borg check --archives-only --repair| fails with the same error (Segment
> entry checksum mismatch).

If you can see from borg check or the logs which archives had such errors, you maybe should delete them. But maybe it is a good idea to wait with that until the fix for #1138 is there because more connection issues could cause more corruption otherwise.

> I can't run full |borg check --repair|, because it would download almost
> 1TB from remote location, what I can't afford.

Are there cloud storage providers offering CIFS shares?

**Comment by ThomasWaldmann** [comment] 2016-06-27 16:05
Likely duplicate of #1138.

**Comment by ThomasWaldmann** [comment] 2016-06-27 16:11
@enkore see above.

**Comment by piotrjurkiewicz** [comment] 2016-06-27 23:50
I deleted manually the last segment file (file with the highest number from data/) and the error is gone. I hope I didn't break my repository by this. (index.%d and hints.%d numbers were lower than this file number)

> Are there cloud storage providers offering CIFS shares?

[hetzner.de](https://www.hetzner.de/gb/hosting/produktmatrix/storagebox-produktmatrix)

One can access Storage Box with FTP, SFTP, CIFS or WebDAV. I use CIFS because I found it most stable. SFTP connections were regularly terminated on their side.

**Comment by ThomasWaldmann** [comment] 2016-06-28 09:46
@piotrjurkiewicz the archive that was to be created in the failed `borg create` run is not there, is it?

**Comment by ThomasWaldmann** [comment] 2016-07-04 13:30
Likely duplicate of #1138.

**Closed by ThomasWaldmann** 2016-07-04 13:30 UTC

**Comment by ThomasWaldmann** [comment] 2016-07-09 23:57
Note: while the serious bug #1138 was fixed in 1.0.4/1.0.5, another small problem, was introduced: you can't have the repo on smbfs because smbfs does not support os.fsync on a directory fd. a workaround for that will be in 1.0.6, soon.

**Comment by bedros** [comment] 2017-02-11 20:12
is this issue fixed in 10.6? I had smbfs mounted backup drive caused following error

> Starting repository check
Segment entry checksum mismatch [segment 19907, offset 8]
Segment entry checksum mismatch [segment 27182, offset 3452036]
Index object count mismatch. 4661517 != 4661510
Completed repository check, errors found.

is it safer to use sshfs?

I need to know if the issue is not 100% safe, I'll move it to local drive,

**Comment by ThomasWaldmann** [comment] 2017-02-12 03:51
@bedros we have not enough information here to tell the exact cause of these issues. The originally posted issue could likely have been #1138, which is fixed since 1.0.4 (and another smbfs issue fixed in 1.0.6).

So, if you use >= 1.0.6, it can't be #1138.

I'ld suggest you check your hardware as repo corruption can also be caused by a defektive disk or memory, for example. memtest86+ for the memory testing, smartctl -a to have a look at the disk health. If you do not find some obvious error by that, I'ld suggest you start a new issue with as much information as possible.

**Comment by bedros** [comment] 2017-02-12 19:33
@ThomasWaldmann here's my setup, I use 6TB mycloud as my external backup which is a NAS drive mounted as smbfs. I also rsync that drive to local external 6TB drive, which saved my digital life in this case. on the external 6TB I use btrfs with taking a snapshot after each rsync.

mycloud web app says there's no smart error, I also took drive out and checked it for errors. none. So, it's not a hardware problem, either smbfs or mycloud software itself, mycloud is plugged through a  switch to my computer, no wifi.

I'm moving backup to local internal 6tb, and turning mycloud into a shared drive for photos and movies.

Have you guys done testing with unreliable network while doing backup etc.?

Thanks

**Comment by ThomasWaldmann** [comment] 2017-02-12 19:55
We don't have automated testing with unreliable network, but I guess you are not the only one who has a unreliable connection in practice.

I am not aware of post-1.0.4 corruption bugs on linux/bsd/osx.

There is an issue on cygwin (with root cause inside cygwin), but only with ssh://... remote repos - this was worked around recently in borg (will be in 1.0.10) and fixed in cygwin daily build (not sure if already in a release).

So, if you want to help with fixing / debugging this, I'ld suggest you open a new ticket and try to find a way how to reproduce this with a current borg release (preferably without having to own some specifc hardware).
