### ISSUE TITLE
NTFS volume unmounts while backup is in progress causing it to fail

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#4111] opened 2018-10-16 17:26 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION, possibly a bug?

#### Your borg version (borg -V).

1.1.6

#### Operating system (distribution) and version.

Linux Mint 18.3 Cinnamon 64-bit
Kernel: 4.15.0-32-generic

#### Hardware / network configuration, and filesystems used.

CPU: Intel Core i7-6700HQ CPU@2.60Ghz x 65534
RAM: 32GB

Both external HDs use NTFS (since I have to share them with a Windows and MacOS boxes). The box borg is a Linux Mint 18.3 box with a 2TB SSD that is formatted with LUKS ext4.

#### How much data is handled by borg?

~600GB (the data on the external NTFS 1TB hd)

#### Full borg command line that led to the problem (leave away excludes and passwords)

```
      /usr/local/bin/borg create /media/veracrypt1/backups/backup1::archive_foo_test \                                                                                                           
        "/media/1tbntfs" \                                                                                                                                                     
        -v \                                                                                                                                                              
        --stats \                                                                                                                                                         
        --list \                                                                                                                                                          
        --progress \                                                                                                                                                      
        --verbose \                                                                                                                                                       
        --exclude-from excludes_empty.txt \                                                                                                                                 
        --compression zstd,22 \  
```

## Describe the problem you're observing.

I'm trying to backup the full content of an external 1TB hard-drive (NTFS) to another 2TB hard-drive (NTFS) connected to the same system. 

Borg starts well but then after a while it suddenly fails:

```
...
A /media/1tbntfs/movies/foo
A /media/1tbntfs/movies/foo.avi
d /media/1tbntfs/movies/foo/sample
/media/1tbntfs/movies/indiegamethemovie_1080p.mp4: read: [Errno 5] Input/output error                                                                          
E /media/1tbntfs/movies/indiegamethemovie_1080p.mp4
/media/1tbntfs/movies/BBS.The.Documentary: stat: [Errno 2] No such file or directory: '/media/1tbntfs/movies/BBS.The.Documentary'
E /media/1tbntfs/movies/BBS.The.Documentary'
/media/1tbntfs/movies/Get.Lamp.2010: stat: [Errno 2] No such file or directory: '/media/1tbntfs/movies/Get.Lamp.2010'
``` 

What I noticed is that at the moment the errors happen, the drive suddenly unmounts and then mounts again, but then borg already erro'ed and exited, and that archive failed.

I tested reading those files individually and they work well. It seems to be something that happens after a couple of files are read from the HD. I ran an NTFS checker on my macos box (Paragon NTFS) and it found no errors in the 1TB external hd filesystem, so it might be something related to the Linux NTFS driver trying to read a lot of files? Not sure :/

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, see above.

#### Include any warning/errors/backtraces from the system logs

Not sure where to look at atm, but feel free to ask me for more details and I'll look.

**Comment by ThomasWaldmann** [comment] 2018-10-16 18:03
Well, guess either the NTFS fs is not stable enough or it unmounts due to underlying errors on the block device (e.g. bad sectors on the hdd).

Did you check the kernel logs (see dmesg output) when that happens?

Also, check `smartctl -t long /dev/sdx` and `smartctl -a /dev/sdx` for the disks in question.

**Comment by ThomasWaldmann** [comment] 2018-10-16 18:09
In case you are using veracrypt (see mount path), that could potentially also be a layer where stuff can go wrong (just guessing, nothing specific).

**Comment by fullofcaffeine** [comment] 2018-10-16 18:28
Regarding veracrypt, I don't think it's the problem. I use this encrypted external hd as an staging area before `rclone`ing the the repos to the cloud (wasabi) and it has been working very well. However, all of my backups so far were from local targets, this is the first time I'm backing up from external hd -> external hd.

**Comment by fullofcaffeine** [comment] 2018-10-16 21:59
Apparently, the problem is somewhere in my Linux box :/. I'm doing the same backup but this time from my MacOS box (specs here: https://www.dropbox.com/s/4prtg1spkpkl6lq/Screenshot%202018-10-16%2016.56.32.png?dl=0) and so far it's working fine. At this point it'd already have broken if it were running from the Linux box. And veracrypt doesn't seem to be the problem either, the veracrypt-encrypted NTFS hard-drive holds the borg that is receiving the data for the backup at this moment.

**Comment by fullofcaffeine** [comment] 2018-10-16 22:01
I've found the following output from `dmesg` that might be relevant:

```
[213645.434817] blk_partition_remap: fail for partition 1
[213645.434822] Buffer I/O error on dev sdc1, logical block 123439533, async page read
[213645.435850] blk_partition_remap: fail for partition 1
[213645.435855] Buffer I/O error on dev sdc1, logical block 86901917, async page read
[213645.436128] blk_partition_remap: fail for partition 1
[213645.436131] Buffer I/O error on dev sdc1, logical block 86901917, async page read
[213645.713515] blk_partition_remap: fail for partition 1
[213645.713519] Buffer I/O error on dev sdc1, logical block 86901917, async page read
[213645.718412] blk_partition_remap: fail for partition 1
[213645.718415] Buffer I/O error on dev sdc1, logical block 86901917, async page read
[207533.497628] scsi 4:0:0:0: Direct-Access     ADATA    HV610            5438 PQ: 0 ANSI: 6
[207533.498425] sd 4:0:0:0: Attached scsi generic sg0 type 0
[207533.498602] sd 4:0:0:0: [sdc] 1953525164 512-byte logical blocks: (1.00 TB/932 GiB)
[207533.499030] sd 4:0:0:0: [sdc] Write Protect is off
[207533.499036] sd 4:0:0:0: [sdc] Mode Sense: 23 00 00 00
[207533.499486] sd 4:0:0:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[207533.695300]  sdc: sdc1
[207533.697022] sd 4:0:0:0: [sdc] Attached SCSI disk
[207650.416911] blk_partition_remap: fail for partition 1
[207650.416917] Buffer I/O error on dev sdd1, logical block 123439533, async page read
[207650.417506] blk_partition_remap: fail for partition 1
[207650.417510] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207650.417773] blk_partition_remap: fail for partition 1
[207650.417777] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207650.505595] blk_partition_remap: fail for partition 1
[207650.505600] Buffer I/O error on dev sdd1, logical block 123439533, async page read
[207650.506450] blk_partition_remap: fail for partition 1
[207650.506455] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207650.506726] blk_partition_remap: fail for partition 1
[207650.506730] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207650.606306] blk_partition_remap: fail for partition 1
[207650.606312] Buffer I/O error on dev sdd1, logical block 123439533, async page read
[207650.606661] blk_partition_remap: fail for partition 1
[207650.606667] Buffer I/O error on dev sdd1, logical block 123439533, async page read
[207650.606965] blk_partition_remap: fail for partition 1
[207650.606969] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207650.636278] blk_partition_remap: fail for partition 1
[207650.636284] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207650.644200] blk_partition_remap: fail for partition 1
[207650.652168] blk_partition_remap: fail for partition 1
[207650.664531] blk_partition_remap: fail for partition 1
[207650.670721] blk_partition_remap: fail for partition 1
[207650.681685] blk_partition_remap: fail for partition 1
[207650.693452] blk_partition_remap: fail for partition 1
[207650.841221] blk_partition_remap: fail for partition 1
[207650.842048] blk_partition_remap: fail for partition 1
[207650.842463] blk_partition_remap: fail for partition 1
[207650.990543] blk_partition_remap: fail for partition 1
[207651.358241] blk_partition_remap: fail for partition 1
[207651.358716] blk_partition_remap: fail for partition 1
[207651.358918] blk_partition_remap: fail for partition 1
[207651.859490] blk_partition_remap: fail for partition 1
[207651.860376] blk_partition_remap: fail for partition 1
[207651.860651] blk_partition_remap: fail for partition 1
[207651.890267] blk_partition_remap: fail for partition 1
[207651.890923] blk_partition_remap: fail for partition 1
[207651.891273] blk_partition_remap: fail for partition 1
[207652.424020] blk_partition_remap: fail for partition 1
[207652.424433] blk_partition_remap: fail for partition 1
[207652.424574] blk_partition_remap: fail for partition 1
[207652.560293] blk_partition_remap: fail for partition 1
[207652.561204] blk_partition_remap: fail for partition 1
[207652.561477] blk_partition_remap: fail for partition 1
[207653.790457] blk_partition_remap: fail for partition 1
[207653.791308] blk_partition_remap: fail for partition 1
[207653.791748] blk_partition_remap: fail for partition 1
[207654.290166] blk_partition_remap: fail for partition 1
[207654.290886] blk_partition_remap: fail for partition 1
[207654.291250] blk_partition_remap: fail for partition 1
[207658.179546] blk_partition_remap: fail for partition 1
[207658.179551] buffer_io_error: 31 callbacks suppressed
[207658.179554] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.190691] blk_partition_remap: fail for partition 1
[207658.190697] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.197844] blk_partition_remap: fail for partition 1
[207658.197849] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.205589] blk_partition_remap: fail for partition 1
[207658.205598] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.213264] blk_partition_remap: fail for partition 1
[207658.213276] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.220679] blk_partition_remap: fail for partition 1
[207658.220684] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.229542] blk_partition_remap: fail for partition 1
[207658.229545] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.233234] blk_partition_remap: fail for partition 1
[207658.233237] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.236608] blk_partition_remap: fail for partition 1
[207658.236613] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.245026] blk_partition_remap: fail for partition 1
[207658.245030] Buffer I/O error on dev sdd1, logical block 86901917, async page read
[207658.971400] blk_partition_remap: fail for partition 1
[207658.981031] blk_partition_remap: fail for partition 1
[207658.988260] blk_partition_remap: fail for partition 1
[207658.994217] blk_partition_remap: fail for partition 1
[207658.999494] blk_partition_remap: fail for partition 1
[207659.010001] blk_partition_remap: fail for partition 1
[207659.019840] blk_partition_remap: fail for partition 1
[207659.024023] blk_partition_remap: fail for partition 1
[207659.027659] blk_partition_remap: fail for partition 1
[207659.034993] blk_partition_remap: fail for partition 1
[207662.001361] blk_partition_remap: fail for partition 1
[207662.015761] blk_partition_remap: fail for partition 1
[207673.530458] blk_partition_remap: fail for partition 1
[207673.530463] buffer_io_error: 12 callbacks suppressed
[207673.530466] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.540426] blk_partition_remap: fail for partition 1
[207673.540432] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.549441] blk_partition_remap: fail for partition 1
[207673.549447] Buffer I/O error on dev sda1, logical block 203103731, async page read
[207673.557799] blk_partition_remap: fail for partition 1
[207673.557805] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.562640] blk_partition_remap: fail for partition 1
[207673.562645] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.569292] blk_partition_remap: fail for partition 1
[207673.569298] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.585475] blk_partition_remap: fail for partition 1
[207673.585486] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.592420] blk_partition_remap: fail for partition 1
[207673.592425] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.596843] blk_partition_remap: fail for partition 1
[207673.596847] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207673.604297] blk_partition_remap: fail for partition 1
[207673.604304] Buffer I/O error on dev sda1, logical block 86901917, async page read
[207676.374495] blk_partition_remap: fail for partition 1
[207676.379202] blk_partition_remap: fail for partition 1
[208572.099933] usb 2-1: USB disconnect, device number 24
[208572.364498] sd 4:0:0:0: [sdc] Synchronizing SCSI cache
[208572.364522] sd 4:0:0:0: [sdc] Synchronize Cache(10) failed: Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK
```

And:

```
[208572.551422] blk_partition_remap: fail for partition 1
[208572.551425] buffer_io_error: 2 callbacks suppressed
[208572.551426] Buffer I/O error on dev sdc1, logical block 130827087, async page read
```

**Comment by ThomasWaldmann** [comment] 2018-10-17 09:41
The disk(s) look(s) defective.

**Comment by fullofcaffeine** [comment] 2018-10-17 16:32
The exact same backup with the same disks completed successfully in my macos box. I think it might have to do with the NTFS implementation. Is there anything else I could do to confirm what the problem is?

**Comment by ThomasWaldmann** [comment] 2018-10-17 23:46
All these I/O errors from the kernel log show rather clearly that there is a hw issue.
SMART can tell you more, post the output from the command I gave.

**Comment by fullofcaffeine** [comment] 2018-10-18 18:50
The supposedly faulty HD is mounted at /dev/sda1. I tried the following commands:

```
sudo smartctl -t long /dev/sda1                                                                       [2.5.0]
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-32-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Long (extended) offline self test failed [unsupported scsi opcode]
```

And:

```
 sudo smartctl -t long /dev/sda                                                                        [2.5.0]
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-32-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Unknown USB bridge [0x125f:0xa21a (0x6503)]
Please specify device type with the -d option.
```

The backup worked fine when this same HD was mounted in the macos box, which makes this issue not so critical for me. However, I'm very curious as to why it fails when mounted from the Linux Mint box. Any insights appreciated. Let me know if you need more data.

**Comment by ThomasWaldmann** [comment] 2018-10-18 19:20
Try: `sudo smartctl -dsat -t long /dev/sda`

It'll announce how long it will run and afterwards you need to read the results with `-a`.

**Comment by fullofcaffeine** [comment] 2018-10-20 03:10
I've started the test and enough time has passed, but I'm not sure how to get the results now. What do you mean by `read the results with -a`? I tried:

```
sudo smartctl -a /dev/sda                                                         [2.5.0]
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-32-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Unknown USB bridge [0x125f:0xa21a (0x6503)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
``` 

But I get the error above. Am I doing something wrong?

Thanks a lot for the help so far!

**Comment by robaato** [comment] 2018-10-20 08:17
Have you got the error mentioned when you used 
`sudo smartctl -dsat -t long /dev/sda` ?
if not read the results using similar command:
`sudo smartctl -dsat -a /dev/sda`

Howewer, if you had an this error while issuing the first command then your USB bridge may not be supported. You can try other type of bridges or try to identify a chip which is driving it. The option -d is for passing a device type. Try to look at: https://www.smartmontools.org/wiki/Supported_USB-Devices

**Comment by fullofcaffeine** [comment] 2018-10-20 17:12
@robaato Thanks a lot, reading the results with the command you provided worked.

Here they are:

```
sudo smartctl -dsat -a /dev/sda                                      [2.5.0]
[sudo] password for fullofcaffeine: 
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-32-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Toshiba 2.5" HDD MQ01ABD...
Device Model:     TOSHIBA MQ01ABD100
Serial Number:    X4PASU8AS
LU WWN Device Id: 5 000039 5d5a88b61
Firmware Version: AX101U
User Capacity:    1 000 204 886 016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS (minor revision not indicated)
SATA Version is:  SATA 2.6, 3.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Sat Oct 20 12:10:54 2018 CDT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART Status not supported: Incomplete response, ATA output registers missing
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (  25)	The self-test routine was aborted by
					the host.
Total time to complete Offline 
data collection: 		(  120) seconds.
Offline data collection
capabilities: 			 (0x5b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 ( 230) minutes.
SCT capabilities: 	       (0x003d)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   050    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0005   100   100   050    Pre-fail  Offline      -       0
  3 Spin_Up_Time            0x0027   100   100   001    Pre-fail  Always       -       2606
  4 Start_Stop_Count        0x0032   100   100   000    Old_age   Always       -       2232
  5 Reallocated_Sector_Ct   0x0033   100   100   050    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000b   100   100   050    Pre-fail  Always       -       0
  8 Seek_Time_Performance   0x0005   100   100   050    Pre-fail  Offline      -       0
  9 Power_On_Hours          0x0032   095   095   000    Old_age   Always       -       2122
 10 Spin_Retry_Count        0x0033   144   100   030    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       268
191 G-Sense_Error_Rate      0x0032   100   100   000    Old_age   Always       -       12
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       146
193 Load_Cycle_Count        0x0032   100   100   000    Old_age   Always       -       6588
194 Temperature_Celsius     0x0022   100   100   000    Old_age   Always       -       27 (Min/Max 21/51)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   200   253   000    Old_age   Always       -       19
220 Disk_Shift              0x0002   100   100   000    Old_age   Always       -       64
222 Loaded_Hours            0x0032   099   099   000    Old_age   Always       -       447
223 Load_Retry_Count        0x0032   100   100   000    Old_age   Always       -       0
224 Load_Friction           0x0022   100   100   000    Old_age   Always       -       0
226 Load-in_Time            0x0026   100   100   000    Old_age   Always       -       179
240 Head_Flying_Hours       0x0001   100   100   001    Pre-fail  Offline      -       0

SMART Error Log Version: 1
ATA Error Count: 19 (device log contains only the most recent five errors)
	CR = Command Register [HEX]
	FR = Features Register [HEX]
	SC = Sector Count Register [HEX]
	SN = Sector Number Register [HEX]
	CL = Cylinder Low Register [HEX]
	CH = Cylinder High Register [HEX]
	DH = Device/Head Register [HEX]
	DC = Device Command Register [HEX]
	ER = Error register [HEX]
	ST = Status register [HEX]
Powered_Up_Time is measured from power on, and printed as
DDd+hh:mm:SS.sss where DD=days, hh=hours, mm=minutes,
SS=sec, and sss=millisec. It "wraps" after 49.710 days.

Error 19 occurred at disk power-on lifetime: 2039 hours (84 days + 23 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 c0 b8 81 b0 40  Error: ICRC, ABRT 192 sectors at LBA = 0x00b081b8 = 11567544

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  25 00 00 78 7b b0 40 00      08:05:32.988  READ DMA EXT
  25 00 f0 88 74 b0 40 00      08:05:32.979  READ DMA EXT
  25 00 00 88 6c b0 40 00      08:05:32.969  READ DMA EXT
  25 00 00 88 64 b0 40 00      08:05:32.961  READ DMA EXT
  25 00 00 88 5c b0 40 00      08:05:32.927  READ DMA EXT

Error 18 occurred at disk power-on lifetime: 2039 hours (84 days + 23 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 60 58 65 06 40  Error: ICRC, ABRT 96 sectors at LBA = 0x00066558 = 419160

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  25 00 00 b8 5f 06 40 00      08:00:30.332  READ DMA EXT
  25 00 00 b8 57 06 40 00      08:00:30.322  READ DMA EXT
  25 00 00 b8 4f 06 40 00      08:00:30.312  READ DMA EXT
  25 00 00 b8 47 06 40 00      08:00:30.304  READ DMA EXT
  25 00 00 b8 3f 06 40 00      08:00:30.269  READ DMA EXT

Error 17 occurred at disk power-on lifetime: 1949 hours (81 days + 5 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 d0 58 f0 9f 40  Error: ICRC, ABRT 208 sectors at LBA = 0x009ff058 = 10481752

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  25 00 00 28 ee 9f 40 00      02:08:02.519  READ DMA EXT
  35 00 00 28 0d a8 40 00      02:08:02.518  WRITE DMA EXT
  35 00 00 28 0c a8 40 00      02:08:02.518  WRITE DMA EXT
  35 00 00 28 0b a8 40 00      02:08:02.517  WRITE DMA EXT
  35 00 00 28 0a a8 40 00      02:08:02.516  WRITE DMA EXT

Error 16 occurred at disk power-on lifetime: 1726 hours (71 days + 22 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 00 17 d0 d2 40  Error: ICRC, ABRT at LBA = 0x00d2d017 = 13815831

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  25 00 08 10 d0 d2 40 00      01:17:06.105  READ DMA EXT
  25 00 10 c8 68 8b 40 00      01:17:05.990  READ DMA EXT
  25 00 10 58 63 8b 40 00      01:17:05.958  READ DMA EXT
  25 00 10 a8 6e 8b 40 00      01:17:05.949  READ DMA EXT
  25 00 10 68 71 8b 40 00      01:17:05.939  READ DMA EXT

Error 15 occurred at disk power-on lifetime: 1646 hours (68 days + 14 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 60 b8 d4 ad 40  Error: ICRC, ABRT 96 sectors at LBA = 0x00add4b8 = 11392184

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  25 00 00 18 d4 ad 40 00      01:21:12.547  READ DMA EXT
  25 00 00 18 d3 ad 40 00      01:21:12.543  READ DMA EXT
  25 00 00 18 d2 ad 40 00      01:21:12.542  READ DMA EXT
  25 00 00 18 d1 ad 40 00      01:21:12.540  READ DMA EXT
  25 00 00 18 d0 ad 40 00      01:21:12.538  READ DMA EXT

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Aborted by host               90%      2109         -
# 2  Extended offline    Aborted by host               90%      2105         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```

@ThomasWaldmann 

Again, I should mention that this disk works great when mounted from the MacOS box, but for some reason the failures happen when using it from this Linux box.

**Comment by ThomasWaldmann** [comment] 2018-10-20 17:30
I am closing this as it looks quite clearly like a hw issue.

Keep us updated if you find the root cause.

**Closed by ThomasWaldmann** 2018-10-20 17:30 UTC
Labels: hardware-issue
