### ISSUE TITLE
stats argument of borg create with a remote repository doesn't work without verbose

### ISSUE THREAD

**Issue by ronalde** [borgbackup/borg#2542] opened 2017-05-21 10:30 UTC
LS, in current stable version 1.0.10 `borg create --progress --stats` with a remote repository doesn't work without adding the *verbose* parameter, ie `borg create --progress --stats --verbose`. 

It seems stats should work regardless of the verbose setting?

Regards,
Ronald

**Comment by enkore** [comment] 2017-05-21 10:44
In 1.0 you also need to supply -v/--verbose (see examples in docs)

Duplicate of #771, #865, #1958

https://borgbackup.readthedocs.io/en/stable/usage.html#type-of-log-output

**Comment by ronalde** [comment] 2017-05-21 10:59
Sorry, for missing those!

Although it may look like I dind't read anyhting, I did look up the description of the stats argument in the man page:
```
 -s, --stats           print statistics for the created archive
```
The crucial information of the required logging output is located in another (non-related) section of the man page. 

I guess this would solve this (and prevent future duplicate issues like mine ;):

```diff
--- borg-create.1.ori   2017-05-21 12:54:09.855358858 +0200
+++ borg-create.1       2017-05-21 12:58:05.148575608 +0200
@@ -88,10 +88,10 @@
 do not create a backup archive
 .TP
 .B \-s\fP,\fB  \-\-stats
-print statistics for the created archive
+print statistics for the created archive (requires at least INFO logging output)
 .TP
 .B \-\-list
-output verbose list of items (files, dirs, ...)
+output verbose list of items (files, dirs, ...)  (requires at least INFO logging output)
 .TP
 .BI \-\-filter \ STATUSCHARS
 only display items with the given status characters
```

Cheers,
Ronald

**Comment by enkore** [comment] 2017-05-21 15:02
That's actually a very good point.

**Closed** 2017-05-21 15:19 UTC
Labels: documentation, duplicate
