### ISSUE TITLE
sshfs and OSError Input/output

### ISSUE THREAD

**Issue by liminspace** [borgbackup/borg#1775] opened 2016-10-30 03:38 UTC
Hi.
I mounded remote dir via sshfs:

```
sshfs -o password_stdin -o idmap=user -o reconnect -o allow_root -o cache=no ... /mnt/rd
```

then run borg init:

```
cd /mnt/rd
BORG_PASSPHRASE="" borg init --no-files-cache --encryption keyfile borg_repo
```

and sometimes I get error:

```
Error: Exception ignored in: <bound method Repository.__del__ of <Repository /mnt/hdd1/tmp/remote_dest_l5clyxj_/borg_repo>>
Traceback (most recent call last):
  File "borg/repository.py", line 72, in __del__
  File "borg/repository.py", line 192, in close
  File "borg/locking.py", line 298, in release
  File "borg/locking.py", line 216, in modify
KeyError: (('myhost', 25642, 0),)
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1928, in main
  File "borg/archiver.py", line 1873, in run
  File "borg/archiver.py", line 87, in wrapper
  File "borg/repository.py", line 94, in __exit__
  File "borg/repository.py", line 192, in close
  File "borg/locking.py", line 300, in release
  File "borg/locking.py", line 196, in remove
OSError: [Errno 5] Input/output error: '/mnt/rd/borg_repo/lock.roster'

Platform: Linux myhost 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64
Linux: debian 8.6
Borg: 1.0.8  Python: CPython 3.5.2
PID: 25642  CWD: /mnt/rd
sys.argv: ['borg', 'init', '--no-files-cache', '--encryption', 'keyfile', 'borg_repo']
SSH_ORIGINAL_COMMAND: None
```

The same situation if I use command `borg create`.

What I do wrong?

**Comment by ThomasWaldmann** [comment] 2016-10-30 14:04
That seems to be the main thing in the output:
```
OSError: [Errno 5] Input/output error: '/mnt/rd/borg_repo/lock.roster'
```

So maybe just your ssh connection broke down?

BTW, I would not cd into the sshfs mount. If it breaks down, it also makes your cwd invalid.

**Comment by liminspace** [comment] 2016-10-30 21:59
It is SFTP and connections is OK, I tried copy large files.
I use cd to mount directory because I want key file with name borg_repo, but not mnt-rd-borg_repo.

**Comment by ThomasWaldmann** [comment] 2016-10-30 23:35
Hmm, it is sshfs, why do you say it is sftp?

**Comment by liminspace** [comment] 2016-10-30 23:41
I don't sure but here https://www.hetzner.de/ot/hosting/storagebox/bx40 and here https://wiki.hetzner.de/index.php/Storage_Boxes/en no information about SSH.

**Comment by ThomasWaldmann** [comment] 2016-10-31 00:04
Oh, sshfs seems based on sftp. I thought it is using ssh transport in a similar way like borg does.

**Comment by ThomasWaldmann** [comment] 2016-10-31 00:06
Can you reproduce this issue? Does it always blow up or just sometimes?

If you try the same thing locally, I assume it works? If it does, you have a sshfs issue (or an issue with the remote server), not an issue with borg.

**Comment by liminspace** [comment] 2016-10-31 01:40
It good works on local directory.
Now I found good solution using davfs/webdav. It works very good. I mount davfs, run backup, then unmount with waiting to sync davfs-cache, and then clear davfs-cache.

I think it's good idea to add logic with trying when it use remote directory, because if network is not stable it should works without errors.

**Comment by ThomasWaldmann** [comment] 2016-10-31 01:50
Hmm, I am tending to close this. What you see are problems of the network filesystems you use, borg just does normal file operations and expects them working normally. Retry / Reconnect logic should be implemented there, transparently.

What borg does on the application layer is checkpointing (in 1.0: every 5 minutes), so if your backup ran for an hour and then the connection breaks down or some other fatal error happens, you will have 55 minutes or so stored in the last checkpoint archive. If you then just start the borg command again, it will not need to transfer that data again.

**Comment by enkore** [comment] 2016-10-31 09:06
> Oh, sshfs seems based on sftp. I thought it is using ssh transport in a similar way like borg does.

SFTP = something somewhat similar to FTP but with just one pipe over SSH

FTPS = the loathed FTP protocol over SSL/TLS

**Comment by enkore** [comment] 2016-10-31 09:06
When sshfs throws up it can be helpful to run it in foreground (-f) mode to see what it's saying.

**Comment by ThomasWaldmann** [comment] 2016-10-31 09:11
@enkore I know it is not ftps. But I somehow assumed sshfs is using ssh rather than sftp, maybe due to the name. :P

**Comment by ThomasWaldmann** [comment] 2016-11-04 01:17
Closing, not a borg issue.

**Closed by ThomasWaldmann** 2016-11-04 01:17 UTC

**Comment by ThomasLeister** [comment] 2016-12-09 15:26
@liminspace have you found a solution or the source of the problem, yet? I'm facing the same issue with my Hetzner Backup Storage and can't figure out why Borg crashes. :(

**Comment by enkore** [comment] 2016-12-09 16:08
I don't know either, but since it generally works fine over sshfs it's,
likely either an outdated/buggy version of sshfs on the client or the
same on their servers, although I think it would be more likely that
it's an older version of sshfs.

@Op is using Debian, which ships sshfs 2.5 (2014); 2.8 is the current
version, for example.
