### ISSUE TITLE
with-lock reader instead of exclusive

### ISSUE THREAD

**Issue by jarondl** [borgbackup/borg#4425] opened 2019-03-06 20:18 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes. This is somewhat related to #3779
## Is this a BUG / ISSUE report or a QUESTION?

Feature request

`borg with-lock` creates an exclusive lock. It also creates an empty commit on the repo (for backwards compatibility). But for my use case (remote replication), I don't need an exclusive lock, I just need a reader's lock. A readers lock will allow me to run consistency checks together with remote replication.

I propose to add a `"--reader"` flag to `with-lock`, that will create a reader lock instead of an exclusive lock. It will also avoid creating the empty commit.

I could try to implement it if the maintainers accept the idea.

**Comment by infectormp** [comment] 2019-03-06 20:23
related to https://github.com/borgbackup/borg/issues/1035

**Comment by ThomasWaldmann** [comment] 2019-03-06 21:51
we had different kinds of locks for a while, but after noticing some fundamental issues, there is currently always an exclusive lock.

**Comment by jarondl** [comment] 2019-03-06 23:23
Can you shed some light on the fundamental issues? I thought there were still two kinds, it's just that with-lock uses the exclusive one?

The naive implementation for the requested feature (without updating documentation) is ff3f2f90b9087abd76e3b4f6c1330d3f806a73c9

**Comment by ThomasWaldmann** [comment] 2019-03-06 23:27
One problem was that "upgrading" a lock could deadlock.

**Comment by ThomasWaldmann** [comment] 2019-04-03 15:30
closing this, currently not doable.

**Closed by ThomasWaldmann** 2019-04-03 15:30 UTC

**Comment by alfredo08154711** [comment] 2020-02-24 12:36
I would also like to have exactly this feature. (Yes, I know about the downside of copying repos around: counter reuse in CTR mode. But this is an issue of its own and could or should be improved independently, see #4883, for example.) Aside from that, I would like to have a comprising understanding of the locking problem after I have already prepared two locking related PRs. Maybe I could help.

If you mean the lock upgrade deadlock problem as described in #1220 and (almost) fixed since 1.0.7 (specifying and applying the lock type explicitly and up-front in Repository.open()): I don't see how this could prevent the feature from being implemented in a usable way.

First of all, the upgrade deadlock problem is not really a deadlock, because we use a timeout during lock acquisition. As far as I understand, this was an issue in the described situation, bot not a bug. Since version 1.0.7 the uprade is only done in special cases.

Looking at and playing around with the code (we only look at new *client* versions here, because a new with-lock option is implemented on the client side), the only situation in which a silent lock upgrade is still performed locally or in a serving backend is if an automatic index rebuild (Repository.replay_segments()) is necessary, because the last borg command crashed between a commit tag write and an index save. This is done anyway before the first access, irrespective of the command. Adding a with-lock mode working with a shared instead of an exclusive lock would not change this situation. And I don't see why a with-lock mode with a shared lock should not work even with an old server: Currently, in order to acquire an exclusive lock on the remote side, a dummy write transaction is performed, so that the server upgrades the lock to exclusive.

We could just make a case distinction looking at the server version which is known from the result of the initiating negotiate() call (RemoteRepository.server_version): If we deal with a local repo, or if the server is >= 1.0.7, or if we only want to use a shared lock, we simply don't do that dummy write. Thus, we can even grant the wish to avoid that empty commit. Of course, for version >= 1.0.7 the 'exclusive' parameter must be passed correctly to the Repository.open() method.

I will try to implement it like this and experiment with it. As soon as I am satisfied, I will come back here.

**Comment by alfredo08154711** [comment] 2020-02-24 22:15
See https://github.com/alfredo08154711/borg/tree/with-lock-shared . But I have not yet implemented related tests.
