### ISSUE TITLE
borg upgrade fails

### ISSUE THREAD

**Issue by davidak** [borgbackup/borg#2355] opened 2017-03-29 15:58 UTC
I just tried to `borg upgrade` my repo since i updated borgbackup (without reading the manual).

```
davidak@unibook:~$ borg upgrade /run/user/1000/gvfs/smb-share\:server\=10.101.65.7\,share\=root/Technik/dkl/backup
Local Exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 2089, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 2025, in run
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 75, in wrapper
    return method(self, args, repository=None, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 783, in do_upgrade
    repo.upgrade(args.dry_run, inplace=args.inplace, progress=args.progress)
  File "/usr/local/lib/python3.5/dist-packages/borg/upgrader.py", line 39, in upgrade
    shutil.copytree(self.path, backup, copy_function=os.link)
  File "/usr/lib/python3.5/shutil.py", line 309, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup.upgrade-2017-03-29-17:24:37'

Platform: Linux unibook 4.8.0-44-generic #47~16.04.1-Ubuntu SMP Wed Mar 22 18:51:56 UTC 2017 x86_64 x86_64
Linux: "elementary" 0.4 loki
Borg: 1.0.10  Python: CPython 3.5.2
PID: 1265  CWD: /home/davidak
sys.argv: ['/usr/local/bin/borg', 'upgrade', '/run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup']
SSH_ORIGINAL_COMMAND: None
```

When you use it correctly it does work. But it would be nice to get a meaningful error message instead of that stacktrace.

https://borgbackup.readthedocs.io/en/stable/usage.html?highlight=upgrade#borg-upgrade

```
davidak@unibook:~$ borg upgrade --tam /run/user/1000/gvfs/smb-share\:server\=10.101.65.7\,share\=root/Technik/dkl/backup/
Enter passphrase for key /run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup: 
Manifest contents:
unibook-2.local-2016-08-25           Thu, 2016-08-25 13:00:13 [xxxxx]
Key updated
Key location: /run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup
Updated security database
```

Thanks for the work on borgbackup! (you can't say it enough)

**Comment by ThomasWaldmann** [comment] 2017-03-29 16:21
You're quite brave feeding such strange pathes to tools. I guess I'ld always mount to a "normal looking" path first and then give that to the tool.

I don't find the traceback bad in this case, you could at least see that mkdir stumbled over the path you provided. If we provide pretty, short error msgs, some of that information could be lost and you could do nothing about it (esp. not if it is a one-time issue and can't be reproduced easily with --debug or whatever).

**Comment by enkore** [comment] 2017-03-29 16:24
We should probably redo the upgrade CLI, e.g. `borg upgrade --from-attic ...`, (since it's overloaded in the C++ sense now) and also add some checks that the path looks like an attic repo.

**Comment by davidak** [comment] 2017-03-29 16:40
>I guess I'ld always mount to a "normal looking" path first and then give that to the tool.

GVFS mounts to this strange paths, but else it works great. I don't have to use `sudo` to `mount` the share and can do everything in the backup script.

>mkdir stumbled over the path

yes, the `:` is the problem

```
davidak@unibook:~$ mkdir "/run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup.upgrade-2017-03-29-17:24"
mkdir: das Verzeichnis »/run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup.upgrade-2017-03-29-17:24“ kann nicht angelegt werden: Ist kein Verzeichnis
davidak@unibook:~$ mkdir "/run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup.upgrade-2017-03-29-17"
```

**Comment by ThomasWaldmann** [comment] 2017-03-29 22:33
iirc, we already have a ticket about shorter / more pretty error msgs, so I am closing this one.

**Closed by ThomasWaldmann** 2017-03-29 22:33 UTC
