### ISSUE TITLE
extract: original mtime not preserved on files with ResourceFork

### ISSUE THREAD

**Issue by rxgh99** [borgbackup/borg#7234] opened 2022-12-29 09:08 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug. Originally logged under Vorta bug [#939](https://github.com/borgbase/vorta/issues/939).

## System information. For client/server mode post info for both machines.

Macbook Air, M1. 

#### Your borg version (borg -V).

1.2.3

#### Operating system (distribution) and version.

macOS 12.6.2

#### Hardware / network configuration, and filesystems used.

Local APFS (encrypted)

#### How much data is handled by borg?

n/a

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg extract

## Describe the problem you're observing.

Any file that has macOS xattr com.apple.ResourceFork is restored with a "modified" date equal to the date and time of the restore and not the original modified time of the file.  Example below. 

```
$ touch test1.txt  //create test file 1
$ touch test2.txt  //create test file 2
$ xattr -w com.apple.ResourceFork mytestrf test1.txt  //Add com.apple.ResourceFork to test1.txt
$ xattr -p com.apple.ResourceFork test1.txt           //Check xattr is added
mytestrf

$ ls -l test*.txt
-rw-r--r--@ 1 rxgh99  admin  0 Dec 29 00:32 test1.txt  <-- Original modified date/time of test1
-rw-r--r--  1 rxgh99  admin  0 Dec 29 00:31 test2.txt

$ borg create test-repo::xattr2 test*.txt

$ borg list test-repo::xattr2
-rw-r--r-- rxgh99   admin         0 Thu, 2022-12-29 00:32:03 test1.txt  <-- As captured in the repo
-rw-r--r-- rxgh99   admin         0 Thu, 2022-12-29 00:31:56 test2.txt

$ cd restore
$ borg extract ../test-repo::xattr2

$ date
Thu Dec 29 00:41:36 PST 2022

$ ls -l
-rw-r--r--@ 1 rxgh99  admin  0 Dec 29 00:41 test1.txt  <-- Modified date/time at restore
-rw-r--r--  1 rxgh99  admin  0 Dec 29 00:31 test2.txt

$ xattr -p com.apple.ResourceFork test1.txt  //Check xattr is restored
mytestrf
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. Any restore of a file that includes com.apple.ResourceFork results in this behavior. 

#### Include any warning/errors/backtraces from the system logs

No warnings or errors.

**Comment by ThomasWaldmann** [comment] 2022-12-29 12:07
Thanks for this report. Does this happen also if only any other xattr is set on a file?

**Comment by rxgh99** [comment] 2022-12-29 19:19
I have not tested all xattrs, but based on my (limited) testing it only appears to happen when com.apple.ResourceFork is present as an xattr. 

```
WITH com.apple.ResourceFork
$ borg list test-repo::xattr3
-rw-r----- rxgh99   admin   1522481 Fri, 2012-06-15 18:26:28 VFX_Manual.pdf  //com.apple.ResourceFork present
-rw-r----- rxgh99   admin    277504 Tue, 2011-02-01 20:55:39 WI_setup.doc    //com.apple.ResourceFork present
-rw-r----- rxgh99   admin   1522481 Fri, 2012-06-15 18:26:28 test-norf.pdf   //no xattrs
-rw-r--r-- rxgh99   admin         0 Thu, 2022-12-29 00:32:03 test1.txt       //com.apple.ResourceFork present
-rw-r--r-- rxgh99   admin         0 Thu, 2022-12-29 00:31:56 test2.txt       //no xattrs

$ ls -l restore3
-rw-r-----@ 1 rxgh99  admin  1522481 Dec 29 11:01 VFX_Manual.pdf  <-- date at restore time
-rw-r-----@ 1 rxgh99  admin   277504 Dec 29 11:01 WI_setup.doc    <-- date at restore time
-rw-r-----@ 1 rxgh99  admin  1522481 Jun 15  2012 test-norf.pdf
-rw-r--r--@ 1 rxgh99  admin        0 Dec 29 11:01 test1.txt
-rw-r--r--  1 rxgh99  admin        0 Dec 29 00:31 test2.txt       <-- date at restore timne

restore3 $ xattr WI*
com.apple.ResourceFork
com.apple.metadata:kMDItemWhereFroms

REMOVED com.apple.ResourceFork from WI_setup.doc
$ borg list test-repo::xattr4
-rw-r----- rxgh99   admin   1522481 Fri, 2012-06-15 18:26:28 VFX_Manual.pdf //com.apple.ResourceFork still present
-rw-r----- rxgh99   admin    277504 Tue, 2011-02-01 20:55:39 WI_setup.doc   //Removed com.apple.ResourceFork
-rw-r----- rxgh99   admin   1522481 Fri, 2012-06-15 18:26:28 test-norf.pdf
-rw-r--r-- rxgh99   admin         0 Thu, 2022-12-29 00:32:03 test1.txt
-rw-r--r-- rxgh99   admin         0 Thu, 2022-12-29 00:31:56 test2.txt

$ ls -l restore4
total 6512
-rw-r-----@ 1 rxgh99  admin  1522481 Dec 29 11:03 VFX_Manual.pdf  <-- date at restore time
-rw-r-----@ 1 rxgh99  admin   277504 Feb  1  2011 WI_setup.doc    <-- original date
-rw-r-----@ 1 rxgh99  admin  1522481 Jun 15  2012 test-norf.pdf
-rw-r--r--@ 1 rxgh99  admin        0 Dec 29 11:03 test1.txt
-rw-r--r--  1 rxgh99  admin        0 Dec 29 00:31 test2.txt

restore4 rxgh99$ xattr VFX*
com.apple.Preview.UIstate.v1
com.apple.ResourceFork
com.apple.metadata:kMDItemWhereFroms

restore4 $ xattr WI*
com.apple.metadata:kMDItemWhereFroms
```

**Comment by ThomasWaldmann** [comment] 2022-12-29 20:21
Hmm, there is no code in borg that special-cases ResourceFork.

So, is it maybe macOS "jumping on" that freshly extracted file and touching it, modifying its timestamp? Maybe some indexing or security stuff?

**Comment by rxgh99** [comment] 2022-12-29 20:45
That I do not know - I was wondering if it was a "timing" issue of some sort, between the extract process and, as you suggest, some OS activities. But then why might the OS only touch those with com.apple.ResourceFork xattr attribute and not others? It's an old attribute, for sure. 

I previously tried a similar process with Duplicacy and Arq. Duplicacy showed the same behavior as here but Arq restored the original modified date.

**Comment by jdchristensen** [comment] 2022-12-29 21:05
Is there something like linux's `strace` that you could use to see what syscalls `borg extract` is making, just to confirm whether it is borg or the OS?

**Comment by jdchristensen** [comment] 2022-12-29 21:23
I noticed that borg seems to set the mtime before setting the xattrs.  Would it help to do it in the other order?  Does MacOS update the mtime when that particular xattr is set?

**Comment by ThomasWaldmann** [comment] 2022-12-29 21:23
https://github.com/borgbackup/borg/blob/1.2.3/src/borg/archive.py#L885

this is how borg 1.2.3 extracts the metadata (after extracting file data, but before closing the file).

**Comment by ThomasWaldmann** [comment] 2022-12-29 21:34
@jdchristensen yeah, changing order might help.

but if there is some race with macOS touching fresh files, it would depend on who wins the race.

also it does not explain why it only happens with ResourceFork xattr entry.

**Comment by ThomasWaldmann** [comment] 2022-12-29 21:47
From samba git:

On Darwin other than all the normal filesystem operations, 'Finder' (like
Explorer in Windows but a little more) keeps its information in two extended
attributes named 'com.apple.FinderInfo' and 'com.apple.ResourceFork'.

If these xattrs are not implemented the filesystem won't be shown on Finder, and if they
are not implemented properly there may be issues when some of the file operations
are done through GUI of Finder. But when a filesystem is used over mountpoint in a
terminal, everything is fine and these xattrs are not required.

**Comment by ThomasWaldmann** [comment] 2022-12-29 22:04
Note: I am trying to write a test for this.

**Comment by rxgh99** [comment] 2022-12-29 22:11
> Is there something like linux's `strace` that you could use to see what syscalls `borg extract` is making, just to confirm whether it is borg or the OS?

There is dtruss that encapsulates dtrace, but need to remove SIP protection to run.

**Comment by ThomasWaldmann** [comment] 2022-12-29 22:36
@jdchristensen no, moving the timestamp setting code close to the end (right before the place where it might set the immutable flag) does not help.

**Comment by ThomasWaldmann** [comment] 2022-12-29 23:15
@rxgh99 btw, congrats for finding this. guess this is a rather old and "special" bug...

**Comment by ThomasWaldmann** [comment] 2022-12-29 23:22
This might be even an issue in macOS. Guess setting the `ResourceFork` xattr should not modify mtime because setting any other xattr does not do that either. Likely same for atime.

So, the "bug" in borg is just that we can work around this for mtime and this is what the PR implements. The issue is still there for atime, though.

**Comment by rxgh99** [comment] 2022-12-29 23:30
Old indeed ;) But it (the resource fork) can tend to litter prior installations and data, especially data that may have traversed a few years and OS versions. Would be rather good, though, if a resolution was found, for consistency across all xattrs.

I have not seen if additional time fields, other than modified and created, are affected by e.g. Arq. But that is the only tool so far that I've tested that restored those fields per the original values (modified and created times). 

Which time fields are you testing for - mtime, atime, others? I can test with Arq to see if there are similarities or not.

**Comment by ThomasWaldmann** [comment] 2022-12-29 23:34
Tested: birthtime, mtime (and atime, but that is commented out in the final test code).

OK: birthtime

Fixed / worked around after #7235: mtime
 
Not fixed: atime (but guess we can not fix this in borg)

ctime can not be set by userspace.

**Comment by rxgh99** [comment] 2022-12-30 02:32
A quick and dirty compare. Colours are compared to the original. Green = exact match; red = mismatch to original. 
Interestingly, Arq appears to set atime to same as mtime (which is same as btime each time). 

<img width="714" alt="restore-compare" src="https://user-images.githubusercontent.com/81989963/210028658-713b18ba-f072-4d80-a3c7-8072cfbdb11c.png">

**Comment by rxgh99** [comment] 2022-12-30 08:45
If I create an archive with --atime, files without com.apple.ResourceFork are extracted with original atime. (Files with com.apple.ResourceFork exhibit current behavior). Note values for test-norf.pdf below. 

```
 $ stat -f "%N%n atime:%Sa%n ctime:%Sc%n mtime:%Sm%n btime:%SB%n" *
VFX_Manual.pdf
 atime:Dec 30 00:41:14 2022
 ctime:Dec 30 00:41:13 2022
 mtime:Dec 30 00:41:13 2022
 btime:Jun 15 18:26:28 2012
WI_setup.doc
 atime:Dec 30 00:41:14 2022
 ctime:Dec 30 00:41:13 2022
 mtime:Dec 30 00:41:13 2022
 btime:Feb  1 20:55:39 2011
test-norf.pdf
 atime:Apr  8 12:37:33 2022
 ctime:Dec 30 00:41:13 2022
 mtime:Jun 15 18:26:28 2012
 btime:Jun 15 18:26:28 2012
```

**Closed** 2023-01-06 21:25 UTC
Labels: bug, cmd: extract, os: macOS
