### ISSUE TITLE
"borg init ." deletes cwd (if empty) when being cancelled

### ISSUE THREAD

**Issue by DarrienG** [borgbackup/borg#4365] opened 2019-02-14 20:08 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

## System information. For client/server mode post info for both machines.

macOS Mojave 10.14.3 / N/A
Ubuntu 18.04 / N/A

#### Your borg version (borg -V).

borg 1.1[5-9]

#### Operating system (distribution) and version.

macOS Mojave 10.14.3 / N/A
Ubuntu 18.04 / N/A

#### Hardware / network configuration, and filesystems used.

APFS/EXT4

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ borg init -e repokey .
^C
```

## Describe the problem you're observing.

^C'ing out of the command deletes the current directory you're in.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Make a directory, cd to it, run 

```
$ borg init -e repokey .
^C
```

Borg will delete the directory you are in.

#### Include any warning/errors/backtraces from the system logs

No errors when running. Python complains after the path doesn't exist when running any command afterwards.

```
$ borg init -e repokey --help
Traceback (most recent call last):
  File "borg/__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/vagrant/.pyenv/versions/3.5.6/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/archiver.py", line 30, in <module>
  File "borg/logger.py", line 210, in create_logger
  File "borg/logger.py", line 156, in __init__
  File "borg/logger.py", line 127, in find_parent_module
  File "inspect.py", line 706, in getmodule
  File "inspect.py", line 689, in getabsfile
  File "inspect.py", line 677, in getsourcefile
  File "inspect.py", line 706, in getmodule
  File "inspect.py", line 690, in getabsfile
  File "posixpath.py", line 362, in abspath
FileNotFoundError: [Errno 2] No such file or directory
Failed to execute script __main__
```

**Comment by DarrienG** [comment] 2019-02-14 22:35
Update - this happens if given any directory and leaving before giving a passphrase. This is dangerous behavior.

**Comment by ThomasWaldmann** [comment] 2019-02-14 23:23
You shouldn't give `.` as a repo directory, but a new, not yet existing directory.

Is that happening on Linux or on macOS or both?

Are you using the all-in-one fat binary (made with pyinstaller) from github releases?

**Comment by ThomasWaldmann** [comment] 2019-02-14 23:26
(and sorry in case you lost data due to that, but nobody brought that up yet)

**Comment by lfam** [comment] 2019-02-14 23:41
> Is that happening on Linux or on macOS or both?

I can reproduce the issue on Linux 4.20.8. Send SIGINT with Ctrl+C after the password prompt is shown.

> Are you using the all-in-one fat binary (made with pyinstaller) from github releases?

I'm using the Guix package of Borg 1.1.8.

**Comment by DarrienG** [comment] 2019-02-14 23:47
No worries. I was just testing it out and really confused.

It happens on both Linux and macOS. Package installed from brew on macOS, install from apt on Ubuntu.

This behavior happens even without passing `.` in as the arg. 

Try:

```
$ docker run --rm -it ubuntu:18.04
$ apt update -y && apt install -y borgbackup
$ mkdir test
$ ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  test  tmp  usr  var
borg init -e repokey test
Enter new passphrase: ^C
$ ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

**Comment by ThomasWaldmann** [comment] 2019-02-15 01:26
It only kills the directory if it is empty. Otherwise it refuses to work with it anyway.

So, this is a minor issue.

We can fix this by remembering whether we created the directory and only kill it in that case if init gets cancelled, but don't touch it if it was already there.

**Comment by ThomasWaldmann** [comment] 2019-02-15 01:48
The problem of running into issues with the cwd when destroying the repository `.` is likely a "wontfix".

Some users might use `.` for non-destructive borg commands and this works without an issue (AFAIK).

In case of `borg init .` and cancelling it, it internally calls `borg delete .` (kind of) to get rid of the half-made repo. You could also call `borg delete .` manually to get rid of a repo. In both cases, you'll blow away the directory you have as current work dir and that's not a nice thing to do.

So, for consistency, I guess we won't forbid using `.`.

**Comment by ThomasWaldmann** [comment] 2019-02-15 02:01
As a side note, the intended way of using init is like:
```
borg init ... /some/existing/path/not_existing_directory
```
So:
- it is not `.`
- no need to create the dir first (doesn't harm if you do create an empty dir)
- borg will create the repo dir and if you cancel in the middle, remove the half-finished one again

**Comment by ThomasWaldmann** [comment] 2019-05-09 20:26
I just had a try at fixing this.

For local repos, it would be not too hard to fix, but guess one could produce the same issue by remote "cwd" or remote "pre-made-directory" repos. To consistently fix it there also, it would need a extension of the RPC api just for this never intended kind of usage.

There is no danger of data loss here, because borg won't let you use a non-empty directory.

So just do `borg init repodir` and don't use `.` for the repodir and don't make the repodir directory beforehands, borg will create it.

**Closed by ThomasWaldmann** 2019-05-09 20:26 UTC
Labels: wontfix

**Comment by ThomasWaldmann** [comment] 2019-05-09 20:32
btw, in case some people are using "." to avoid having to type the repo name, there is the `BORG_REPO` env var for that purpose.
