### ISSUE TITLE
File changed while we backed it up

### ISSUE THREAD

**Issue by Rudd-O** [borgbackup/borg#6989] opened 2022-08-23 02:48 UTC
```
var/lib/varnish/varnishd/_.vsm_child/_.Log.73f1ce7a608eeb1e: file changed while we backed it up
```

These weren't errors before, but now in 1.2.1 they cause `borg` to exit with error.

Why was this behavior changed?  I know these files are changing and it's okay if they do change, but that should not cause my pipeline of backups to break.

Fedora 36.

**Comment by ThomasWaldmann** [comment] 2022-08-23 11:16
The **problem** was always there, borg < 1.2 just did not check for it (and thus, did not warn you about it).

borg 1.2.x does **not** exit with an error (rc 2), but with a warning (rc 1) status. Basically it means you have to check the logs and decide for yourself whether it was something severe or not.

That decision can not be done by borg, it can't know whether that is some unimportant crap file or some important valuable file that changed internally while it was being backed up.

BTW, iirc there is already some other issue open about this, can you find it?

**Comment by ThomasWaldmann** [comment] 2023-02-11 18:35
Duplicate of #6622, closing.

**Closed by ThomasWaldmann** 2023-02-11 18:35 UTC
Labels: duplicate, question
