### ISSUE TITLE
making the borg mount command non locking

### ISSUE THREAD

**Issue by frankpolte** [borgbackup/borg#952] opened 2016-04-21 08:44 UTC
what would it take to make the mounting non locking?

**Comment by infectormp** [comment] 2016-04-21 08:51
see also https://github.com/borgbackup/borg/issues/768, https://github.com/borgbackup/borg/issues/420

**Comment by enkore** [comment] 2016-04-21 08:52
Duplicate of #768

**Closed by enkore** 2016-04-21 08:52 UTC

**Comment by frankpolte** [comment] 2016-04-21 08:58
I just wanted to discuss it with my issue [#953](https://github.com/borgbackup/borg/issues/953) and [#954](https://github.com/borgbackup/borg/issues/954)
