### ISSUE TITLE
Error correction and detection with par2

### ISSUE THREAD

**Issue by neutrinus** [borgbackup/borg#373] opened 2015-11-04 13:44 UTC
I think it's not for now, just as an idea. 

Because we are using deduplication, flipping only one bit on disk may end in a destruction of many files. We could use something like [par2](https://github.com/Parchive/par2cmdline) to add durability to repository - with error detection and correction.

**Comment by ThomasWaldmann** [comment] 2015-11-04 13:56
duplicate of https://github.com/borgbackup/borg/issues/225

**Closed by ThomasWaldmann** 2015-11-04 13:56 UTC
Labels: duplicate
