### ISSUE TITLE
Input of "borg config" is not validated

### ISSUE THREAD

**Issue by seschwar** [borgbackup/borg#3653] opened 2018-03-02 12:40 UTC
The input of `borg config` is not validated at all. It allows to set any option -- even non-existing ones -- to any value.  For non-existing options this isn't really a problem. It's just a bit odd that one can add arbitrary data to the repository configuration like that. However changing existing options to invalid values causes the repository to become inaccessible.

To illustrate this I created the following script:

``` sh
#!/bin/sh
set -x

export BORG_PASSPHRASE=ResistanceIsFutile
readonly tmp="`mktemp -d`"
trap 'rm -fr -- \"$tmp\"' EXIT

for name in foo id key version
do
    export BORG_REPO="$tmp/$name"
    borg init --encryption=repokey --error ::
    borg config --error :: "$name" 0
    borg config --error :: "$name"
done
```

It creates new temporary repositories and then calls `borg config` with invalid values on them.
Here's the output of the script:

```
+ export BORG_PASSPHRASE=ResistanceIsFutile
+ mktemp -d
+ readonly tmp=/tmp/tmp.ivnx1GISKL
+ trap rm -fr -- \"$tmp\" EXIT
+ export BORG_REPO=/tmp/tmp.ivnx1GISKL/foo
+ borg init --encryption=repokey --error ::
+ borg config --error :: foo 0
+ borg config --error :: foo
0
+ export BORG_REPO=/tmp/tmp.ivnx1GISKL/id
+ borg init --encryption=repokey --error ::
+ borg config --error :: id 0
+ borg config --error :: id
Exception ignored in: <bound method Repository.__del__ of <Repository /tmp/tmp.ivnx1GISKL/id>>
Traceback (most recent call last):
  File "borg/repository.py", line 171, in __del__
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 137, in wrapper
  File "borg/repository.py", line 181, in __enter__
  File "borg/repository.py", line 394, in open
binascii.Error: Odd-length string

Platform: Linux edge 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64
Linux: debian stretch/sid 
Borg: 1.1.4  Python: CPython 3.5.4
PID: 8318  CWD: /home/seschwar
sys.argv: ['borg', 'config', '--error', '::', 'id']
SSH_ORIGINAL_COMMAND: None

+ export BORG_REPO=/tmp/tmp.ivnx1GISKL/key
+ borg init --encryption=repokey --error ::
+ borg config --error :: key 0
+ borg config --error :: key
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 139, in wrapper
  File "borg/helpers.py", line 334, in load
  File "borg/crypto/key.py", line 131, in key_factory
  File "borg/crypto/key.py", line 577, in detect
  File "borg/crypto/key.py", line 763, in load
  File "borg/crypto/key.py", line 591, in _load
binascii.Error: Incorrect padding

Platform: Linux edge 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64
Linux: debian stretch/sid 
Borg: 1.1.4  Python: CPython 3.5.4
PID: 8337  CWD: /home/seschwar
sys.argv: ['borg', 'config', '--error', '::', 'key']
SSH_ORIGINAL_COMMAND: None

+ export BORG_REPO=/tmp/tmp.ivnx1GISKL/version
+ borg init --encryption=repokey --error ::
+ borg config --error :: version 0
+ borg config --error :: version
/tmp/tmp.ivnx1GISKL/version is not a valid repository. Check repo config.
+ rm -fr -- "/tmp/tmp.ivnx1GISKL"
```

As you can see the second invocation of `borg config` (and any other `borg` command) fails in all cases but the first.

One might say that breaking ones repository by invoking `borg config :: version 0` is one's own fault. However I do think tools should be safe to use, unless their usage and power is excessively restricted by said safety. This isn't the case for `borg config` though.

Therefore I consider the behavior of `borg config` being able to break the repository a bug.

**Comment by ThomasWaldmann** [comment] 2018-03-02 12:46
borg config was meant to replace `vim repo/config` and as you and some other people noticed rather simple in its first incarnation: no validation. vim also does no validation, but borg of course could.

there is some initial work in #3581 to improve this, but it is not finished/merged yet.

**Comment by ThomasWaldmann** [comment] 2018-03-02 22:15
duplicate of #3566

**Closed by ThomasWaldmann** 2018-03-02 22:15 UTC
