### ISSUE TITLE
LockTimeout problem?

### ISSUE THREAD

**Issue by MatejKovacic** [borgbackup/borg#2807] opened 2017-07-10 14:16 UTC
So, I am running this command:
`borg list ssh://pi@backup.rpi/media/backup/matej`

And got a bunch of errors:

```
Remote: Borg 1.0.7: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "borg/locking.py", line 136, in acquire
Remote: FileExistsError: [Errno 17] File exists: '/media/backup/matej/lock.exclusive'
Remote: 
Remote: During handling of the above exception, another exception occurred:
Remote: 
Remote: Traceback (most recent call last):
Remote:   File "borg/remote.py", line 98, in serve
Remote:   File "borg/remote.py", line 136, in open
Remote:   File "borg/repository.py", line 82, in __enter__
Remote:   File "borg/repository.py", line 171, in open
Remote:   File "borg/locking.py", line 268, in acquire
Remote:   File "borg/locking.py", line 120, in __enter__
Remote:   File "borg/locking.py", line 141, in acquire
Remote: borg.locking.LockTimeout: /media/backup/matej/lock.exclusive
Remote: Platform: Linux backup 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l
Remote: Linux: debian 8.0 
Remote: Borg: 1.0.7  Python: CPython 3.5.2
Remote: PID: 26403  CWD: /home/pi
Remote: sys.argv: ['borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
('Remote Exception (see remote log for the traceback)', 'LockTimeout')
Platform: Linux cryptoloop 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.7  Python: CPython 3.5.2
PID: 4324  CWD: /home/matej
sys.argv: ['/usr/bin/borg', 'list', 'ssh://pi@backup.rpi//media/backup/matej']
SSH_ORIGINAL_COMMAND: None
```
And yes, I am using version 1.0.7 on both sides.

The problem might be, I am running first initial backup at the same time. It seems there is a problem with lock.

Is it true?

Anyway, by my opinion error message should be much more straightforward.

**Comment by enkore** [comment] 2017-07-10 22:53
> The problem might be, I am running first initial backup at the same time. It seems there is a problem with lock.

Yes

> Anyway, by my opinion error message should be much more straightforward.

Fixed in [1.1 series](https://www.borgbackup.org/releases/)

--

Duplicate of #768 et al

**Closed by enkore** 2017-07-10 22:53 UTC
