### ISSUE TITLE
borg is incompatible with setuptools 50.0.0

### ISSUE THREAD

**Issue by shadowlmd** [borgbackup/borg#5312] opened 2020-08-31 13:19 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE report

#### Your borg version (borg -V).

1.1.13

#### Operating system (distribution) and version.

Ubuntu 16.04

#### Hardware / network configuration, and filesystems used.

N/A

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg --version

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

1. pip install --upgrade setuptools
2. borg --version

#### Include any warning/errors/backtraces from the system logs

```
$ borg --version
Traceback (most recent call last):
  File "/opt/python/bin/borg", line 5, in <module>
    from borg.archiver import main
  File "/opt/python/lib/python3.5/site-packages/borg/__init__.py", line 1, in <module>
    from distutils.version import LooseVersion
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "/opt/python/lib/python3.5/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module 'setuptools' not loaded, cannot perform relative import
```

**Comment by shadowlmd** [comment] 2020-08-31 13:21
Please note that I am running borg inside venv, here's pip list output:
```
$ pip list
Package            Version
------------------ -------
argcomplete        1.12.0
borgbackup         1.1.13
importlib-metadata 1.7.0
packaging          20.4
pip                20.2.2
pipupgrade         1.7.4
pkg-resources      0.0.0
pyparsing          2.4.7
PyYAML             5.3.1
setuptools         50.0.0
six                1.15.0
wheel              0.35.1
xmltodict          0.12.0
yq                 2.10.1
zipp               1.2.0
```

**Comment by FreyJo** [comment] 2020-09-01 12:50
https://github.com/pypa/setuptools/issues/2352

setuptools 50.0 seems to break stuff all over the place..

**Comment by ThomasWaldmann** [comment] 2020-09-01 19:31
Guess we can not do much about that, but also guess there will be a fixed setuptools release soon.

Until then, just use "setuptools<50".

**Comment by ThomasWaldmann** [comment] 2020-09-22 10:51
We have 50.3.0 meanwhile, can we still reproduce?

**Comment by shadowlmd** [comment] 2020-09-22 11:21
v50.1.0¶
02 Sep 2020

#2350: Setuptools reverts using the included distutils by default. Platform maintainers and system integrators and others are strongly encouraged to set SETUPTOOLS_USE_DISTUTILS=local to help identify and work through the reported issues with distutils adoption, mainly to file issues and pull requests with pypa/distutils such that distutils performs as needed across every supported environment.

**Comment by shadowlmd** [comment] 2020-09-22 11:30
So the issue doesn't reproduce with setuptools >= 50.1 but it will most probably happen again later.

**Comment by ThomasWaldmann** [comment] 2020-09-22 11:36
OK, so considering it is not a borg bug and works now, I'll close this.

**Comment by shadowlmd** [comment] 2020-09-22 12:18
Nice problem solving. In fact this is a borg bug. You should either use setuptools package like it is intended by its developers or not use it at all.

**Comment by ThomasWaldmann** [comment] 2020-09-22 13:42
Oh? So, can you point at what precisely is wrong? Or do a PR with a fix?

**Comment by shadowlmd** [comment] 2020-09-22 14:10
I am no python dev, so don't expect much from me. I am just reading what setuptools devs are saying. This is a quote from 50.0 changelog:
```#2232: Once again, Setuptools overrides the stdlib distutils on import. For environments or invocations where this behavior is undesirable, users are provided with a temporary escape hatch. If the environment variable SETUPTOOLS_USE_DISTUTILS is set to stdlib, Setuptools will fall back to the legacy behavior. Use of this escape hatch is discouraged, but it is provided to ease the transition while proper fixes for edge cases can be addressed.```
So it was possible to use `escape hatch`, and I can confirm that it worked. But they make it very clear that this is not the right way and people should fix their packages, including borgbackup, properly. I have no idea how. Just saying.

**Comment by ThomasWaldmann** [comment] 2020-09-22 18:28
```
$ pip uninstall borgbackup
Uninstalling borgbackup-1.1.14.dev32+g62fa50c4:
  Would remove:
    /home/user/w/borg-env/bin/borg
    /home/user/w/borg-env/bin/borgfs
    /home/user/w/borg-env/lib/python3.8/site-packages/borgbackup.egg-link
Proceed (y/n)? y
  Successfully uninstalled borgbackup-1.1.14.dev32+g62fa50c4

$ SETUPTOOLS_USE_DISTUTILS=local pip install -e .
Obtaining file:///home/user/w/borg
Installing collected packages: borgbackup
  Running setup.py develop for borgbackup
Successfully installed borgbackup
WARNING: You are using pip version 19.2.3, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ SETUPTOOLS_USE_DISTUTILS=local borg -V
borg 1.1.14.dev32+g62fa50c4

$ SETUPTOOLS_USE_DISTUTILS=stdlib borg -V
borg 1.1.14.dev32+g62fa50c4

$ pip list|grep setuptools
setuptools        50.3.0                 
setuptools-scm    4.1.2                  
```

So, works for me.

**Closed by ThomasWaldmann** 2020-09-22 18:28 UTC

**Comment by ThomasWaldmann** [comment] 2020-09-22 18:32
Note: also tried 1.1.13 (`pip install borgbackup`) - it also worked.
