### ISSUE TITLE
repair stops with error 

### ISSUE THREAD

**Issue by andrewufrank** [borgbackup/borg#4260] opened 2019-01-21 15:52 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes, advice is to run check with --repair, fills blocks missing with zeros

## Is this a BUG / ISSUE report 

issue

#### Your borg version (borg -V).
borg 1.1.8

#### Operating system (distribution) and version.
debian buster -  linux
#### Hardware / network configuration, and filesystems used.
amd64 - ext4
#### How much data is handled by borg?
1 TB 
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
sudo borg check --repair siam1
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES

## Describe the problem you're observing.
I have (stupid me!) deleted the borg repositories partially (i.e. till I stopped the delete) - 1/3 is gone. I wanted to see how much of the original data can be recovered or if all is lost.

when I run borg check --repair I get the unexpected error message
```
Adding commit tag to segment 323382
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 313, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 925, in check
    self.io.write_commit()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1479, in write_commit
    fd = self.get_write_fd()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1270, in get_write_fd
    self._write_fd = SyncFile(self.segment_filename(self.segment), binary=True)
  File "src/borg/platform/linux.pyx", line 248, in borg.platform.linux.SyncFile.__init__
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 106, in __init__
    self.fd = open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/media/frank/siam_borg/borg/siam1/data/32/323383'

Platform: Linux prag 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64
Linux: debian buster/sid 
Borg: 1.1.8  Python: CPython 3.7.2
PID: 18801  CWD: /media/frank/siam_borg/borg
sys.argv: ['/usr/bin/borg', 'check', '--repair', 'siam1']
SSH_ORIGINAL_COMMAND: None
```

I would have assumed that a missing file is considered the same as a set of lost blocks. I was interested to see if and how many files can be recovered (after a capital error on my part). I have additional backup thus it is ok for now, if nothing can be restored, but I think more could be possible.

**Comment by ThomasWaldmann** [comment] 2019-01-21 21:01
/media/frank/siam_borg/borg/siam1/data/32/ can you check if that directory is there and if not, create it with correct permissions?

**Comment by ThomasWaldmann** [comment] 2019-01-21 21:04
duplicate of #3225?

**Comment by andrewufrank** [comment] 2019-01-21 22:45
I will do it tomorrow morning - what would be the correct permissions?

**Comment by ThomasWaldmann** [comment] 2019-01-21 23:31
same as the other directories you see there.

**Comment by andrewufrank** [comment] 2019-02-01 10:23
It worked as expected - and took forever (days for a 500 GB repository - I ran it on an old computer with slow usb). I think it would be a good idea to automate the construction of this empty directory automatically. 
Now: is there a way i can find out which files are still complete and which have holes?  Can I reconstruct just the files which are complete? or any other similar filter?

**Comment by ThomasWaldmann** [comment] 2019-02-01 10:34
ok, so i am closing this as a duplicate.

if you ran a full `borg check --repair`, borg should have replaced missing chunks with all-zero chunks of same size. you can try backing up the same source files again (if you still have them) and run `borg check --repair` again after that. If some previously lost chunks now are present in the repo again, the repair will heal the respective files.

**Closed by ThomasWaldmann** 2019-02-01 10:34 UTC
