### ISSUE TITLE
borg ignores mounted drive

### ISSUE THREAD

**Issue by TheOneWhoKnocks** [borgbackup/borg#1106] opened 2016-05-30 13:20 UTC
Hi, I tried using borg backup today, but I have a really odd problem. It seems to ignore my mounted drives?
 I've mounted my backup drive to /mnt created the repo /mnt/backup and started the first backup, but any data is written directly to /mnt WITHOUT using the drive mounted to it? no byte is written to the mounted drive, but if I umount the drive I can see everything has been written to /mnt directly.

 I can also see the rising used disk space on my / partitition, but no byte is stored to the mounted drive at /mnt?

The drive I've used is a 1TB HDD, formatted using ext4 and mounted with the command "mount /dev/sdc1 /mnt"

Normal writes using cp/mv/rsync etc. work perfectly fine.

**Comment by ThomasWaldmann** [comment] 2016-05-30 13:59
That sounds unusual, borg does not do anything special with mounts or the filesystem. I suspect you did something wrong or there maybe was some interference with some automounter?

**Comment by TheOneWhoKnocks** [comment] 2016-05-30 14:11
Very unusual, I'm having this problem since a few days and also talked to the manjaro delevelopers (the os I'm using). Since normal cp/mv etc. operations work, there must be something other borg is doing.

That's exactly what I did:

Created a partition using fdisk
mkfs.ext4 /dev/sdc1
mount /dev/sdc1 /storage
borg init  root@172.17.2.25:/storage/borg
--- nothing happens, the directory borg/ isn't visible in /storage using ls ---
umount /storage
ls shows the repository borg/ under /storage without any problem

I've also tried reinstalling my os (Manjaro 16 KDE), nothing seems to help.

**Comment by enkore** [comment] 2016-05-30 14:31
Since you are accessing over SSH, did you try things like `ssh root@172.17.2.25 -c 'ls -l /storage/'`?

**Comment by ThomasWaldmann** [comment] 2016-05-30 15:18
@TheOneWhoKnocks LOL, congrats to nickname and avatar.

**Comment by TheOneWhoKnocks** [comment] 2016-05-31 09:47
Well, it works when I mount the drive using the automount feature. If I umount the automounted drive and mount it somewhere else again, it won't work. But I'm okay with that, at least it works now. I'll do some more research (thx for this hint @enkore ) but I'm just happy it finally does his job.

@ThomasWaldmann , haha, thank you. Thats actually one of the few websites the name was still available

**Comment by ThomasWaldmann** [comment] 2016-06-21 12:15
Guess that without more information and evidence pointing into borg's direction, I'ld assume that the issue seen is not caused by borg (but somehow by the OS) and close this issue soon.

**Closed** 2016-06-26 11:59 UTC
