### ISSUE TITLE
DistributionNotFound error with msgpack-python 0.5.0 installed

### ISSUE THREAD

**Issue by bradst** [borgbackup/borg#3515] opened 2018-01-07 00:15 UTC
Borg fails to launch with msgpack-python 0.5.0, because upstream has [renamed the package to `msgpack`](https://github.com/msgpack/msgpack-python/commit/89e4f8b7b3a43fc84ea0dd278a4b8b54b1fac4bd).

```
$ borg --help
Traceback (most recent call last):
  File "/usr/bin/borg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python>=0.4.6' distribution was not found and is required by borgbackup
```

**Comment by KopfKrieg** [comment] 2018-01-07 01:43
I've got the same problem on archlinux. Temporary solution is to rename the requirment to msgpack instead of msgpack-python.

**Comment by ThomasWaldmann** [comment] 2018-01-07 04:19
On pypi, there is a transition-package msgpack-python (in addition to the newly named msgpack package).

If there is no better way to deal with it, arch could just package that also.

**Comment by ThomasWaldmann** [comment] 2018-01-07 04:31
A slightly dirty workaround is to `pip install msgpack-python`.

**Comment by paavoris** [comment] 2018-01-07 04:47
I just had this error too with some of my Ubuntu (16.04, 17.10 and "18.04") and Rasbian machines. Upgrading borg via pip(3) is now installing msgpack 0.5.0 and this breaks borg.

My dirty little workaround was to downgrade msgpack: `pip3 install msgpack-python==0.4.8` since `pip3 install msgpack-python` just gives me this:

```
Requirement already satisfied: msgpack-python in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: msgpack>=0.5 in /usr/local/lib/python3.6/dist-packages (from msgpack-python)
```

Not a perfect solution of course and this will break again if I try to upgrade borgbackup via pip: `pip3 install -U borgbackup`

**Comment by ThomasWaldmann** [comment] 2018-01-07 04:53
@paavoris just some minutes ago, I upgraded borg with pip and it was no problem. There is that transition package `msgpack-python` on pypi and that pulls the `msgpack` package, so everything should be happy.

**Comment by paavoris** [comment] 2018-01-07 05:13
Hmmm... is there something funky going on with my installs? All of them are failing if I upgrade.

```
root@helix:~# pip3 install -U borgbackup
Requirement already up-to-date: borgbackup in /usr/local/lib/python3.5/dist-packages
Collecting msgpack-python>=0.4.6 (from borgbackup)
  Using cached msgpack_python-0.5.0-py3-none-any.whl
Requirement already up-to-date: msgpack>=0.5 in /usr/local/lib/python3.5/dist-packages (from msgpack-python>=0.4.6->borgbackup)
Installing collected packages: msgpack-python
  Found existing installation: msgpack-python 0.4.8
    Uninstalling msgpack-python-0.4.8:
      Successfully uninstalled msgpack-python-0.4.8
Successfully installed msgpack-python-0.5.0

root@helix:~# pip3 install msgpack-python
Requirement already satisfied: msgpack-python in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: msgpack>=0.5 in /usr/local/lib/python3.5/dist-packages (from msgpack-python)

root@helix:~# borg -V
Traceback (most recent call last):
  File "/usr/local/bin/borg", line 7, in <module>
    from borg.archiver import main
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 32, in <module>
    import msgpack
ImportError: No module named 'msgpack'

root@helix:~# pip3 install msgpack-python==0.4.8
Collecting msgpack-python==0.4.8
Installing collected packages: msgpack-python
  Found existing installation: msgpack-python 0.5.0
    Uninstalling msgpack-python-0.5.0:
      Successfully uninstalled msgpack-python-0.5.0
Successfully installed msgpack-python-0.4.8

root@helix:~# borg -V
borg 1.1.4

root@helix:~# python3 -V && pip3 -V
Python 3.5.2
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
```

(I personally can't code even "hello world" with python, so I'm no python expert. I may have messed up something. 🤓 )

**Comment by eli-schwartz** [comment] 2018-01-07 14:28
> On pypi, there is a transition-package msgpack-python (in addition to the newly named msgpack package).
> 
> If there is no better way to deal with it, arch could just package that also.

We could, and probably should as borg is not the only package users are having issues with. That being said, transitional dummy packages are there for transitional purposes... so it's probably best to migrate to the new module name sooner rather than later.

Anyway, yeah, this issue should most likely only affect distro users.

**Comment by eli-schwartz** [comment] 2018-01-07 21:33
This should be fixed for Arch Linux systems, as we now install the transitional dummy package alongside the main package: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/python-msgpack&id=d366653e36f3fbe10f689097de3ca2317118efd1

As new installations of newer versions of borg should be installed with then-current versions of msgpack, it makes sense to just fully move over to depending on msgpack now, instead of python-msgpack -- which will fix this for the future (when we potentially drop the dummy package) as well as for other distros that may not have (yet?) done this.

**Comment by 0x022b** [comment] 2018-01-08 13:06
This also happens on Ubuntu running on WSL.

```
$ sudo pip install --upgrade borgbackup
Collecting borgbackup
  Downloading borgbackup-1.1.4.tar.gz (3.4MB)
    100% |████████████████████████████████| 3.4MB 480kB/s
Collecting msgpack-python>=0.4.6 (from borgbackup)
  Downloading msgpack_python-0.5.0-py3-none-any.whl
Collecting msgpack>=0.5 (from msgpack-python>=0.4.6->borgbackup)
  Downloading msgpack-0.5.0.tar.gz (142kB)
    100% |████████████████████████████████| 143kB 5.0MB/s
Installing collected packages: msgpack, msgpack-python, borgbackup
  Running setup.py install for msgpack ... done
  Found existing installation: msgpack-python 0.4.8
    Uninstalling msgpack-python-0.4.8:
      Successfully uninstalled msgpack-python-0.4.8
  Found existing installation: borgbackup 1.1.3
    Uninstalling borgbackup-1.1.3:
      Successfully uninstalled borgbackup-1.1.3
  Running setup.py install for borgbackup ... done
Successfully installed borgbackup-1.1.4 msgpack-0.5.0 msgpack-python-0.5.0
ModuleNotFoundError: No module named 'msgpack'

$ borg --version
Traceback (most recent call last):
  File "/usr/local/bin/borg", line 9, in <module>
    load_entry_point('borgbackup==1.1.4', 'console_scripts', 'borg')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 32, in <module>
    import msgpack
ImportError: No module named 'msgpack'
```

Workaround is to downgrade msgpack-python.
```
sudo pip install msgpack-python==0.4.8
```

**Comment by ThomasWaldmann** [comment] 2018-01-10 07:04
The issue was fixed in msgpack 0.5.1 (see link directly above this post).

As a side note: py34 testing (and thus official support for py34) was removed in msgpack 0.5.0.

As borg 1.0 and 1.1 still support py34 and only master branch requires py35+, we will adjust requirements:
- 1.0 and 1.1: msgpack-python>=0.4.6,<0.5.0
- master: msgpack-python>=0.4.6,!=0.5.0,<0.6.0

The <0.6.0 requirement for master is mostly a precaution against sudden incompatible api changes before we have tested them and will be increased after we have successfully tested new msgpack releases.

**Closed by ThomasWaldmann** 2018-01-10 07:04 UTC

**Comment by quicktrick** [comment] 2018-02-27 11:45
I have just the same problem as in the first message of this thread when trying to connect to a repo remotely via ssh.  If I connect to the same repo locally from the server it's located on, everything is Ok. The thing is that the server containing the repo is `Qnap` where I [installed Borg](https://github.com/borgbackup/borg/issues/690#issuecomment-367516948) from the source code. The other server is openSUSE, and I installed Borg as a package there.  At first everything worked fine, but after some attempts to install `Fuse` on `Qnap` I got this problem.  I tried to install `msgpack-python==0.4.8` and just `msgpack`, but it doesn't solve the problem.  `Borg` works fine locally, but remotely it gives the errors just like in the first message of this thread.

**Comment by quicktrick** [comment] 2018-02-27 13:47
Thomas, I found out that the problem is not in Qnap, but in openSUSE.  I have openSUSE Tumbleweed, and yesterday I updated the system.  And now Bord doesn't work there (it shows those errors).  I tried to remove it with the dependencies and reinstall -- the problem didn't disappear.

**Comment by ThomasWaldmann** [comment] 2018-02-27 23:32
OK, it works now, but what was the root cause for the breakage?

Is python3-msgpack-0.5.4-1.1.x86_64 broken?

**Comment by ThomasWaldmann** [comment] 2018-02-28 13:38
@quicktrick sounds like you want to discuss that with the opensuse borg maintainers.

Here's the fix for the non-ascii header file / ascii build env issue: https://github.com/borgbackup/borg/pull/3580/files (alternatively, one can just use a utf-8 capable locale, which is quite the norm nowadays).
