### ISSUE TITLE
Borg create while another archive is mounted gives strange behavior?

### ISSUE THREAD

**Issue by emmenlau** [borgbackup/borg#1243] opened 2016-07-02 18:13 UTC
I'm using your Linux binary borgbackup 1.0.3. I have one archive mounted, and try to run borg create to create another archive. I would have expected that it either works or refuses to start, but the behavior I see seems to be a mix of both? I get many errors like the following, mixed with what looks like a progress bar and a seemingly progressing backup(?), until I eventually killed it:
```
...
Remote: Borg 1.0.3: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "borg/remote.py", line 96, in serve
Remote:   File "borg/repository.py", line 455, in put
Remote:   File "borg/repository.py", line 199, in prepare_txn
Remote:   File "borg/locking.py", line 299, in upgrade
Remote:   File "borg/locking.py", line 258, in acquire
Remote:   File "borg/locking.py", line 287, in _wait_for_readers_finishing
Remote: borg.locking.LockTimeout: /mnt/dmcrypt1/borgbackup/lock
Remote: Platform: Linux bool 4.4.14-040414-generic #201606241434 SMP Fri Jun 24 18:36:45 UTC 2016 x86_64 x86_64
Remote: Linux: debian stretch/sid
Remote: Borg: 1.0.3  Python: CPython 3.5.1
Remote: PID: 3534  CWD: /mnt/dmcrypt1
Remote: sys.argv: ['/opt/bda/bin/borgbackup', 'serve', '--restrict-to-path', '/mnt/dmcrypt1']
Remote: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077'
Remote:
Remote: Borg 1.0.3: exception in RPC call:ouch
Remote: Traceback (most recent call last):
Remote:   File "borg/remote.py", line 96, in serve
Remote:   File "borg/repository.py", line 455, in put
Remote:   File "borg/repository.py", line 199, in prepare_txn
Remote:   File "borg/locking.py", line 299, in upgrade
Remote:   File "borg/locking.py", line 258, in acquire
Remote:   File "borg/locking.py", line 287, in _wait_for_readers_finishing
Remote: borg.locking.LockTimeout: /mnt/dmcrypt1/borgbackup/lock
Remote: Platform: Linux bool 4.4.14-040414-generic #201606241434 SMP Fri Jun 24 18:36:45 UTC 2016 x86_64 x86_64
Remote: Linux: debian stretch/sid
Remote: Borg: 1.0.3  Python: CPython 3.5.1
Remote: PID: 3534  CWD: /mnt/dmcrypt1
Remote: sys.argv: ['/opt/bda/bin/borgbackup', 'serve', '--restrict-to-path', '/mnt/dmcrypt1']
Remote: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077'
Remote:
Remote: Borg 1.0.3: exception in RPC call:lockmgr_server
Remote: Traceback (most recent call last):
Remote:   File "borg/remote.py", line 96, in serve
Remote:   File "borg/repository.py", line 455, in put
Remote:   File "borg/repository.py", line 199, in prepare_txn
Remote:   File "borg/locking.py", line 299, in upgrade
Remote:   File "borg/locking.py", line 258, in acquire
Remote:   File "borg/locking.py", line 287, in _wait_for_readers_finishing
Remote: borg.locking.LockTimeout: /mnt/dmcrypt1/borgbackup/lock
Remote: Platform: Linux bool 4.4.14-040414-generic #201606241434 SMP Fri Jun 24 18:36:45 UTC 2016 x86_64 x86_64
Remote: Linux: debian stretch/sid
Remote: Borg: 1.0.3  Python: CPython 3.5.1
Remote: PID: 3534  CWD: /mnt/dmcrypt1
Remote: sys.argv: ['/opt/bda/bin/borgbackup', 'serve', '--restrict-to-path', '/mnt/dmcrypt1']
Remote: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077'
```

PS: might be related to #768

**Comment by ThomasWaldmann** [comment] 2016-07-02 19:49
Duplicate of #562.

**Closed by ThomasWaldmann** 2016-07-02 19:49 UTC

**Comment by emmenlau** [comment] 2016-07-02 19:54
Sorry, I searched the bug database before but seems I did not use the right keywords to find the duplicate! So I understand now the issue with locking. Thanks!

**Comment by ThomasWaldmann** [comment] 2016-07-02 20:08
No problem. :)

Locking has some issues still. But at least it doesn't have the compatibility issues as in attic and also it really locks so nothing really bad can happen.

**Comment by emmenlau** [comment] 2016-07-02 20:14
Especially this is good to know that nothing bad can happen. I also sanity-checked my archive after the incident, and found that only one file had a new modification date: the lock file :-) So I already guessed that everything is save and sound, but thanks a lot for the confirmation... it scared me for a second.
