### ISSUE TITLE
Broken dependencies in the EPEL repository

### ISSUE THREAD

**Issue by C0Nd3Mnd** [borgbackup/borg#5964] opened 2021-08-22 12:13 UTC
When trying to `dnf upgrade` from `borgbackup-1.1.16-1.el8.x86_64` to `borgbackup-1.1.17-1.el8.x86_64` I get the following error on RockyLinux 8.4:

```
$ sudo dnf upgrade
Last metadata expiration check: 3:05:24 ago on Sun 22 Aug 2021 10:59:39 AM CEST.
Error: 
 Problem: cannot install the best update candidate for package borgbackup-1.1.16-1.el8.x86_64
  - nothing provides python3.6dist(packaging) needed by borgbackup-1.1.17-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

This has been happening for a few weeks now. I checked if it works with a completely clean install of RockyLinux 8 (or any RHEL 8 distro), but it doesn't work there either.

**Comment by ThomasWaldmann** [comment] 2021-08-22 12:34
duplicate of #5953.

**Closed by ThomasWaldmann** 2021-08-22 12:34 UTC
