### ISSUE TITLE
Crash: listxattr failed

### ISSUE THREAD

**Issue by pepa65** [borgbackup/borg#1462] opened 2016-08-11 00:45 UTC
(Same issue as https://github.com/jborg/attic/issues/120 it seems, very similar traceback.)

Borg (1.0.6-2~ubuntu14.04.1~ppa1) failed just now. From xfs to xfs (on same file system), on Ubuntu 14.04 trusty. Of my five directories (each a separate archive, same repo) only one worked. Yesterday all five worked.
Example failure:
``` 
borg create -v --show-rc --stats -C lz4 /data/store/borg::Public-20160810 /data/Public
Enter passphrase for key /data/store/borg:
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1609, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1546, in run
    return args.func(args)
File "/usr/lib/python3/dist-packages/borg/archiver.py", line 81, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 247, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 219, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process     read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 275, in _process
     status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 683, in process_file
    item.update(self.stat_attrs(st, path))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 573, in stat_attrs
    xattrs = xattr.get_all(path, follow_symlinks=False)
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 31, in get_all
    for name in listxattr(path, follow_symlinks=follow_symlinks))
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 115, in listxattr
    raise Exception('listxattr failed')
Exception: listxattr failed

Platform: Linux brain2 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64
Linux: Ubuntu 14.04 trusty
Borg: 1.0.6  Python: CPython 3.4.3
PID: 21726  CWD: /home/administrator
sys.argv: ['/usr/bin/borg', 'create', '-v', '--show-rc', '--stats', '-C', 'lz4', '/data/store/borg::Public-20160810', '/data/Public']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

**Comment by ThomasWaldmann** [comment] 2016-08-11 00:47
Can you reproduce this with patched code if i give you some patch?

**Comment by pepa65** [comment] 2016-08-11 00:50
OK, should I build it then from github? (I was running from a repo package...)

**Comment by ThomasWaldmann** [comment] 2016-08-11 00:51
```
diff --git a/borg/xattr.py b/borg/xattr.py
index e88d7ce..87531d4 100644
--- a/borg/xattr.py
+++ b/borg/xattr.py
@@ -112,7 +112,7 @@ if sys.platform.startswith('linux'):  # pragma: linux only
         namebuf = create_string_buffer(n)
         n2 = _check(func(path, namebuf, n), path)
         if n2 != n:
-            raise Exception('listxattr failed')
+            raise Exception('listxattr failed, n=%d, n2=%d' % (n, n2))
         return [os.fsdecode(name) for name in namebuf.raw.split(b'\0')[:-1] if not name.startswith(b'system.posix_acl_')]
 
     def getxattr(path, name, *, follow_symlinks=True):
```

Maybe make a copy of the original file, then apply patch.
You can also do that with a dist package's code, you just need to locate borg/xattr.py in the filesystem.

**Comment by pepa65** [comment] 2016-08-11 00:56
It says this:
```
File "/usr/lib/python3/dist-packages/borg/xattr.py", line 115
    raise Exception('listxattr failed', n=%d, n2=%d' % (n, n2))
                                                                       ^
SyntaxError: invalid syntax
```

**Comment by ThomasWaldmann** [comment] 2016-08-11 00:58
You didn't apply the patch, you have one single-quote too much, after "failed".

**Comment by ThomasWaldmann** [comment] 2016-08-11 01:04
Note: the code for freebsd and darwin is rather similar, so might need the same fix.

**Comment by ThomasWaldmann** [comment] 2016-08-11 01:05
related: https://github.com/jborg/attic/issues/120

**Comment by ThomasWaldmann** [comment] 2016-08-11 01:28
@pepa65 still there?

**Comment by pepa65** [comment] 2016-08-11 03:04
Sorry, I had to go somewhere. I'll have a look as soon as I get back.

-------- Original Message --------

**Comment by pepa65** [comment] 2016-08-11 04:00
Result:
```
borg create -v --show-rc --stats -C lz4 /data/store/borg::Public-20160810 /data/Public
Enter passphrase for key /data/store/borg: 
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1609, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1546, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 81, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 247, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 219, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 275, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 683, in process_file
    item.update(self.stat_attrs(st, path))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 573, in stat_attrs
    xattrs = xattr.get_all(path, follow_symlinks=False)
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 31, in get_all
    for name in listxattr(path, follow_symlinks=follow_symlinks))
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 115, in listxattr
    raise Exception('listxattr failed, n=%d, n2=%d' % (n, n2))
Exception: listxattr failed, n=45, n2=24

Platform: Linux brain2 3.13.0-93-generic #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016 x86_64 x86_64
Linux: Ubuntu 14.04 trusty
Borg: 1.0.6  Python: CPython 3.4.3
PID: 31818  CWD: /home/administrator
sys.argv: ['/usr/bin/borg', 'create', '-v', '--show-rc', '--stats', '-C', 'lz4', '/data/store/borg::Public-20160810', '/data/Public']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

**Comment by pepa65** [comment] 2016-08-11 06:37
I initiated a new repo and tried the same 5 datasets, only www succeeds. It might be because of not having utf-8 filenames, or because simpler permissions??

**Comment by enkore** [comment] 2016-08-11 08:16
The code looks racy. Is this a consistent issue that always appears on the same file or a bit more random looking?

> 1. query object size
> 2. alloc buffer
> 3. query object
> 4. fail if size doesn't match

**Comment by ThomasWaldmann** [comment] 2016-08-11 11:35
I've looked at some other xattr code, their strategy:
- call xattr func with a small buffer (they used 128B, I'ld rather use 4kiB I guess)
- if it does not succeed due to too small buffer, call it again, giving the max allowed xattr size.

**Comment by enkore** [comment] 2016-08-11 12:14
> use similar approach as for lz4 buffer growing (thread-local module level buffer)?

Yes. 4K is a sane starting buffer size and would often require no resizing at all.

**Comment by pepa65** [comment] 2016-08-11 14:55
Here is the /proc/mounts line for source and dest:
`/dev/mapper/trusty-data /data xfs rw,relatime,attr2,inode64,noquota 0 0`

**Comment by enkore** [comment] 2016-08-11 16:44
There is at least another race in the xattr code: #906

**Comment by pepa65** [comment] 2016-08-12 02:41
Could you give me some instructions how I could try this?

**Comment by ThomasWaldmann** [comment] 2016-08-12 12:32
You would need to pull from the branch the pull request is made from and install borg from source (see docs).

Or just wait until this got reviewed/merged, it will hopefully get into 1.0.7rc2 and can be tried there.

**Comment by ThomasWaldmann** [comment] 2016-08-12 16:22
Fixed by #1464.

**Closed by ThomasWaldmann** 2016-08-12 16:22 UTC
Labels: bug

**Comment by pepa65** [comment] 2016-08-12 17:55
Sure, I'm eager to try! Which branch was the pull request made from??

**Comment by ThomasWaldmann** [comment] 2016-08-12 18:03
As it is merged now, you can use 1.0-maint branch.

**Comment by pepa65** [comment] 2016-08-13 01:07
So far I did:
```
clone https://github.com/borgbackup/borg.git
cd borg
git checkout -t origin/1.0-maint
apt install python3-setuptools cython3 libssl-dev liblz4-dev 
python3 setup.py
```
Then it seems I am on a too old distribution (Ubuntu 14.04.5):
```
Installed /home/PeterPasschier1965/git/borg/setuptools_scm-1.11.1-py3.4.egg
your setuptools is too old (<12)
setuptools_scm functionality is degraded
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```
Don't want to mess too much with this box... If I store them on ext4 this bug won't be a problem, right??

**Comment by ThomasWaldmann** [comment] 2016-08-13 03:37
I've just released 1.0.7rc2 (with a lot of xattr fixes/changes), so you could just take that.

**Comment by pepa65** [comment] 2016-08-13 06:53
I got the standalone binary borg-linux64, and did:
```
sudo cp borg-linux64 /usr/local/bin/borg
sudo chown root:root /usr/local/bin/borg
sudo chmod 755 /usr/local/bin/borg
```
`borg -V` outputs `borg 1.0.7rc2`
If I do the same command as at the start of this issue:
`borg create -v --show-rc --stats -C lz4 /data/store/borg::Public-20160813 /data/Public`
It comes back with: `terminating with success status, rc 0'!

Thank you very much Thomas and friends!

**Comment by ThomasWaldmann** [comment] 2016-08-13 13:20
Thanks for testing.
