### ISSUE TITLE
borg check > /dev/null is not quiet

### ISSUE THREAD

**Issue by ganja1447** [borgbackup/borg#1590] opened 2016-09-12 08:41 UTC
borg create can be made silent by not using --progress and piping stdout to /dev/null

Check can not be made silent though, I have tried adding --warning, --error, --critical, it's still outputting it's progress to stderr. Like this:
Remote: Checking segments 0.0%
Remote: Checking segments 0.1%
...

Wouldn't it make sense to either only output that if --progress or -v is used? Or at least only output it when at --info level? I don't see how it suits the warning+ levels. The issue here is that it's hard to make regular checks using cron.

I have tried digging through the old tickets and found a few similar ones, but not regarding check itself. If I understand it correctly, it has been fixed for create for example.

**Comment by enkore** [comment] 2016-09-12 08:45
Hi, thanks for the report.

This issue is fixed in the 1.1 series (currently in beta). A backport of the fix to the 1.0 series isn't planned at the moment. Duplicate of #824.

**Closed by enkore** 2016-09-12 08:45 UTC
Labels: duplicate

**Comment by ganja1447** [comment] 2016-09-12 08:57
Is it supposed to be in the current downloadable beta binary? I downloaded that yesterday (or if it was two days ago) and tested with that one as well. I was supposed to add which versions I tested with, but forgot. I have tested with 1.0.7 and 1.1.0-b1

root@host1:/usr/local/bin# ./borgbackup-1.1.0-b1 --version
borgbackup-1.1.0-b1 1.1.0b1
root@host1:/usr/local/bin# ./borgbackup-1.1.0-b1 check --critical --last 1 --no-files-cache borg@host2:/data/borg/host1/MonThu.borg >/dev/null 

Or am I just misunderstanding the syntax?

**Comment by ganja1447** [comment] 2016-09-12 09:10
Oops, my example wasn't complete. Seems like my head isn't working straight today. I missed the most important line, bolded below.

root@host1:/usr/local/bin# ./borgbackup-1.1.0-b1 --version
borgbackup-1.1.0-b1 1.1.0b1
root@host1:/usr/local/bin# ./borgbackup-1.1.0-b1 check --critical --last 1 --no-files-cache borg@host2:/data/borg/host1/MonThu.borg >/dev/null 
**Remote: Checking segments 1.2%**
and then I pressed ctrl-c.

**Comment by enkore** [comment] 2016-09-12 09:43
It needs the new version on both client and server

**Comment by ganja1447** [comment] 2016-09-12 11:07
Thank you very much for making me realize that. I have now made a proper test with both sides running the 1.1.0-b1 version, seems to work great. It was a bit tricky due to the LD_LIBRARY_PATH issue though, but I have read that it's fixed in git.

Sorry for taking up your time.

**Comment by enkore** [comment] 2016-09-12 12:55
> Sorry for taking up your time.

Not at all, glad to help! :)

**Comment by guillaume-uH57J9** [comment] 2017-08-16 18:09
I am also affected. 
Anyone knows of a workaround for the 1.0 series? 

The 1.1 series is not available in Debian yet, so I cannot use it.

There is this trivial workaround, but it would also suppress error message, which is undesired;
borg command &> /dev/null

**Comment by enkore** [comment] 2017-08-16 18:13
borg check REPO 2>&1 | tr '\r' '\n' | grep -v "^Checking segments"

**Comment by guillaume-uH57J9** [comment] 2017-08-16 18:54
Thanks for the suggestion. 
The workaround isn't efficient since leaves this undesired output untouched: 
> Remote: Checking segments 0.0%
> Remote: Checking segments 50.0%
> Remote:                         

But this gave me enough of a hint to write a different and working workaround:
borg check REMOTEREPO | sed -E 's/[^\r]+\r//g'

**Comment by enkore** [comment] 2017-08-16 19:07
For remote repos `borg check REPO 2>&1 | tr '\r' '\n' | grep -v "^(Remote: )?Checking segments"` probably works.

**Comment by w3llschmidt** [comment] 2018-04-26 19:10
> #borg check ssh://user@host.de:23/./filer | tr '\r' '\n' | grep -v "^(Remote: )?Checking segments"
> Remote: Checking segments 8.0%

???

**Comment by enkore** [comment] 2018-04-26 19:26
stderr vs stdout, you forgot the 2>&1.
