### ISSUE TITLE
Make hostname lookup lazy instead of static

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#3172] opened 2017-10-16 10:24 UTC
https://github.com/borgbackup/borg/blob/master/src/borg/platform/posix.pyx#L21

While it would be really complicated to somehow judge whether those calls can block for some time, they don't need to be done unconditionally. Making it lazy (i.e. along the lines of functools.lru_cache) would avoid performing these operations for thins like help pages.

See #3171

**Comment by wzyboy** [comment] 2017-10-16 10:27
On the node in question, there is no self-entry in `/etc/hosts`, but it does have its FQDN set in `/etc/hostname` (by `hostnamectl set-hostname` during installation). The Python `socket.getfqdn()` blocks in this situation, but the `/usr/bin/hostname` program can display the value without blocking. `strace hostname` shows it uses `uname()` syscall. Could we consider using the correponding Python wrapper `os.uname().nodename` instead of `socket.getfqdn()`?

**Comment by enkore** [comment] 2017-10-16 10:37
getfqdn() and hostname/uname() yield different results. getfqdn() has a relatively higher chance of being unique, especially inside one organization.

**Comment by wzyboy** [comment] 2017-10-16 10:46
Hi @enkore ,

If I am understanding correctly, `socket.gethostname()` or `os.uname().nodename` just returns the locally configured hostname without resolving, no matter it's full-qualified or not; while `socket.getfqdn()` always tries to resolve, no matter it hits the `/etc/hosts` file, a local DNS resolver in the LAN, or an upstream DNS resolver on the Internet. (If it misses the first one, the latter ones may block)

Trying to get FQDN from network may not reliable in some networks. I am not a macOS user but I heard that macOS users suffer from wrongly-configured Wi-Fi networks. A friend of mine finds her macOS terminal prompt be changed to `hername@bogon` after connecting her MacBook Pro to a free Wi-Fi in a café. [A Google search of "mac bogon"](https://www.google.com/search?q=mac+bogon) shows this is not a rare case.

> getfqdn() has a relatively higher chance of being unique, especially inside one organization.

Since we are already combing (full-qualified or not) hostname with MAC address, the chance of collision is already very low, since MAC addresses are (in theory) globally unique.

**Comment by ThomasWaldmann** [comment] 2017-10-16 16:19
This is a problem located outside of borg. Every tool that tries to find out the hostname (or maybe also when just using the hostname to make some connection) will have this problem.

So we can also just not change that and let the admin fix /etc/hosts (or DNS) when noticing that problem, to solve the root cause (and also get rid of all the issue that it is causing, not just borg).

**Closed by ThomasWaldmann** 2017-10-16 16:19 UTC
