### ISSUE TITLE
list how many new chunks a file produced

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#371] opened 2015-11-04 08:24 UTC
I'ld like to see how many new chunks were generated for a file.

Each file is stored as a metadata item that has a list of content chunk IDs. These content chunks are stored as separate objects and all references (==IDs) to these objects are equal and direct.

If the counter of a chunk ID referenced by the chunks list of a file is "1" then this file has "caused" that chunk.

**Comment by ThomasWaldmann** [comment] 2015-11-04 13:57
- mount the repo
- ls -l /mountpoint/*/the/file/you/are/interested/in

**Comment by ClipperS87** [comment] 2015-11-04 14:22
..i specified my approach more clearly now, hopefully

**Comment by ThomasWaldmann** [comment] 2015-11-04 14:26
well, did you try my suggestion? if so, what was the problem with it?

**Comment by ClipperS87** [comment] 2015-11-04 15:15
As I am usign cygwin I canout mount to see if ls -l would list this information...

**Comment by ThomasWaldmann** [comment] 2015-11-04 15:21
Ah, ok. Reopening. Can you edit title and description, so it is more clear?

**Comment by ThomasWaldmann** [comment] 2015-11-04 15:53
Hmm, it sounds a bit like you think of it doing some incremental-style backup with back-references for unchanged files. That's not the case though.

Each file is stored as a metadata item that has a list of content chunk IDs. These content chunks are stored as separate objects and all references (==IDs) to these objects are equal and direct.

So, you can't see directly from the ID list whether a file was new, updated or same.
To do that, you'ld have to compare all metadata and chunk ID lists to one or all previous archives, which seems a rather expensive operation (memory, I/O, time).

**Comment by ThomasWaldmann** [comment] 2015-11-04 16:00
A simple approach to improve would be to introduce `borg list --long` that does a `ls -l` style listing of the archive. It's not the most comfortable thing to get a single file's history, but could be used for that also.

**Comment by ClipperS87** [comment] 2015-11-04 16:05
--long would be perfect as you describe it

**Comment by ThomasWaldmann** [comment] 2015-11-04 16:05
See also #177.bb

**Comment by ThomasWaldmann** [comment] 2015-11-06 13:44
Hmm, I remembered the current state of "borg list" wrong (I thought it only gives a filename-only listing).

But, it already gives a "ls -l" style listing with mode, user, group, timestamp and size of the files, so changes can be discovered there already. Thus, I am closing this issue.

Functionality that goes beyond that (like diffs of archives) can be discussed in #177.

**Comment by ClipperS87** [comment] 2015-11-06 18:11
IMHO it is wrong to close that.
the request was to see how many new chunks were generated:
_Each file is stored as a metadata item that has a list of content chunk IDs. These content chunks are stored as separate objects and all references (==IDs) to these objects are equal and direct._

I do assume that a chunk is deleted as soon is not referenced anymore, or?
On opposite, if the counter of a chunk ID referenced by a metadata item of a file is "1" then this file has "caused" a chunk - and this is the info i am looking for...

**Comment by ThomasWaldmann** [comment] 2015-11-06 18:30
I removed all the discussion and updated the first post accordingly to what I now understood what you want.

You said you want to see how MANY chunks are new. More interesting would be maybe how MUCH the total (compressed) size change is (in the repo, caused by these content chunks)?

**Comment by ThomasWaldmann** [comment] 2015-11-06 18:41
An interesting usecase of that "how many unique chunks (how much unique space) does file x have" listing is that we could sum up and tell the total value for the archive.

So one knows approximately how much gets freed if the archive is deleted.

**Comment by ClipperS87** [comment] 2015-11-06 18:47
I would like to know 
1. which file/s in a backup-set generated new chunks (So I know they have new content (what a simple timestamp/size compare of the current "list" format would not deliver as a file could be moved and renamed) and how many in terms of data (before and after compression)
2. how much this backup produced in new data (before and after compression) (a total of the files mentioned under "1.")

**Comment by ThomasWaldmann** [comment] 2016-03-17 16:31
As an implementation note:

When looking at 1 file in 1 archive in a repository, one can only see which chunks are UNIQUE (have a reference count of 1). Of course that only works if that archive is the first and ONLY archive that has this file (later backups, that still have the same or a similar file will increase refcount to be 2+). 

When comparing a file in archive A to same file in archive B, one can see the relative change (which chunks were added for that file, which chunks were removed).

**Comment by enkore** [comment] 2016-03-17 16:40
`borg diff` can tell you how large added or removed chunks are between archives for every file. It doesn't count the same chunks twice, so this reflects actual repository disk usage (neglecting overhead).

The new `borg list` from #751 can tell you number of unique chunks for each file, but as @ThomasWaldmann notes, this data would need to be collecting before creating another archive(s), since those can increase the refcount.

**Comment by ThomasWaldmann** [comment] 2016-03-17 17:24
Implemented by:

https://github.com/borgbackup/borg/commit/4151db270cd9413f3fac153e173ca13ad77a539a
and
https://github.com/borgbackup/borg/commit/26fe2a35cd409fcc1a3c52acd5a10bd7b755ee5d

**Closed by ThomasWaldmann** 2016-03-17 17:24 UTC
Labels: enhancement
