### ISSUE TITLE
Passing secrets via envorimental variables is insecure(?)

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2623] opened 2017-06-06 18:44 UTC
Having seen https://unix.stackexchange.com/questions/369566/why-is-passing-the-secrets-via-environmental-variables-considered-extremely-ins I'd doubt, whether it is the best way to `export BORG_PASSPHRASE`. Are not there some risks? What is your stance on this topic?

(You can also comment on the question there, if a general answer answers this topic sufficiently.)

**Comment by enkore** [comment] 2017-06-06 18:50
All recent unix-like operating systems protect process environments pretty much the same way they protect files, so only the user running the command can see the process environment. On most systems the same user could also use a debugger to pry the passphrase or the master keys from Borg's memory.

Recently BORG_PASSCOMMAND was merged into master. This allows much easier use of keyrings and hardware keys.

> When set, use the standard output of the command (trailing newlines are stripped) to answer the passphrase question for encrypted repositories. It is used when a passphrase is needed to access an encrypted repo as well as when a new passphrase should be initially set when initializing an encrypted repo. If BORG_PASSPHRASE is also set, it takes precedence. See also BORG_NEW_PASSPHRASE.

Duplicate of #1103.

**Closed by enkore** 2017-06-06 18:50 UTC

**Comment by enkore** [comment] 2017-06-06 18:52
Note that there are insecure ways to pass environment variables, e.g. `BORG_PASSPHRASE=... borg` will typically show the passphrase in the process list, which **is** world-readable on most systems by default. For scripts, using `export ...` is not problematic.

**Comment by enkore** [comment] 2017-06-06 18:54
There are some other angles on passphrase memory persistence, see e.g. #2525.

**Comment by rugk** [comment] 2017-06-06 19:23
> BORG_PASSPHRASE=... borg will typically show the passphrase in the process list,

Uuh, that's new to me. And you also do not mention in this in your docs. (Note: You should.)
On [this page](https://borgbackup.readthedocs.io/en/stable/quickstart.html#pitfalls-with-shell-variables-and-environment-variables) this insecure method is even mentioned/suggested (without any warning).
Also a note/warning may be useful [here](https://borgbackup.readthedocs.io/en/0.28.1/usage.html#environment-variables) and in this [note block](https://borgbackup.readthedocs.io/en/stable/faq.html#password-env), where many unsafe ways are already mentioned, but not the one you mentioned.

**Comment by enkore** [comment] 2017-06-06 19:25
The first link suggests the opposite of this method, using export.

**Comment by rugk** [comment] 2017-06-06 19:26
Yes, but later on:
>  Hint: see env_keep in sudoers(5), or try sudo BORG_PASSPHRASE='yourphrase' borg syntax.

"or just try it…"

**Comment by enkore** [comment] 2017-06-06 19:26
Blimey.

**Comment by textshell** [comment] 2017-06-06 19:44
`BORG_PASSPHRASE=... borg` on a real shell will not leak the passphrase. It might on things that pretend to be shells and just stuff everything into /bin/sh -c 'stuff', of course.

I believe using the environment currently is the most likely way for users to balance ease of backup and security.
Borg might want to improve this (i.e. support password managers, offer good scripts for BORG_PASSCOMMAND etc). But for now we don't have a realistic better way to offer.

`sudo` actually is a problem though. the only really available channel there is using an fd in some way (i.e. stdin) but that's not really easy to do in a user friendly robust way. Maybe borg should add something here.

**Comment by enkore** [comment] 2017-06-06 19:47
I don't think shells are obligated to remove environment variables from the command line, but it's the easiest way of implementation (using fork+execve). `sudo B_P borg` on the other hand *will* leak the passphrase.

**Comment by textshell** [comment] 2017-06-06 19:53
execve doesn't take environment variables in the `filename` or `argv` arguments (it does in the envp, but that is never shown in ps). The `VAR=something command` syntax in shells does not include (and can't) the `VAR=something` part in command. It's just another quirky thing in shell syntax (similar to the way quotes are not passed to execve or stream redirections).
