### ISSUE TITLE
doc: "Edit on github" links are broken

### ISSUE THREAD

**Issue by okurz** [borgbackup/borg#451] opened 2015-12-01 19:22 UTC
Each documentation page shows a "Edit on GitHub" link on top-right corner, e.g. http://borgbackup.readthedocs.org/en/stable/index.html references https://github.com/borgbackup/borg/blob/55fef2457e483701254e5b2a7d4a1a60963971a8/docs/index.rst which is broken. Same as on other subpages.

**Comment by ThomasWaldmann** [comment] 2015-12-01 20:16
This issue is tracked there:

https://github.com/rtfd/readthedocs.org/issues/1820

**Comment by anarcat** [comment] 2015-12-10 15:09
... and was originally reported in #413.

**Comment by ThomasWaldmann** [comment] 2015-12-25 17:59
Closing this as duplicate as it is not in our codebase and the issue is tracked in rtd issue tracker.

**Closed by ThomasWaldmann** 2015-12-25 17:59 UTC
Labels: duplicate
