### ISSUE TITLE
borg import-tar fails with error and stacktrace

### ISSUE THREAD

**Issue by CarlosCastaneda** [borgbackup/borg#7721] opened 2023-07-08 20:23 UTC
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).
debian (raspberry) 1.2.4
ubuntu (laptop) 1.2.0

#### Operating system (distribution) and version.
Linux nextcloudpi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

#### Hardware / network configuration, and filesystems used.
ext4 filesystem

#### How much data is handled by borg?
40GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg import-tar --timestamp nextcloud-bkp_20230708_1688778006.tar.gz --list --stats ::nextcloud-bkp_20230708_1688778006.tar.gz nextcloud-bkp_20230708_1688778006.tar.gz

## Describe the problem you're observing.
borg import dies with the following error message and stack trace:

```
gzip: stdin: unexpected end of file
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 5213, in main
  File "borg/archiver.py", line 5144, in run
  File "borg/archiver.py", line 181, in wrapper
  File "borg/archiver.py", line 1744, in do_import_tar
  File "borg/archiver.py", line 1774, in _import_tar
  File "borg/archive.py", line 1522, in process_file
  File "borg/archive.py", line 1272, in process_file_chunks
  File "borg/archive.py", line 232, in backup_io_iter
  File "src/borg/chunker.pyx", line 270, in borg.chunker.Chunker.__next__
  File "tarfile.py", line 693, in readinto
  File "tarfile.py", line 684, in read
tarfile.ReadError: unexpected end of data

Platform: Linux nextcloudpi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64
Linux: Unknown Linux
Borg: 1.2.4  Python: CPython 3.8.6 msgpack: 1.0.5 fuse: llfuse 1.3.6 [pyfuse3,llfuse]
PID: 462236  CWD: /media/myCloudBackupCop/ncp-backups
sys.argv: ['borg', 'import-tar', '--timestamp', 'nextcloud-bkp_20230708_1688778006.tar.gz', '--list', '--stats', '::nextcloud-bkp_20230708_1688778006.tar.gz', 'nextcloud-bkp_20230708_1688778006.tar.gz']
SSH_ORIGINAL_COMMAND: None

```
but succeeds when importing tar file into another borg repository on the very same machine.
borg check on repository above terminated without any error. 
Also works on ubuntu based laptop when rsyncing this repository and tar.gz followed by import-tar command spezified above.

```
------------------------------------------------------------------------------
Repository: /media/myCloudBackup/ncp_tar_borgbackups
Archive name: nextcloud-bkp_20230708_1688778006.tar.gz
Archive fingerprint: 3c226d77bf0db13156cbdc09801b8f318e5357f89e17110a68f84a1a94b90704
Time (start): Sat, 2023-07-08 04:04:05
Time (end):   Sat, 2023-07-08 04:40:56
Duration: 36 minutes 51.33 seconds
Number of files: 275720
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               48.14 GB             42.47 GB              3.65 GB
All archives:                2.21 TB              1.92 TB             43.86 GB

                       Unique chunks         Total chunks
Chunk index:                  134735             10577046
------------------------------------------------------------------------------

```
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, run same command again and it stack traces at the same position. But as mentioned above, works in another Repository (set up two distinct according to recommendation on documentation) as well as on ubuntu (copied the whole repository and tar file).

#### Include any warning/errors/backtraces from the system logs
Besides borg import-tar's output there are no errors in syslog.

**Comment by ThomasWaldmann** [comment] 2023-07-08 23:19
Looks like it either can't read from the tar file or it is empty/corrupted.

**Comment by CarlosCastaneda** [comment] 2023-07-09 21:06
> Looks like it either can't read from the tar file or it is empty/corrupted.

Looks like, but it isn't. The very same file has been successfully imported to another borg repository on the same box, as well as to binary copy of the entire repository and tar file in question. Consequently isn't corruped or empty. There has to be another reason I cannot explan. Meanwhile there are 3 checkpoints because of 3 unsuccessfull imports. 

Do you have an idea how to narrow down the problem? Debugger, trace flags,...

**Comment by ThomasWaldmann** [comment] 2023-07-09 21:19
```
gzip: stdin: unexpected end of file
````

Looks like gzip already has a problem with that file. Check:
- if gzip is installed and working
- if you can decompress the tgz using gzip on the command line

**Comment by CarlosCastaneda** [comment] 2023-07-10 06:20
> ```
> gzip: stdin: unexpected end of file
> ```
> 
> Looks like gzip already has a problem with that file. Check:
> 
>     * if gzip is installed and working
if not the import into the other repository on tme same machine could not have worked
> 
>     * if you can decompress the tgz using gzip on the command line
Ran the following command
```
sudo bash -c "tar xvzf /media/myCloudBackup/ncp-backups/nextcloud-bkp_20230708_1688778006.tar.gz --to-stdout | wc " > tar_check.txt 2>&1 &

 cat -n tar_check.txt | tail -n3
191948  nextcloud/config/.htaccess
191949  nextcloud/config/config.php
191950  229540969 1236248029 48098258616

```
Ran without error. In the process (ps auxf) it can be seen that tar calls "gzip -d", the very same as borg  import-tar does. So that is equivalent.

**Comment by ThomasWaldmann** [comment] 2023-07-10 08:31
Well, looks like you have a weird issue there. Maybe something is broken on that rpi.

I'll close this, because it is not a problem in borgbackup:
- gzip binary throws: "gzip: stdin: unexpected end of file"
- tarfile.py (python library) throws: "tarfile.ReadError: unexpected end of data" (likely due to the first error)

**Closed by ThomasWaldmann** 2023-07-10 08:31 UTC

**Comment by CarlosCastaneda** [comment] 2023-07-10 10:11
> Well, looks like you have a weird issue there. Maybe something is broken on that rpi.
> 
I can't imagine what that should be. Then the other backups should not work either.
> I'll close this, because it is not a problem in borgbackup:
> 
Why are they so sure about that? You have made it very easy for yourself. Issue closed, problem solved.
>     * gzip binary throws: "gzip: stdin: unexpected end of file"
This is just an error message that says file end reached. How can you be sure that chunker does not read beyond the end, maybe due to an internal error.
> 
>     * tarfile.py (python library) throws: "tarfile.ReadError: unexpected end of data" (likely due to the first error)
The error message says it exactly: "likely" and not that's the reason.

Honestly, I'm totally disappointed that I can't get more help here to narrow down the problem. It is very easy to close the issue and thus declare that the problem is solved.

I myself have years of experience in IT, including analyzing and troubleshooting SW issues at various levels. But I have never encountered such behavior. I know that software has bugs, I know how to isolate problems and how to exclude some of them (like here). I also know that there can be (data) constellations that nobody suspects, because it is so clear and logical that one's own software works and is error-free and therefore there can be no error (it can not be what must not be) . This is exactly what I have personally experienced many times. For this very reason, it is especially helpful to involve another person in order to counter one's own operational blindness.

I simply asked you if there are ways to narrow down the problem further, be it debugging, trace flags, etc.... Very often in software products there are "non official" traceflags for developers to achieve exactly that.

But no answer to just any of my questions regarding this. It seems that here also: the problem is the "customer".
Very disappointing.

**Comment by ThomasWaldmann** [comment] 2023-07-10 10:50
Hmm, I was assuming gzip reads the file, but in fact it gets the data from the borg process.

I had a look at the borg 1.2.4 source, the flow of data is like this:
- borg opens the tgz file
- a `gzip -d` filter subprocess has its stdin connected to that open tgz file and its stdout goes back to borg
- tarfile (python stdlib) processes the stream of data coming from the subprocess stdout

I hope you see now that there is not much "borg" involved. It's python core and stdlib functionality and a gzip subprocess.

One still missing piece of information is **when** this "unexpected end of file" occurs - is it at the very beginning or after processing some stuff?

But still: the fact that this usually works and that you can't reproduce on another system (and also that we already got quite a lot of weird issues reported from rpi installations in the past) points to a problem in that environment.

What you can try:
- decompress the `.tgz` manually before invoking `borg import-tar`, so you just have a `.tar` and thus borg won't create that `gzip -d` filter subprocess, which simplifies the situation quite a bit.
- give `--debug` to borg
- use `strace`
- use a python debugger of your choice
- edit the borg source code (see `archiver.py`, `do_import_tar`) to add additional debug logging, if needed.

**Comment by ThomasWaldmann** [comment] 2023-07-10 11:04
Some of the "usual" issues on rpi you can also check:
- out of memory? swap?
- broken sdcard issues?
- power supply issues?
- 64bit kernel issues?
- some library code broken due to alignment issues? (usually gives other error msgs though)

**Comment by ThomasWaldmann** [comment] 2023-07-10 11:45
Analysed the traceback:

Looks like this happens when chunking a regular file's content from the tar.

Ideas:
- invoke borg with `-v --list` to determine which file it is
- is the file length in tar metadata consistent with what can be read from the tar for this file?
- use `tarfile` python module to experiment on that tar / that tar member file
- use `--chunker-params=fixed,65536` - does the problem reproduce or go away? the fixed chunker is way simpler to work with / to debug than the buzhash default chunker.

**Comment by ThomasWaldmann** [comment] 2023-07-10 11:54
BTW, you use borg 1.2.4 on debian bullseye - looks like that neither comes from `bullseye` nor from `bullseye-backports`.  Please update the top post about how you installed borg 1.2.4.

**Comment by CarlosCastaneda** [comment] 2023-07-10 15:18
> BTW, you use borg 1.2.4 on debian bullseye - looks like that neither comes from `bullseye` nor from `bullseye-backports`. Please update the top post about how you installed borg 1.2.4.

It' from the recommended site according to the installation guide [https://borgbackup.readthedocs.io/en/stable/installation.html](url) and ARM binaries are built by Johann Bauer, see: https://borg.bauerj.eu/

**Comment by ThomasWaldmann** [comment] 2023-07-10 15:46
`--debug` only modifies the log level, so that stuff logged at that level actually gets output.
The logging output is on stderr, so it should not interfere with other stuff.

**Comment by ThomasWaldmann** [comment] 2023-07-10 15:48
Did you try deleting the imported archive from the repo and then running it again?

**Comment by jdchristensen** [comment] 2023-07-10 17:18
I'd be inclined to suspect a hardware issue: RAM, sdcard, power supply, etc.  I'd run a long memory test, as well as some kind of test of the sdcard.

**Comment by CarlosCastaneda** [comment] 2023-07-11 08:19
> Did you try deleting the imported archive from the repo and then running it again?
Do you mean the checkpoints created? If so, no, I just ran  the import with the --debug option in the command line.

**Comment by CarlosCastaneda** [comment] 2023-07-11 08:24
> I'd be inclined to suspect a hardware issue: RAM, sdcard, power supply, etc. I'd run a long memory test, as well as some kind of test of the sdcard.
Power supply is fine as rpi and disks each have their own. I replaced the USB Stick with a new sdcard, so that seems to be fine too. Nevertheless I'll run a check.  So what do you mean with run a long memory test?

**Comment by jdchristensen** [comment] 2023-07-11 16:04
Just because the rpi and the disks have their own power supplies doesn't mean that there isn't a problem with the rpi's power supply.  I've had issues with an rpi that went away when switching power supplies.  And just because the sdcard is new doesn't mean it isn't faulty.  About the RAM test, I meant running something like memtester for 24 hours.

**Comment by CarlosCastaneda** [comment] 2023-07-11 19:39
> > > Did you try deleting the imported archive from the repo and then running it again?
> > 
> > 
> > Do you mean the checkpoints created? If so, no, I just ran the import with the --debug option in the command line.
> 
> I think Thomas meant: after the successful import, you could try deleting the new archive and trying the import again, to see if you can reproduce the problem.

Thanks for your reply. I deleted the new archiv as well as the checkpoints and the import succeeded. I have to mention that the rpi has been restarted due to sdcard check (=> ok).

**Comment by CarlosCastaneda** [comment] 2023-07-11 19:42
> Just because the rpi and the disks have their own power supplies doesn't mean that there isn't a problem with the rpi's power supply. I've had issues with an rpi that went away when switching power supplies. And just because the sdcard is new doesn't mean it isn't faulty. About the RAM test, I meant running something like memtester for 24 hours.

But I had no switching power supply so far. I'll run the memtester and will forward the results.
