### ISSUE TITLE
upgraded repository is missing borg keys

### ISSUE THREAD

**Issue by Profpatsch** [borgbackup/borg#580] opened 2016-01-19 11:08 UTC
When I convert a repository without attic keys, no borg key files are created, so commands like `borg list <repo>` fail with the error:

    No key file for repository ../backup.borg/ found in $HOME/.borg/keys.

**Comment by Profpatsch** [comment] 2016-01-19 11:31
This extends to that it doesn’t seem possible to use borg repos without having the corresponding keys. Even if they don’t need keys.

**Comment by ThomasWaldmann** [comment] 2016-01-19 12:29
I'll try if I can reproduce, but the problem seems strange:

why should it want a key if the repo is not encrypted?

if you could post a complete sequence of attic and borg commands that reproduces the problem with a new repo, that would be helpful.

**Comment by Profpatsch** [comment] 2016-01-19 14:10
> why should it want a key if the repo is not encrypted?

That’s exactly the problem. It wants one but did not create one.

Steps to reproduce should be:
1) Create unencrypted attic repo
2) `borg upgrade`
3) `borg list`

**Comment by ThomasWaldmann** [comment] 2016-01-19 23:49
```
tw@tux:~/w/borg$ . ../borg-env/bin/activate

(borg-env)tw@tux:~/w/borg$ git checkout 0.29.0
Note: checking out '0.29.0'.
You are in 'detached HEAD' state. You can ...
HEAD is now at 2ecfa54... ran build_api and build_usage

(borg-env)tw@tux:~/w/borg$ pip install -e .
Obtaining file:///home/tw/w/borg
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.6 in /home/tw/w/borg-env/lib/python3.4/site-packages (from borgbackup==0.29.0)
Installing collected packages: borgbackup
  Running setup.py develop for borgbackup
Successfully installed borgbackup-0.29.0

(borg-env)tw@tux:~/w/borg$ attic init repo
Initializing repository at "repo"
Encryption NOT enabled.
Use the "--encryption=passphrase|keyfile" to enable encryption.
Initializing cache...

(borg-env)tw@tux:~/w/borg$ attic create repo::test docs

(borg-env)tw@tux:~/w/borg$ attic list repo
test                                 Wed Jan 20 00:46:58 2016

(borg-env)tw@tux:~/w/borg$ borg upgrade repo
no key file found for repository

(borg-env)tw@tux:~/w/borg$ borg list repo
test                                 2016-01-20 00:46:58
```

Can not reproduce.

**Comment by Profpatsch** [comment] 2016-01-23 14:54
Did you already have keys in ~/.borg/keys? The folder did not exist on my system.
Unit tests are probably not enough to find bugs like these.

**Comment by ThomasWaldmann** [comment] 2016-01-24 00:18
OK, I'll try again without the keys folder.

**Comment by ThomasWaldmann** [comment] 2016-01-25 11:47
Without .borg folder, I also can not reproduce.

```
(borg-env)tw@tux:~/w/borg$ attic init repo
Initializing repository at "repo"
Encryption NOT enabled.
Use the "--encryption=passphrase|keyfile" to enable encryption.
Initializing cache...
(borg-env)tw@tux:~/w/borg$ attic create repo::test borg
(borg-env)tw@tux:~/w/borg$ attic list repo
test                                 Mon Jan 25 12:42:47 2016
(borg-env)tw@tux:~/w/borg$ ls -la ~/.borg
ls: cannot access /home/tw/.borg: No such file or directory
(borg-env)tw@tux:~/w/borg$ borg upgrade repo
no key file found for repository
(borg-env)tw@tux:~/w/borg$ borg list repo
test                                 Mon, 2016-01-25 12:42:47
```

I'm closing this now until somebody provides a script that reproduces the problem.

**Closed by ThomasWaldmann** 2016-01-25 11:47 UTC
Labels: easy

**Comment by nizedk** [comment] 2016-03-28 00:23
I got this as well, and can reproduce like this. (borg wasn't used on this host before, binary was just copied in)

user@host:~$ attic init --encryption=passphrase sletAttic
Initializing repository at "sletAttic"
Enter passphrase: 
Enter same passphrase again: 
Remember your passphrase. Your data will be inaccessible without it.
Initializing cache...
user@host:~$ attic create sletAttic::1 /home/user/
Enter passphrase for sletAttic::1: 
user@host:~$ borg upgrade -vp sletAttic
making a hardlink copy in /home/user/sletAttic.upgrade-2016-03-28-02:10:37
opening attic repository with borg and converting
no key file found for repository
copying attic cache file from /home/user/.cache/attic/e6673b3c27cbf3e3ba05a829961763a835c99fb2951ff4b751b6cf89047b8149/config to /home/user/.cache/borg/e6673b3c27cbf3e3ba05a829961763a835c99fb2951ff4b751b6cf89047b8149/config
copying attic cache file from /home/user/.cache/attic/e6673b3c27cbf3e3ba05a829961763a835c99fb2951ff4b751b6cf89047b8149/files to /home/user/.cache/borg/e6673b3c27cbf3e3ba05a829961763a835c99fb2951ff4b751b6cf89047b8149/files
copying attic cache file from /home/user/.cache/attic/e6673b3c27cbf3e3ba05a829961763a835c99fb2951ff4b751b6cf89047b8149/chunks to /home/user/.cache/borg/e6673b3c27cbf3e3ba05a829961763a835c99fb2951ff4b751b6cf89047b8149/chunks
converting cache /home/user/.cache/borg/e6673b3c27cbf3e3ba05a829961763a835c99fb2951ff4b751b6cf89047b8149/chunks
converting repo index /home/user/sletAttic/index.4
converting 3 segments...
converting borg 0.xx to borg current
no key file found for repository
user@host:~$ borg list sletAttic
No key entry found in the config of repository /home/user/sletAttic.
user@host:~$ 

using current linux x64 build from today. Hope this helps.

**Comment by ThomasWaldmann** [comment] 2016-03-28 12:11
borg 1.0 does not support passphrase mode any more since 1.0,0, please read the changelog about how to handle this.

**Comment by fabefour** [comment] 2017-01-17 18:00
I have this error on 3 seperate machines upgrading from 1.0.8 to 1.0.9. Two of them armhf devices. One x64. All Debian Jessie.
Version 1.0.9-1~bpo8+1 from jessie-backports repository
All repositories are setup without encryption

```
borg upgrade /mnt/extern/borg
no key file found for repository
no key file found for repository
```

**Comment by enkore** [comment] 2017-01-17 19:41
AFAIK it's only informative and doesn't matter if it's not encrypted, ie. it's expected that in this case no key files can be found. Guess the code that does that doesn't know if it's encrypted or not.

**Comment by fabefour** [comment] 2017-01-17 20:04
Okay, that's nice to know... I tried again with borg upgrade -v and also checked the exit code.
You're absolutely right. The upgrade command succeded.
However I think it's misleading, that the only information you get during an upgrade is a warning. This is why i expected the command to have failed.
