### ISSUE TITLE
Borg cache suddenly becomes huge

### ISSUE THREAD

**Issue by Garamotte** [borgbackup/borg#4860] opened 2019-11-28 07:48 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Probably a bug

#### Your borg version (borg -V).

borg 1.1.9 on client and server (from distrib repo)

#### Operating system (distribution) and version.

Client : Debian stretch
Server : Debian buster

#### Hardware / network configuration, and filesystems used.

Client : [Sheevaplug](https://en.wikipedia.org/wiki/SheevaPlug), ext2
Server : [Kimsufi KS-1](https://www.kimsufi.com/en/servers.xml), ext4
Network between client and server is a slow ADSL 5 Mbps down / 1 Mbps up.

#### How much data is handled by borg?

Info on the last archive :
```
                       Original size      Compressed size    Deduplicated size
This archive:                1.43 GB            639.57 MB            439.52 kB
All archives:                1.93 TB            863.10 GB              5.25 GB
```
Archives count : 1341

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Appeared on `borg create --stats --compression zlib,9 --checkpoint-interval 300 --exclude-from /root/.config/borg/ignore --exclude-caches --exclude-if-present .NOBACKUP --keep-exclude-tags server_hostname:backup::{hostname}-full-{now:%%Y%%m%%d-%%H%%M%%S} /`, but any command that (re)generates the cache will generate the same cache now.

## Describe the problem you're observing.

The cache was 100~200 MB, then suddenly grew up to 1.5 GB during an archive creation.
The client had a filesystem issue. After fixing it (basically fsck then reboot), the next archive creation generated a huge cache. The log of this archive started by :
```
Killed stale lock home.home@264627128674124.17894-0.
Removed stale exclusive roster lock for host home.home@264627128674124 pid 17894 thread 0.
Removed stale exclusive roster lock for host home.home@264627128674124 pid 17894 thread 0.
```
Everything else is fine except the cache's size.
I have another identical backup sent on another server (my nas, on the same lan than the client) that has not the issue (the cache is still ~200 MB, there are 1389 archives).

In addition to the standard monitoring (disk usage, etc.) I store backup duration, number of files and original/compressed/deduplicated/total size after each backup since about 2 weeks. I can provide some information if it can help.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I don't know exactly how to reproduce the issue, but I already had a similar issue on my desktop computer with a higher amount of data (60 GB original size, ~90 GB total repo size). I don't have detailed information about the repos at the date his cache started to grow. On my desktop, the issue appears on 2 of my 3 backups : local disk backup (cache ~8.5 GB) and lan server (cache 4.5 GB), but not on the backup that is sent to the remote server (cache <1 GB).

I tried to delete the cache, and the same was recreated each time.

#### Include any warning/errors/backtraces from the system logs

Nothing except the automatic stale lock deletion.

**Comment by ThomasWaldmann** [comment] 2019-11-28 18:15
Did you read the FAQ about `chunks.archive.d`?

**Comment by sylvain-garancher** [comment] 2019-11-28 23:57
Thanks for your answer.
I already read it and other issues on GitHub about cache, but I found none of them (I think) related to my issue. I don't say that the cache is too huge, but that it _suddenly_ became huge during a single `borg create` command, only for one of two similar backups.

To summarize : I don't understand how creating two backups with the exact same commands (except the destination server) can lead to having ~200 MB of cache for one and 1.5 GB for the other. Both repos have a similar archives count (1341 / 1389), the `borg prune` command run after each `borg create` are also the same.
Both cache directories were using ~200 MB since the beginning until yesterday.

Here is a screenshot from my Grafana showing the (very similar) stats of the two repos from `2019-11-27 15:00:00` to `2019-11-28 05:00:00`:
![image](https://user-images.githubusercontent.com/2804014/69835396-90383b80-1241-11ea-8b88-0482eefb2eff.png)
At ~18h, I made a system update (the small disk usage increase).
At ~20h, the disk usage increase from ~1.7 GB to ~3.1 GB is only due to one `borg create` generating a lot of cache.
Then, I deleted the big cache directory, and it was regenerated by `borg create` shortly after midnight.

Both cache now take a very different space on the disk:
```
# du -sh /root/.cache/borg/*
1,5G    /root/.cache/borg/956ab0ba762d64d725732fe32db56a83bcdedc36758bd1d9dba21050936b2b21
4,0K    /root/.cache/borg/CACHEDIR.TAG
199M    /root/.cache/borg/d17395744c9140de8d1ab410e9c722e7bba793435884111e3b7f6b25b0fc45fd
```

**Comment by ThomasWaldmann** [comment] 2019-11-29 07:03
The generation of the cache might be triggered by borg noticing that what it has in the cache has a smaller timestamp than the repo. This may be because another borg client was working in the same repo (e.g. to create or prune backups).

**Comment by sylvain-garancher** [comment] 2019-11-29 07:13
I have only one client working on each repo. The key file is stored on the client, so the server would not be able to work on the repo.
When I delete the cache, borg recreates exactly the same. I don't know how to reproduce the `Borg's cache becomes crazy` issue, but when it happens, the repo keeps his big cache.

Could this be caused by the filesystem issue (maybe happened during one of the backups) ?

Is there a way to compare the full cache generation between my 2 repos, to determine what are the differences and why borg creates a bigger cache for one of them ?

**Comment by ThomasWaldmann** [comment] 2019-11-29 07:22
Hmm, interesting. I need to have a look at that code...

A `ls -lR` of the cache directories for both repos (see .cache/borg/...) might be interesting.

**Comment by sylvain-garancher** [comment] 2019-11-29 07:43
Here is the result of `ls -lR /root/.cache/borg/*` : https://pastebin.com/raw/Cr67yZAH

**Comment by ThomasWaldmann** [comment] 2019-12-02 21:32
from `borg.cache`:
```
            if sync and self.manifest.id != self.cache_config.manifest_id:
                self.sync()
                self.commit()
```

So, it compares the current repo manifest id with the one it has stored in the cache config when it built the (master) chunks index last time.

**Comment by ThomasWaldmann** [comment] 2019-12-15 22:13
Code looks ok, space-extensive cache rebuilding is expected after:
- another client has written to the repo (modified the manifest), so local cache is out of sync
- local cache has been deleted, so local cache is non-existent

If you still think there is a bug / misbehaviour, I need the full procedure to reproduce the issue.

Use scripts, do not use absolute pathes, but only stuff on home directory. Do not use any options or other compexity that is not needed to reproduce the issue.

**Comment by FabioPedretti** [comment] 2019-12-16 10:49
Today I noticed a similar problem, my chunks.archive.d/ directory was full with 27GB of many old files like this:
```
-rw------- 1 backup disk  68K feb 20  2019 ffca4bf497c45d5283b2abcbb0621b36674dc33c418d8cf90543a006e757c94b.compact
-rw------- 1 backup disk   98 feb 20  2019 ffca4bf497c45d5283b2abcbb0621b36674dc33c418d8cf90543a006e757c94b.compact.integrity
```

**Comment by ThomasWaldmann** [comment] 2019-12-16 11:38
@FabioPedretti that's normal, see the FAQ in case you rather want to wait than have borg use that space.

**Comment by FabioPedretti** [comment] 2019-12-17 12:35
> @FabioPedretti that's normal, see the FAQ in case you rather want to wait than have borg use that space.

Yesterday I deleted all the files inside chunks.archive.d/ and today the backup was still the same speed and no new files are created.
Are all these files really needed and used? They were all 10 months old. I would suppose they were the remnants of something temporary (maybe a borg check I did at that time?).

**Comment by ThomasWaldmann** [comment] 2019-12-17 12:41
See above about why/when this happens.

**Comment by antoniomika** [comment] 2020-03-10 10:46
I just started noticing this in my environments also, but what is most strange is this seems to have started occurring after the DST session started (March 8th). If using the workaround as outlined in the FAQ, does this require the cache to be rebuilt in memory for each backup creation?

**Comment by mew1033** [comment] 2020-03-11 20:29
is there any way for the cache rebuild process to complete and for borg to clear its own cache? Essentially get back into a "good" state?

**Comment by ThomasWaldmann** [comment] 2020-03-11 23:12
The "master chunks index" rebuild only happens if it is out of sync with the repo (e.g. by another client writing to the repo).

The rebuild then needs to merge all "per-archive chunks indexes" to create a new valid master chunks index. It either can fetch these per-archive infos from "chunks.archives.d/*" (local, faster, but potentially needs lots of space) or from repo (potentially remote, slower).

The FAQ tells how to avoid the space usage if you prefer the slower mode.

It only does that when out of sync, afterwards it will be in sync again.

**Comment by ThomasWaldmann** [comment] 2023-04-16 21:08
Guess the FAQ explains this. If it needs more clarification there, please file a PR.

**Closed by ThomasWaldmann** 2023-04-16 21:08 UTC
Labels: question
