### ISSUE TITLE
Assertion error on keyboard interrupt

### ISSUE THREAD

**Issue by cpitclaudel** [borgbackup/borg#4501] opened 2019-04-07 23:03 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

Client: borg 1.1.5

#### Operating system (distribution) and version.

Linux Mint 19.1 Tessa

#### How much data is handled by borg?

~80GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create --progress --show-rc --list --filter AME- --exclude-caches --compression lz4 --exclude-from /tmp/tmp.2i8gD15hbX --stats ::{hostname}-{now} /home/clement/ /scratch/
```

## Describe the problem you're observing.

Pressing Ctrl+C early after starting a backup yields an assertion error:

```
Exception ignored in: <bound method RemoteRepository.__del__ of <RemoteRepository ssh://borgbackup-client@raspi-us/media/hdd/borg-backups/laptop>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 618, in __del__
    assert False, 'cleanup happened in Repository.__del__'
AssertionError: cleanup happened in Repository.__del__
Keyboard interrupt
terminating with error status, rc 2
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I'm I press Ctrl+C quickly, I get this:

```
Traceback (most recent call last):
  File "/usr/bin/borg", line 11, in <module>
    load_entry_point('borgbackup==1.1.5', 'console_scripts', 'borg')()
  File "/home/clement/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/clement/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/clement/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/clement/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 39, in <module>
    from .archive import Archive, ArchiveChecker, ArchiveRecreater, Statistics, is_special
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 24, in <module>
    from .cache import ChunkListEntry
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 30, in <module>
    from .crypto.key import PlaintextKey
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 28, in <module>
    from ..platform import SaveFile
  File "/usr/lib/python3/dist-packages/borg/platform/__init__.py", line 9, in <module>
    from .base import acl_get, acl_set
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 212, in <module>
    fqdn = getfqdn(hostname)
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 198, in getfqdn
    addrs = socket.getaddrinfo(name, None, 0, socket.SOCK_DGRAM, 0, socket.AI_CANONNAME)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
KeyboardInterrupt
```

If I wait ~1s, I get the assertion error fairly reliably.

Thanks for the hard work and for this great program!

**Comment by infectormp** [comment] 2019-04-08 04:09
@cpitclaudel can you reproduce this with borg 1.1.9?

**Comment by cpitclaudel** [comment] 2019-04-08 14:52
Yes

**Comment by ThomasWaldmann** [comment] 2019-04-08 18:39
I had looked at this before (but quite some time ago, so all is "IIRC"), but could not find the root cause, but here are some infos:

- the python context managers used in borg should tear down everything cleanly if borg an exception happens (like with Ctrl-C).
- the AssertionError you see above is an indication that the repository object was not teared down cleanly, but disposed via python's memory management when the process terminates - so it seems like the context manager does not (not always) work as expected.

This both is mostly interesting for the developers of borg and not so much from a users standpoint.

If borg gets killed somehow in the middle, it will not commit a transaction and rollback everything not committed the next time you use borg.

**Comment by ThomasWaldmann** [comment] 2022-11-05 00:50
There was an issue with Ctrl-C sending SIGINT to borg **and** subprocesses (like ssh, tar, ...) at the same time.

So it basically killed the ssh client process before borg was finished with closing the remote repo connection.

I recently fixed that, so it should be a bit better behaved now.

**Closed by ThomasWaldmann** 2022-11-05 00:50 UTC
