### ISSUE TITLE
Segmentation fault in Borg 1.1.11 attempting to copy a locked file from an smb share

### ISSUE THREAD

**Issue by Drone5of90** [borgbackup/borg#5083] opened 2020-04-06 00:28 UTC
Please see also: https://github.com/borgbackup/borg/issues/4709 
which is now an issue that is closed, but didn't appear to have this information to it.

I am also having this issue (relative to the link above).  The part that I believe may need to be addressed is in Borg Backup's  handling this error from the remote side.  

In Linux if I try to use 'cp' to copy the file, it returns an error:
cp: error writing '(the file I was attempting to copy)': Bad address
(side note: the file is 110189 bytes in size, when attempting to use 'cp' to copy the file it made a 210MB file that has all zero bytes in it before kicking out the error). 

If I try to copy this same file from another windows machine, windows returns the error:
The process cannot access the file because another process has locked a portion of the file.

In this case the file is locked (or a portion of the file is locked) on the Windows Server 2016 , and no client can access this.  

In this context it would seem that while Borg Backup is not at fault, but some additional error handling may be necessary to keep it from crashing in cases where a file is partially locked - noting from above that even a windows to windows copy is unable to copy the file.   The desired behavior would be for Borg Backup to handle these cases like it does currently with junction/symbolic-link files over SMB - where Borg would just generate an error and continue processing. 

Thank you to the Borg Backup programmers for making a great utility!

**Comment by ThomasWaldmann** [comment] 2020-04-06 15:55
How can i reproduce? Preferable without needed a windows machine or a samba server.

**Comment by ThomasWaldmann** [comment] 2020-04-06 15:57
guess this is a duplicate of #4709.

**Closed by ThomasWaldmann** 2020-04-06 15:57 UTC

**Comment by Drone5of90** [comment] 2020-04-08 14:43
In order to reproduce this you will have to have a program that locks a portion of a file.  If you cannot easily reproduce this I wonder if there is some information I can gather for you (perhaps some lines of debug code that will spit out whatever the code is that's being returned from the remote server so that you can add a handler for it?

**Comment by ThomasWaldmann** [comment] 2020-04-08 15:54
Please read and continue in #4709.

**Comment by auxym** [comment] 2021-01-25 00:24
I gather from #4709 that this has been deemed a CIFS issue. I have to ask, has anyone reported this to the samba project? I don't think I have the knowledge or qualifications to write up a detailed bug report for them, but maybe @BloodBlight, who has done debugging in #4709?

Seeing as Borg does not run on Windows, running Borg on a VM with CIFS shares mounted was my workaround, but this issue is currently breaking that workflow.
