### ISSUE TITLE
Add an option to disable locking

### ISSUE THREAD

**Issue by Ekleog** [borgbackup/borg#3144] opened 2017-10-11 22:16 UTC
In some cases, it could be useful to ask borg not to lock. Example in case: using read-only borg commands on a read-only borg repository.

As it sounds like quite an unusual scenario, I guess it could be hidden behind a scary name (like `--please-really-do-have-race-conditions`? maybe a bit less scary though), be restricted to read-only commands, and/or prepend a warning at the beginning of the result.

cc @jab416171 for the discussion on IRC.

**Comment by Artefact2** [comment] 2017-10-12 05:47
Would also be useful for me. I would like to mount my backup disk read-only for read-only operations, ie restore a file, check the repository integrity, show repository info…

A "no-lockfile" flag seems enough for this (rare) use-case, imho. The manpage could explain why it should only be used in very specific conditions.

**Comment by enkore** [comment] 2017-10-12 10:28
Duplicate of #1035

**Closed by enkore** 2017-10-12 10:28 UTC
