### ISSUE TITLE
Logfile friendly progress reporting for "borg check"?

### ISSUE THREAD

**Issue by bjornfor** [borgbackup/borg#1556] opened 2016-08-30 22:09 UTC
(Thanks a lot for working on Borg. I'm currently migrating away from Attic and I'm so happy that Borg is well maintained.)

Running ```borg check -v $repo``` outputs a progress bar, i.e. "Checking segments 15.6%", using the CR (0x0d) character to reset the cursor / refreshing the line. This works beautifully in the terminal, but not so much in a logfile / systemd journal, because the journal thinks the data is binary ("blob data"):

```
$ journalctl -u borg-backup --since="18:11:17" --until="22:48:08"
-- Logs begin at to. 2013-07-18 01:22:09 CEST, end at ti. 2016-08-30 23:29:37 CEST. --
aug. 30 18:11:17 mini borg-backup-script[9840]: Starting repository check
aug. 30 18:29:03 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 18:49:07 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 19:04:06 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 19:24:08 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 19:47:23 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 20:05:55 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 20:28:12 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 20:50:46 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 21:44:56 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 21:51:49 mini borg-backup-script[9840]: [236B blob data]
aug. 30 22:10:16 mini borg-backup-script[9840]: [2.0K blob data]
aug. 30 22:29:26 mini borg-backup-script[9840]: [1.6K blob data]
aug. 30 22:48:07 mini borg-backup-script[9840]: [1.7K blob data]
aug. 30 22:48:07 mini borg-backup-script[9840]: Completed repository check, errors found.
```

Using ```journalctl -a``` I am able to see the error message, well hidden inside the noise:

```
$ journalctl -a -u borg-backup --since="18:11:17" --until="22:48:08"
-- Logs begin at to. 2013-07-18 01:22:09 CEST, end at ti. 2016-08-30 23:40:37 CEST. --
aug. 30 18:11:17 mini borg-backup-script[9840]: Starting repository check
aug. 30 18:29:03 mini borg-backup-script[9840]: Checking segments 0.0%^MChecking segments 0.1%^MChecking segments 0.2%^MChecking segments 0.3%^MChecking segments 0.4%^MChecking segments 0.5%^MChecking segments 0.6%^MChecking segments 0.7%^MChecking segments 0.8%^MChecking segments 0.9%^MChecking segments 1.0%^MChecking segments 1.1%^MChecking segments 1.2%^MChecking segments 1.3%^MChecking segments 1.4%^MChecking segments 1.5%^MChecking segments 1.6%^MChecking segments 1.7%^MChecking segments 1.8%^MChecking segments 1.9%^MChecking segments 2.0%^MChecking segments 2.1%^MChecking segments 2.2%^MChecking segments 2.3%^MChecking segments 2.4%^MChecking segments 2.5%^MChecking segments 2.6%^MChecking segments 2.7%^MChecking segments 2.8%^MChecking segments 2.9%^MChecking segments 3.0%^MChecking segments 3.1%^MChecking segments 3.2%^MChecking segments 3.3%^MChecking segments 3.4%^MChecking segments 3.5%^MChecking segments 3.6%^MChecking segments 3.7%^MChecking segments 3.8%^MChecking segments 3.9%^MChecking segments 4.0%^MChecking segments 4.1%^MChecking segments 4.2%^MChecking segments 4.3%^MChecking segments 4.4%^MChecking segments 4.5%^MChecking segments 4.6%^MChecking segments 4.7%^MChecking segments 4.8%^MChecking segments 4.9%^MChecking segments 5.0%^MChecking segments 5.1%^MChecking segments 5.2%^MChecking segments 5.3%^MChecking segments 5.4%^MChecking segments 5.5%^MChecking segments 5.6%^MChecking segments 5.7%^MChecking segments 5.8%^MChecking segments 5.9%^MChecking segments 6.0%^MChecking segments 6.1%^MChecking segments 6.2%^MChecking segments 6.3%^MChecking segments 6.4%^MChecking segments 6.5%^MChecking segments 6.6%^MChecking segments 6.7%^MChecking segments 6.8%^MChecking segments 6.9%^MChecking segments 7.0%^MChecking segments 7.1%^MChecking segments 7.2%^MChecking segments 7.3%^MChecking segments 7.4%^MChecking segments 7.5%^MChecking segments 7.6%^MChecking segments 7.7%^MChecking segments 7.8%^MChecking segments 7.9%^MChecking segments 8.0%^MChecking segments 8.1%^MChecking segments 8.2%^MChecking segments 8.3%^MChecking segments 8.4%^MChecking segments 8.5%^MChecking segments 8.6%^MChecking segments 8.7%^MChecking segments 8.8%^MC
aug. 30 18:49:07 mini borg-backup-script[9840]: hecking segments 8.9%^MChecking segments 9.0%^MChecking segments 9.1%^MChecking segments 9.2%^MChecking segments 9.3%^MChecking segments 9.4%^MChecking segments 9.5%^MChecking segments 9.6%^MChecking segments 9.7%^MChecking segments 9.8%^MChecking segments 9.9%^MChecking segments 10.0%^MChecking segments 10.1%^MChecking segments 10.2%^MChecking segments 10.3%^MChecking segments 10.4%^MChecking segments 10.5%^MChecking segments 10.6%^MChecking segments 10.7%^MChecking segments 10.8%^MChecking segments 10.9%^MChecking segments 11.0%^MChecking segments 11.1%^MChecking segments 11.2%^MChecking segments 11.3%^MChecking segments 11.4%^MChecking segments 11.5%^MChecking segments 11.6%^MChecking segments 11.7%^MChecking segments 11.8%^MChecking segments 11.9%^MChecking segments 12.0%^MChecking segments 12.1%^MChecking segments 12.2%^MChecking segments 12.3%^MChecking segments 12.4%^MChecking segments 12.5%^MChecking segments 12.6%^MChecking segments 12.7%^MChecking segments 12.8%^MChecking segments 12.9%^MChecking segments 13.0%^MChecking segments 13.1%^MChecking segments 13.2%^MChecking segments 13.3%^MChecking segments 13.4%^MChecking segments 13.5%^MChecking segments 13.6%^MChecking segments 13.7%^MChecking segments 13.8%^MChecking segments 13.9%^MChecking segments 14.0%^MChecking segments 14.1%^MChecking segments 14.2%^MChecking segments 14.3%^MChecking segments 14.4%^MChecking segments 14.5%^MChecking segments 14.6%^MChecking segments 14.7%^MChecking segments 14.8%^MChecking segments 14.9%^MChecking segments 15.0%^MChecking segments 15.1%^MChecking segments 15.2%^MChecking segments 15.3%^MChecking segments 15.4%^MChecking segments 15.5%^MChecking segments 15.6%^MChecking segments 15.7%^MChecking segments 15.8%^MChecking segments 15.9%^MChecking segments 16.0%^MChecking segments 16.1%^MChecking segments 16.2%^MChecking segments 16.3%^MChecking segments 16.4%^MChecking segments 16.5%^MChecking segments 16.6%^MChecking segments 16.7%^MChecking segments 16.8%^MChecking segments 16.9%^MChecking segments 17.0%^MChecking segments 17.1%^MChecking segments 17.2%^MChecking segments 17.3%^MChecking segments 17
aug. 30 19:04:06 mini borg-backup-script[9840]: .4%^MChecking segments 17.5%^MChecking segments 17.6%^MChecking segments 17.7%^MChecking segments 17.8%^MChecking segments 17.9%^MChecking segments 18.0%^MChecking segments 18.1%^MChecking segments 18.2%^MChecking segments 18.3%^MChecking segments 18.4%^MChecking segments 18.5%^MChecking segments 18.6%^MChecking segments 18.7%^MChecking segments 18.8%^MChecking segments 18.9%^MChecking segments 19.0%^MChecking segments 19.1%^MChecking segments 19.2%^MChecking segments 19.3%^MChecking segments 19.4%^MChecking segments 19.5%^MChecking segments 19.6%^MChecking segments 19.7%^MChecking segments 19.8%^MChecking segments 19.9%^MChecking segments 20.0%^MChecking segments 20.1%^MChecking segments 20.2%^MChecking segments 20.3%^MChecking segments 20.4%^MChecking segments 20.5%^MChecking segments 20.6%^MChecking segments 20.7%^MChecking segments 20.8%^MChecking segments 20.9%^MChecking segments 21.0%^MChecking segments 21.1%^MChecking segments 21.2%^MChecking segments 21.3%^MChecking segments 21.4%^MChecking segments 21.5%^MChecking segments 21.6%^MChecking segments 21.7%^MChecking segments 21.8%^MChecking segments 21.9%^MChecking segments 22.0%^MChecking segments 22.1%^MChecking segments 22.2%^MChecking segments 22.3%^MChecking segments 22.4%^MChecking segments 22.5%^MChecking segments 22.6%^MChecking segments 22.7%^MChecking segments 22.8%^MChecking segments 22.9%^MChecking segments 23.0%^MChecking segments 23.1%^MChecking segments 23.2%^MChecking segments 23.3%^MChecking segments 23.4%^MChecking segments 23.5%^MChecking segments 23.6%^MChecking segments 23.7%^MChecking segments 23.8%^MChecking segments 23.9%^MChecking segments 24.0%^MChecking segments 24.1%^MChecking segments 24.2%^MChecking segments 24.3%^MChecking segments 24.4%^MChecking segments 24.5%^MChecking segments 24.6%^MChecking segments 24.7%^MChecking segments 24.8%^MChecking segments 24.9%^MChecking segments 25.0%^MChecking segments 25.1%^MChecking segments 25.2%^MChecking segments 25.3%^MChecking segments 25.4%^MChecking segments 25.5%^MChecking segments 25.6%^MChecking segments 25.7%^MChecking segments 25.8%^MChecking segments 25.9%^MChec
aug. 30 19:24:08 mini borg-backup-script[9840]: king segments 26.0%^MChecking segments 26.1%^MChecking segments 26.2%^MChecking segments 26.3%^MChecking segments 26.4%^MChecking segments 26.5%^MChecking segments 26.6%^MChecking segments 26.7%^MChecking segments 26.8%^MChecking segments 26.9%^MChecking segments 27.0%^MChecking segments 27.1%^MChecking segments 27.2%^MChecking segments 27.3%^MChecking segments 27.4%^MChecking segments 27.5%^MChecking segments 27.6%^MChecking segments 27.7%^MChecking segments 27.8%^MChecking segments 27.9%^MChecking segments 28.0%^MChecking segments 28.1%^MChecking segments 28.2%^MChecking segments 28.3%^MChecking segments 28.4%^MChecking segments 28.5%^MChecking segments 28.6%^MChecking segments 28.7%^MChecking segments 28.8%^MChecking segments 28.9%^MChecking segments 29.0%^MChecking segments 29.1%^MChecking segments 29.2%^MChecking segments 29.3%^MChecking segments 29.4%^MChecking segments 29.5%^MChecking segments 29.6%^MChecking segments 29.7%^MChecking segments 29.8%^MChecking segments 29.9%^MChecking segments 30.0%^MChecking segments 30.1%^MChecking segments 30.2%^MChecking segments 30.3%^MChecking segments 30.4%^MChecking segments 30.5%^MChecking segments 30.6%^MChecking segments 30.7%^MChecking segments 30.8%^MChecking segments 30.9%^MChecking segments 31.0%^MChecking segments 31.1%^MChecking segments 31.2%^MChecking segments 31.3%^MChecking segments 31.4%^MChecking segments 31.5%^MChecking segments 31.6%^MChecking segments 31.7%^MChecking segments 31.8%^MChecking segments 31.9%^MChecking segments 32.0%^MChecking segments 32.1%^MChecking segments 32.2%^MChecking segments 32.3%^MChecking segments 32.4%^MChecking segments 32.5%^MChecking segments 32.6%^MChecking segments 32.7%^MChecking segments 32.8%^MChecking segments 32.9%^MChecking segments 33.0%^MChecking segments 33.1%^MChecking segments 33.2%^MChecking segments 33.3%^MChecking segments 33.4%^MChecking segments 33.5%^MChecking segments 33.6%^MChecking segments 33.7%^MChecking segments 33.8%^MChecking segments 33.9%^MChecking segments 34.0%^MChecking segments 34.1%^MChecking segments 34.2%^MChecking segments 34.3%^MChecking segments 34.4%^MChecking seg
aug. 30 19:47:23 mini borg-backup-script[9840]: ments 34.5%^MChecking segments 34.6%^MChecking segments 34.7%^MChecking segments 34.8%^MChecking segments 34.9%^MChecking segments 35.0%^MChecking segments 35.1%^MChecking segments 35.2%^MChecking segments 35.3%^MChecking segments 35.4%^MChecking segments 35.5%^MChecking segments 35.6%^MChecking segments 35.7%^MChecking segments 35.8%^MChecking segments 35.9%^MChecking segments 36.0%^MChecking segments 36.1%^MChecking segments 36.2%^MChecking segments 36.3%^MChecking segments 36.4%^MChecking segments 36.5%^MChecking segments 36.6%^MChecking segments 36.7%^MChecking segments 36.8%^MChecking segments 36.9%^MChecking segments 37.0%^MChecking segments 37.1%^MChecking segments 37.2%^MChecking segments 37.3%^MChecking segments 37.4%^MChecking segments 37.5%^MChecking segments 37.6%^MChecking segments 37.7%^MChecking segments 37.8%^MChecking segments 37.9%^MChecking segments 38.0%^MChecking segments 38.1%^MChecking segments 38.2%^MChecking segments 38.3%^MChecking segments 38.4%^MChecking segments 38.5%^MChecking segments 38.6%^MChecking segments 38.7%^MChecking segments 38.8%^MChecking segments 38.9%^MChecking segments 39.0%^MChecking segments 39.1%^MChecking segments 39.2%^MChecking segments 39.3%^MChecking segments 39.4%^MChecking segments 39.5%^MChecking segments 39.6%^MChecking segments 39.7%^MChecking segments 39.8%^MChecking segments 39.9%^MChecking segments 40.0%^MChecking segments 40.1%^MChecking segments 40.2%^MChecking segments 40.3%^MChecking segments 40.4%^MChecking segments 40.5%^MChecking segments 40.6%^MChecking segments 40.7%^MChecking segments 40.8%^MChecking segments 40.9%^MChecking segments 41.0%^MChecking segments 41.1%^MChecking segments 41.2%^MChecking segments 41.3%^MChecking segments 41.4%^MChecking segments 41.5%^MChecking segments 41.6%^MChecking segments 41.7%^MChecking segments 41.8%^MChecking segments 41.9%^MChecking segments 42.0%^MChecking segments 42.1%^MChecking segments 42.2%^MChecking segments 42.3%^MChecking segments 42.4%^MChecking segments 42.5%^MChecking segments 42.6%^MChecking segments 42.7%^MChecking segments 42.8%^MChecking segments 42.9%^MChecking segments 43
aug. 30 20:05:55 mini borg-backup-script[9840]: .0%^MChecking segments 43.1%^MChecking segments 43.2%^MChecking segments 43.3%^MChecking segments 43.4%^MChecking segments 43.5%^MChecking segments 43.6%^MChecking segments 43.7%^MChecking segments 43.8%^MChecking segments 43.9%^MChecking segments 44.0%^MChecking segments 44.1%^MChecking segments 44.2%^MChecking segments 44.3%^MChecking segments 44.4%^MChecking segments 44.5%^MChecking segments 44.6%^MChecking segments 44.7%^MChecking segments 44.8%^MChecking segments 44.9%^MChecking segments 45.0%^MChecking segments 45.1%^MChecking segments 45.2%^MChecking segments 45.3%^MChecking segments 45.4%^MChecking segments 45.5%^MChecking segments 45.6%^MChecking segments 45.7%^MChecking segments 45.8%^MChecking segments 45.9%^MChecking segments 46.0%^MChecking segments 46.1%^MChecking segments 46.2%^MChecking segments 46.3%^MChecking segments 46.4%^MChecking segments 46.5%^MChecking segments 46.6%^MChecking segments 46.7%^MChecking segments 46.8%^MChecking segments 46.9%^MChecking segments 47.0%^MChecking segments 47.1%^MChecking segments 47.2%^MChecking segments 47.3%^MChecking segments 47.4%^MChecking segments 47.5%^MChecking segments 47.6%^MChecking segments 47.7%^MChecking segments 47.8%^MChecking segments 47.9%^MChecking segments 48.0%^MChecking segments 48.1%^MChecking segments 48.2%^MChecking segments 48.3%^MChecking segments 48.4%^MChecking segments 48.5%^MChecking segments 48.6%^MChecking segments 48.7%^MChecking segments 48.8%^MChecking segments 48.9%^MChecking segments 49.0%^MChecking segments 49.1%^MChecking segments 49.2%^MChecking segments 49.3%^MChecking segments 49.4%^MChecking segments 49.5%^MChecking segments 49.6%^MChecking segments 49.7%^MChecking segments 49.8%^MChecking segments 49.9%^MChecking segments 50.0%^MChecking segments 50.1%^MChecking segments 50.2%^MChecking segments 50.3%^MChecking segments 50.4%^MChecking segments 50.5%^MChecking segments 50.6%^MChecking segments 50.7%^MChecking segments 50.8%^MChecking segments 50.9%^MChecking segments 51.0%^MChecking segments 51.1%^MChecking segments 51.2%^MChecking segments 51.3%^MChecking segments 51.4%^MChecking segments 51.5%^MChec
aug. 30 20:28:12 mini borg-backup-script[9840]: king segments 51.6%^MChecking segments 51.7%^MChecking segments 51.8%^MChecking segments 51.9%^MChecking segments 52.0%^MChecking segments 52.1%^MChecking segments 52.2%^MChecking segments 52.3%^MChecking segments 52.4%^MChecking segments 52.5%^MChecking segments 52.6%^MChecking segments 52.7%^MChecking segments 52.8%^MChecking segments 52.9%^MChecking segments 53.0%^MChecking segments 53.1%^MChecking segments 53.2%^MChecking segments 53.3%^MChecking segments 53.4%^MChecking segments 53.5%^MChecking segments 53.6%^MChecking segments 53.7%^MChecking segments 53.8%^MChecking segments 53.9%^MChecking segments 54.0%^MChecking segments 54.1%^MChecking segments 54.2%^MChecking segments 54.3%^MChecking segments 54.4%^MChecking segments 54.5%^MChecking segments 54.6%^MChecking segments 54.7%^MChecking segments 54.8%^MChecking segments 54.9%^MChecking segments 55.0%^MChecking segments 55.1%^MChecking segments 55.2%^MChecking segments 55.3%^MChecking segments 55.4%^MChecking segments 55.5%^MChecking segments 55.6%^MChecking segments 55.7%^MChecking segments 55.8%^MChecking segments 55.9%^MChecking segments 56.0%^MChecking segments 56.1%^MChecking segments 56.2%^MChecking segments 56.3%^MChecking segments 56.4%^MChecking segments 56.5%^MChecking segments 56.6%^MChecking segments 56.7%^MChecking segments 56.8%^MChecking segments 56.9%^MChecking segments 57.0%^MChecking segments 57.1%^MChecking segments 57.2%^MChecking segments 57.3%^MChecking segments 57.4%^MChecking segments 57.5%^MChecking segments 57.6%^MChecking segments 57.7%^MChecking segments 57.8%^MChecking segments 57.9%^MChecking segments 58.0%^MChecking segments 58.1%^MChecking segments 58.2%^MChecking segments 58.3%^MChecking segments 58.4%^MChecking segments 58.5%^MChecking segments 58.6%^MChecking segments 58.7%^MChecking segments 58.8%^MChecking segments 58.9%^MChecking segments 59.0%^MChecking segments 59.1%^MChecking segments 59.2%^MChecking segments 59.3%^MChecking segments 59.4%^MChecking segments 59.5%^MChecking segments 59.6%^MChecking segments 59.7%^MChecking segments 59.8%^MChecking segments 59.9%^MChecking segments 60.0%^MChecking seg
aug. 30 20:50:46 mini borg-backup-script[9840]: ments 60.1%^MChecking segments 60.2%^MChecking segments 60.3%^MChecking segments 60.4%^MChecking segments 60.5%^MChecking segments 60.6%^MChecking segments 60.7%^MChecking segments 60.8%^MChecking segments 60.9%^MChecking segments 61.0%^MChecking segments 61.1%^MChecking segments 61.2%^MChecking segments 61.3%^MChecking segments 61.4%^MChecking segments 61.5%^MChecking segments 61.6%^MChecking segments 61.7%^MChecking segments 61.8%^MChecking segments 61.9%^MChecking segments 62.0%^MChecking segments 62.1%^MChecking segments 62.2%^MChecking segments 62.3%^MChecking segments 62.4%^MChecking segments 62.5%^MChecking segments 62.6%^MChecking segments 62.7%^MChecking segments 62.8%^MChecking segments 62.9%^MChecking segments 63.0%^MChecking segments 63.1%^MChecking segments 63.2%^MChecking segments 63.3%^MChecking segments 63.4%^MChecking segments 63.5%^MChecking segments 63.6%^MChecking segments 63.7%^MChecking segments 63.8%^MChecking segments 63.9%^MChecking segments 64.0%^MChecking segments 64.1%^MChecking segments 64.2%^MChecking segments 64.3%^MChecking segments 64.4%^MChecking segments 64.5%^MChecking segments 64.6%^MChecking segments 64.7%^MChecking segments 64.8%^MChecking segments 64.9%^MChecking segments 65.0%^MChecking segments 65.1%^MChecking segments 65.2%^MChecking segments 65.3%^MChecking segments 65.4%^MChecking segments 65.5%^MChecking segments 65.6%^MChecking segments 65.7%^MChecking segments 65.8%^MChecking segments 65.9%^MChecking segments 66.0%^MChecking segments 66.1%^MChecking segments 66.2%^MChecking segments 66.3%^MChecking segments 66.4%^MChecking segments 66.5%^MChecking segments 66.6%^MChecking segments 66.7%^MChecking segments 66.8%^MChecking segments 66.9%^MChecking segments 67.0%^MChecking segments 67.1%^MChecking segments 67.2%^MChecking segments 67.3%^MChecking segments 67.4%^MChecking segments 67.5%^MChecking segments 67.6%^MChecking segments 67.7%^MChecking segments 67.8%^MChecking segments 67.9%^MChecking segments 68.0%^MChecking segments 68.1%^MChecking segments 68.2%^MChecking segments 68.3%^MChecking segments 68.4%^MChecking segments 68.5%^MChecking segments 68
aug. 30 21:44:56 mini borg-backup-script[9840]: .6%^MChecking segments 68.7%^MChecking segments 68.8%^MChecking segments 68.9%^MChecking segments 69.0%^MChecking segments 69.1%^MChecking segments 69.2%^MChecking segments 69.3%^MChecking segments 69.4%^MChecking segments 69.5%^MChecking segments 69.6%^MChecking segments 69.7%^MChecking segments 69.8%^MChecking segments 69.9%^MChecking segments 70.0%^MChecking segments 70.1%^MChecking segments 70.2%^MChecking segments 70.3%^MChecking segments 70.4%^MChecking segments 70.5%^MChecking segments 70.6%^MChecking segments 70.7%^MChecking segments 70.8%^MChecking segments 70.9%^MChecking segments 71.0%^MChecking segments 71.1%^MChecking segments 71.2%^MChecking segments 71.3%^MChecking segments 71.4%^MChecking segments 71.5%^MChecking segments 71.6%^MChecking segments 71.7%^MChecking segments 71.8%^MChecking segments 71.9%^MChecking segments 72.0%^MChecking segments 72.1%^MChecking segments 72.2%^MChecking segments 72.3%^MChecking segments 72.4%^MChecking segments 72.5%^MChecking segments 72.6%^MChecking segments 72.7%^MChecking segments 72.8%^MChecking segments 72.9%^MChecking segments 73.0%^MChecking segments 73.1%^MChecking segments 73.2%^MChecking segments 73.3%^MChecking segments 73.4%^MChecking segments 73.5%^MChecking segments 73.6%^MChecking segments 73.7%^MChecking segments 73.8%^MChecking segments 73.9%^MChecking segments 74.0%^MChecking segments 74.1%^MChecking segments 74.2%^MChecking segments 74.3%^MChecking segments 74.4%^MChecking segments 74.5%^MChecking segments 74.6%^MChecking segments 74.7%^MChecking segments 74.8%^MChecking segments 74.9%^MChecking segments 75.0%^MChecking segments 75.1%^MChecking segments 75.2%^MChecking segments 75.3%^MChecking segments 75.4%^MChecking segments 75.5%^MChecking segments 75.6%^MChecking segments 75.7%^MChecking segments 75.8%^MChecking segments 75.9%^MChecking segments 76.0%^MChecking segments 76.1%^MChecking segments 76.2%^MChecking segments 76.3%^MChecking segments 76.4%^MChecking segments 76.5%^MChecking segments 76.6%^MChecking segments 76.7%^MChecking segments 76.8%^MChecking segments 76.9%^MChecking segments 77.0%^MChecking segments 77.1%^MChec
aug. 30 21:51:49 mini borg-backup-script[9840]: king segments 77.2%^MChecking segments 77.3%^MChecking segments 77.4%^MChecking segments 77.5%^MChecking segments 77.6%^MChecking segments 77.7%^MSegment entry data short read [segment 286690, offset 3756103]: expected 129484, got 28592 bytes
aug. 30 22:10:16 mini borg-backup-script[9840]: Checking segments 77.8%^MChecking segments 77.9%^MChecking segments 78.0%^MChecking segments 78.1%^MChecking segments 78.2%^MChecking segments 78.3%^MChecking segments 78.4%^MChecking segments 78.5%^MChecking segments 78.6%^MChecking segments 78.7%^MChecking segments 78.8%^MChecking segments 78.9%^MChecking segments 79.0%^MChecking segments 79.1%^MChecking segments 79.2%^MChecking segments 79.3%^MChecking segments 79.4%^MChecking segments 79.5%^MChecking segments 79.6%^MChecking segments 79.7%^MChecking segments 79.8%^MChecking segments 79.9%^MChecking segments 80.0%^MChecking segments 80.1%^MChecking segments 80.2%^MChecking segments 80.3%^MChecking segments 80.4%^MChecking segments 80.5%^MChecking segments 80.6%^MChecking segments 80.7%^MChecking segments 80.8%^MChecking segments 80.9%^MChecking segments 81.0%^MChecking segments 81.1%^MChecking segments 81.2%^MChecking segments 81.3%^MChecking segments 81.4%^MChecking segments 81.5%^MChecking segments 81.6%^MChecking segments 81.7%^MChecking segments 81.8%^MChecking segments 81.9%^MChecking segments 82.0%^MChecking segments 82.1%^MChecking segments 82.2%^MChecking segments 82.3%^MChecking segments 82.4%^MChecking segments 82.5%^MChecking segments 82.6%^MChecking segments 82.7%^MChecking segments 82.8%^MChecking segments 82.9%^MChecking segments 83.0%^MChecking segments 83.1%^MChecking segments 83.2%^MChecking segments 83.3%^MChecking segments 83.4%^MChecking segments 83.5%^MChecking segments 83.6%^MChecking segments 83.7%^MChecking segments 83.8%^MChecking segments 83.9%^MChecking segments 84.0%^MChecking segments 84.1%^MChecking segments 84.2%^MChecking segments 84.3%^MChecking segments 84.4%^MChecking segments 84.5%^MChecking segments 84.6%^MChecking segments 84.7%^MChecking segments 84.8%^MChecking segments 84.9%^MChecking segments 85.0%^MChecking segments 85.1%^MChecking segments 85.2%^MChecking segments 85.3%^MChecking segments 85.4%^MChecking segments 85.5%^MChecking segments 85.6%^MChecking segments 85.7%^MChecking segments 85.8%^MChecking segments 85.9%^MChecking segments 86.0%^MChecking segments 86.1%^MChecking segments 86.2%^MChecking
aug. 30 22:29:26 mini borg-backup-script[9840]:  segments 86.3%^MChecking segments 86.4%^MChecking segments 86.5%^MChecking segments 86.6%^MChecking segments 86.7%^MChecking segments 86.8%^MChecking segments 86.9%^MChecking segments 87.0%^MChecking segments 87.1%^MChecking segments 87.2%^MChecking segments 87.3%^MChecking segments 87.4%^MChecking segments 87.5%^MChecking segments 87.6%^MChecking segments 87.7%^MChecking segments 87.8%^MChecking segments 87.9%^MChecking segments 88.0%^MChecking segments 88.1%^MChecking segments 88.2%^MChecking segments 88.3%^MChecking segments 88.4%^MChecking segments 88.5%^MChecking segments 88.6%^MChecking segments 88.7%^MChecking segments 88.8%^MChecking segments 88.9%^MChecking segments 89.0%^MChecking segments 89.1%^MChecking segments 89.2%^MChecking segments 89.3%^MChecking segments 89.4%^MChecking segments 89.5%^MChecking segments 89.6%^MChecking segments 89.7%^MChecking segments 89.8%^MChecking segments 89.9%^MChecking segments 90.0%^MChecking segments 90.1%^MChecking segments 90.2%^MChecking segments 90.3%^MChecking segments 90.4%^MChecking segments 90.5%^MChecking segments 90.6%^MChecking segments 90.7%^MChecking segments 90.8%^MChecking segments 90.9%^MChecking segments 91.0%^MChecking segments 91.1%^MChecking segments 91.2%^MChecking segments 91.3%^MChecking segments 91.4%^MChecking segments 91.5%^MChecking segments 91.6%^MChecking segments 91.7%^MChecking segments 91.8%^MChecking segments 91.9%^MChecking segments 92.0%^MChecking segments 92.1%^MChecking segments 92.2%^MChecking segments 92.3%^MChecking segments 92.4%^MChecking segments 92.5%^MChecking segments 92.6%^MChecking segments 92.7%^MChecking segments 92.8%^MSegment entry data short read [segment 318309, offset 1519829]: expected 214508, got 159522 bytes
aug. 30 22:48:07 mini borg-backup-script[9840]: Checking segments 92.9%^MChecking segments 93.0%^MChecking segments 93.1%^MChecking segments 93.2%^MChecking segments 93.3%^MChecking segments 93.4%^MChecking segments 93.5%^MChecking segments 93.6%^MChecking segments 93.7%^MChecking segments 93.8%^MChecking segments 93.9%^MChecking segments 94.0%^MChecking segments 94.1%^MChecking segments 94.2%^MChecking segments 94.3%^MChecking segments 94.4%^MChecking segments 94.5%^MChecking segments 94.6%^MChecking segments 94.7%^MChecking segments 94.8%^MChecking segments 94.9%^MChecking segments 95.0%^MChecking segments 95.1%^MChecking segments 95.2%^MChecking segments 95.3%^MChecking segments 95.4%^MChecking segments 95.5%^MChecking segments 95.6%^MChecking segments 95.7%^MChecking segments 95.8%^MChecking segments 95.9%^MChecking segments 96.0%^MChecking segments 96.1%^MChecking segments 96.2%^MChecking segments 96.3%^MChecking segments 96.4%^MChecking segments 96.5%^MChecking segments 96.6%^MChecking segments 96.7%^MChecking segments 96.8%^MChecking segments 96.9%^MChecking segments 97.0%^MChecking segments 97.1%^MChecking segments 97.2%^MChecking segments 97.3%^MChecking segments 97.4%^MChecking segments 97.5%^MChecking segments 97.6%^MChecking segments 97.7%^MChecking segments 97.8%^MChecking segments 97.9%^MChecking segments 98.0%^MChecking segments 98.1%^MChecking segments 98.2%^MChecking segments 98.3%^MChecking segments 98.4%^MChecking segments 98.5%^MChecking segments 98.6%^MChecking segments 98.7%^MChecking segments 98.8%^MChecking segments 98.9%^MChecking segments 99.0%^MChecking segments 99.1%^MChecking segments 99.2%^MChecking segments 99.3%^MChecking segments 99.4%^MChecking segments 99.5%^MChecking segments 99.6%^MChecking segments 99.7%^MChecking segments 99.8%^MChecking segments 99.9%^M                        ^MIndex object count mismatch. 19913584 != 19913422
aug. 30 22:48:07 mini borg-backup-script[9840]: Completed repository check, errors found.
```

Maybe borg can check if stdout is a not a tty and in that case replace the CR with an LF? Or better yet, don't output any "interactive" progress bar unless a ```--progress``` option is passed? ("borg check" currently lack such an option.)

I also tried to remove the verbose flag (-v), but the progress bar is still there.

Using Borg 1.0.7.

**Comment by enkore** [comment] 2016-08-30 22:29
Thanks for the report. This is a duplicate of #824 and fixed for the 1.1+ series (current pre-release is 1.1.0b1).

**Closed by enkore** 2016-08-30 22:29 UTC
