### ISSUE TITLE
KeyError on extract

### ISSUE THREAD

**Issue by domenkozar** [borgbackup/borg#4681] opened 2019-07-12 09:13 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

1.1.10

#### Operating system (distribution) and version.

Ubuntu 16.10

#### How much data is handled by borg?
~100G

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

![IMG_20190712_104817](https://user-images.githubusercontent.com/126339/61117024-07895080-a496-11e9-9b0e-9d05cdca99ee.jpg)

**Comment by ThomasWaldmann** [comment] 2019-07-12 10:14
guess this is a duplicate of #4607.

workarounds: https://github.com/borgbackup/borg/issues/4607#issuecomment-500514777

**Closed by ThomasWaldmann** 2019-07-12 10:14 UTC
