### ISSUE TITLE
borg extract does not restore directory permissions

### ISSUE THREAD

**Issue by SanskritFritz** [borgbackup/borg#3176] opened 2017-10-16 21:22 UTC
My repository was initialised with borg 1.0.11. Filesystem is ext4. Below commands were done with borg 1.1.

Repo contains an archive listing only a few files created with this script:
```
#!/bin/bash
borg create --verbose --stats --progress --compression=lz4 borg_repository::important-{now:%Y-%m-%dT%H:%M:%S} "/home/frank/.keepassx"
```
Then later I do:
```
root@HomeC /C/B/borg# borg list borg_repository::important-2017-09-30T17:45:59 --format="{path} {user} {group}{NL}"
home/frank/.keepassx frank users
home/frank/.keepassx/SanskritFritzHome.kdb frank users
home/frank/.keepassx/SanskritFritzUPC.kdb frank users
```
When I do
```
root@HomeC /C/B/borg# cd /home/frank/temp/emptydir/
root@HomeC /h/f/t/emptydir# borg extract /Common/Backup/borg/borg_repository::important-2017-09-30T17:45:59
root@HomeC /h/f/t/emptydir# ls -lRa
.:
total 12
drwxr-xr-x 3 frank users 4096 okt   16 22.56 ./
drwxr-xr-x 7 frank users 4096 okt    4 22.50 ../
drwx------ 3 root  root  4096 okt   16 22.56 home/

./home:
total 12
drwx------ 3 root  root  4096 okt   16 22.56 ./
drwxr-xr-x 3 frank users 4096 okt   16 22.56 ../
drwx------ 3 root  root  4096 okt   16 22.56 frank/

./home/frank:
total 12
drwx------ 3 root  root  4096 okt   16 22.56 ./
drwx------ 3 root  root  4096 okt   16 22.56 ../
drwxr-xr-x 2 frank users 4096 szept 30 15.44 .keepassx/

./home/frank/.keepassx:
total 332
drwxr-xr-x 2 frank users   4096 szept 30 15.44 ./
drwx------ 3 root  root    4096 okt   16 22.56 ../
-rw-r--r-- 1 frank users 102796 szept 30 15.44 SanskritFritzHome.kdb
-rw------- 1 frank users 222604 2014 máj   22 SanskritFritzUPC.kdb
```
The leading path elements are root:root, instead of frank:users.
This might not strictly be a bug, since the path elements are not backed up per se, but still quite confusing and also prohibiting frank to reach his restored files.

**Comment by ThomasWaldmann** [comment] 2017-10-16 21:52
That's known (and not related to 1.1, this is same in 1.0 and has always been like that).
IIRC we already have an issue about this.

borg saved fs items starting at .keepassx to the archive, so it does not have metadata about the upper directories. It still knows the path though as the full path is in each item in the archive, so it will auto-create missing directories with default permissions and current user/group.

**Comment by ThomasWaldmann** [comment] 2017-10-17 04:27
duplicate of #1751

**Closed by ThomasWaldmann** 2017-10-17 04:27 UTC

**Comment by SanskritFritz** [comment] 2017-10-17 07:32
Thank you, I thought so. Sorry for not searching here first for this problem.
So now the solution is to backup the directories themselves as well either via patterns or using exception rules.
