### ISSUE TITLE
OOM kill of client left remote serve alive

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1774] opened 2016-10-29 10:09 UTC
_Somehow_ that happened*. Perhaps an OOM kill on Linux has special semantics that break this.

\* Actually I know exactly how that happened: `dd if=/dev/zero ... | borg create` with create asking a question.

**Comment by enkore** [comment] 2016-11-08 17:31
Okay, I'm starting to see a pattern here.

Is it possible that if the pipe dies without saying goodbye that then both the client and the remote serve instance can get deadlocked?

**Comment by lutoma** [comment] 2016-11-23 11:12
> Is it possible that if the pipe (SSH) dies without saying goodbye that then both the client and the remote serve instance can get deadlocked?

If by "can get deadlocked" you mean the remote server will keep running (and keep the repository locked) without actually having a client connected to it, yes. Happens to me too from time to time when doing backups of my laptop and changing networks/suspending it while forgetting to stop borg first.

I usually just SIGTERM the remote server, which tends to remove the lock.

**Comment by ThomasWaldmann** [comment] 2016-11-26 21:17
I did ~5 tries to reproduce this issue using `borg create` (ssh: repo) and killing the client via `kill -9 pid`.

There never was a server process still running after that, but I usually had to use `borg break-lock`.

**Comment by ThomasWaldmann** [comment] 2016-11-26 21:33
I also tried the OOM kill using dd, same there: no server process left.

Close?

**Comment by enkore** [comment] 2016-11-26 23:23
Yes, I only observed this once with vanilla Borg, and since it is known that OOM on Linux isn't really stable, this one is probably problem outside borg.

**Comment by enkore** [comment] 2016-11-26 23:24
Hmm, what happens if the client is killed when the server executes a long-running command (check). I guess it runs till the RPC call returns and fails to write to the broken pipes.

**Comment by ThomasWaldmann** [comment] 2016-11-27 00:44
OK, I'll check "check".

**Comment by ThomasWaldmann** [comment] 2016-11-27 01:05
I ran `borg check --repository-only ssh://...` on a repo with a few GBs of data.

It displays the "Checking segments N%" all the time on the client.

Then, about in the middle, killed client with `kill -9`.

The server was there after that, but only shortly (few secs), then the server process terminated (could be regular end or irregular end after short timeout).

There was no lock left behind.

Close this because not reproducable?

**Comment by enkore** [comment] 2016-11-27 10:08
Thanks for your investigation! :)

**Closed** 2016-11-27 10:08 UTC
Labels: question
