### ISSUE TITLE
slow borg check (0.27 and prior releases)

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#259] opened 2015-10-07 13:21 UTC
On this repo (230GB, 87 archives), "borg check" consumes 100% of a CPU core, but doesn't have much disk traffic as measured by 'atop'.  And 'lsof /path/to/filesystem' shows it opening one file every few minutes.

Ctrl-C while running almost always causes it to emit this trace.

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1030, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 986, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 95, in do_check
    repository, repair=args.repair, archive=args.repository.archive, last=args.last):
  File "/usr/lib64/python3.4/site-packages/borg/archive.py", line 627, in check
    self.rebuild_refcounts(archive=archive, last=last)
  File "/usr/lib64/python3.4/site-packages/borg/archive.py", line 795, in rebuild_refcounts
    for item in robust_iterator(archive):
  File "/usr/lib64/python3.4/site-packages/borg/archive.py", line 760, in robust_iterator
    for item in unpacker:
  File "/usr/lib64/python3.4/site-packages/borg/archive.py", line 607, in __next__
    return next(self._unpacker)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 557, in next
    ret = self._fb_unpack(EX_CONSTRUCT, None)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 538, in _fb_unpack
    ret[key] = self._fb_unpack(EX_CONSTRUCT, write_bytes)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 517, in _fb_unpack
    ret.append(self._fb_unpack(EX_CONSTRUCT, write_bytes))
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 517, in _fb_unpack
    ret.append(self._fb_unpack(EX_CONSTRUCT, write_bytes))
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 498, in _fb_unpack
    typ, n, obj = self._read_header(execute, write_bytes)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 346, in _read_header
    c = self._fb_read(1, write_bytes)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 312, in _fb_read
    return buffs[self._fb_buf_i][self._fb_buf_o - n:self._fb_buf_o]

**Comment by ThomasWaldmann** [comment] 2015-10-07 13:52
Can you add more details, please:
platform, repo encryption, archive compression? commandline you used for check?

lsof /path/to/filesystem - your mean the repository path? or local cache? or both?

msgpack fallback sounds suspicious. usually msgpack compiles a C extension when it is installed, but fallback rather sounds like it is using the pure-python fallback code.

**Comment by ThomasWaldmann** [comment] 2015-10-07 13:57
for a bigger amount of small files, like source code, one segment file (5MB) in the repo could contain quite a lot of compressed src files.

**Comment by tgharold** [comment] 2015-10-07 14:13
CentOS 6.4, Python 3.4.3, no repo encryption, default compression (probably initially created under 0.25 or 0.26), the repo is about 4-5 weeks old.

borg check --archives-only file://backup/path/repo.borg

lsof /path/to/repofilesystem (i.e. /backup/path) since it is a separate ext4 file system for easy monitoring.

I suspect that there are a lot of small files in each segment file, not sure why it is so slow at reading through the file list.

**Comment by ThomasWaldmann** [comment] 2015-10-07 14:33
@tgharold you followed the issues why the binaries do now get built on debian7 rather than centos6?

I initially thought centos6 is a good idea because of long term support and even lower glibc requirements (so the binary really runs everywhere, including on centos6), but the binary that came out there was somehow 2-4 times slower than expected with `borg list`. The issue went away when building on debian7.

I don't know the reason for the binary slowness (and I didn't do from-source performance measurements on centos6).

Maybe the slowness here is also related to centos6?

**Comment by tgharold** [comment] 2015-10-07 14:34
Yeah, I'm wondering if #222 is related.

**Comment by tgharold** [comment] 2015-10-07 18:59
I'm going to tentatively say that the binaries in #222 are an order of magnitude (or two) faster then the "pip3 install borgmagic" binaries.

borg 0.26.2.dev13+ngaef71ac.d20151003

**Comment by ThomasWaldmann** [comment] 2015-10-07 20:03
@tgharold yeah, they were built on debian7. but they are superseded by 0.27 binaries, also built on debian7 - they should have same speed.

**Comment by ThomasWaldmann** [comment] 2015-10-07 20:05
So, close this or is there anything left?

**Comment by tgharold** [comment] 2015-10-07 20:07
Probably needs a warning in the readme/install notes that CentOS 6.x users have to use the binary edition of borgbackup in order to avoid a speed issue in msgpack.  Not sure if "pip3 install borgbackup" grabs the binary version or if you have to specifically download a wheel (.whl) to get the binary.

**Comment by ThomasWaldmann** [comment] 2015-10-07 21:05
msgpack/fallback.py means it can't load the compiled C version of msgpack. maybe because it was not compiled or there is some other issue. using the fallback pure python version makes it quite slower, but that is not a borgbackup problem in general.

you could try to install it from source again and have an eye on what exactly goes wrong when it installs msgpack (maybe there is a compiler error or compiler is not found or so).

as this is a installation issue and not a bug, I am closing this.

**Closed by ThomasWaldmann** 2015-10-07 21:05 UTC

**Comment by ThomasWaldmann** [comment] 2015-10-10 10:48
@tgharold about the binary needed: there are no linux binary wheels on pypi, AFAIK it would always compile the msgpack C extension. So, if it does not have the compiled C extension and is using the slow pure-python fallback code on linux, something is going wrong with that compilation.

**Comment by ThomasWaldmann** [comment] 2015-10-31 20:07
btw, see #342 - I found what was missing on centos that led to msgpack not compiling the C (C++?) extension.
