### ISSUE TITLE
optimize borg check duration

### ISSUE THREAD

**Issue by mahikeulbody** [borgbackup/borg#4180] opened 2018-11-18 18:46 UTC
It is a request (not an issue).

I would check my repo after each create. In my use case, a create take a few minutes but a check take 1h40 (without any option) (repo size : 540Gb). It is a long time and that deters probably many users to do systematically a check.

So, could it be possible to introduce some multi-threading into borg check ?

_I don't know if it would be simpler than to introduce multi-threading into borg create but at least it is less risky since it is only a reading operation and may be more useful._

**Comment by ThomasWaldmann** [comment] 2018-11-18 19:14
how long something takes depends on how much data is dealt with.

`borg create` is highly optimized and due to caching and change detection it can skip dealing with a lot of unchanged data. so, if you do not have a lot of changes, it's done quite quickly as it does not have to process a lot of data.

otoh, `borg check` really looks at a lot or even all the data stored in the repo (depends on the options you give), which naturally takes a lot longer.

that said, if you automate your backups and checks and they run in the background, it shouldn't matter if it takes an hour as you don't need to watch it / wait for it.

we have multithreading plans (search this issue tracker), but they will rather address `borg create` first, not `borg check`. whether multithreading would help with borg check depends on quite some factors. MT is good for parallelizable (cpu bound) algorithms. if something is I/O bound it can help or not, that depends on quite a lot of other factors and the I/O subsystems involved and their capabilities.

**Comment by mahikeulbody** [comment] 2018-11-19 08:06
Thanks you for the quick answer.

> if you automate your backups and checks and they run in the background, it shouldn't matter if it takes an hour as you don't need to watch it / wait for it.

One could say the same about create, no ? So, why do you plan multithreading for create (it is a true question) ?

But in fact check duration **does matter** in order to be able to do frequent creates (one per hour for example) : in this situation, borg create tends to be fast (in most use cases) when borg check will take the same long time. So, it seems (IMHO) that multithreading efforts on check would be more valuable than multithreading efforts on create.

On the other side, performance benchs between borg, restic, bup or whatever are related mainly to the create operation so... but I don't believe you are drived by such considerations ;-)

Anyway, thanks all for the great work !
Regards.
Michel

**Comment by ThomasWaldmann** [comment] 2018-11-19 11:48
When you have a lot of changes between your backups, borg create will need to deal with the changed data.
Also, even if you don't, but you're trying to do an initial backup of a huge amount of data.

You do not need to run borg check after each backup (esp. not when doing hourly or so), just run it frequently enough to notice early enough when something is going wrong.

**Comment by mahikeulbody** [comment] 2018-11-19 13:00
I sync the repo on the cloud with rclone after each create. So, if something is going wrong, my cloud backup will be wrong also. Of course, I have the original data yet and I can init a new repo* **but I would loss all history of this data**. So I prefer to check the repo before to sync it to the cloud in order to be able to restore the repo from the cloud in case of problem found by borg check.

Not being able to do systematic checks impacts the global robustness of the solution as that could lead to discover a problem too late to recovery the data history or, worse, too late to recovery the data itself.

Of course, one can adapt create frequency to check duration if needed but it is not very satisfactory.

Anyway, whatever borg future will be, it is not available now so in the meantime I will adapt create frequency, hoping a best priority will be given to check perf.

_* or try to repair it with --repair option but without any guaranty to be successful._

**Comment by dragetd** [comment] 2019-02-03 07:48
Checking every byte is an expensive operation. In theory you are running the complete dataset through your IO stack twice.

If a segment gets corrupted by something, you usually loose that segment data and not your whole repository(*). And segments are always just created and appended, never updated/rewritten. Thus if you sync it with rclone your 'good data' should stay good… while e.g. a weekly 'borg check' would still allow to catch corruptions within one week.

And depending on the level of hardware issue, this corruption might only affect one version of a file in one archive.

For very important data I would consider using redundant storage on the backup target (zfs, btrfs, ceph, raid* whatnot) and/or even snapshots (copies) of your backup.


(*) For peace of mind, you could use --archives-only with borg check after every create. It checks if the archives are intact, such that a corruption does not affect archive data and not segments.

**Comment by ThomasWaldmann** [comment] 2019-02-03 12:55
if a content data chunk gets corrupted, it will affect all files in all archives that use this chunk.

if a archive metadata stream chunk gets corrupted, it will affect all archives that use this chunk (this can be 1 or multiple, depending on how good that metadata stream dedups over time).

**Comment by ThomasWaldmann** [comment] 2019-02-16 11:22
closing this as mostly duplicate of #1657.

**Closed by ThomasWaldmann** 2019-02-16 11:22 UTC
