### ISSUE TITLE
Trying to upgrade from 0.30.0 to 1.0.0rc2 big mess

### ISSUE THREAD

**Issue by ovizii** [borgbackup/borg#706] opened 2016-03-01 19:00 UTC
I have decided to try out the new version but thigns got messed up so it looks like I need some handholding.

**trying to move the keys:**

borg upgrade /mnt/backup/bailey
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1481, in main
  File "borg/archiver.py", line 1435, in run
  File "borg/archiver.py", line 601, in do_upgrade
  File "borg/upgrader.py", line 38, in upgrade
  File "shutil.py", line 353, in copytree
shutil.Error: [('/mnt/backup/bailey/data/0', '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20/data/0', "[Errno 5] Input/output error: '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20/data/0'"), ('/mnt/backup/bailey/data', '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20/data', "[Errno 5] Input/output error: '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20/data'"), ('/mnt/backup/bailey/lock.exclusive', '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20/lock.exclusive', "[Errno 5] Input/output error: '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20/lock.exclusive'"), ('/mnt/backup/bailey', '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20', "[Errno 5] Input/output error: '/mnt/backup/bailey.upgrade-2016-03-01-18:53:20'")]

Platform: Linux bailey 4.2.8-1-pve #1 SMP Wed Feb 3 16:33:06 CET 2016 x86_64
Linux: debian 8.3   LibC: glibc 2.3
Borg: 1.0.0rc2  Python: CPython 3.5.1
PID: 16885  CWD: /root/.borg
sys.argv: ['borg', 'upgrade', '/mnt/backup/bailey']
SSH_ORIGINAL_COMMAND: None

---------
**according to the changelog I need to migrate:**

borg migrate-to-repokey /mnt/backup/bailey
Failed to create/acquire the lock /mnt/backup/bailey/lock.exclusive (timeout).

---------
**after a few tries: **

s -al /mnt/backup/bailey
bailey/                             bailey.upgrade-2016-03-01-18:52:31/ bailey.upgrade-2016-03-01-18:53:08/ bailey.upgrade-2016-03-01-18:53:20/

-----------
**the change log says: remove deprecated "borg verify", use "borg extract --dry-run" instead**

I am using borg check -v /mnt/backup/bailey - is that the same?

-----------
**having backed up my old backups, I am trying to start fresh with borg 1.0.0rc2 and I end up with postfix owning all my backups even though I am using borg as root?**

borg init --encryption=keyfile /mnt/backup/bailey
Enter new passphrase:
Enter same passphrase again:
root@bailey:~/.borg# ls -al /mnt/backup/
total 22
drwxr-xr-x 7 postfix users    9 Mar  1 19:18 .
drwxr-xr-x 3 root    root  4096 Dec 10 19:15 ..
drwx------ 3 postfix users    8 Mar  1 19:18 bailey

**Comment by ThomasWaldmann** [comment] 2016-03-01 21:14
shutil.copytree is just a recursive copy command.
it encountered a lot of input/output errors (see output), so, is your disk or disk interface defect maybe?

**Comment by ovizii** [comment] 2016-03-02 06:49
hm, the backup is a NFS mount which I mounted right before executing these commands.
but before this upgrade, I had it all wrapped up in a nice script and it has been running for 3-4 months already and always survived upgrades i.e. my oldest borg Version I was working with was 0.28.X if I remember correctly.

**Comment by ThomasWaldmann** [comment] 2016-03-02 12:56
ok, then it could also be a network issue additionally.

can you reproduce the IOErrors?

**Comment by ovizii** [comment] 2016-03-02 13:42
Thanks Thomas, I will try again tonight and let you know. I have 3 servers being backed up. I have meanwhile started a fresh set of backups with the smallest one of them but if that keeps running fine I guess I'll start all 3 of them from scratch. 

Would you mind checking out my other questions in this thread? Or maybe give me some links to read up? 

**i.e. **
- - why does the postfix user own the backups? The docs haven't yielded anything for this. I run the backup scripts via crontab as root.
- - the change log says: remove deprecated "borg verify", use "borg extract --dry-run" instead. I am using borg check -v /mnt/backup/bailey - is that the same?

**Comment by ThomasWaldmann** [comment] 2016-03-02 13:51
postfix: did you maybe create a new user for borg and accidentally you used the same uid as postfix?

no, borg extract --dry-run and borg check are not the same. please read the usage section of the docs.

**Comment by ThomasWaldmann** [comment] 2016-03-02 14:04
btw, do you use borgbackup to backup proxmox VMs?

**Comment by ovizii** [comment] 2016-03-02 14:29
> btw, do you use borgbackup to backup proxmox VMs?
Yes, but I run borg within the VMs and backup only specific data from inside.

**Comment by manwegit** [comment] 2016-03-02 15:34
Testing on a nfs mount with Release 1.0.0rc2 from releases page.

```
/opt/scripts/borgbin/borg-0.30.0 init -v  /mnt/nfs/testing/backup
/opt/scripts/borgbin/borg-0.30.0 init -v -e passphrase /mnt/nfs/testing/backup2
/opt/scripts/borgbin/borg-0.30.0 init -v -e keyfile /mnt/nfs/testing/backup3
/opt/scripts/borgbin/borg-0.30.0 init -v -e repokey /mnt/nfs/testing/backup4

/opt/scripts/borgbin/borg-0.30.0 create  /mnt/nfs/testing/backup::test$(date +%s) /tmp/borg-linux64
/opt/scripts/borgbin/borg-0.30.0 create  /mnt/nfs/testing/backup2::test$(date +%s) /tmp/borg-linux64
/opt/scripts/borgbin/borg-0.30.0 create  /mnt/nfs/testing/backup3::test$(date +%s) /tmp/borg-linux64
/opt/scripts/borgbin/borg-0.30.0 create  /mnt/nfs/testing/backup4::test$(date +%s) /tmp/borg-linux64

/tmp/borg-linux64 upgrade /mnt/nfs/testing/backup
/tmp/borg-linux64 upgrade /mnt/nfs/testing/backup2
/tmp/borg-linux64 upgrade /mnt/nfs/testing/backup3
/tmp/borg-linux64 upgrade /mnt/nfs/testing/backup4
```

`/tmp/borg-linux64 migrate-to-repokey /mnt/nfs/testing/backup`
#703
`/tmp/borg-linux64 migrate-to-repokey /mnt/nfs/testing/backup2`
OK - works as expected
`/tmp/borg-linux64 migrate-to-repokey /mnt/nfs/testing/backup4`
#703
`/tmp/borg-linux64 migrate-to-repokey /mnt/nfs/testing/backup3`
#703

**Comment by ThomasWaldmann** [comment] 2016-03-02 17:00
so "borg upgrade" worked?

**Comment by manwegit** [comment] 2016-03-02 17:27
Ah sorry, yes.
I could not generate errors except those related to migrate-to-repokey

normal operations, list etc all worked fine with the new  version after upgrade.
`/tmp/borg-linux64` is the 1.0.0rc2 version from releases

**Comment by manwegit** [comment] 2016-03-02 17:29
Just though that those error might be related to nfs locking. Maybe mounted with no lock support or something like that.
But I could not reproduce with working nfs3 mount.

**Comment by ThomasWaldmann** [comment] 2016-03-02 17:49
borg does not use posix locking (or any other locking that needs special support).
it just creates a directory to represent the lock.

**Comment by manwegit** [comment] 2016-03-02 21:41
What system is the nfs server? I just thought that if there's some compatibility layer with nfs servers FS for windows shares then colon in filenames might be a problem.
(have you ever copied a file with colon to usb drive (ntfs) and then given it to a windows person..)

**Comment by ovizii** [comment] 2016-03-03 08:06
Hi guys, I highly appreciate your support, I haven't dropped the ball, I'm just not having much time at the moment. I will reply here as soon I get a few minutes. 

So regarding the nfs shares, the server is with SoYouStart and they are notorious for problems with their nfs shares. I guess I was just lucky it all worked so well so far.

@manwegit the touch command worked just fine.

So what I did for now is pause 2 out of 3 borg backups until I have time to solve this. 
The 3rd VM is now backing up using Release 1.0.0rc2 from releases page and has apparently successfully run for 3 days now. I simply created a new repo for it and ignored the old one to avoid upgrade problems.

The way this works is borg is running inside all 3 of these machines and backing up stuff, I am not backing up whole VMs.

btw. here is the script I managed to cobble together from the borg page, if you could have a look to make sure there's nothign in there I am screwing up: [http://pastebin.com/kZ9WTbwt]

**Comment by ThomasWaldmann** [comment] 2016-03-03 10:11
I'll close this for now, do not see anything going wrong inside borg here.

If you find something later, feel free to reopen it with more details.

**Closed by ThomasWaldmann** 2016-03-03 10:11 UTC
