### ISSUE TITLE
Bug after upgrading to msgpack-python 0.5.2

### ISSUE THREAD

**Issue by huettenhain** [borgbackup/borg#3597] opened 2018-02-06 00:04 UTC
Hey! Admittedly, I am running borg under unconventional circumstances:

- *Operating System:* Cygwin on Windows 10
- *Borg Version:* Both `1.1.2` and `1.1.4`

However, borg does work very well with `msgpack-python` version 0.5.1 and below, however after upgrading to 0.5.2, I get the following error message:

```
$ borg init ssh://user@host/~/foo/bar/ -e repokey
Local Exception
Traceback (most recent call last):
  File "/cygdrive/c/venv/borg/src/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/cygdrive/c/venv/borg/src/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/cygdrive/c/venv/borg/src/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/cygdrive/c/venv/borg/src/borg/archiver.py", line 270, in do_init
    manifest.write()
  File "/cygdrive/c/venv/borg/src/borg/helpers.py", line 409, in write
    data = self.key.pack_and_authenticate_metadata(manifest.as_dict())
  File "/cygdrive/c/venv/borg/src/borg/crypto/key.py", line 211, in pack_and_authenticate_metadata
    packed = msgpack.packb(metadata_dict, unicode_errors='surrogateescape')
  File "/cygdrive/c/venv/lib/python3.6/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 136, in msgpack._packer.Packer.__init__
TypeError: expected bytes, str found
```
A working fix is downgrading to `msgpack-python==0.5.1`, so this is not very dramatic. 
I still wanted to report it.

**Comment by ThomasWaldmann** [comment] 2018-02-06 01:25
try 0.5.3.

**Comment by ThomasWaldmann** [comment] 2018-02-06 08:38
Duplicate of #3586.

**Closed by ThomasWaldmann** 2018-02-06 08:38 UTC

**Comment by ThomasWaldmann** [comment] 2018-02-06 08:40
I filed a bug at msgpack-python project that the package needs a pypi upload. Only msgpack was updated on pypi, but msgpack-python (old package name for same thing) was forgotten...

A workaround is to install 0.5.1 or < 0.5.0.

**Comment by huettenhain** [comment] 2018-02-06 12:11
Thanks! Sorry for the duplicate.
