### ISSUE TITLE
`borg list` or `borg prune` hangs

### ISSUE THREAD

**Issue by pierreozoux** [borgbackup/borg#3777] opened 2018-04-18 09:03 UTC
It started some days ago, it is just from one server to another (other servers are fine).
From time to time, `borg list` command hangs.

Do you have any idea how to debug that?
(I tried to run it various times manually with `--debug` without success.

Thanks for your help!

**Comment by ThomasWaldmann** [comment] 2018-04-18 10:08
borg list usually does not hang, but if the ssh connection is stalling or disconnected, it can be caused by that.

It could be also that the borg server is very busy with other disk or network I/O, so borg list comes a bit short.

**Comment by pierreozoux** [comment] 2018-04-18 12:40
investigating a bit further, not just the `list` hangs, but `prune` too.
And it just doesn't answer anymore.
It looks like an ssh issue then. On this server, there is memory available, cpu is around 10%, just there is no swap available. can it be the issue?
Is there a timeout on the ssh command? Or is there an option to set it? (I searched quickly the doc, didn't find it)

**Comment by ThomasWaldmann** [comment] 2018-04-19 13:27
In general, borg needs enough memory to load some indexes and caches into memory (and they can be huge if your repo is huge, there is a formula in the docs to estimate memory usage). If borg runs out of available (virtual) memory, you'll get a MemoryError exception.

If you don't have on-disk swap available, the slow down can not be cause by on-disk swapping activity.

So I guess you have a network or ssh issue.

**Comment by ThomasWaldmann** [comment] 2018-04-28 17:29
I am closing this for now as this is not actionable.

Reopen if you have more information, esp. when it points to a problem within borg.

**Closed by ThomasWaldmann** 2018-04-28 17:29 UTC
Labels: question
