### ISSUE TITLE
borg export/import commands to export/import a archive

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#4337] opened 2019-02-10 13:17 UTC
the basic idea is to provide a "tar-alike" input/output stream that supports full rounding of an archive content

the main reason for tar-alike is, that python does not provide a sane/sound library for modern meta-data supporting tar archives - if this can ever be added/supported the export/import commands can be argumented with a tar-import command

if there a way to take the exact meta-data + the actual file contents in a stream that would allow borg to recreate the same  archive, even if chunking/compression/encryption where configured differently

aka solve #3867

**Comment by ThomasWaldmann** [comment] 2019-02-10 19:20
not sure what you mean by tar-alike. tar+pax or just anything that is a stream with metadata and data?

**Comment by RonnyPfannschmidt** [comment] 2019-02-10 19:51
@ThomasWaldmann just a stream of data + metadata since pax is not ready atm, pax support can come if a reasonable pax suporting tar lib is out

**Comment by ThomasWaldmann** [comment] 2019-02-10 20:04
ok, for that, some things come to mind:
- just writing the same metadata (msgpacked, with file size, but without chunks list of course) as borg would write to the repo + the binary file content directly afterwards
- make up something similar with json (needs special care for arbitrary bytes metadata values) instead of msgpack
- if borg version on both sides is required to be the same, trouble with different sets of metadata keys can be avoided.

**Comment by RonnyPfannschmidt** [comment] 2019-02-10 20:27
i believe using exactly the same borg version should be a requirement . the borg version should be part of the first message of the stream

as for serialization, i believe msgpack will do fine, json is something i'd personally avoid due to bytes semantics

**Comment by ThomasWaldmann** [comment] 2019-02-10 21:09
when sending the length of the msgpacked metadata as a (32bit) binary value first, reading the metadata gets easy.

**Comment by RonnyPfannschmidt** [comment] 2019-02-15 09:11
i just noticed, that the tar library in the stdlib actually has support for adding pax headers to archives and supports emitting the pax format in recent enough versions, perhaps that  can be used instead

**Comment by liori** [comment] 2021-11-01 15:04
For those who are fine with a quick'n'dirty hack, this script is a rough draft that was good enough for me: https://gist.github.com/liori/58413ca26d82391dbb6649dd9bd00fea

**Comment by callegar** [comment] 2022-02-12 15:11
@liori thanks for the script. It is unclear to me if your script is lossy or not, though.  I have a feeling it may be lossy because of the `--numeric-owner`. If I understand correctly, borg usually stores the *string* owner and group owner of a file in addition to the *numeric* uid and gid (is this correct? incidentally, isn't this redundant? Why for each archive a single table reporting the correspondence between users and uids and between groups and gids cannot be enough?). However when you mount with fuse I believe this information is necessarily lost. It is unclear to me if `borg mount` uses the string owner and group info at all (in fact, even for `create` and `extract` the documentation about how things work without `--numeric-owner` is at best *a bit too terse*).

Hence, if I understand correctly, as of today, *there is no way at all to move an archive to another repo with full fidelty*. Even considering the fuse approach the sole possibility would be to fuse mount to a machine that has the exact uid/git -> user/group correspondence and *not* to use --numeric-owner. Is this correct?

**Comment by liori** [comment] 2022-02-19 12:30
@callegar, whether you want matching by numeric or textual representation of the owner depends on your use case. In my case, this is a full root file system backup. If I wanted to restore it, I want the numeric owners to match the restored system's /etc/passwd identifiers. That wouldn't happen if I were to restore the backup by string owners, because then the file system would store numeric identifiers of the OS used for the restore procedure, and not the the identifiers of the restored system.

I don't know what is used by `borg mount`. It's a FUSE file system, and how the ownership of files under FUSE file systems works was always quite unclear to me.

**Comment by ThomasWaldmann** [comment] 2022-02-19 12:46
`borg mount` historically used the numeric ids by default. It was recently changed to behave like `borg extract` and use the names by default and numeric ids only if requested by `--numeric-ids`.

**Comment by dhouck** [comment] 2022-02-19 19:02
Is it otherwise lossy (eg. xattrs, acls)?  Iʼd expect so since `borg mount` doesnʼt seem to reproduce ACLs (based on other issues I see here)

**Comment by ThomasWaldmann** [comment] 2022-02-19 19:11
xatts: don't remember, needs checking.
acls and flags: for sure no support for that in borgfs (and maybe not even in FUSE)

**Comment by callegar** [comment] 2022-03-09 09:03
I wonder if the usage of *numeric* and *string* IDs could be slightly better documented. What happens if you do not use `--numeric ids`? I understand that `mount` and `extract` will try to match the string ID stored in the archive with the local IDs and get the correct local numeric ID for each of them on the local system. But what if a corresponding local ID is missing? What happens in this case? Is this *silently* managed somehow? Do `extract` or `mount` fall back to using numeric IDs even if this shall most likely not give the intended result? Or do you get an error and the command to abort? Do you get a warning? Is there a quick way to check all the string IDs that are present in an archive to check if the local system onto which the archive is to be extracted contains the correct string IDs or if the numeric IDs match?

Until a lossless export/import is available (btw, thanks and congratulations for the 1.2 release! I hope that now that it is out this will be possible), I think that it may be important to know all the possible sources of data loss while using workarounds. Now that after a few years `borg` has been in deployment and that many users have accumulated many repos, I think that the need to do some *maintenance work` on them is becoming more important. More so as in the beginnings the implications of creating repos mixing backups from multiple machines were not all that clear to many users (me included).

**Comment by callegar** [comment] 2022-03-09 09:38
I have tried to look a bit into the matter. If I understand correctly, the mapping is done through the `user2uid` and `group2gid` helpers. I understand that these return `None` if a matching is not found. Then the `uid` and `gid` returned by these helpers is passed to `os.fchown` (for `extract`, haven't looked at what happens with `mount` yet). However, from the Python documentation, I cannot get what happens when `os.fchown` is passed `None` as a `uid` or `gid` argument. The only thing being said is that `-1` is interpreted as a *do not change uid, gid*. Is a `None` interpreted as a `0`? Can this lead to files getting incorrectly owned by `root` on extract? Can mismatching owners be dangerous somehow in case of `suid` files?

**Comment by callegar** [comment] 2022-03-09 09:49
I have looked a bit into the matter and I understand that this is managed via the `user2uid` (and `group2gid`) helpers. I understand that these return `None` if no matching is found and that in this case there will be a silent fallback to using the numeric `uid` and/or `gid` (because of `uid = item.uid if uid is None else uid`). Is this correct? Incidentally, this should be very much of a corner case, but may silently mismatching IDs have implications in case of suid files? Would a warning be appropriate?

**Comment by ThomasWaldmann** [comment] 2022-03-09 10:32
Yes, that is correct, see there: https://github.com/borgbackup/borg/blob/1.2.0/src/borg/archive.py#L395
- 399 is first try to get a uid, will be None if name->id lookup fails or if we want to work with numeric ids anyway
- 400 is second try to get a uid, it will either be a not-None uid from 399 or item.uid
- usually we have a valid (>= 0) uid now, but in case we got crap like -1, we will force it to the default uid

Guess this is the best we can do. Can't help if the user has "other expectations" (magic?). :-)

Guess one either needs to know that names will work (restoring on same system with same mapping) or just user --numeric-ids (esp. for full-system restore on empty disk using a rescue system).

Maybe try how tar or rsync behaves in a "mismatching" case?

BTW, we're getting a bit off-topic here, this issue is about tar import/export.

**Comment by callegar** [comment] 2022-03-09 10:43
> BTW, we're getting a bit off-topic here, this issue is about tar import/export.

You are right, sorry about that... my many questions came from considerations about workarounds usable on `1.1.x` that still misses tar import.  Thanks for all the explanations you provided nonetheless. Would it be OK if I opened a (low priority) enhancement-suggestion issue under the lines of *Wishlist: warn when non-numeric UIDs, GIDs cannot be matched exactly*? (incidentally, `tar` does exactly as borg, silently falls back to numeric values when a match cannot be found: "If it fails, then it uses the user id stored in the archive instead")

**Comment by ThomasWaldmann** [comment] 2022-03-09 10:50
Yeah, all relating comments would be better located in a new issue about name <-> id matching.

**Comment by ThomasWaldmann** [comment] 2022-04-02 17:01
see #5830

**Comment by ThomasWaldmann** [comment] 2022-04-02 20:02
closing in favour of #5830.

**Closed by ThomasWaldmann** 2022-04-02 20:02 UTC
