### ISSUE TITLE
borg create and duplicate files in command line

### ISSUE THREAD

**Issue by qurczak** [borgbackup/borg#2883] opened 2017-07-26 16:27 UTC
> $ borg --version
```
borg 1.0.11
```
I couldn't find similar issue.

Creating backup with the duplicate path or file, show as invalid information about of added files. If we add 3 the same files, we will have information about 3 files we added, but these files pointing to the same file on the filesystem. Also the size of archive is diffrent.

Scenario [1]

>$ borg info example::test1

```[...]
Command line: /usr/bin/borg create --info -C none example::test1 /tmp/1
Number of files: 1

                       Original size      Compressed size    Deduplicated size
This archive:                1.58 kB              1.71 kB              1.71 kB
All archives:                1.58 kB              1.71 kB              1.71 kB
[...]
```

> $ borg list example::test1
```
-rw-rw-r-- user user     1024 Wed, 2017-07-26 17:52:30 tmp/1
```

====
Scenario [2] (rm  example + borg init)

> $ borg info example::test1
```
[...]
Command line: /usr/bin/borg create --info -C none example::test1 /tmp/1 /tmp/1 /tmp/1
Number of files: 3

                       Original size      Compressed size    Deduplicated size
This archive:                3.95 kB              4.17 kB              2.03 kB
All archives:                3.95 kB              4.17 kB              2.03 kB
[...]
```

> $ borg list example::test1
```
-rw-rw-r-- user user     1024 Wed, 2017-07-26 17:54:49 tmp/1
-rw-rw-r-- user user     1024 Wed, 2017-07-26 17:54:49 tmp/1
-rw-rw-r-- user user     1024 Wed, 2017-07-26 17:54:49 tmp/1
```

===

Is this normal behaviour? Also the size of archive is inconsistent: 1.58 kB vs 3.95 kB, and number of files 1 vs 3.
Should I never duplicate file on command line?

**Comment by ThomasWaldmann** [comment] 2017-07-26 16:46
Well, if you give it 3 times, you get it 3 times...

I guess this is a wontfix, because it would not help just to dedup pathes on the commandline - you could also refer to the same file(s) via 2 different mountpoints.

So guess it is the administrators task not to give pathes in a overlapping way.

**Closed by ThomasWaldmann** 2017-07-26 16:46 UTC

**Comment by ThomasWaldmann** [comment] 2017-07-26 16:48
BTW, that it needs a bit more space is expected, it stores the metadata of the file 3 times (and while metadata stream is deduped also, this is way below the granularity of that process).

**Comment by enkore** [comment] 2017-07-26 17:03
Expected behaviour. The same thing happens with most archivers.

**Comment by qurczak** [comment] 2017-07-26 18:15
Ok, wontfix, but if I understand correctly (in this specific scenario) I will not have *direct* access to files with size 10486357 and 10486390? Only the last one will be avaliable?

```
$ borg list example::test1
-rw-rw-r-- user user 10486357 Wed, 2017-07-26 19:57:22 tmp/1
-rw-rw-r-- user user 10486390 Wed, 2017-07-26 19:57:22 tmp/1
-rw-rw-r-- user user 10486423 Wed, 2017-07-26 19:57:22 tmp/1
$ borg mount example::test1 /tmp/mount/
$ ls -l /tmp/mount/tmp/
razem 10241
-rw-rw-r-- 1 user user 10486423 07-26 19:57 1
```

**Comment by enkore** [comment] 2017-07-26 18:16
Yes.
