### ISSUE TITLE
Connection closed by remote host. Is borg working on the server?

### ISSUE THREAD

**Issue by fujisan43** [borgbackup/borg#1929] opened 2016-12-05 10:26 UTC
Hello,
I have trouble running 'borg list':
```
[smith@host2] $ borg list host1:/data/borgbackups/smith::2016-12-05@02:00:01
Remote: ssh_exchange_identification: Connection closed by remote host
Connection closed by remote host. Is borg working on the server?
```
but this works: 
```
[smith@host2] $ borg list host1:/data/borgbackups/smith
2016-11-28@02:00:01                  Mon, 2016-11-28 02:00:04
2016-11-29@02:00:01                  Tue, 2016-11-29 02:00:04
2016-11-30@02:00:02                  Wed, 2016-11-30 02:00:04
2016-12-01@02:00:01                  Thu, 2016-12-01 02:00:04
2016-12-02@02:00:01                  Fri, 2016-12-02 02:00:04
2016-12-05@02:00:01                  Mon, 2016-12-05 02:00:04
```
and I have
```
rpm -q borgbackup
borgbackup-1.0.8-2.fc25.x86_64
```

F.

**Comment by ThomasWaldmann** [comment] 2016-12-05 11:36
Try smith@host1 instead of just host1.

I suspect the parser gets confused by you using @ inside the archive name.

**Comment by ThomasWaldmann** [comment] 2016-12-05 13:03
Duplicate of #1930.

**Closed by ThomasWaldmann** 2016-12-05 13:03 UTC
