### ISSUE TITLE
Disk usage option (ie what will compact save)

### ISSUE THREAD

**Issue by paulharris** [borgbackup/borg#5768] opened 2021-04-19 02:54 UTC
Suggestion: add an "actual disk usage" option in borg, and what could be saved with compact (or repair)

Sorry if this is already in borg 1.2, but I didn't see anything obvious when I checked the docs on git (ie no extra params for borg compact).

When using borgbase.com , you can't run "ssh whatever@whatever du" (like you can with rsync.net - borgbase runs borgserver)
and the "borg info" command appears to only compute the archive size of the existing archives.

In append-only mode, the prune command leaves orphaned chunks behind, and these don't seem to be included in any of the numbers provided by "borg info"

So for example, I have a long-running backup on borgbase, using append-only and pruning to only about 10 recent backups.

If I run:
borg info
borg check --repair
borg info

The "borg info" outputs are identical,
but the disk usage on the web interface of borgbase.com show that the actual disk usage got dramatically smaller.

Would be great if there were "actual disk usage" and even "orphaned chunks disk usage" in the borg-info outputs, or perhaps in their own unique command.

Would be nice :)

**Comment by ThomasWaldmann** [comment] 2021-04-19 16:57
Yes, `borg info` is working on a higher level than the (quite low-level) `append-only` feature.

"orphaned chunks" sounds rather bad, but is somehow true from the current repo state.
but the append-only feature also preserves **all** previous repo states (and from there, these chunks are not orphaned, but part of a valid past state).

Guess we could quite simply sum up all segment file sizes and return that as repo data size.
There are also some other files, e.g. the repo index.

Actual disk usage will be a bit higher due to fs block size, but guess we rather ignore that.

IIRC, there is another ticket about reporting disk usage or disk free space - this is mainly an API issue, the current API does not support this and when adding this, the client/server api needs to be extended.

**Comment by paulharris** [comment] 2021-04-20 00:50
I thought "orphaned chunks" was the right terminology?
I was using that as shorthand for "chunks that are not used by the most recent repo state",
ie those transactions that have not been marked for discarding.

The goal is to be able to print out how much space could be saved with a "borg clean" or "borg compact".   The overall size of the backup is also a nice to have, but that number can be seen with other approaches - ie borgbase.com's web, or "du" if possible.   But that doesn't show what space can be reclaimed.

**Comment by ThomasWaldmann** [comment] 2021-04-20 17:22
`Orphaned` is usually used to describe a bad state, but for borg append-only, it is just "working as intended" and not bad.

OK, I see your point, you want to see what can be freed by compact_segments.

**Comment by ThomasWaldmann** [comment] 2024-09-24 10:14
I am closing this for these reasons:
- in borg2, the repo and borg compact works very differently. computing the space that can be freed by compact would already do most of the work that actually freeing the space would require, so I don't see the point yet only doing the computation and not doing the computation plus actually freeing the space in one borg compact invocation.
- it is unlikely that there will be major changes in borg 1.4.x because of the above.

**Closed by ThomasWaldmann** 2024-09-24 10:14 UTC
Labels: enhancement
