### ISSUE TITLE
Into documentation, "Edit on GitHub" link gives an Error 404

### ISSUE THREAD

**Issue by Honiix** [borgbackup/borg#2981] opened 2017-08-28 20:59 UTC
Example of a faulty link: https://github.com/borgbackup/borg/blob/9d1cf686508673a0b2081ec7f806967b839ad921/docs/index.rst

I've never used "Read The Docs" and Sphinx so I'm nowhere near able to find the problem and do a PR.

I've looked in the "Read the Docs" documentation : http://read-the-docs.readthedocs.io/en/latest/vcs.html?highlight=edit%20github and didn't found the "html_context" block in the conf.py

May I help fix this little problem?

**Comment by enkore** [comment] 2017-08-28 22:05
It's a known readthedocs bug that pops up from time to time. It has been around for a few years now with no fix. See rtfd/readthedocs.org#1820.

Duplicate of #1570, #766, #689, #451 and #413.

**Closed by enkore** 2017-08-28 22:05 UTC
Labels: duplicate
