### ISSUE TITLE
Invalid call to lru_cache throwing TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by Bluewind** [borgbackup/borg#7027] opened 2022-09-15 11:22 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

borg -V fails, but package version is `1.2.2-1~bpo18.04.1~ppa8`.

#### Operating system (distribution) and version.

Ubuntu 18.04

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg -V

## Describe the problem you're observing.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 87, in <module>
    from .selftest import selftest
  File "/usr/lib/python3/dist-packages/borg/selftest.py", line 24, in <module>
    from .testsuite.hashindex import HashIndexDataTestCase, HashIndexRefcountingTestCase, HashIndexTestCase
  File "/usr/lib/python3/dist-packages/borg/testsuite/__init__.py", line 61, in <module>
    @functools.lru_cache
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

For some reason this appeared after an update to 1.2.2 and was not happening with 1.2.0 even though no other packages were updated.

#### Fix

I can fix the issue by changing the annotations from `@functools.lru_cache` to `@functools.lru_cache()`, but I don't know which values for the parameters would be appropriate here.

**Comment by ThomasWaldmann** [comment] 2022-09-15 12:04
@LocutusOfBorg ^ as I said on IRC, the minimum requirement for borg 1.2 is python 3.8.

The 1.2.x code is regularly / automatically tested on 3.8/3.9/3.10/3.11, but not on any older versions. See the compatibility declarations and also the `python_requires='>=3.8'` in `setup.py`.

borg 1.1.x still supports older python versions, so guess the latest 1.1.x would be better as an "upgrade" for ubuntu 18.04.

About this specific issue: using `@functools.lru_cache(None)` would be the intended behaviour here.

**Comment by ThomasWaldmann** [comment] 2022-09-15 12:05
Tagging as invalid and closing due to running on an unsupported python version.

**Closed by ThomasWaldmann** 2022-09-15 12:05 UTC
Labels: invalid

**Comment by ThomasWaldmann** [comment] 2022-09-15 12:07
BTW, there are the "fat binaries" available on github releases page. They have a supported python version (and everything else needed) bundled into them, so that would be a supported way to run borg 1.2.x on ubuntu 18.04.

**Comment by ss23** [comment] 2022-09-15 20:57
This is mainly a problem because the linked PPA on the install page, https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup, offers an 18.04 package that no longer functions. I've messaged the maintainer of the PPA on Libera in case they don't follow things on here.

**Comment by LocutusOfBorg** [comment] 2022-09-16 04:48
I'll fix yes.

**Comment by LocutusOfBorg** [comment] 2022-09-16 04:59
I reuploaded 1.2.0 (last fine with old python), called
borgbackup - 1.2.2-1~bpo18.04.1~ppa8.is.1.2.0-1~ubuntu18.04.1~ppa2.

That ppa won't receive any more update for bionic I would say :)

**Comment by LocutusOfBorg** [comment] 2022-09-16 06:53
1:1.2.0-1~ubuntu18.04.1~ppa1
this is the correct version with the old content.

**Comment by ThomasWaldmann** [comment] 2022-09-16 13:03
bionic will run out of support soon anyway. many users could just upgrade to a rather stable focal.

**Comment by LocutusOfBorg** [comment] 2022-09-16 13:35
yes, indeed. I hope they will
