### ISSUE TITLE
Output of 'borg create' on files with Permission Denied inline with progress output

### ISSUE THREAD

**Issue by dragetd** [borgbackup/borg#691] opened 2016-02-23 10:34 UTC
Minor cosmetic thing:
when using --progress to see the files being progressed while a file or folder is not accessible, the error 'Permission Denied' is rendered over the progress output which is then continued in the next line. It would be good if the line was cleared first.

Example output:
/home/draget/sshfs: [Errno 13] Permission denied: '/home/draget/sshfs'.runner/Models/Beats/Level4/SpringBoard.aescn
<current progress>

Expected:
/home/draget/sshfs: [Errno 13] Permission denied: '/home/draget/sshfs'
<current progress>

**Comment by ThomasWaldmann** [comment] 2016-02-24 15:28
The problem is that the 2 mechanisms do not know from each other.

Progress display: starts from empty line, outputs progress line, but does not emit a line feed, but just a CR so cursor is waiting at beginning of same line until the next line (usually next progress line) gets output. The line needs to stay visible on screen until the next line overwrites it (in case of progress line: overwrites it completely, full terminal width) or it would not be visible long enough.

Warnings: output by logging system, expects an empty line, emits CR/LF at the end. We shall not append blanks at the end of the msg to fill to terminal width because the msg could also be written to a log file and blanks are not wanted there.

So the only quick fix I see here is having a special "full line width" screen logger, that is only used for terminal log output.

Alternatively, if we do a terminal UI refactoring / modularisation / OO approach, that could keep some state and handle this also. Or use curses to have different on-screen windows for different purposes (there is already a ticket for this).

**Comment by ThomasWaldmann** [comment] 2016-03-03 10:13
I am closing this for now, we already have another ticket about UI improvements, which will solve this also.

**Closed by ThomasWaldmann** 2016-03-03 10:13 UTC
