### ISSUE TITLE
Brew cask running really slow on OSX

### ISSUE THREAD

**Issue by realsirjoe** [borgbackup/borg#5185] opened 2020-05-12 09:41 UTC
hello there, I installed borgbackup via brew cask and its running really slow.

`borg help  0.88s user 0.25s system 8% cpu 13.565 total`

I am running OSX 10.15.4 Catalina. I also tried installing from source and pip3 which also leads to the same problem. Is there an easy fix to this and is anybody else experiencing similar issues?

Thanks a lot!

**Comment by infectormp** [comment] 2020-05-12 09:55
https://github.com/borgbackup/borg/issues/4859#issuecomment-560100854

**Comment by ThomasWaldmann** [comment] 2020-05-12 10:39
Maybe try `vorta` or the `borg` that comes with it.

IIRC, @m3nu (vorta author) solved it at least to the extend that the delay caused by macOS only happens once.

**Comment by m3nu** [comment] 2020-05-12 12:16
Yes, you can copy the `Resources/borg-dir` folder from the Vorta app. It's the same as the binary release, but not packaged. Since it stays in-place, macOS only validates it once. So after the first start, it will be fast.

Or, if you only want Borg, install it via PIP.

**Comment by m3nu** [comment] 2020-05-12 12:23
If @ThomasWaldmann is fine with it, I could add some code to build a directory-style release for macOS in macOS Vagrant? As an extra option for macOS. I tried many things and the fat binary will be hard to bring back, unless we use another packager (there are a few). The method PyInstaller uses isn't working any more.

I'd also use this dir-style release in Vorta. Would make it more official.

**Comment by realsirjoe** [comment] 2020-05-12 12:58
mine also does not work from pip maybe I am facing a different issue?

**Comment by m3nu** [comment] 2020-05-12 14:02
Yes. Then you may face a different issue.

Pip keeps all the files and binaries in the same place and macOS gatekeeper should be quick to verify them only once.

You can look for network activity by a process called `syspolicyd` or check the Console for related messages (not sure which text, but you will get lots of messages when running it.)

**Comment by realsirjoe** [comment] 2020-05-12 14:29
also i tried it with the vorta borg build which gives better but still not good results: 
./borg.exe  0.26s user 0.06s system 6% cpu 5.342 total

tested a couple times takes 5-7s

**Comment by realsirjoe** [comment] 2020-05-12 14:33
Still though I l checked console and syspolicyd is causing it, so somehow these fixes are not working for me

**Comment by m3nu** [comment] 2020-05-12 14:39
5s is still pretty long. There may be something else going on.

**Comment by philipkozeny** [comment] 2020-05-12 20:07
Seeing the same thing here as you have described @m3nu 

Borg installed via brew:

```
➜  ~ time borg --version
borg 1.1.11
borg --version  0.57s user 0.18s system 5% cpu 14.098 total
```

vs your bundled version

> ➜  ~ time /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe --version
> borg.exe 1.1.11.dev128+gae78914c
> /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe --version  0.28s user 0.06s system 86% cpu 0.390 total

While the brew version is starting I am seeing lots of `Error checking with notarization daemon: 3` errors from `syspolicyd` in the console.

**Comment by msilano** [comment] 2020-05-27 13:42
Hmmm.  I can beat that on Mac OSX (10.5.15) with Borg 1.1.11 installed directly.   Happens on High Sierra too (older Mac Mini) but not to this degree.   

```
~ % time /usr/local/bin/borg --version
borg 1.1.11
/usr/local/bin/borg --version  0.51s user 0.24s system 1% cpu 39.511 total
```

**Comment by ThomasWaldmann** [comment] 2020-07-25 09:22
@m3nu guess adding a directory-based macos borg build to the vagrantfile would be good. for now, also keep the single file.

first master, later 1.1-maint also.

**Comment by m3nu** [comment] 2020-07-25 09:40
No problem. I also prefer to ship an "official" build with Vorta, rather than my own.

Best if you assign it to me and I'll get to it in about a week.

**Comment by ThomasWaldmann** [comment] 2020-08-15 19:21
@m3nu this is the last thing on the alpha9 milestone, can you do it soon?

**Comment by m3nu** [comment] 2020-08-16 01:20
I’ll add the single folder setup today, but not the notarization since it’s probably not necessary for CLI apps and needs a $99/year Apple subscription and private keys.

**Comment by m3nu** [comment] 2020-08-16 07:26
I've added a PR for this, but didn't test it on Vagrant yet, since the download takes a while.

In addition, I've added a new [Homebrew formula](https://github.com/Homebrew/homebrew-core/pull/59717) that uses the Python release of Borg instead of the pre-built binary. This is probably less risky in terms of dependencies and doesn't cause any Gatekeeper issues.

**Comment by m3nu** [comment] 2020-08-17 07:13
I found that none of the old Vagrant virtualbox macOS VMs are working any more. Most just kernel panic while booting. The version referenced in Vagrant is also quite old. 10.12, with 10.16 about to come out. So 10.14 would be a reasonable "oldstable". That's what I'm trying currently.

In general macOS users are probably best served by using the Python/Homebrew formula, which will be smallest and most portable. Only drawback is that it needs Homebrew installed. Trying to get this approved over the next days.

**Comment by ThomasWaldmann** [comment] 2020-08-17 12:00
I use older machines for building the pyinstaller binaries because usually the resulting binaries then can be used on any same or newer OS version.

Last time I tried, my local vagrant macOS box worked.

And yes, of course a real package made for / compiled on the target OS is best.

The pyinstaller-made fat binaries were primarily meant for situations where this is not available or too much work, e.g. when trying to restore a machine from a live USB stick.

**Comment by m3nu** [comment] 2020-08-17 12:33
> The pyinstaller-made fat binaries were primarily meant for situations where this is not available or too much work, e.g. when trying to restore a machine from a live USB stick.

In such a situation, they can probably live with a 10-20 second delay when starting it and I'd keep the current fat binary for its simplicity.

Then my main contributions here will be:

- Improving the Homebrew package to NOT use the fat binary, but a normal Python installation. (Fully solves the issue reported here, after [added](https://github.com/Homebrew/homebrew-core/pull/59717) to Homebrew)
- Update the Vagrant build to 10.14 and use a public VM. (Couldn't get earlier macOS versions to work.)

**Closed** 2020-09-23 11:25 UTC

**Comment by dbuenzli** [comment] 2021-01-13 09:54
Hello, 

I'm still hitting that problem on macos 11, despite the new (non-cask) formula. On *each run* a simple `borg --version` takes up to 5s: 
```
> time borg --version
borg 1.1.15
borg --version  0.21s user 0.07s system 5% cpu 5.304 total
```
When I run the above I get the following in the OS console which is correlated with `borg`'s dependencies:
```
error	02:25:51.029700+0100	kernel	Sandbox: logd_helper(528) deny(1) file-read-data /usr/local/Cellar/xz/5.2.5/lib/liblzma.5.dylib
error	02:25:51.030257+0100	kernel	Sandbox: logd_helper(528) deny(1) file-read-data /usr/local/Cellar/openssl@1.1/1.1.1i/lib/libssl.1.1.dylib
error	02:25:51.030492+0100	kernel	Sandbox: logd_helper(528) deny(1) file-read-data /usr/local/Cellar/openssl@1.1/1.1.1i/lib/libcrypto.1.1.dylib
error	02:25:51.030747+0100	kernel	Sandbox: logd_helper(528) deny(1) file-read-data /usr/local/Cellar/libb2/0.98.1/lib/libb2.1.dylib
error	02:25:51.030951+0100	kernel	Sandbox: logd_helper(528) deny(1) file-read-data /usr/local/Cellar/xxhash/0.8.0/lib/libxxhash.0.8.0.dylib
error	02:25:51.031166+0100	kernel	Sandbox: logd_helper(528) deny(1) file-read-data /usr/local/Cellar/lz4/1.9.3/lib/liblz4.1.9.3.dylib
error	02:25:51.031372+0100	kernel	Sandbox: logd_helper(528) deny(1) file-read-data /usr/local/Cellar/zstd/1.4.8/lib/libzstd.1.4.8.dylib
```
Any idea on how one can move on to solve this problem ?

**Comment by m3nu** [comment] 2021-01-13 10:07
Two problems to unpack here:

Regarding the binary verification slowing down Borg startup: I can't reproduce this. You can look at the console log for issues or network traffic with/of `syspolicyd`.

```
$ brew install borgbackup
==> Downloading https://homebrew.bintray.com/bottles/xxhash-0.8.0.big_sur.bottle.tar.gz
...
==> Installing borgbackup
==> Pouring borgbackup-1.1.15.big_sur.bottle.1.tar.gz
🍺  /usr/local/Cellar/borgbackup/1.1.15: 685 files, 10.5MB
$ time borg --version
borg 1.1.15
borg --version  0.35s user 0.16s system 8% cpu 6.009 total
$ time borg --version
borg 1.1.15
borg --version  0.21s user 0.12s system 92% cpu 0.359 total
$ time borg --version
borg 1.1.15
borg --version  0.20s user 0.14s system 75% cpu 0.456 total
```

The second problem you see is related to permissions. You will need to grant *Full Disk Access* to Python, iTerm2, Terminal or BorgBackup in *Preferences > Security > Privacy*. Else Borg can't read any files.

**Comment by dbuenzli** [comment] 2021-01-13 11:10
Thanks! Well actually I had tried to grant full disk access to borg but that didn't work I suspect you need to add the concrete binary executable which in this case should end up being:
```
/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/bin/python3.9
```
However for some obscure reason I'm not able to select it in the Security UI. It seem the high-level interface (and the Finder FWIW) sees it as a simple document despite the fact that:
```
> ls -l@ python3.9
-rwxr-xr-x  1 dbuenzli  staff  50472 Jan 13 01:54 python3.9*
> file python3.9
python3.9: Mach-O 64-bit executable x86_64
> ./python3
Python 3.9.1 (default, Jan  8 2021, 17:17:43) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by m3nu** [comment] 2021-01-13 11:32
You may need to add the Terminal application or Vorta (if you use that) in the security settings. It generally won't allow you to select single binaries, but only the top level desktop app running it.

**Comment by dbuenzli** [comment] 2021-01-13 12:07
@m3nu thanks for your suggestions, very much appreciated. Unfortunately I already have `Terminal.app` in there. 

In general I can select individual executables, but for some reason `python3.9`'s spotlight metadata does not label it as an executable which I suspect is the reason why I can't select it. For example I can select the `pip3` executable. The difference is quite obvious:
```
> mdls python3.9 | grep 'kMDItemContentType '
kMDItemContentType                     = "dyn.ah62d4rv4ge8xw"
> mdls pip3 | grep 'kMDItemContentType ' 
kMDItemContentType                     = "public.unix-executable"
```
I tried to retrigger a metadata indexation via `sudo mdutil -E / ` but that didn't seem to have changed anything and also tried to resinstall python@3.9. But the executable gets the same dynamic type identifier.

So far I haven't found a way to change that information manually.
