### ISSUE TITLE
invalid segment entry size - too big

### ISSUE THREAD

**Issue by tex** [borgbackup/borg#1977] opened 2016-12-22 18:08 UTC
borg 1.0.9:

fenix# borg check /mnt/1/Backup.borg 
Invalid segment entry size 1195725663 - too big [segment 74304, offset 5439325]
Invalid segment entry size 1195725663 - too big [segment 74305, offset 5651708]
Invalid segment entry size 1195725663 - too big [segment 74306, offset 7320996]
Invalid segment entry size 1195725663 - too big [segment 74307, offset 6769104]
Invalid segment entry size 1195725663 - too big [segment 74309, offset 2692895]
Completed repository check, errors found.

What am I supposed to do? Even `list` does not work...

**Comment by enkore** [comment] 2016-12-22 18:20
`check --repair` should fix this but might loose some data in the process that might still be salvageable with manual forensics.

This also looks rather curious with the value being exactly the same in all five instances. I assume these files are not actually >1 GB (data/7/74304 ... 74309)?

**Comment by tex** [comment] 2016-12-22 19:33
borg 1.0.9

**Comment by tex** [comment] 2016-12-22 19:34
fenix# ls /mnt/1/Backup.borg/data/7/74304 -lah
-rw------- 1 root root 11M 27. lis 21.38 /mnt/1/Backup.borg/data/7/74304
fenix# ls /mnt/1/Backup.borg/data/7/74305 -lah
-rw------- 1 root root 11M 27. lis 21.38 /mnt/1/Backup.borg/data/7/74305
fenix# ls /mnt/1/Backup.borg/data/7/74306 -lah
-rw------- 1 root root 13M 27. lis 21.38 /mnt/1/Backup.borg/data/7/74306
fenix# ls /mnt/1/Backup.borg/data/7/74307 -lah
-rw------- 1 root root 12M 27. lis 21.38 /mnt/1/Backup.borg/data/7/74307
fenix# ls /mnt/1/Backup.borg/data/7/74309 -lah
-rw------- 1 root root 3,6M 27. lis 21.39 /mnt/1/Backup.borg/data/7/74309
fenix# ls /mnt/1/Backup.borg/data/7/74308 -lah
-rw------- 1 root root 5,1M 27. lis 21.39 /mnt/1/Backup.borg/data/7/74308

**Comment by tex** [comment] 2016-12-22 19:42
I'm more interested about how to prevent this.
I'm using one storage for 3 or 4 computers. So far (like more than a half a year) it worked OK.
Is it more software or hardware (bad disk) issue?

Maybe this is a price for me using borg break-lock? Sometimes (quite frequently) it happens that backup is interrupted (Ethernet down, PC power down) and there is lock which prevents other PC to backup.
Any clean solution for this?

**Comment by enkore** [comment] 2016-12-22 20:04
I believe that software-wise this could have happened with the bug I fixed in [1.0.4](http://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-4-potential-repo-corruption), if there is an underlying hardware (or FS) issue. Otherwise the corruption cases I've investigated where normally not in stable releases or a hardware defect (bad memory / bad disk sectors).

Borg itself doesn't implement redundancy / forward error correction but leaves that to the host (file system / OS) to provide, if necessary (at least for now - there were quite long previous technical discussions on this).

**Comment by tex** [comment] 2016-12-22 20:48
Thank you!

**Comment by ThomasWaldmann** [comment] 2016-12-22 21:49
@tex how many files (or hardlinks or other fs objects) do you have in the biggest file-count backup archive in that repo?

**Comment by tex** [comment] 2016-12-22 22:03
Well, the check --repair seemed to fix it. I can run borg list now. But yes, the root cause is still unknown. Reopening.

Any easy way to count that? I backup full Linux installation including my home folder.
Total size of repository is 276GiB. Kinda need to refine this setup :-)

**Comment by enkore** [comment] 2016-12-22 22:04
> how many files (or hardlinks or other fs objects) do you have in the biggest file-count backup archive in that repo?

I think that one is very unlikely (1.1 GB archive item?).

**Comment by ThomasWaldmann** [comment] 2016-12-22 22:17
@enkore yes, 1.1GB would be gigantic.

I just was reminded of that (from source):
```
        if size > MAX_OBJECT_SIZE:
            # if you get this on an archive made with borg < 1.0.7 and millions of files and
            # you need to restore it, you can disable this check by using "if False:" above.
            raise IntegrityError('Invalid segment entry size {} - too big [segment {}, offset {}]'.format(
                size, segment, offset))
```
Pity we do not have a separate repo header checksum.

**Comment by ThomasWaldmann** [comment] 2016-12-22 22:19
But as the files are only ~10-15MB, it must be wrong.

**Comment by tex** [comment] 2016-12-22 22:45
Well, my storage is on USB disk and does not seem to support SMART.
No visible errors in logs though.
Most probably this is because power-off during backup...

=== START OF INFORMATION SECTION ===
Vendor:               Seagate
Product:              Expansion
Revision:             0502
Compliance:           SPC-4
User Capacity:        1 000 204 885 504 bytes [1,00 TB]
Logical block size:   512 bytes
Logical Unit id:      0x5000000000000001
Serial number:        NA4C33NG
Device type:          disk
Local Time is:        Thu Dec 22 23:39:07 2016 CET
SMART support is:     Available - device has SMART capability.
SMART support is:     Disabled
Temperature Warning:  Disabled or Not Supported
Read Cache is:        Enabled
Writeback Cache is:   Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported

Device does not support Self Test logging
Device does not support Background scan results logging

**Comment by ThomasWaldmann** [comment] 2016-12-22 22:55
try `smartctl -dsat -son -Son -a /dev/sdx` - still no smart infos?

**Comment by tex** [comment] 2016-12-22 22:57
```
 ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x002f   100   100   051    Pre-fail  Always       -       9
  2 Throughput_Performance  0x0026   252   252   000    Old_age   Always       -       0
  3 Spin_Up_Time            0x0023   090   090   025    Pre-fail  Always       -       3119
  4 Start_Stop_Count        0x0032   100   100   000    Old_age   Always       -       99
  5 Reallocated_Sector_Ct   0x0033   252   252   010    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x002e   252   252   051    Old_age   Always       -       0
  8 Seek_Time_Performance   0x0024   252   252   015    Old_age   Offline      -       0
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       16663
 10 Spin_Retry_Count        0x0032   252   252   051    Old_age   Always       -       0
 11 Calibration_Retry_Count 0x0032   100   100   000    Old_age   Always       -       34
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       64
191 G-Sense_Error_Rate      0x0022   252   252   000    Old_age   Always       -       0
192 Power-Off_Retract_Count 0x0022   100   100   000    Old_age   Always       -       17
194 Temperature_Celsius     0x0002   064   054   000    Old_age   Always       -       22 (Min/Max 15/48)
195 Hardware_ECC_Recovered  0x003a   100   100   000    Old_age   Always       -       0
196 Reallocated_Event_Count 0x0032   252   252   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   252   252   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   252   252   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0036   200   200   000    Old_age   Always       -       0
200 Multi_Zone_Error_Rate   0x002a   100   100   000    Old_age   Always       -       258
223 Load_Retry_Count        0x0032   100   100   000    Old_age   Always       -       34
225 Load_Cycle_Count        0x0032   085   085   000    Old_age   Always       -       155072
```

**Comment by tex** [comment] 2016-12-22 22:59
I admit that I can not read this report clearly. How bad is it?

**Comment by ThomasWaldmann** [comment] 2016-12-22 23:06
Nothing suspicious there. If you want to be sure, do a `-t long` and look again after it finished.

**Comment by ThomasWaldmann** [comment] 2017-01-23 19:10
closing as duplicate of #2099 (see more info there).

**Closed by ThomasWaldmann** 2017-01-23 19:10 UTC

**Comment by textshell** [comment] 2017-01-23 19:14
Just for reference (if anyone is curious why this has to be the same cause): 
ascii of the size fits 2099
bytes(reversed(binascii.unhexlify(hex(1195725663)[2:]))) --> b'_SEG'
