### ISSUE TITLE
help usage docs yield error

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#312] opened 2015-10-19 15:03 UTC
i think #297 may have broken a part of the docs generation:

```
/home/anarcat/src/borg/docs/usage.rst:377: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/help.rst.inc'.
```

@ThomasWaldmann?

**Comment by ThomasWaldmann** [comment] 2015-10-19 16:27
I had modified setup.py to generate that.

**Comment by anarcat** [comment] 2015-10-21 00:36
sorry, i don't understand... is this fixed then? if not, i think it should be for 0.28!

**Comment by ThomasWaldmann** [comment] 2015-10-21 00:39
well, IIRC i had to call python setup.py build_usage manually to create the help.rst.inc.
i thought it is intended to be that way, but maybe it is not?

**Comment by anarcat** [comment] 2015-10-21 00:45
it's not. build_usage is hooked into the main builds in all sorts of ways, it was quite painful.

**Comment by ThomasWaldmann** [comment] 2015-10-21 01:02
ok, then maybe some trigger is missing.

**Comment by anarcat** [comment] 2015-10-21 01:10
well, all the other parts of usage/*.rst.inc are generated, only help.rst.inc is missing, and that was tampered with in #297, so i thought it was related.

if i revert to the commit before #927 was merged (1b426c5), the error disappears, so it's clearly a regression introduced in the merge (908e944).

**Comment by ThomasWaldmann** [comment] 2015-10-21 23:19
after killing docs/usage/* and cd docs ; make html:
```
...
InputError: [Errno 2] No such file or directory: 'usage/check.rst.inc'.
/home/tw/w/borg/docs/usage.rst:262: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/rename.rst.inc'.
/home/tw/w/borg/docs/usage.rst:264: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/delete.rst.inc'.
/home/tw/w/borg/docs/usage.rst:266: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/list.rst.inc'.
/home/tw/w/borg/docs/usage.rst:288: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/prune.rst.inc'.
/home/tw/w/borg/docs/usage.rst:322: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/info.rst.inc'.
/home/tw/w/borg/docs/usage.rst:341: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/mount.rst.inc'.
/home/tw/w/borg/docs/usage.rst:353: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/change-passphrase.rst.inc'.
/home/tw/w/borg/docs/usage.rst:375: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/serve.rst.inc'.
/home/tw/w/borg/docs/usage.rst:390: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'usage/help.rst.inc'.
```
As you see, nothing gets built automatically, including help.rst.inc.

Now I run this manually:
```
$ python setup.py build_usage
running build_usage
generating usage docs
found commands: ['create', 'delete', 'list', 'extract', 'info', 'prune', 'change-passphrase', 'mount', 'rename', 'help', 'upgrade', 'check', 'init', 'serve']
generating help for create
generating help for delete
generating help for list
generating help for extract
generating help for info
generating help for prune
generating help for change-passphrase
generating help for mount
generating help for rename
generating help for help
generating help for upgrade
generating help for check
generating help for init
generating help for serve
```
As you see, it builds all the usage files, including help.rst.inc ("help for help").

**Comment by anarcat** [comment] 2015-10-22 13:12
On 2015-10-21 19:19:16, TW wrote:
> after killing docs/usage/* and cd docs ; make html:

make html won't generate the usage docs, as sphinx bypasses `setup.py`.

`python setup.py install` or `build` will build them.

> ```
> ...
> InputError: [Errno 2] No such file or directory: 'usage/check.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:262: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/rename.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:264: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/delete.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:266: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/list.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:288: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/prune.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:322: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/info.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:341: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/mount.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:353: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/change-passphrase.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:375: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/serve.rst.inc'.
> /home/tw/w/borg/docs/usage.rst:390: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'usage/help.rst.inc'.
> ```
> As you see, nothing gets built automatically, including help.rst.inc.
>
> Now I run this manually:
> ```
> $ python setup.py build_usage
> running build_usage
> generating usage docs
> found commands: ['create', 'delete', 'list', 'extract', 'info', 'prune', 'change-passphrase', 'mount', 'rename', 'help', 'upgrade', 'check', 'init', 'serve']
> generating help for create
> generating help for delete
> generating help for list
> generating help for extract
> generating help for info
> generating help for prune
> generating help for change-passphrase
> generating help for mount
> generating help for rename
> generating help for help
> generating help for upgrade
> generating help for check
> generating help for init
> generating help for serve
> ```
> As you see, it builds all the usage files, including help.rst.inc ("help for help").

Yeah, odd... i can't reproduce the problem anymore.

Maybe the "out of date" detection is out of whack.

oh well.

a.

-- 
I believe that if someone choose arts as their subject but do not
criticize the issues of their society, they have have betrayed
themselves, their conscience, and their society.
                        - Atena Farghadani

**Comment by ThomasWaldmann** [comment] 2015-10-24 22:24
I am closing this, reopen if it can be reproduced.

**Closed by ThomasWaldmann** 2015-10-24 22:24 UTC
