### ISSUE TITLE
Borg exits with an error code when it shouldn't

### ISSUE THREAD

**Issue by elitegreg** [borgbackup/borg#4121] opened 2018-10-22 15:37 UTC
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.1.5

#### Operating system (distribution) and version.

Ubuntu 18.04

#### Hardware / network configuration, and filesystems used.

Repo is on a btrfs volume on an external usb drive.

#### How much data is handled by borg?

Borg completes the backup and appears to be successful, but exits with a non-zero error code, causing scripts that do further processing to fail.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create /mnt/backup-drive-2/borgarchive/scarif-repo::{hostname}-home-{now} /home --patterns-from '/tmp/tmpzx2rj5qu --exclude-caches --exclude-if-present .nobackup --compression zstd,4 --one-file-system --umask 77 --info --stats

## Describe the problem you're observing.

Borg appears to be scanning files that are excluded. My .cache directory is excluded and this is verified by the fact that it doesn't exist in any of my previous successful backups. However I see this as the only error from the borg create command line:

/home/greg/.cache/google-chrome/Default/Cache/acede752fed9f478_0: stat: [Errno 2] No such file or directory: '/home/greg/.cache/google-chrome/Default/Cache/acede752fed9f478_0'

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

It happens once every few weeks with a nightly backup.

**Comment by elitegreg** [comment] 2018-10-22 15:38
The problem statement should go on to say that borg appears to complete successfully, but returns a non-zero exit status.

**Comment by ThomasWaldmann** [comment] 2018-10-22 16:48
borg knows 2 different kinds of excludes:
- exclude, but scan below for potential includes
- exclude, no scan below

By which means is your `.cache` excluded? Can you reproduce with 1.1.7?

The message you get is just a warning referring to a vanished input file (vanished between directory scan and trying to `stat` it). This is expected for a changing filesystem (if you do not use some snapshotting mechanism), but borg will just skip the file and continue with the remaining files/dirs.

Which exit status did it return? Please note that rc = 1 means warning, not error.

**Comment by elitegreg** [comment] 2018-10-23 14:07
I'm unfamiliar with the 2 types of excludes. I'm using a pattern file like:

`R /home
- /home/*/.cache`

I'm using borgmatic to run borg. It appears to assume any non-zero exit code is an error. I'm not sure if borg create is exiting with a warning or not. Would a vanished input file cause borg to exit(1)?

**Comment by ThomasWaldmann** [comment] 2018-10-23 14:21
https://borgbackup.readthedocs.io/en/stable/usage/general.html#return-codes

https://borgbackup.readthedocs.io/en/stable/usage/help.html (see stuff with red marker at the sides, it describes `--patterns(-from)` syntax, search for "exclude-norecurse")

**Comment by ThomasWaldmann** [comment] 2018-10-23 14:22
i'm closing this, i don't see a bug in borg, works as documented.

**Closed by ThomasWaldmann** 2018-10-23 14:22 UTC
Labels: question

**Comment by vwas2** [comment] 2021-07-09 22:33
exit 1 for warnings makes `borg create .... || die $? `  end with error;  Especially the relocated repo warning causes 1 despite `export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes` being set ..

**Comment by ThomasWaldmann** [comment] 2021-07-10 15:25
@vwas2 i can't reproduce. please open a new bug report, give all the details and also a script that reproduces the issue.
