### ISSUE TITLE
Inconsistent stats information (1.1.1)

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#3250] opened 2017-11-03 11:00 UTC
Hi, yesterday something weird happened after having completed a backup using borg 1.1.1. I'm not sure if I'm understanding something wrong, or there is a bug.
This is what I have right now for my last backup (yesterdays'):
```
Archive name: 2017-11-02_21:17:42
Archive fingerprint: 768433befe28fcf1a7cdffbf71eac147ef352c9f6d57d5d9714675675d831550
Comment: 
Hostname: vaioalex
Username: root
Time (start): Thu, 2017-11-02 21:18:16
Time (end): Thu, 2017-11-02 22:09:58
Duration: 51 minutes 41.59 seconds
Number of files: 196699
Command line: ****************
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               28.92 GB             15.75 GB            871.86 MB
All archives:                2.50 TB              1.43 TB             57.57 GB

                       Unique chunks         Total chunks
Chunk index:                  332245             11364234
```
So far so good. It seems consistent with having lasted 51 minutes (SSH backup). But I wanted to know why those 871MB (since it did not make sense to me), so I executed the following:
```
borg list --format "{dcsize:<10}{TAB}{path}{NL}" REPOSITORY::2017-11-02_21:17:42
```
And here comes the surprise. The SUM of all the dcsizes is ~95MB, way far from the 871MB. 
If I do the above procedure for previous archives, the results of "info" and "list" match. It just for this specific archive.

So I checked the repository, and I got:
```
Starting repository check
Data integrity error: Segment entry checksum mismatch [segment 16116, offset 821416]
Starting repository index check
Index object count mismatch.
committed index: 332246 objects
rebuilt index:   332242 objects
ID                                                               rebuilt index    committed index 
5885069594543536162fbd9fd2ccf3a09d54e3723486a27b03c17a9a9f9f68a4 <not found>      (16116, 2542336)
b0725f0769755bd8c5f24c37e719731dbf74b23d41f21f9800ea59eaa3fe60bb <not found>      (16116, 8)      
17b34b15c268b4d0d9d78a7c312542f7f601dc642b6c7968d542ddfb901b1a50 <not found>      (16116, 821416) 
d5e504574310108f70ed6a56c904f5973947abaf5848b232b921a274fe96fc66 <not found>      (16116, 2918512)
Completed repository check, errors found.
```
I was surprised, so I checked again and it then said "no problems".

Right now, the sizes do not match, but borg check reports no problems. Any ideas?

**Comment by ThomasWaldmann** [comment] 2017-11-03 12:33
I guess a `borg check` (addressing both repo and archives, so do not use --repository-only or --archives-only) would be good. So it is just `borg check repo` (and if anything found: `borg check --repair repo`).

While your stuff is corrupted somehow, we can't search for stats consistency issues - corruption can cause anything. Also, the sum of the dcsizes is just for the files' content, it does not consider the metadata.

Then maybe do a new backup and check again if you still see the issue.

**Comment by alejandro-perez** [comment] 2017-11-03 12:42
> I guess a borg check (addressing both repo and archives, so do not use --repository-only or --archives-only) would be good. So it is just borg check repo (and if anything found: borg check --repair repo).

I already did it, and now it reports no errors.

> While your stuff is corrupted somehow, we can't search for stats consistency issues - corruption can cause anything. Also, the sum of the dcsizes is just for the files' content, it does not consider the metadata.

Yes, but 750MB metadata worth seems quite too much.

> Then maybe do a new backup and check again if you still see the issue.

I made an additional backup today, and then (of course) both today's and yesterday's reported low deduplicated sizes (because both contribute to the same chunks). Then I deleted today's backup again, and yesterdays is back to report 800MB. I will delete yesterday's backup and create it again, and see if today it does the same.

**Comment by ThomasWaldmann** [comment] 2017-11-03 12:52
Also worth noting: the borg 1.1 metadata stream likely won't dedup against any previous 1.0 metadata stream because of small changes (e.g. addition of bsdflags on linux).

**Comment by alejandro-perez** [comment] 2017-11-03 12:57
Yeah, but I upgraded the 25th Oct, and almost a daily backup ever since.
I've deleted the "problematic" backup, and recreating now. Let's see what happens. I'll keep you posted.

**Comment by alejandro-perez** [comment] 2017-11-03 13:03
Side proposal: #3251

**Comment by alejandro-perez** [comment] 2017-11-03 13:14
Ok, I think I have the answer. I performed again the backup. It seems the reason for the big amount of size was a vmdk file (from a Vagrantfile deployment). Now, here comes the question. But, the file was NOT listed with borg list. 

So I have a question: what happens if I upload say 700MB worth of chunks of a file and then the file is removed? I might (don't remember, but quite possible) have "vagrant destroy" at some moment while the backup was being perfomed. Is it possible that I had the chunks without an actual file associated to them? If so, should borg check realize

**Comment by ThomasWaldmann** [comment] 2017-11-03 13:33
borg 1.1 creates checkpoints every `--checkpoint-interval` (default for borg 1.1 is 30 minutes).

these checkpoints can be in the middle of a file (for borg 1.1) and in that case borg will create hidden "part" file(s) that reference the chunks belonging to that part. there's a commandline switch to show these part files (usually they are not interesting as one is primarily interested in the complete file). maybe this explains the difference you've seen.

about removing a file while it is backed up: maybe try this in a separate repo under more controlled / reproducable conditions.

guess there is no problem reading the contents as posix filesystems won't really remove a file while it is still opened by a process (borg in this case). not totally sure about the metadata though as borg gather some stuff before backing up all the contents and also afterwards.

also, if you backup a running VM without at least doing some snapshot, the backup will not be consistent.

**Comment by alejandro-perez** [comment] 2017-11-03 15:07
> these checkpoints can be in the middle of a file (for borg 1.1) and in that case borg will create hidden "part" file(s) that reference the chunks belonging to that part. there's a commandline switch to show these part files (usually they are not interesting as one is primarily interested in the complete file). maybe this explains the difference you've seen.

Sadly I deleted the old archive. Otherwise, I'd try to show them.



> about removing a file while it is backed up: maybe try this in a separate repo under more controlled / reproducible conditions

That sounds fun. Let's try :)

> also, if you backup a running VM without at least doing some snapshot, the backup will not be consistent.

I know, it wasn't running. I decided to remove the disk file and was unaware of the borg backup being run. It runs on a "anacron-like" daily.

**Comment by alejandro-perez** [comment] 2017-11-03 15:14
It seems to work fine even though I deleted the file.

On the other hand, can an archive which is not a checkpoint have "part" files in it? Because that archive was not a checkpoint.

**Comment by ThomasWaldmann** [comment] 2017-11-03 15:57
@alejandro-perez yes, it will have the part file entries. It's because once these entries are written into the metadata stream, we can't take them back any more.

**Comment by ThomasWaldmann** [comment] 2017-11-21 16:14
Somehow this ticket is not actionable, too unclear what happened / what could cause this.
Guess it is better to close this and maybe try to reproduce the issue under more controlled circumstances.

**Closed by ThomasWaldmann** 2017-11-21 16:14 UTC

**Comment by alejandro-perez** [comment] 2018-01-10 21:26
Just to note that I think this one was #3522
