### ISSUE TITLE
Index object count mismatch. 51251 != 51250

### ISSUE THREAD

**Issue by magma1447** [borgbackup/borg#1598] opened 2016-09-15 08:58 UTC
I am currently having 18 borg-repos. Backups from 6 different servers, 3 repos per server. My idea is to rotate them for different weekdays (Mon+Thu, TueSat, Wed+Fri+Sun) in case a repo breaks. My way of protecting against the downside of deduplication. Even with three mirrors of the data I am saving lots of space. The backup scripts does a create, prune, check.

I have been running this for 1-2 weeks now, with the last 4 days or so using the 1.1.0-b1 version. After I started to use the beta version I started to get the Index object count mismatch from the check-jobs. I currently have the issue with 4 of my 18 repos. The interesting fact is that this far, all of them has a mismatch of **one**.

At first I only noticed the issue with one host. I deleted a repo to make sure I started over from scratch, and removed the prune job from the backup script, hoping the prune was the issue. This did not help.

Earlier I was using version 1.0.7 and did not get these issues, so I assume it's something with the new code, though I can't be certain.

I assume this isn't a known issue since I couldn't find anything about it. Any ideas what could be the cause? Anything I could do to help finding the issue? Any other ideas?

One of my simplest repos are backed up like this:
${BORG} create --compression lzma,1 borg@${DESTHOST}:${DESTPATH}${BORGREPO}.borg::{now} /etc /usr/local/bin /root /home
Eg, no weird options at all, and it happened to this one early this morning.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/37897778-index-object-count-mismatch-51251-51250)

**Comment by enkore** [comment] 2016-09-15 09:25
Can you try [this branch](https://github.com/enkore/borg/tree/issue/1598)? Maybe that gives some insight.

**Comment by ganja1447** [comment] 2016-09-15 09:27
I'll try to compile it and run a check later today. Have some work I need to finish first though. Thank you again for your prompt assistance.

**Comment by ganja1447** [comment] 2016-09-15 10:42
I followed the guide at https://borgbackup.readthedocs.io/en/stable/installation.html#using-git to build your branch. I did not get any additional information from it though.

BORG_PASSPHRASE='foo' borg-env/bin/borg check /data/borg/thor/MonThu.borg/
Index object count mismatch. 51251 != 51250
Completed repository check, errors found.

**Comment by ganja1447** [comment] 2016-09-15 11:00
After realizing I built your master branch and not issue/1598 I got some new output:

BORG_PASSPHRASE='foo' ../borg-env/bin/borg check /data/borg/thor/MonThu.borg/
Index object count mismatch.
committed index: 51251 objects
rebuilt index:   51250 objects
ID                                                               rebuilt index    committed index 
0000000000000000000000000000000000000000000000000000000000000000 <not found>      (903, 3904605)  
Completed repository check, errors found.

I assume it tells you at least a bit more than it tells me.

**Comment by enkore** [comment] 2016-09-15 12:00
Thanks.

It seems somehow the manifest was lost.

Can you check whether there is a file `903` in `<repository>/data/0/`?

**Comment by ganja1447** [comment] 2016-09-15 12:15
Starting from 903 and going up numerically there are these:
-rw------- 1 borg root  3905361 Sep 15 05:00 903
-rw------- 1 borg root       17 Sep 15 05:00 904
-rw------- 1 borg root   851961 Sep 15 05:00 905
-rw------- 1 borg root       17 Sep 15 05:00 906
-rw------- 1 borg root      805 Sep 15 12:45 907

**Comment by enkore** [comment] 2016-09-15 12:24
Hm. Could you rebuild from my branch (`git pull && <install>`, should be commit 7fae010e) and re-run the check with `--debug`?

**Comment by ganja1447** [comment] 2016-09-15 12:46
Of course! I did a "git pull && pip install -e .", I assume that should be sufficient for getting a new "binary".

BORG_PASSPHRASE='foo' ../borg-env/bin/borg check --debug /data/borg/thor/MonThu.borg/
using builtin fallback logging configuration
29 self tests completed in 0.11 seconds
Starting repository check
Read committed index of transaction 906
Segment transaction is    906
Determined transaction is 906
Found 884 segments
Starting repository index check
Index object count mismatch.
committed index: 51251 objects
rebuilt index:   51250 objects
ID                                                               rebuilt index    committed index 
0000000000000000000000000000000000000000000000000000000000000000 <not found>      (903, 3904605)  
Completed repository check, errors found.

**Comment by enkore** [comment] 2016-09-15 13:04
> Of course! I did a "git pull && pip install -e .", I assume that should be sufficient for getting a new "binary".

Thanks, yes that works.

Okay, it seems the problem lies elsewhere, since it designates 906 as the transaction (>= 903).

Does running `borg debug-get-obj <repository> 0000000000000000000000000000000000000000000000000000000000000000 some-file` give you an error?

**Comment by ganja1447** [comment] 2016-09-15 13:11
Not sure I understand what we are doing now, to be more precise, the parameters for debug-get-obj, please correct me if some-file should have been something specific, I ran this:
BORG_PASSPHRASE='foo' borg debug-get-obj /data/borg/thor/MonThu.borg/ 0000000000000000000000000000000000000000000000000000000000000000 some-file
**Output:**
object 0000000000000000000000000000000000000000000000000000000000000000 fetched.

The borg binary used seems to be the one from your repo.
borg --version
borg 1.0.1.dev959+ng7fae010

I assume that we can say that it gave us no error.

**Comment by enkore** [comment] 2016-09-15 13:18
> Not sure I understand what we are doing now, to be more precise, the parameters for debug-get-obj, please correct me if some-file should have been something specific, I ran this

Thanks, looks good. debug-get-obj takes an object ID, fetches it from the repository and writes it to a file - the second parameter `some-file`.

Since borg-check reported that this object ID (00....0000 = Manifest) is missing from the repository we now checked whether the object is *actually* missing. Which doesn't seem to be the case.

So, I'm not sure how this is happening:

- the object is there, we can get it
- it's in the index, like it's supposed to be
- the referenced segment exists
- segment size, object role (manifest) and offset match well and make sense
- segment is in the committed range (=commit @ 906)
- there is no segment corruption, since the ID, CRC and tag are checked on get

So what remains as possible causes?

- maybe the segment is not found for some reason

Hmm. Can you run `find <repository>/data -type f | wc -l` to see whether the number of segments in the directories matches the number of segments seen by check (`Found 884 segments`)?

**Comment by ganja1447** [comment] 2016-09-15 13:25
Ah, I get the syntax now. I tried to look at some-file that I created, can't tell if it's garbage or not, it doesn't look like anything I recognize at least. But maybe it's still encrypted? Or maybe it's just a part of a file?

The number of files seems to match the number of segments.
`find /data/borg/thor/MonThu.borg/data/ -type f | wc -l`
`884`

**Comment by enkore** [comment] 2016-09-15 13:30
Yes, it will still be encrypted.

> The number of files seems to match the number of segments.
> `find /data/borg/thor/MonThu.borg/data/ -type f | wc -l
884`

I'm officially out of ideas for now as to the cause of this. Maybe I'll have some new later.
Thanks for the report and your help debugging this :)

**Comment by ganja1447** [comment] 2016-09-15 13:33
It's me who owes you a thank you. I will see if I can manage to make a reproduction case on a smaller amount of data, and data that I don't mind distributing. It doesn't really make it easier when I sit on the data and you the knowledge.

**Comment by ganja1447** [comment] 2016-09-15 14:24
Reproducing it is (too) easy. I can't say what's triggering it though, because it seems like some random factor.

Create a test folder
`mkdir test && cd test`
Init a repo, using borg version 1.0.7
`borg init -e none foo.borg ; mkdir data`
Create and backup some random data, using borg version 1.1.0-b1
`for i in $(seq 1 3) ; do dd if=/dev/urandom of=data/$i bs=1k count=10k ; LD_LIBRARY_PATH=/foo  /usr/local/bin/borgbackup-1.1.0-b1 create foo.borg::{now} data ; LD_LIBRARY_PATH=/foo /usr/local/bin/borgbackup-1.1.0-b1 check --info foo.borg ; echo ; done`

After running the last command 2-5 times I get:
`Index object count mismatch. 51 != 50` or similar

I have reproduced it several times now actually, on two systems. One using Debian Testing, the other using Ubuntu 16.10. I did not manage to reproduce the case when creating the borg-repo with version 1.1.0-b1.

I tried running `LD_LIBRARY_PATH=/foo BORG_PASSPHRASE='foo' /usr/local/bin/borgbackup-1.1.0-b1 upgrade /data/borg/thor/MonThu.borg` on one of my broken repos. That seemed to work, but a check failed even after that. Maybe it's too late for the upgrade. But if the versions aren't compatible I assume they should warn the user and reject the new backups.

I guess a solution for me would be to delete all repos I have and create new ones, but if I had several months of backup I wouldn't really be happy about that. In this actual case I don't really care since it's only 1-2 weeks of data. I can probably recreate them in 15-20 minutes as well.

**Comment by enkore** [comment] 2016-09-15 14:44
They are (or should be) compatible, no upgrade is needed.

I'll try your reproduction instructions later.

**Comment by ganja1447** [comment] 2016-09-16 11:57
I do get the issue even though the repo is created with 1.1.0-b1, for one of my servers. I can not tell why though.

I can't repo that on my Ubuntu though, I created over 500 backups without success. But as soon as I create the repo with 1.0.7 it takes me less than 10 backups every time.

**Comment by enkore** [comment] 2016-09-18 13:42
I managed to reproduce it, the reason why it's happening with 1.0 repos but rarely with 1.1 repos is that an incorrect condition caused an inconsistency in the repository. That condition depends on moving objects around, which is more likely with the smaller segments used in 1.0 repos by default, while the larger segments in repos created by 1.1 are less likely to trigger the issue.

If it only affects the manifest, then this is self-healing with the next create/delete/prune operation with a fixed version or 1.0.x. If it affects data chunks then a manual repair (*not* borg-check --repair) may be required.

**Comment by ThomasWaldmann** [comment] 2016-09-18 16:32
Just to make clear: that corruption issue only affects master / 1.1.0b1, right?

**Comment by enkore** [comment] 2016-09-18 16:38
Yes.

**Closed** 2016-09-25 21:09 UTC
Labels: Bountysource, bug, cmd: check, corruption

**Comment by ThomasWaldmann** [comment] 2016-09-28 01:38
@enkore don't forget to claim the bounty.
